<?xml version="1.0"?>
<doc>
    <assembly>
        <name>DynaWorks22</name>
    </assembly>
    <members>
        <member name="T:DynaWorks22.ClashDetection.ClashDetection">
            <summary>
                Class to handle all the clash detection
            </summary>
        </member>
        <member name="F:DynaWorks22.ClashDetection.ClashDetection._clash">
            <summary>
                Navisworks Clash Object
            </summary>
        </member>
        <member name="F:DynaWorks22.ClashDetection.ClashDetection._OpenNavisFile">
            <summary>
            Navisworks Open File
            </summary>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.#ctor(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
                Constructor for Clash Detection Toolset
            </summary>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetClashDetection(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
                Gets the Clash Detection tools from the Open NWF file.
            </summary>
            <param name="OpenNavisFile">Open Autodesk Navisworks NWF File.</param>
            <returns name="ClashDetection">Clash Detection Tools</returns>
            <search>Navisworks,Clash</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.RemoveResolvedClashes(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
            Removes Resolved Clashes from the clash test
            </summary>
            <param name="OpenNavisFile">Opened Navisworks File</param>
            <returns name="ClashDetection">Clash Detection Tools</returns>
            <returns name="OpenNavisFile">Opened Navisworks Project</returns>
            <search>Navisworks,Clash,Remove</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.ClearClashResults(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
            Clears Clash results from the clash test
            </summary>
            <param name="OpenNavisFile">Opened Navisworks File</param>
            <returns name="ClashDetection">Clash Detection Tools</returns>
            <returns name="OpenNavisFile">Opened Navisworks Project</returns>
            <search>Navisworks,Clash,Remove</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.RunAllTests(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
            Runs all Clash detection test
            </summary>
            <param name="OpenNavisFile">Opened Navisworks File</param>
            <returns name="ClashDetection">Clash Detection Tools</returns>
            <returns name="OpenNavisFile">Opened Navisworks Project</returns>
            <search>Navisworks,Clash,Run</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetClashTests(DynaWorks22.ClashDetection.ClashDetection)">
            <summary>
                Returns a list of all the Clash tests
            </summary>
            <param name="ClashDetection">Open Autodesk Navisworks NWF File.</param>
            <returns name="Test">Clash Detection Tools</returns>
            <search>Navisworks,Clash,Test</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetAllClashResults(DynaWorks22.ClashDetection.OclClashTest)">
            <summary>
                Returns a list of all the Clash Results
            </summary>
            <param name="ClashTest">Navisworks Clash Test</param>
            <returns name="Results">List of Results in Clash Test</returns>
            <search>Navisworks,Clash,Results</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetClashGroupResults(DynaWorks22.ClashDetection.OclClashTest)">
            <summary>
                Returns a list of all the Clash Groups per List
            </summary>
            <param name="ClashTest">Navisworks Clash Test</param>
            <returns name="GroupResults">List of Results in Clash Test</returns>
            <search>Navisworks,Clash,Results</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetClashResultComments(DynaWorks22.ClashDetection.OclTestResult)">
            <summary>
                Returns a list of ClashResult Comments per List
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <returns name="string">List of Comments in Clash Result</returns>
            <search>Navisworks,Clash,Results,</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.RenameClashResult(DynaWorks22.ClashDetection.OclTestResult,System.String)">
            <summary>
                Rename clashes.
            </summary>
            <param name="Result">Navisworks Clash</param>
            <param name="Name">Navisworks Clash New Name</param>
            <returns name="string">Clash Result</returns>
            <search>Navisworks,Clash,Results,</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.UpdateClashResultStatus(DynaWorks22.ClashDetection.OclTestResult,System.String)">
            <summary>
                Updates status's on clashes.
            </summary>
            <param name="Result">Navisworks Clash</param>
            <param name="Status">Navisworks Clash Status</param>
            <returns name="string">Clash Result</returns>
            <search>Navisworks,Clash,Results,</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetSuitableEyePoint(DynaWorks22.ClashDetection.OclTestResult)">
            <summary>
                Returns a list Clash Result Suitable Camera View Points in Feet
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <returns name="Point">List of Comments in Clash Result</returns>
            <search>Navisworks,Clash,Results,Points</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetSuitableDirectionPoint(DynaWorks22.ClashDetection.OclTestResult)">
            <summary>
                Returns a list Clash Result Suitable Direction View Points
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <returns name="Point">List of Comments in Clash Result</returns>
            <search>Navisworks,Clash,Results,Points</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetClashPoint(DynaWorks22.ClashDetection.OclTestResult,System.Boolean)">
            <summary>
                Returns the Point of a Clash Result based on first or second object
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <param name="FirstClashItem">Navisworks Clash Result</param>
            <returns name="Point">Point of Clash</returns>
            <search>Navisworks,Clash,Point</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetClashBoundingBox(DynaWorks22.ClashDetection.OclTestResult)">
            <summary>
                Returns the Bounding Box of a Clash Result
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <returns name="BoundingBox">Bounding Box of Clash</returns>
            <search>Navisworks,Clash,BoundingBox</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.mGetSuitableEyePoint(DynaWorks22.ClashDetection.OclTestResult)">
            <summary>
                Returns a list Clash Result Suitable Camera View Points in Millimetres
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <returns name="Point">List of Comments in Clash Result</returns>
            <search>Navisworks,Clash,Results,Points</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.mGetSuitableDirectionPoint(DynaWorks22.ClashDetection.OclTestResult)">
            <summary>
                Returns a list Clash Result Suitable Direction View Points in Millimetres
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <returns name="Point">List of Comments in Clash Result</returns>
            <search>Navisworks,Clash,Results,Points</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.mGetClashPoint(DynaWorks22.ClashDetection.OclTestResult,System.Boolean)">
            <summary>
                Returns the Point of a Clash Result based on first or second object in Millimetres
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <param name="FirstClashItem">Navisworks Clash Result</param>
            <returns name="Point">Point of Clash</returns>
            <search>Navisworks,Clash,Point</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.mGetClashBoundingBox(DynaWorks22.ClashDetection.OclTestResult)">
            <summary>
                Returns the Bounding Box of a Clash Result in Millimetres
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <returns name="BoundingBox">Bounding Box of Clash</returns>
            <search>Navisworks,Clash,BoundingBox</search>
        </member>
        <member name="M:DynaWorks22.ClashDetection.ClashDetection.GetClashNodes(DynaWorks22.ClashDetection.OclTestResult,System.Boolean)">
            <summary>
                Returns a List of Nodes of a Clash Results
            </summary>
            <param name="Result">Navisworks Clash Result</param>
            <param name="FirstClashItem">Navisworks Clash Result</param>
            <returns name="Node">List of Nodes in a Clash Result</returns>
            <search>Navisworks,Clash,Node</search>
        </member>
        <member name="T:DynaWorks22.ClashDetection.OclClashTest">
            <summary>
                Class wrapper for Native COM Clash Tests
            </summary>
        </member>
        <member name="P:DynaWorks22.ClashDetection.OclClashTest.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.ClashDetection.OclClashTest.GetClashTests(DynaWorks22.ClashDetection.ClashDetection)">
            <summary>
                Class for handling clash test lists
            </summary>
        </member>
        <member name="M:DynaWorks22.ClashDetection.OclClashTest.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.ClashDetection.OclTestResult">
            <summary>
                Class wrapper for Native COM clash Result
            </summary>
        </member>
        <member name="P:DynaWorks22.ClashDetection.OclTestResult.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.ClashDetection.OclTestResult.GetResults(DynaWorks22.ClashDetection.OclClashTest)">
            <summary>
            Gets The Results from the Clash Tests
            </summary>
            <param name="ClashTest"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.ClashDetection.OclTestResult.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.ClashDetection.OclTestResult2">
            <summary>
                Class wrapper for Native COM clash Result
            </summary>
        </member>
        <member name="P:DynaWorks22.ClashDetection.OclTestResult2.inobjects">
            <summary>
                inobjects property
            </summary>
        </member>
        <member name="M:DynaWorks22.ClashDetection.OclTestResult2.GetGroupResults(DynaWorks22.ClashDetection.OclClashTest)">
            <summary>
            Gets the Group Clash Results
            </summary>
            <param name="ClashTest"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.ClashDetection.OclTestResult2.ToString">
            <summary>
                ToString output
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.CallBackGeomToDynamo">
            <summary>
                Gets the Fragments (Geometry) in a Node
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.LTransform3f">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.LVec3f">
            <summary>
                Gets the Materials in a Node
            </summary>
        </member>
        <member name="P:DynaWorks22.Objects.LVec3f.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.LVec3f.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.NavisAttributes">
            <summary>
                Gets the list of Attributes in a Node
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.NavisAttributes.GetNavisAttributesFromNodesList(DynaWorks22.Objects.OaNode)">
            <summary>
                Gets a List of Navisworks Attributes from Nodes
            </summary>
            <param name="Node">Navisworks Clash Result</param>
            <returns name="GetNavisAttributesList">Navisworks Object</returns>
            <search>Navisworks,Node</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisAttributes.GetNavisAttByClassName(System.Collections.Generic.IList{DynaWorks22.Objects.OaAttribute},System.String)">
            <summary>
                Gets a Naviswork Attribute by Class Name
            </summary>
            <param name="NavisAttributesList">Navisworks Attributes</param>
            <param name="ClassName">Class Name</param>
            <returns name="NavisAtt">Node Attributes</returns>
            <search>Navisworks,attribute</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisAttributes.GetNavisAttByClassUserName(System.Collections.Generic.IList{DynaWorks22.Objects.OaAttribute},System.String)">
            <summary>
                Gets a Naviswork Attribute by Class User Name
            </summary>
            <param name="NavisAttributesList">Nodet</param>
            <param name="ClassUserName">Class User Name</param>
            <returns name="NavisAtt">Node Attributes</returns>
            <search>Navisworks,Node</search>
        </member>
        <member name="T:DynaWorks22.Objects.NavisData">
            <summary>
                Gets the list of Attributes in a Node
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.NavisData.GetObjectNames(System.Object)">
            <summary>
                Gets a Navisworks Object Names as a list
            </summary>
            <param name="NavisObject">Navis Objects</param>
            <returns name="string">List of Names in the Object</returns>
            <search>Navisworks,object,properties</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisData.GetObjectValues(System.Object,System.String)">
            <summary>
                Gets a Navisworks Object values as a list
            </summary>
            <param name="NavisObject">Navis Objects</param>
            <param name="ObjectName">Navisworks object Name</param>
            <returns name="string">List of values by property name</returns>
            <search>Navisworks,object,properties, values</search>
        </member>
        <member name="T:DynaWorks22.Objects.NavisFragments">
            <summary>
            Navisworks Fragments
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.NavisFragments.GetNavisGeometry(DynaWorks22.Objects.OaNode)">
            <summary>
            Returns the geometry from Navisworks Elements as Dynamo Geometry
            </summary>
            <param name="Node"></param>
            <returns></returns>
        </member>
        <member name="T:DynaWorks22.Objects.NavisMaterials">
            <summary>
            Navisworks Materials
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.NavisMaterials.UpdateAmbientColor(System.Collections.Generic.List{DynaWorks22.Objects.OaNode},System.Int32,System.Int32,System.Int32)">
            <summary>
            This Updates the Ambient Color of the Nodes.
            </summary>
            <param name="Nodes"></param>
            <param name="r"></param>
            <param name="g"></param>
            <param name="b"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.NavisMaterials.UpdateDiffuseColor(System.Collections.Generic.List{DynaWorks22.Objects.OaNode},System.Int32,System.Int32,System.Int32)">
            <summary>
            This Updates the Diffuse Color of the Nodes.
            </summary>
            <param name="Nodes"></param>
            <param name="r"></param>
            <param name="g"></param>
            <param name="b"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.NavisMaterials.UpdateEmissiveColor(System.Collections.Generic.List{DynaWorks22.Objects.OaNode},System.Int32,System.Int32,System.Int32)">
            <summary>
            Updates Emissive Color
            </summary>
            <param name="Nodes"></param>
            <param name="r"></param>
            <param name="g"></param>
            <param name="b"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.NavisMaterials.UpdateSpecularColor(System.Collections.Generic.List{DynaWorks22.Objects.OaNode},System.Int32,System.Int32,System.Int32)">
            <summary>
            Updates the specular colors
            </summary>
            <param name="Nodes"></param>
            <param name="r"></param>
            <param name="g"></param>
            <param name="b"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.NavisMaterials.UpdateShininess(System.Collections.Generic.List{DynaWorks22.Objects.OaNode},System.Int32)">
            <summary>
            This updates the shininess of an object
            </summary>
            <param name="Nodes"></param>
            <param name="Shininess"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.NavisMaterials.UpdateTransparency(System.Collections.Generic.List{DynaWorks22.Objects.OaNode},System.Int32)">
            <summary>
            This controls the ability to update the transparency
            </summary>
            <param name="Nodes"></param>
            <param name="Transparency"></param>
            <returns></returns>
        </member>
        <member name="T:DynaWorks22.Objects.NavisNodes">
            <summary>
                Gets the list of Attributes in a Node
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.NavisNodes.NodeByClassNameList(System.Collections.Generic.IList{DynaWorks22.Objects.OaNode},System.String)">
            <summary>
                Gets a List of Navisworks Nodes by ClassName
            </summary>
            <param name="NodeList">Navisworks List of Nodes</param>
            <param name="ClassName">String Name of User Class</param>
            <returns name="GetNavisAttributesList">Navisworks Object</returns>
            <search>Navisworks,Node</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisNodes.NodeByClassUserNameList(System.Collections.Generic.IList{DynaWorks22.Objects.OaNode},System.String)">
            <summary>
                Gets a List of Navisworks Nodes by ClassUserName
            </summary>
            <param name="NodeList">Navisworks List of Nodes</param>
            <param name="ClassUserName">String Name of User Class</param>
            <returns name="GetNavisAttributesList">Navisworks Object</returns>
            <search>Navisworks,Node</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisNodes.GetFilesInProject(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
                Gets a List of all nwc files in the loaded Project as Nodes
            </summary>
            <param name="OpenNavisFile">open Navisworks Project</param>
            <returns name="Node">Nodes</returns>
            <search>Navisworks,Node</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisNodes.GetNodeChildren(DynaWorks22.Objects.OaNode)">
            <summary>
                Gets a List of all the children nodes of a Node if the Nodes is a group
            </summary>
            <param name="Node">Navisworks Node</param>
            <returns name="list">Nodes</returns>
            <search>Navisworks,Node</search>
        </member>
        <member name="T:DynaWorks22.Objects.NavisProperties">
            <summary>
            Navisworks Properties
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.NavisProperties.GetPropertiesList(DynaWorks22.FileSettings.OpenNavisFile,DynaWorks22.Objects.OaAttribute)">
            <summary>
                Gets a list of Navisworks property names from Attributes
            </summary>
            <param name="OpenNavisFile">Nodet</param>
            <param name="NavisAttribute">Class User Name</param>
            <returns name="NavisProperty">Node Attributes</returns>
            <search>Navisworks,property,attribute</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisProperties.GetValuesAsStringClassUserName(DynaWorks22.FileSettings.OpenNavisFile,System.Collections.Generic.IList{DynaWorks22.Objects.OaAttribute},System.String,System.String)">
            <summary>
                Returns a List of Property Values from Navisworks Attributes Class User Name and Property Name
            </summary>
            <param name="OpenNavisFile">Nodet</param>
            <param name="NavisAttributesList">Class User Name</param>
            <param name="ClassUserName">Class User Name</param>
            <param name="PropertyName">Class User Name</param>
            <returns name="string">Node Attributes</returns>
            <search>Navisworks,property,attribute</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisProperties.GetValuesAsStringClassName(DynaWorks22.FileSettings.OpenNavisFile,System.Collections.Generic.IList{DynaWorks22.Objects.OaAttribute},System.String,System.String)">
            <summary>
                Returns a List of Property Values from Navisworks Attributes ClassName and Property Name
            </summary>
            <param name="OpenNavisFile">Nodet</param>
            <param name="NavisAttributesList">Class User Name</param>
            <param name="ClassName">Class User Name</param>
            <param name="PropertyName">Class User Name</param>
            <returns name="string">Node Attributes</returns>
            <search>Navisworks,property,attribute</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisProperties.AddNewProperties(DynaWorks22.FileSettings.OpenNavisFile,DynaWorks22.Objects.OpSelection,System.String,System.String,System.String)">
            <summary>
            Add New Properties to Selection
            </summary>
            <param name="openNavisFile"></param>
            <param name="Selection"></param>
            <param name="tab"></param>
            <param name="field"></param>
            <param name="value"></param>
            <returns></returns>
        </member>
        <member name="T:DynaWorks22.Objects.NavisSelection">
            <summary>
                Gets the list of Attributes in a Node
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.NavisSelection.GetSelectionSetsInProject(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
                Gets list of selection sets in project
            </summary>
            <param name="OpenNavisFile">open Navisworks Project</param>
            <returns name="list">SelectionSets</returns>
            <search>Navisworks,SelectionSets</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisSelection.GetNodesFromSelectionSets(DynaWorks22.Objects.OpSelectionSet)">
            <summary>
                Selects all Nodes in SelectionSets list
            </summary>
            <param name="Selectsets">List of Selection Sets</param>
            <returns name="list">Nodes</returns>
            <search>Navisworks,Nodes</search>
        </member>
        <member name="M:DynaWorks22.Objects.NavisSelection.GetSelection(DynaWorks22.FileSettings.OpenNavisFile,DynaWorks22.Objects.OpSelectionSet)">
            <summary>
            Gets the Selection from the SelectionSet
            </summary>
            <param name="OpenNavisFile"></param>
            <param name="SelectionSet"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.NavisSelection.OverrideColor(DynaWorks22.FileSettings.OpenNavisFile,DynaWorks22.Objects.OpSelection,System.Int32,System.Int32,System.Int32)">
            <summary>
            Override Color by Selection
            </summary>
            <param name="OpenNavisFile"></param>
            <param name="Selection"></param>
            <param name="r"></param>
            <param name="g"></param>
            <param name="b"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.NavisSelection.OverrideTransparency(DynaWorks22.FileSettings.OpenNavisFile,DynaWorks22.Objects.OpSelection,System.Double)">
            <summary>
            Applies Transparency to Selections
            </summary>
            <param name="OpenNavisFile"></param>
            <param name="Selection"></param>
            <param name="Transparency"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.NavisSelection.GetCurrentSelection(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
            Get Current Mouse Selection of Objects
            </summary>
            <param name="OpenNavisFile"></param>
            <returns></returns>
        </member>
        <member name="T:DynaWorks22.Objects.OaAttribute">
            <summary>
                Gets the list of Attributes in a Node
            </summary>
        </member>
        <member name="P:DynaWorks22.Objects.OaAttribute.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.OaAttribute.getOaAttributeFromNode(DynaWorks22.Objects.OaNode)">
            <summary>
            Gets all the attributes from Objects
            </summary>
            <param name="node"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.OaAttribute.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.OaFragment3">
            <summary>
                Gets the Fragments (Geometry) in a Node
            </summary>
        </member>
        <member name="P:DynaWorks22.Objects.OaFragment3.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.OaFragment3.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.OaMaterial">
            <summary>
                Gets the Materials in a Node
            </summary>
        </member>
        <member name="P:DynaWorks22.Objects.OaMaterial.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.OaMaterial.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.OaProperty">
            <summary>
                Gets the list of Attributes in a Node
            </summary>
        </member>
        <member name="P:DynaWorks22.Objects.OaProperty.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.OaProperty.GetNavisProperties(DynaWorks22.FileSettings.OpenNavisFile,DynaWorks22.Objects.OaAttribute)">
            <summary>
            Gets the Properties from Attributes
            </summary>
            <param name="OpenNavisFile"></param>
            <param name="NavisAttribute"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.OaProperty.GetValueByUserClassAndByProperty(DynaWorks22.FileSettings.OpenNavisFile,System.Collections.Generic.IList{DynaWorks22.Objects.OaAttribute},System.String,System.String)">
            <summary>
            Gets the Property Value by User Class and Property Name
            </summary>
            <param name="OpenNavisFile"></param>
            <param name="NavisAttributesList"></param>
            <param name="ClassUserName"></param>
            <param name="PropertyName"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.OaProperty.GetValueByClassAndByProperty(DynaWorks22.FileSettings.OpenNavisFile,System.Collections.Generic.IList{DynaWorks22.Objects.OaAttribute},System.String,System.String)">
            <summary>
            
            </summary>
            <param name="OpenNavisFile"></param>
            <param name="NavisAttributesList"></param>
            <param name="ClassName"></param>
            <param name="PropertyName"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.OaProperty.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.OaNode">
            <summary>
                Wrapper for handling Navis Nodes
            </summary>
        </member>
        <member name="P:DynaWorks22.Objects.OaNode.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.OaNode.GetClashNodes(DynaWorks22.ClashDetection.OclTestResult,System.Boolean)">
            <summary>
            Get the Clashing Objects
            </summary>
            <param name="Result"></param>
            <param name="FirstClashItem"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Objects.OaNode.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.OpSelection">
            <summary>
                Selection Object
            </summary>
        </member>
        <member name="P:DynaWorks22.Objects.OpSelection.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.OpSelection.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Objects.OpSelectionSet">
            <summary>
                SelectionSet Object
            </summary>
        </member>
        <member name="P:DynaWorks22.Objects.OpSelectionSet.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Objects.OpSelectionSet.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.FileSettings.OpenNavisFile">
            <summary>
                Opened Navisworks File Object
            </summary>
        </member>
        <member name="F:DynaWorks22.FileSettings.OpenNavisFile._doc">
            <summary>
                Opened Navisworks Document
            </summary>
        </member>
        <member name="F:DynaWorks22.FileSettings.OpenNavisFile._state">
            <summary>
                Opened Navisworks File State
            </summary>
        </member>
        <member name="F:DynaWorks22.FileSettings.OpenNavisFile._fp">
            <summary>
            filename location for save command
            </summary>
        </member>
        <member name="M:DynaWorks22.FileSettings.OpenNavisFile.#ctor(NavisworksAutomationAPI19.Document,System.String,System.Boolean)">
            <summary>
                Constructor for the OpenNavisworks File.
            </summary>
        </member>
        <member name="M:DynaWorks22.FileSettings.OpenNavisFile.OpenFile(System.String,System.Boolean)">
            <summary>
                Opens a Navisworks File for a single session, can be open for UserInteraction or in the background to save on memory and GUI.
            </summary>
            <param name="FilePath">File path to the Autodesk Navisworks NWF File.</param>
            <param name="Visible">If Navisworks UI is opened</param>
            <returns name="OpenNavisFile">Opened Navisworks File</returns>
            <search>Navisworks,File</search>
        </member>
        <member name="M:DynaWorks22.FileSettings.OpenNavisFile.StayOpenFile(System.String)">
            <summary>
                Opens a Navisworks File and keeps it open once script has run.
            </summary>
            <param name="FilePath">File path to the Autodesk Navisworks NWF File.</param>
            <returns name="OpenNavisFile">Opened Navisworks File</returns>
            <search>Navisworks,File</search>
        </member>
        <member name="M:DynaWorks22.FileSettings.OpenNavisFile.AppendFile(DynaWorks22.FileSettings.OpenNavisFile,System.String)">
            <summary>
                Appends a file to the Navisworks open project
            </summary>
            <param name="OpenNavisFile">Opened Navisworks File</param>
            <param name="FilePath">File path to a appendable Navisworks File</param>
            <returns name="OpenNavisFile">Opened Navisworks File</returns>
            <search>Navisworks,File</search>
        </member>
        <member name="M:DynaWorks22.FileSettings.OpenNavisFile.SaveFile(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
            Saves the Current Open Navisworks Project
            </summary>
            <param name="OpenNavisFile"></param>
            <returns name="OpenNavisFile">Opened Navisworks File</returns>
            <search>Navisworks,File</search>
        </member>
        <member name="M:DynaWorks22.FileSettings.OpenNavisFile.SaveAs(DynaWorks22.FileSettings.OpenNavisFile,System.String)">
            <summary>
                SaveAs current opened Navisworks project
            </summary>
            <param name="OpenNavisFile">Opened Navisworks File</param>
            <param name="FilePath">File path to new saved Navisworks File</param>
            <returns name="OpenNavisFile">Opened Navisworks File</returns>
            <search>Navisworks,File</search>
        </member>
        <member name="M:DynaWorks22.FileSettings.OpenNavisFile.PublishFile(DynaWorks22.FileSettings.OpenNavisFile,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.String)">
            <summary>
            Publishes the Navisworks Project to nwd format. Please fill in all details
            </summary>
            <param name="OpenNavisFile">Opened Navisworks File</param>
            <param name="FileName">File path to new saved Navisworks File</param>
            <param name="Title">Title</param>
            <param name="Password">Password place empty string if none</param>
            <param name="Subject"></param>
            <param name="Author"></param>
            <param name="Publisher"></param>
            <param name="Copyright"></param>
            <param name="PublishedFor"></param>
            <param name="Comments"></param>
            <param name="Keywords"></param>
            <param name="RequiresPassword">Requires Password to Open</param>
            <param name="Resave">Can be resaved</param>
            <param name="DisplayOnOpen"></param>
            <param name="EmbedTexturesRecap"></param>
            <param name="EmbedDatabase"></param>
            <param name="PreventProps">Prevent Properties from being exported</param>
            <param name="Expire">File can Expire</param>
            <param name="ExpiryDate">String Expiry Date Year-Month-Day</param>
            <returns name="OpenNavisFile">Opened Navisworks File</returns>
            <search>Navisworks,File</search>
        </member>
        <member name="T:DynaWorks22.Views.OpView">
            <summary>
                Gets a list of saved views from the project
            </summary>
        </member>
        <member name="P:DynaWorks22.Views.OpView.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Views.OpView.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Views.OpSavedView">
            <summary>
                Gets a list of saved views from the project
            </summary>
        </member>
        <member name="F:DynaWorks22.Views.OpSavedView._sview">
            <summary>
                Native saved View
            </summary>
        </member>
        <member name="F:DynaWorks22.Views.OpSavedView._nView">
            <summary>
                NavisView Object
            </summary>
        </member>
        <member name="F:DynaWorks22.Views.OpSavedView._ilviews">
            <summary>
                List of NavisView Objects
            </summary>
        </member>
        <member name="T:DynaWorks22.Views.NvViewPoint">
            <summary>
                Gets a list of saved views from the project
            </summary>
        </member>
        <member name="P:DynaWorks22.Views.NvViewPoint.inobjects">
            <summary>
                inobjects Property
            </summary>
        </member>
        <member name="M:DynaWorks22.Views.NvViewPoint.ToString">
            <summary>
                ToString
            </summary>
        </member>
        <member name="T:DynaWorks22.Views.NavisViews">
            <summary>
                Gets a list of saved views from the project
            </summary>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.GetSavedViews(DynaWorks22.FileSettings.OpenNavisFile)">
            <summary>
                Gets a list of saved views from the project
            </summary>
            <param name="OpenNavisFile">Open Navisworks File</param>
            <returns name="GetSavedViews">Navisworks Views List</returns>
            <search>Navisworks,Views,List</search>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.GetSavedViewCommentsByName(DynaWorks22.FileSettings.OpenNavisFile,System.String)">
            <summary>
                Gets a list of comments from saved views from the project
            </summary>
            <param name="OpenNavisFile">Open Navisworks File</param>
            <param name="ViewName">View Name</param>
            <returns name="string">Navisworks Comments List</returns>
            <search>Navisworks,Views,Comments</search>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.CreateView(DynaWorks22.FileSettings.OpenNavisFile,System.String)">
            <summary>
            Create a new Saved View
            </summary>
            <param name="openNavisFile"></param>
            <param name="name"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.CreateAViewFolder(DynaWorks22.FileSettings.OpenNavisFile,System.String)">
            <summary>
            Creates a Folder for Saved Views
            </summary>
            <param name="openNavisFile"></param>
            <param name="name"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.CreateAnimation(DynaWorks22.FileSettings.OpenNavisFile,System.String)">
            <summary>
            Creates an Animation
            </summary>
            <param name="openNavisFile"></param>
            <param name="name"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.CreateViewInAnimation(DynaWorks22.FileSettings.OpenNavisFile,System.String,System.String)">
            <summary>
            Creates a view in an animation Folder
            </summary>
            <param name="openNavisFile"></param>
            <param name="Animation"></param>
            <param name="name"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.CreateViewInFolder(DynaWorks22.FileSettings.OpenNavisFile,System.String,System.String)">
            <summary>
            Creates a new View in a Folder The Folder must exist
            </summary>
            <param name="openNavisFile"></param>
            <param name="Folder"></param>
            <param name="name"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.GetView(DynaWorks22.Views.OpView)">
            <summary>
                Gets a ViewPoint from Navisworks View
            </summary>
            <param name="NavisView">Navisworks View</param>
            <returns name="ViewPoint">Navisworks View Point</returns>
            <search>Navisworks,Views</search>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.ApplyMaterialHideSetting(DynaWorks22.Views.OpView,System.Boolean,System.Boolean)">
            <summary>
            Apply Hide and Material Settings to Views
            </summary>
            <param name="navisView"></param>
            <param name="HideSetting"></param>
            <param name="MaterialSetting"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.RenameView(DynaWorks22.Views.OpView,System.String)">
            <summary>
            Users can rename Views
            </summary>
            <param name="navisView"></param>
            <param name="Name"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.GetCameraPoint(DynaWorks22.Views.OpView)">
            <summary>
                Gets the Camera point as a Geometry Point
            </summary>
            <param name="NavisView">NavisView</param>
            <returns name="Point">Geometry Point</returns>
            <search>Navisworks,Views,Point</search>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.UpdateCameraPoint(DynaWorks22.Views.OpView,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Update a Camera Position with Dynamo Point
            </summary>
            <param name="NavisView"></param>
            <param name="p"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.GetDirectionPoint(DynaWorks22.Views.OpView)">
            <summary>
                Gets the Camera Direction point as a Geometry Point
            </summary>
            <param name="NavisView">NavisView</param>
            <returns name="Point">Geometry Point</returns>
            <search>Navisworks,Views,Point</search>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.UpdateDirectionPoint(DynaWorks22.Views.OpView,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Update View Camera Direction with Point
            </summary>
            <param name="NavisView"></param>
            <param name="p"></param>
            <returns></returns>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.GetViewDirection(DynaWorks22.Views.OpView)">
            <summary>
                Gets the View Direction as a Geometry Vector
            </summary>
            <param name="NavisView">Navisworks View</param>
            <returns name="Vector">Geometry Vector</returns>
            <search>Navisworks,Views,Vector</search>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.mGetCameraPoint(DynaWorks22.Views.OpView)">
            <summary>
                Gets the Camera point as a Geometry Point in MM
            </summary>
            <param name="NavisView">NavisView</param>
            <returns name="Point">Geometry Point</returns>
            <search>Navisworks,Views,Point</search>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.mGetDirectionPoint(DynaWorks22.Views.OpView)">
            <summary>
                Gets the Camera Direction point as a Geometry Point in MM
            </summary>
            <param name="NavisView">NavisView</param>
            <returns name="Point">Geometry Point</returns>
            <search>Navisworks,Views,Point</search>
        </member>
        <member name="M:DynaWorks22.Views.NavisViews.mGetViewDirection(DynaWorks22.Views.OpView)">
            <summary>
                Gets the View Direction as a Geometry Vector in MM
            </summary>
            <param name="NavisView">Navisworks View</param>
            <returns name="Vector">Geometry Vector</returns>
            <search>Navisworks,Views,Vector</search>
        </member>
    </members>
</doc>
