{
  "Uuid": "22715bc5-f95f-43ee-9cfd-b6d6e47575a4",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Points.RoallerCoaster",
  "Description": "Cleans a set of Points using a segmenth Length",
  "Name": "CleanPointsbyCurvatureandSegmenthLength",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Points": {
        "Key": "Geometry.Points",
        "Value": "LunchBox.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByControlPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "f3aaf292dbf3496796fb21be19e7ae9b",
      "Inputs": [
        {
          "Id": "23523c08698347c0b7abda44277b479f",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "57bcb24f60ec4ab09e2ad28d850448ec",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by using explicit control points. NOTE 1: BSplineCurves with deg=1 have G1 discontinuities, which cause problems for extrusion, sweep, and other operations. They should be avoided. Use a PolyCurve instead. NOTE 2: If the curve is periodic (closed), then the first and last points MUST be the same.\n\nNurbsCurve.ByControlPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.Length",
      "Id": "108978dcdf0e464894a201873584853e",
      "Inputs": [
        {
          "Id": "778fb297eef24811a6f710f9401d7f5b",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d2288a15349a4e2d958a72f729d8e42f",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The total arc length of the curve\n\nCurve.Length: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0..v..d;",
      "Id": "47ba0b5c16c74a319898e782b0a6480d",
      "Inputs": [
        {
          "Id": "4bc469f5cc38482e8d7474000ab3f59b",
          "Name": "v",
          "Description": "v",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "609c64cd5f9645cd8ed42821534d66fe",
          "Name": "d",
          "Description": "d",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "57e5a086dd234043b102c998edd130f7",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.AddItemToEnd@var[]..[],var[]..[]",
      "Id": "561071e0dd7c47428049e48afa0c6ae1",
      "Inputs": [
        {
          "Id": "02158997b3cd4287bdaa11c455454412",
          "Name": "item",
          "Description": "Item to be added.Item could be an object or a list.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2ec2ef8393e04bcea65b5df5bde3d849",
          "Name": "list",
          "Description": "List to add on to.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "fb91f7f014d846dcab6e9427b42a6953",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Adds an item to the end of a list.\n\nList.AddItemToEnd (item: var[]..[], list: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtSegmentLength@double",
      "Id": "93265ca84970464caf5331f6247775dc",
      "Inputs": [
        {
          "Id": "77727cc2bf3b4860a373319a6c31b76f",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c6d404bb972d4759ac7a54c128a83591",
          "Name": "segmentLength",
          "Description": "The distance along the curve at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ba7fa94c533a4a22b0cd44c6d605d634",
          "Name": "Point",
          "Description": "The point at the given arc length",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point at a particular arc length along the curve\n\nCurve.PointAtSegmentLength (segmentLength: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByControlPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "1b71593e4abb44c4a7c9a737881c47da",
      "Inputs": [
        {
          "Id": "786439af27584e029b5482c0ca6e9792",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3fcc511758d24fea807554ba6662cbb4",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by using explicit control points. NOTE 1: BSplineCurves with deg=1 have G1 discontinuities, which cause problems for extrusion, sweep, and other operations. They should be avoided. Use a PolyCurve instead. NOTE 2: If the curve is periodic (closed), then the first and last points MUST be the same.\n\nNurbsCurve.ByControlPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtSegmentLength@double",
      "Id": "5ba90910fa0b47ecbe2318afe80f3ead",
      "Inputs": [
        {
          "Id": "46be026d976c449b803e90a58d820e1d",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e969c3c23de3410a93bd3a3e35acbaf1",
          "Name": "segmentLength",
          "Description": "The distance along the curve at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c5d3847ec92b48b194597f68d80bcc06",
          "Name": "Point",
          "Description": "The point at the given arc length",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point at a particular arc length along the curve\n\nCurve.PointAtSegmentLength (segmentLength: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "0fdc4a389ff64786b79f65437fbf9427",
      "Inputs": [
        {
          "Id": "33dbc4adfc26468ea5abe420dd1e4406",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0ff1ac0938b94f09835d2e9d379e832e",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by interpolating between points.\n\nNurbsCurve.ByPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtSegmentLength@double",
      "Id": "9ac9b66516ac4d8dacb4c032ac1162d2",
      "Inputs": [
        {
          "Id": "cb4d3c9f9909483389e94d26e9c3cd15",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7154d7b1136e4c769a629217d16e218a",
          "Name": "segmentLength",
          "Description": "The distance along the curve at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c6936af8c6ea451392c09dda79fc9218",
          "Name": "Point",
          "Description": "The point at the given arc length",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point at a particular arc length along the curve\n\nCurve.PointAtSegmentLength (segmentLength: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "points",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "78cf4ea667ae4afeb2f142a56765b25e",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "21d9a70a9f3841a48cd8380aa274f9ff",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "segmenthDistance",
        "TypeName": "double",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "15bbdf2f4d854387b61662bb03c84ac6",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "ceb55b9732c24def94055c758525024a",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "NurbsCurve",
      "Id": "ca394cf8fb88437790fc728582e40451",
      "Inputs": [
        {
          "Id": "645ad5c725c14bb086acacca3a914fe6",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Point[]",
      "Id": "eea270b759624734ac8a3982f0645d59",
      "Inputs": [
        {
          "Id": "fb20119057d348d69807300e643cf390",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "57bcb24f60ec4ab09e2ad28d850448ec",
      "End": "778fb297eef24811a6f710f9401d7f5b",
      "Id": "14261157feed409f8b65eed8886172be"
    },
    {
      "Start": "57bcb24f60ec4ab09e2ad28d850448ec",
      "End": "77727cc2bf3b4860a373319a6c31b76f",
      "Id": "09e2e3b6fd124dc892cdfb43b838f999"
    },
    {
      "Start": "d2288a15349a4e2d958a72f729d8e42f",
      "End": "4bc469f5cc38482e8d7474000ab3f59b",
      "Id": "4eb44f9aa0bd48ce897c2643f395f891"
    },
    {
      "Start": "d2288a15349a4e2d958a72f729d8e42f",
      "End": "02158997b3cd4287bdaa11c455454412",
      "Id": "c3b775ce4f8a4386a984a9509f2d5963"
    },
    {
      "Start": "57e5a086dd234043b102c998edd130f7",
      "End": "2ec2ef8393e04bcea65b5df5bde3d849",
      "Id": "9a266bdfad1a44ecbc36d26561516107"
    },
    {
      "Start": "fb91f7f014d846dcab6e9427b42a6953",
      "End": "c6d404bb972d4759ac7a54c128a83591",
      "Id": "8c162687d10a496bb19c1081ce6ff3c8"
    },
    {
      "Start": "fb91f7f014d846dcab6e9427b42a6953",
      "End": "e969c3c23de3410a93bd3a3e35acbaf1",
      "Id": "2fa8abae7bd744e091dd0c0cfbcff85f"
    },
    {
      "Start": "fb91f7f014d846dcab6e9427b42a6953",
      "End": "7154d7b1136e4c769a629217d16e218a",
      "Id": "670a2e12c38f437db4314e40ba647f06"
    },
    {
      "Start": "ba7fa94c533a4a22b0cd44c6d605d634",
      "End": "786439af27584e029b5482c0ca6e9792",
      "Id": "cd29b3a3f4a54d849be49245135ec5a9"
    },
    {
      "Start": "3fcc511758d24fea807554ba6662cbb4",
      "End": "46be026d976c449b803e90a58d820e1d",
      "Id": "902faa0c88414647b40d42c72add834a"
    },
    {
      "Start": "c5d3847ec92b48b194597f68d80bcc06",
      "End": "33dbc4adfc26468ea5abe420dd1e4406",
      "Id": "7bb6ded2558f4d06b59edd19d0737bc0"
    },
    {
      "Start": "0ff1ac0938b94f09835d2e9d379e832e",
      "End": "cb4d3c9f9909483389e94d26e9c3cd15",
      "Id": "b13485865f894bebbf42d7d3cb57049f"
    },
    {
      "Start": "0ff1ac0938b94f09835d2e9d379e832e",
      "End": "645ad5c725c14bb086acacca3a914fe6",
      "Id": "a1671e7a7d704328aca4f4d766c60374"
    },
    {
      "Start": "c6936af8c6ea451392c09dda79fc9218",
      "End": "fb20119057d348d69807300e643cf390",
      "Id": "5066562bf03e4d78ae92dfc9b63b983b"
    },
    {
      "Start": "21d9a70a9f3841a48cd8380aa274f9ff",
      "End": "23523c08698347c0b7abda44277b479f",
      "Id": "9b0cc4e57022400a91ceea7b221572f2"
    },
    {
      "Start": "ceb55b9732c24def94055c758525024a",
      "End": "609c64cd5f9645cd8ed42821534d66fe",
      "Id": "415da8f5d9dc42b89e18dfa814012201"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -54.205751442834668,
      "EyeY": 41.831236577905251,
      "EyeZ": -60.662400012455272,
      "LookX": 37.1850057986054,
      "LookY": -43.268074246310213,
      "LookZ": 58.796706449422622,
      "UpX": 0.17842282810891619,
      "UpY": 0.94264149109226314,
      "UpZ": 0.28212109754704723
    },
    "NodeViews": [
      {
        "ShowGeometry": false,
        "Name": "NurbsCurve.ByControlPoints",
        "Id": "f3aaf292dbf3496796fb21be19e7ae9b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 250.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": false,
        "Name": "Curve.Length",
        "Id": "108978dcdf0e464894a201873584853e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 477.100040786931,
        "Y": 95.0474776993778
      },
      {
        "ShowGeometry": false,
        "Name": "Code Block",
        "Id": "47ba0b5c16c74a319898e782b0a6480d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 710.17557216929117,
        "Y": 208.80131955342472
      },
      {
        "ShowGeometry": false,
        "Name": "List.AddItemToEnd",
        "Id": "561071e0dd7c47428049e48afa0c6ae1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 858.93350019517266,
        "Y": 64.8328612548122
      },
      {
        "ShowGeometry": false,
        "Name": "Curve.PointAtSegmentLength",
        "Id": "93265ca84970464caf5331f6247775dc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 928.28115022596057,
        "Y": 235.6504922333279
      },
      {
        "ShowGeometry": false,
        "Name": "NurbsCurve.ByControlPoints",
        "Id": "1b71593e4abb44c4a7c9a737881c47da",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1446.7074366071697,
        "Y": 147.76821969529919
      },
      {
        "ShowGeometry": false,
        "Name": "Curve.PointAtSegmentLength",
        "Id": "5ba90910fa0b47ecbe2318afe80f3ead",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1630.7765321025931,
        "Y": 16.005014091112685
      },
      {
        "ShowGeometry": false,
        "Name": "NurbsCurve.ByPoints",
        "Id": "0fdc4a389ff64786b79f65437fbf9427",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1938.7023297625396,
        "Y": 322.75418591061123
      },
      {
        "ShowGeometry": false,
        "Name": "Curve.PointAtSegmentLength",
        "Id": "9ac9b66516ac4d8dacb4c032ac1162d2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2223.659389261918,
        "Y": 185.51038004515442
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "78cf4ea667ae4afeb2f142a56765b25e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "15bbdf2f4d854387b61662bb03c84ac6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 150.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "ca394cf8fb88437790fc728582e40451",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2543.659389261918,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "eea270b759624734ac8a3982f0645d59",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2543.659389261918,
        "Y": 150.0
      }
    ],
    "Annotations": [],
    "X": -555.0,
    "Y": 468.0,
    "Zoom": 1.0
  }
}