{
  "Uuid": "b05f2998-d2f5-4edd-92c6-814a9523c12c",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Revit.Elements.Floor",
  "Description": "Creates multiple floors by two sets of points",
  "Name": "FloorbyLevelandtwosetsofPointsM",
  "ElementResolver": {
    "ResolutionMap": {
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Level.Elevation",
      "Id": "dc2fcd526b164a22abdd95f4ee6f1ebb",
      "Inputs": [
        {
          "Id": "d0b67156fc304d4692ef549cfb9b2685",
          "Name": "level",
          "Description": "Revit.Elements.Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "54d2076990594187836838c51cef2897",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The elevation of the level above ground level\n\nLevel.Elevation: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "b0ad1f102979439c82f081f020cecd16",
      "Inputs": [
        {
          "Id": "089cfee2c108410b9846106572b80eab",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "fbcd5f5ae4b843ebb85be1e57a887422",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "6c1b2ff5be4c4e378fac3722848e841d",
      "Inputs": [
        {
          "Id": "70045247dedd4120881fc9a46654a256",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bb713c60b3904eda9c06d14663760267",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c91e0fc133dd4066a7f8e96c0938da0b",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "faf7de5a8d71454ebda0513173713452",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "75ae86a20ac04ea1b1076fb0f38e284c",
      "Inputs": [
        {
          "Id": "05b3161c748a483db03f6336b6cb90a8",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "04f8f86086cb4318acab851dc0066448",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "2546a2f53d054ae7b762d193fb49ad3d",
      "Inputs": [
        {
          "Id": "b4bf9c701904449db3007768f87842e8",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "59a02a17837a46e1aaf3036d828ada08",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "d6b15f038ff14d4899c6eaeea485092d",
      "Inputs": [
        {
          "Id": "d0e4a1b5c1f74f24b364c9f1cf0b9069",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3e639123791b467b8ba354b89fc4b550",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fad6924acf0b41218c13ae2178c681e1",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9b8ee6274482451e81b08286402332ad",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByControlPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "585a262e88c442b0856ef808a9aa94ee",
      "Inputs": [
        {
          "Id": "14b3b6a940574b7fbba3d193971e4481",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cf72ef7992134682985bb98cbfc43b65",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by using explicit control points. NOTE 1: BSplineCurves with deg=1 have G1 discontinuities, which cause problems for extrusion, sweep, and other operations. They should be avoided. Use a PolyCurve instead. NOTE 2: If the curve is periodic (closed), then the first and last points MUST be the same.\n\nNurbsCurve.ByControlPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByControlPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "0a534db7d3714cbf94194fb302baa471",
      "Inputs": [
        {
          "Id": "0f7d9b430bd24d91a693b1cafdc4388c",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7488435b62674b3194819b667b56f2d8",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by using explicit control points. NOTE 1: BSplineCurves with deg=1 have G1 discontinuities, which cause problems for extrusion, sweep, and other operations. They should be avoided. Use a PolyCurve instead. NOTE 2: If the curve is periodic (closed), then the first and last points MUST be the same.\n\nNurbsCurve.ByControlPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "02d0fa36e49f48b4a2b8e12b57aaaf08",
      "Inputs": [
        {
          "Id": "5c72bff788eb4017b95274d8ac6c1e7d",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0f95de552ee64c4f8b0d6985632fb857",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "6a1fd48a739642b4b52a38370e748da0",
      "Inputs": [
        {
          "Id": "48cc69d85d224030b2c3273b3934448a",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1248e67df7cb4ac29271cb359c4f710d",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4df78f285df043b69f92c0b9604a7937",
          "Name": "list",
          "Description": "A list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Transpose@var[]..[]",
      "Id": "ee428276af2d45b9a816f4f04a3b91b2",
      "Inputs": [
        {
          "Id": "7d857514895e459c952418a4ddea2ce7",
          "Name": "lists",
          "Description": "A list of lists to be transposed.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "5d8c7379169f448aa1b499833a234792",
          "Name": "lists",
          "Description": "A list of transposed lists.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Swaps rows and columns in a list of lists. If there are some rows that are shorter than others, null values are inserted as place holders in the resultant array such that it is always rectangular.\n\nList.Transpose (lists: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "cf1302094e90450f83e790a0e68ad7bb",
      "Inputs": [
        {
          "Id": "759b4f6417c24e808d24b3fab9713f49",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0b1e372a54c143a18fd08c5c13029b33",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by lofting between input cross section Curves.\n\nSurface.ByLoft (crossSections: Curve[]): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PerimeterCurves",
      "Id": "b3d9d43d3d9a48b29278dba7829477ad",
      "Inputs": [
        {
          "Id": "0f0fd29ecfbe4b4ea774eecb10460c41",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ee23d9492c19425ba7e88b2f9a22fd99",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return all the boundary Curves of the Surface.\n\nSurface.PerimeterCurves ( ): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "level",
        "TypeName": "Revit.Elements.Level",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "80c61a1a950341ceb74187afd3eea0bd",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "0569deae1ee24933a381466687f693ed",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "point",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "b7450f9b4d3f405699074bc06d351221",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "de3b5da4eb3d4fed82ec4368cdd2e8b3",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "point",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "2410636a922d4b9aa2eab60e042a4823",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1b3109991a874e13bf897b165eb4a62c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Curve[]",
      "Id": "796cf4275f7649adb6b6c64a4dd57c1e",
      "Inputs": [
        {
          "Id": "b293e7d4f3a34e10b48a14917447920a",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "54d2076990594187836838c51cef2897",
      "End": "c91e0fc133dd4066a7f8e96c0938da0b",
      "Id": "9421ee565d38441ca8542e2dd03ef5d0"
    },
    {
      "Start": "54d2076990594187836838c51cef2897",
      "End": "fad6924acf0b41218c13ae2178c681e1",
      "Id": "ae453fd645ca46ff8bcaa080ec05a2f2"
    },
    {
      "Start": "fbcd5f5ae4b843ebb85be1e57a887422",
      "End": "70045247dedd4120881fc9a46654a256",
      "Id": "6e5cd4ae798c464eb4eecc1451496233"
    },
    {
      "Start": "faf7de5a8d71454ebda0513173713452",
      "End": "0f7d9b430bd24d91a693b1cafdc4388c",
      "Id": "878c05bc29b5418faeaf423627e43e1f"
    },
    {
      "Start": "04f8f86086cb4318acab851dc0066448",
      "End": "bb713c60b3904eda9c06d14663760267",
      "Id": "6532558f8b5f412fa5cb40a1991e37d2"
    },
    {
      "Start": "59a02a17837a46e1aaf3036d828ada08",
      "End": "d0e4a1b5c1f74f24b364c9f1cf0b9069",
      "Id": "2a07eab599204c7abae455f21c3f72ea"
    },
    {
      "Start": "9b8ee6274482451e81b08286402332ad",
      "End": "14b3b6a940574b7fbba3d193971e4481",
      "Id": "16a2beea924b4bbfa03ebc8a14ef71ec"
    },
    {
      "Start": "cf72ef7992134682985bb98cbfc43b65",
      "End": "1248e67df7cb4ac29271cb359c4f710d",
      "Id": "c1dda396078f4233891d34ee1da54b0d"
    },
    {
      "Start": "7488435b62674b3194819b667b56f2d8",
      "End": "48cc69d85d224030b2c3273b3934448a",
      "Id": "f3dcf03b4afa410fb555379916dbf139"
    },
    {
      "Start": "0f95de552ee64c4f8b0d6985632fb857",
      "End": "3e639123791b467b8ba354b89fc4b550",
      "Id": "ab260360a85d43ae8c0f2d2090e04d67"
    },
    {
      "Start": "4df78f285df043b69f92c0b9604a7937",
      "End": "7d857514895e459c952418a4ddea2ce7",
      "Id": "2479551c905847a7bef52d9aea690fe3"
    },
    {
      "Start": "5d8c7379169f448aa1b499833a234792",
      "End": "759b4f6417c24e808d24b3fab9713f49",
      "Id": "af72f12dc01d4217b35ee6ef7c518bfc"
    },
    {
      "Start": "0b1e372a54c143a18fd08c5c13029b33",
      "End": "0f0fd29ecfbe4b4ea774eecb10460c41",
      "Id": "8fc0192b09434509acafb50bfd3c44e5"
    },
    {
      "Start": "ee23d9492c19425ba7e88b2f9a22fd99",
      "End": "b293e7d4f3a34e10b48a14917447920a",
      "Id": "9df6756ba13f4f9e86aa1f1cc12c34da"
    },
    {
      "Start": "0569deae1ee24933a381466687f693ed",
      "End": "d0b67156fc304d4692ef549cfb9b2685",
      "Id": "366faafd44bb4c64947c2717f52a2efa"
    },
    {
      "Start": "de3b5da4eb3d4fed82ec4368cdd2e8b3",
      "End": "089cfee2c108410b9846106572b80eab",
      "Id": "cc0af51a477344069ba79efe2f47e5bb"
    },
    {
      "Start": "de3b5da4eb3d4fed82ec4368cdd2e8b3",
      "End": "05b3161c748a483db03f6336b6cb90a8",
      "Id": "6da5827600554eac890cac924583c2c6"
    },
    {
      "Start": "1b3109991a874e13bf897b165eb4a62c",
      "End": "b4bf9c701904449db3007768f87842e8",
      "Id": "255e78efc3ab414fb75032947fbe0783"
    },
    {
      "Start": "1b3109991a874e13bf897b165eb4a62c",
      "End": "5c72bff788eb4017b95274d8ac6c1e7d",
      "Id": "bb8bfef52331434c9746ae45de5ee8c5"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 54.410457371887382,
      "EyeY": 6.1879165153195643,
      "EyeZ": -54.775998538577227,
      "LookX": 16.237807172854296,
      "LookY": -16.512855269039118,
      "LookZ": -29.06679763186888,
      "UpX": 0.11798474873873595,
      "UpY": 0.970295726276031,
      "UpZ": -0.21120085851056089
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Level.Elevation",
        "Id": "dc2fcd526b164a22abdd95f4ee6f1ebb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 250.0,
        "Y": 96.2434419644236
      },
      {
        "ShowGeometry": true,
        "Name": "Point.X",
        "Id": "b0ad1f102979439c82f081f020cecd16",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 255.5756897845813,
        "Y": 202.04932154993855
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "6c1b2ff5be4c4e378fac3722848e841d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 605.92414118620854,
        "Y": 142.24908532315249
      },
      {
        "ShowGeometry": true,
        "Name": "Point.Y",
        "Id": "75ae86a20ac04ea1b1076fb0f38e284c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 254.4049897181867,
        "Y": 311.83330837521169
      },
      {
        "ShowGeometry": true,
        "Name": "Point.X",
        "Id": "2546a2f53d054ae7b762d193fb49ad3d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 265.6718230333654,
        "Y": 382.22477214888465
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "d6b15f038ff14d4899c6eaeea485092d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 596.6588933187968,
        "Y": 379.72730992009667
      },
      {
        "ShowGeometry": true,
        "Name": "NurbsCurve.ByControlPoints",
        "Id": "585a262e88c442b0856ef808a9aa94ee",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 840.78972406851062,
        "Y": 339.04600046790245
      },
      {
        "ShowGeometry": true,
        "Name": "NurbsCurve.ByControlPoints",
        "Id": "0a534db7d3714cbf94194fb302baa471",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 847.1503509164686,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Point.Y",
        "Id": "02d0fa36e49f48b4a2b8e12b57aaaf08",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 263.08915477155824,
        "Y": 466.59333145666267
      },
      {
        "ShowGeometry": true,
        "Name": "List Create",
        "Id": "6a1fd48a739642b4b52a38370e748da0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1132.2104136273517,
        "Y": 182.65085230708826
      },
      {
        "ShowGeometry": true,
        "Name": "List.Transpose",
        "Id": "ee428276af2d45b9a816f4f04a3b91b2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1284.5975972518395,
        "Y": 193.008041089706
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ByLoft",
        "Id": "cf1302094e90450f83e790a0e68ad7bb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1497.9503416976595,
        "Y": 195.486321021877
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.PerimeterCurves",
        "Id": "b3d9d43d3d9a48b29278dba7829477ad",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1913.0861583770243,
        "Y": 196.93903363862222
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "80c61a1a950341ceb74187afd3eea0bd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "b7450f9b4d3f405699074bc06d351221",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -11.432620376596674,
        "Y": 220.2289537419511
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "2410636a922d4b9aa2eab60e042a4823",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -17.965546306080569,
        "Y": 485.931092612161
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "796cf4275f7649adb6b6c64a4dd57c1e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2392.5835129531106,
        "Y": 0.0
      }
    ],
    "Annotations": [],
    "X": -1076.223912920193,
    "Y": 70.066715065338627,
    "Zoom": 0.79882542504955845
  }
}