{
  "Uuid": "21110ea5-af76-4908-b1e1-f1d840fd1da6",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Curves",
  "Description": "Create Points from a Curve using a given segment length",
  "Name": "PointsfromCurvebyNSegmenthLength",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.Length",
      "Id": "1a30f9d6e70d46748e8583ad09bcc2a6",
      "Inputs": [
        {
          "Id": "96bb5e6d43a44382b01084bcf10da16b",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9c95271ae2ff4e02a552cf762ac7b0b4",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The total arc length of the curve\n\nCurve.Length: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0..a..b;",
      "Id": "2e6346318af14b9a833f96434d78f1c9",
      "Inputs": [
        {
          "Id": "3065221d51eb453e8710ef9395b9c338",
          "Name": "a",
          "Description": "a",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "42f2a6914dd04eea8881c58a268a317b",
          "Name": "b",
          "Description": "b",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d40fff6cfceb4d899d4e5815380da296",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.AddItemToEnd@var[]..[],var[]..[]",
      "Id": "a80c40518790421bbf39a06e91c52ba0",
      "Inputs": [
        {
          "Id": "b5293b31d5ce474ab3c33e5e808b976a",
          "Name": "item",
          "Description": "Item to be added.Item could be an object or a list.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cc3ed7ca076a4d5faa2c3f2dc65b2b01",
          "Name": "list",
          "Description": "List to add on to.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ffcc1424e05f483b93aa13013166868f",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Shortest",
      "Description": "Adds an item to the end of a list.\n\nList.AddItemToEnd (item: var[]..[], list: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtSegmentLength@double",
      "Id": "9695b928e3e3499aa0368ec41555c5ec",
      "Inputs": [
        {
          "Id": "9b69a7d7ed85403db295e449866928b0",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8fc67155bbcc42cf93060a66b347d4dd",
          "Name": "segmentLength",
          "Description": "The distance along the curve at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "537db1ac5acb4970a82245d140755926",
          "Name": "Point",
          "Description": "The point at the given arc length",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point at a particular arc length along the curve\n\nCurve.PointAtSegmentLength (segmentLength: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "curve",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "082db5ef222b4f79a667a5b15dc5339a",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "6262b111db804c518bd3b4b4ae988807",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "b",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "f7efbe8f78634faeafe97f439138dade",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1f74ab7bb8de4e90b8f93c9c642421a1",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Point[]",
      "Id": "5f04ae135dd64094bced449bd11fe061",
      "Inputs": [
        {
          "Id": "4e4045bc8cb14598818c5fdacc1652a1",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "9c95271ae2ff4e02a552cf762ac7b0b4",
      "End": "3065221d51eb453e8710ef9395b9c338",
      "Id": "49015cd6489748a0ac41beb35719fa7f"
    },
    {
      "Start": "9c95271ae2ff4e02a552cf762ac7b0b4",
      "End": "b5293b31d5ce474ab3c33e5e808b976a",
      "Id": "063e99ba7c5b449c83bf7a602e9f1cfd"
    },
    {
      "Start": "d40fff6cfceb4d899d4e5815380da296",
      "End": "cc3ed7ca076a4d5faa2c3f2dc65b2b01",
      "Id": "bc89f034607e4d9780b03129f24ba7f9"
    },
    {
      "Start": "ffcc1424e05f483b93aa13013166868f",
      "End": "8fc67155bbcc42cf93060a66b347d4dd",
      "Id": "a0be17f568b84c65b5930480bc1f18fa"
    },
    {
      "Start": "537db1ac5acb4970a82245d140755926",
      "End": "4e4045bc8cb14598818c5fdacc1652a1",
      "Id": "6f4b9f039e9a45c6b218c04b49deab73"
    },
    {
      "Start": "6262b111db804c518bd3b4b4ae988807",
      "End": "96bb5e6d43a44382b01084bcf10da16b",
      "Id": "ce401e7df5404de78a23ec3cbb45f5b2"
    },
    {
      "Start": "6262b111db804c518bd3b4b4ae988807",
      "End": "9b69a7d7ed85403db295e449866928b0",
      "Id": "7a7b60ac5bdf43e1a0a951fc7b8e5375"
    },
    {
      "Start": "1f74ab7bb8de4e90b8f93c9c642421a1",
      "End": "42f2a6914dd04eea8881c58a268a317b",
      "Id": "cc432ddb05f54378b79b4d5a75da25a8"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -12.769942247026538,
      "EyeY": 9.2743760868648888,
      "EyeZ": -7.9071236365815354,
      "LookX": 30.6441007118498,
      "LookY": -13.249204229632545,
      "LookZ": -0.43358708891262321,
      "UpX": 0.1907898984900076,
      "UpY": 0.98162718344773292,
      "UpZ": -0.0026995093593408376
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Curve.Length",
        "Id": "1a30f9d6e70d46748e8583ad09bcc2a6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 250.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "2e6346318af14b9a833f96434d78f1c9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 500.25944115903542,
        "Y": 119.19400969310675
      },
      {
        "ShowGeometry": true,
        "Name": "List.AddItemToEnd",
        "Id": "a80c40518790421bbf39a06e91c52ba0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 748.57925241678345,
        "Y": 93.1458360642286
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.PointAtSegmentLength",
        "Id": "9695b928e3e3499aa0368ec41555c5ec",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1019.4084720628217,
        "Y": 15.145836064228718
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "082db5ef222b4f79a667a5b15dc5339a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "f7efbe8f78634faeafe97f439138dade",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 62.0,
        "Y": 151.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "5f04ae135dd64094bced449bd11fe061",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1339.4084720628216,
        "Y": 0.0
      }
    ],
    "Annotations": [],
    "X": 168.0,
    "Y": 126.0,
    "Zoom": 1.0
  }
}