{
  "Uuid": "b545e308-7188-47e1-9eca-3a8df8abfd55",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Revit.Elements.StructuralFramings",
  "Description": "Projects Structural Framing Line to a Lower Level",
  "Name": "ProjectStructuralFramingtoLowerLevel",
  "ElementResolver": {
    "ResolutionMap": {
      "Category": {
        "Key": "Revit.Elements.Category",
        "Value": "RevitNodes.dll"
      },
      "Element": {
        "Key": "Revit.Elements.Element",
        "Value": "RevitNodes.dll"
      },
      "String": {
        "Key": "DSCore.String",
        "Value": "DSCoreNodes.dll"
      },
      "Geometry": {
        "Key": "Autodesk.DesignScript.Geometry.Geometry",
        "Value": "ProtoGeometry.dll"
      },
      "Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.GetParameterValueByName@string",
      "Id": "02a4ea2fd39249a3a22f1bc5845d74d7",
      "Inputs": [
        {
          "Id": "6e63294fc86e4ffea3d04333b1d671d4",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "da670ddfc0e94636bfb1e621d8ca067c",
          "Name": "parameterName",
          "Description": "The name of the parameter whose value you want to obtain.\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a79b893d662e4829af0c779c583c65f1",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the value of one of the element's parameters.\n\nElement.GetParameterValueByName (parameterName: string): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "\"Reference Level\";",
      "Id": "248978c425194b41b5d3f8b7f42128f6",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "5fcb5cf9159b4133b8bd03e5fa373fad",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "6069e206db2e4e01ac6437188c6ade3a",
      "Inputs": [
        {
          "Id": "1f164fe102384de59f38dc46c906b49f",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f8bb7aa8e0464652b184a786f3c6c907",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "99b973ff949846299dda4649e0ece661",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8029c75a5a6847bcaad84cb1cea2a526",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "a51c5a78-602f-4544-9888-38c441a9701c",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "5badd576e7324ac387b2d312dbf0e3f3",
      "Inputs": [
        {
          "Id": "b573e7f891564629b053008d66fd5c4d",
          "Name": "element",
          "Description": "Element[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "27dbe0d3d38642d898094e92fd8a28f5",
          "Name": "heigthValue",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a99fab925eb844c1861d361c06acdcbf",
          "Name": "levelValue",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get Lower Level from Level with Height"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "90545c98969344ea957300419b0141f9",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "36a5241abf4b468db4c3d1de8020c5de",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector",
      "Id": "22705074388942d5836f2fa8842209e3",
      "Inputs": [
        {
          "Id": "8eb90f986cc940dfa1ca1b07455ae5e4",
          "Name": "origin",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2f6b9646e3cb4b3c829608cfbb13d842",
          "Name": "normal",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "38e2bf71ffd54dc7b90c45f73695d447",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Plane centered at root Point, with input normal Vector.\n\nPlane.ByOriginNormal (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), normal: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PullOntoPlane@Autodesk.DesignScript.Geometry.Plane",
      "Id": "21fea6defcc5468ab392d3fe6571d05f",
      "Inputs": [
        {
          "Id": "8f3f98b197d143f293904f0a47ca9b92",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "def3cbd621844d3094c61bc707c8666c",
          "Name": "plane",
          "Description": "The plane on which to pull the curve\n\nPlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f0a85e0f868f48f393c9e1fb6d25b193",
          "Name": "Curve",
          "Description": "A Curve on the Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a curve by pulling onto plane\n\nCurve.PullOntoPlane (plane: Plane): Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "element",
        "TypeName": "Revit.Elements.Element",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "bb0cf9008eb84c5c90a0cd6df372b733",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "c2cc63bc909045499213042ea18a5f02",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "curve",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "f0103827c9504b5a927d4290f2836498",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "97fba7d29da24842beed012339fc2216",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "ProjectedCurve:Curve",
      "Id": "e72c287f70294dfa80425bbb162ea023",
      "Inputs": [
        {
          "Id": "9e2ea3b0349e466bafd3174a5604aa2f",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "a79b893d662e4829af0c779c583c65f1",
      "End": "b573e7f891564629b053008d66fd5c4d",
      "Id": "57abfcce2eec42b693679730b424694b"
    },
    {
      "Start": "5fcb5cf9159b4133b8bd03e5fa373fad",
      "End": "da670ddfc0e94636bfb1e621d8ca067c",
      "Id": "6633f05e4b69437aa25bbb8b5b301547"
    },
    {
      "Start": "8029c75a5a6847bcaad84cb1cea2a526",
      "End": "8eb90f986cc940dfa1ca1b07455ae5e4",
      "Id": "297859b274fd450f917bae60ae0f70eb"
    },
    {
      "Start": "27dbe0d3d38642d898094e92fd8a28f5",
      "End": "99b973ff949846299dda4649e0ece661",
      "Id": "359fb9ea66b94d70ad484b253bacdc16"
    },
    {
      "Start": "36a5241abf4b468db4c3d1de8020c5de",
      "End": "2f6b9646e3cb4b3c829608cfbb13d842",
      "Id": "ee76ad5bdc7c463cb55fd939f751cdb4"
    },
    {
      "Start": "38e2bf71ffd54dc7b90c45f73695d447",
      "End": "def3cbd621844d3094c61bc707c8666c",
      "Id": "14c62279ff194a79bfe0a0562203616c"
    },
    {
      "Start": "f0a85e0f868f48f393c9e1fb6d25b193",
      "End": "9e2ea3b0349e466bafd3174a5604aa2f",
      "Id": "a98489e38af4418ba2b4fabf57d31787"
    },
    {
      "Start": "c2cc63bc909045499213042ea18a5f02",
      "End": "6e63294fc86e4ffea3d04333b1d671d4",
      "Id": "595ffcb365d64a278e52bf6f6378b647"
    },
    {
      "Start": "97fba7d29da24842beed012339fc2216",
      "End": "8f3f98b197d143f293904f0a47ca9b92",
      "Id": "50bc58ad463d4ea8afb54e1d849f3989"
    }
  ],
  "Dependencies": [
    "a51c5a78-602f-4544-9888-38c441a9701c"
  ],
  "NodeLibraryDependencies": [
    {
      "Name": "PracticalBIM",
      "Version": "2020.0.26",
      "ReferenceType": "Package",
      "Nodes": [
        "5badd576e7324ac387b2d312dbf0e3f3"
      ]
    }
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.3.0.5885",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -208.36379628581716,
      "EyeY": 100.69508635650793,
      "EyeZ": -153.07631867734256,
      "LookX": 195.16730179367863,
      "LookY": -99.570709982983615,
      "LookZ": 142.78527019919864,
      "UpX": 0.14014621407436473,
      "UpY": 0.984807753012232,
      "UpZ": 0.10253159653330386
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Element.GetParameterValueByName",
        "Id": "02a4ea2fd39249a3a22f1bc5845d74d7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 510.06916077403389,
        "Y": 55.669677812212285
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "248978c425194b41b5d3f8b7f42128f6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 250.0,
        "Y": 175.46560573763549
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "6069e206db2e4e01ac6437188c6ade3a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 859.21252137756915,
        "Y": 188.74303134319683
      },
      {
        "ShowGeometry": true,
        "Name": "GetLowerLevelfromLevelwithHeight",
        "Id": "5badd576e7324ac387b2d312dbf0e3f3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 788.5890546019175,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.ZAxis",
        "Id": "90545c98969344ea957300419b0141f9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1084.3085289974795,
        "Y": 58.06856862875793
      },
      {
        "ShowGeometry": true,
        "Name": "Plane.ByOriginNormal",
        "Id": "22705074388942d5836f2fa8842209e3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1114.0803253070719,
        "Y": 160.71271895152529
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.PullOntoPlane",
        "Id": "21fea6defcc5468ab392d3fe6571d05f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1177.8039875192228,
        "Y": 324.74394715403741
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "bb0cf9008eb84c5c90a0cd6df372b733",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "f0103827c9504b5a927d4290f2836498",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 150.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "e72c287f70294dfa80425bbb162ea023",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1595.74688298353,
        "Y": 165.0478669076316
      }
    ],
    "Annotations": [],
    "X": 160.30560946874994,
    "Y": 382.28248581226808,
    "Zoom": 0.59376714062500013
  }
}