{
  "Uuid": "c25752b1-e755-4f7c-bfdc-401a0e439578",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Abstract.Topology",
  "Description": "Creates an Inner Latice of Elements to Centroid",
  "Name": "TopologyLaticetoCentroidbyRadius",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Math": {
        "Key": "DSCore.Math",
        "Value": "DSCoreNodes.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "DSCore.List": {
        "Key": "DSCore.List",
        "Value": "DSCoreNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.Centroid",
      "Id": "3010fafefd0e4d21986ad28e1ff156a7",
      "Inputs": [
        {
          "Id": "289af6514acf4b7eaea43147aa708d25",
          "Name": "solid",
          "Description": "Autodesk.DesignScript.Geometry.Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9b34341dc71d4eb29e14a272c7f54b44",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The centroid of the Solid\n\nSolid.Centroid ( ): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Topology.Vertices",
      "Id": "b66a6365dd0846d3926132f4f4e4dfc0",
      "Inputs": [
        {
          "Id": "024ba42369454ec59816da6f5804f6a5",
          "Name": "topology",
          "Description": "Autodesk.DesignScript.Geometry.Topology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9c3800a821d5498788fb684d9909d4c5",
          "Name": "Vertex[]",
          "Description": "Vertex[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Vertices of the Topology\n\nTopology.Vertices: Vertex[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vertex.PointGeometry",
      "Id": "2ff421540dd54393a54bd7ec11504c24",
      "Inputs": [
        {
          "Id": "7956fb76301e4cdbb721ac1191b5195a",
          "Name": "vertex",
          "Description": "Autodesk.DesignScript.Geometry.Vertex",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0697c5350fd3472e90ebc3a2e7b72d3f",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Point where this Vertex is located\n\nVertex.PointGeometry: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "115b7c05f6cf4108b3c74cd8ffea3e16",
      "Inputs": [
        {
          "Id": "63a4ff624d0d4559bb6987defe562281",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "600658b6ba8f4ed2aa955b706cc97b74",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "aea18071446f4fa7aa26da168f38183b",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "[0,1];",
      "Id": "185824db6725446d8e816d8714392b37",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d4415dc3ee0a44c88b53f9cebf460808",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PlaneAtParameter@double",
      "Id": "b1d4f42586734dbba14ed578f41c6f1d",
      "Inputs": [
        {
          "Id": "e79e203a1b32431795ad898ae83f9188",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3cdd7cf943394049b5db49342c891416",
          "Name": "param",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "745dcc512dda4fb39ffc0cf64f42d7ca",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "CrossProduct",
      "Description": "Returns a Plane whose normal aligns with the tangent of the Curve. Parameters are adjusted such that 0 is always the start Point and 1 is always the end Point.\n\nCurve.PlaneAtParameter (param: double = 0): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByPlaneRadius@Autodesk.DesignScript.Geometry.Plane,double",
      "Id": "ea9cc15b41134f9eb3dd0ed9756a1eb0",
      "Inputs": [
        {
          "Id": "2f97884e2ee043069201a309f56412ce",
          "Name": "plane",
          "Description": "Plane\nDefault value : Autodesk.DesignScript.Geometry.Plane.XY()",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b2304412363547b4a98c6ad3cbf2084e",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cfcd58fc32c8411eb67f31fad6bc0d56",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Circle centered at the input Plane origin (root), lying in the input Plane, with given radius.\n\nCircle.ByPlaneRadius (plane: Plane = Autodesk.DesignScript.Geometry.Plane.XY(), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "3c2456ecf3b142edbf6c10173f3a11bc",
      "Inputs": [
        {
          "Id": "be2a5483ebd643889c7d3a817177f205",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f4c4f9378ff14a5c9b8f9ae5f7ffc400",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid by lofting between input cross section closed Curves.\n\nSolid.ByLoft (crossSections: Curve[]): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "solid",
        "TypeName": "Autodesk.DesignScript.Geometry.Solid",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "64c38c4a5b7b40ce9579b4f785fea727",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "5a4be616c0a94f00a67ce528c9147629",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "radius",
        "TypeName": "double",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "6cec4d46258f4cba80ee785a487e0d60",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "75cf81a7e41344738bd08b4a0c5e2f6b",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Solid",
      "Id": "24051af5b1a548a085630cbe87581e8d",
      "Inputs": [
        {
          "Id": "54b4c949909443d2baf32c050741d74b",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Line",
      "Id": "0817cf91fcc8486f80bb1612cb6c9dea",
      "Inputs": [
        {
          "Id": "65268443a90841b193d30adace13628a",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "9b34341dc71d4eb29e14a272c7f54b44",
      "End": "63a4ff624d0d4559bb6987defe562281",
      "Id": "6534b1bd85b74e1f8daaafde7d944776"
    },
    {
      "Start": "9c3800a821d5498788fb684d9909d4c5",
      "End": "7956fb76301e4cdbb721ac1191b5195a",
      "Id": "4bd447ad26734a90961ac60a0ab0df03"
    },
    {
      "Start": "0697c5350fd3472e90ebc3a2e7b72d3f",
      "End": "600658b6ba8f4ed2aa955b706cc97b74",
      "Id": "51febd54648c4618a607e5ffff03bfe5"
    },
    {
      "Start": "aea18071446f4fa7aa26da168f38183b",
      "End": "e79e203a1b32431795ad898ae83f9188",
      "Id": "f2eb26813b6d45269e4815e6b4486943"
    },
    {
      "Start": "aea18071446f4fa7aa26da168f38183b",
      "End": "65268443a90841b193d30adace13628a",
      "Id": "b8eef441c0144edd9824fa11b32c6b60"
    },
    {
      "Start": "d4415dc3ee0a44c88b53f9cebf460808",
      "End": "3cdd7cf943394049b5db49342c891416",
      "Id": "8271fb6f5f394334bd5511b52eb55711"
    },
    {
      "Start": "745dcc512dda4fb39ffc0cf64f42d7ca",
      "End": "2f97884e2ee043069201a309f56412ce",
      "Id": "b78d14649fba4d9dab0f0b77210d21fb"
    },
    {
      "Start": "cfcd58fc32c8411eb67f31fad6bc0d56",
      "End": "be2a5483ebd643889c7d3a817177f205",
      "Id": "887f550db52649b09e19231cb926a409"
    },
    {
      "Start": "f4c4f9378ff14a5c9b8f9ae5f7ffc400",
      "End": "54b4c949909443d2baf32c050741d74b",
      "Id": "12f477553df34195b717944d372e7cc3"
    },
    {
      "Start": "5a4be616c0a94f00a67ce528c9147629",
      "End": "289af6514acf4b7eaea43147aa708d25",
      "Id": "3d3e20845b41465789a07e949fdad91d"
    },
    {
      "Start": "5a4be616c0a94f00a67ce528c9147629",
      "End": "024ba42369454ec59816da6f5804f6a5",
      "Id": "35d70bb0317c4006a519b75db49ae183"
    },
    {
      "Start": "75cf81a7e41344738bd08b4a0c5e2f6b",
      "End": "b2304412363547b4a98c6ad3cbf2084e",
      "Id": "bfd9cfd38c9441e3937f3c9b8367b0e8"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -5.7430290951172545,
      "EyeY": 4.09649083664278,
      "EyeZ": -11.994309895207378,
      "LookX": 9.20123566833407,
      "LookY": -4.8731766546643875,
      "LookZ": 17.443850357892927,
      "UpX": 0.012212878112811507,
      "UpY": 0.99965734034377085,
      "UpZ": 0.023153371218987532
    },
    "NodeViews": [
      {
        "Id": "3010fafefd0e4d21986ad28e1ff156a7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Solid.Centroid",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 471.46360886612092,
        "Y": 90.974408132402459
      },
      {
        "Id": "b66a6365dd0846d3926132f4f4e4dfc0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Topology.Vertices",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 250.0,
        "Y": 149.87012384131594
      },
      {
        "Id": "2ff421540dd54393a54bd7ec11504c24",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vertex.PointGeometry",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 532.46981312629578,
        "Y": 283.49618600293525
      },
      {
        "Id": "115b7c05f6cf4108b3c74cd8ffea3e16",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Line.ByStartPointEndPoint",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 775.132856298007,
        "Y": 175.89927025846578
      },
      {
        "Id": "185824db6725446d8e816d8714392b37",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 929.67048887718011,
        "Y": 44.212002654263642
      },
      {
        "Id": "b1d4f42586734dbba14ed578f41c6f1d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PlaneAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1104.1614413921088,
        "Y": 50.28911443978609
      },
      {
        "Id": "ea9cc15b41134f9eb3dd0ed9756a1eb0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Circle.ByPlaneRadius",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1431.1810392961706,
        "Y": 47.909059347337234
      },
      {
        "Id": "3c2456ecf3b142edbf6c10173f3a11bc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Solid.ByLoft",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1695.3372563702524,
        "Y": 0.0
      },
      {
        "Id": "64c38c4a5b7b40ce9579b4f785fea727",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "Id": "6cec4d46258f4cba80ee785a487e0d60",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 300.0
      },
      {
        "Id": "24051af5b1a548a085630cbe87581e8d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2001.3372563702524,
        "Y": 0.0
      },
      {
        "Id": "0817cf91fcc8486f80bb1612cb6c9dea",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2037.4179265658745,
        "Y": 159.73434125269978
      }
    ],
    "Annotations": [],
    "X": -1518.4425,
    "Y": 56.514999999999986,
    "Zoom": 1.1575
  }
}