{
  "Uuid": "edabe817-0e46-4c1f-be3a-92345ecb5bd6",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Abstract.Topology",
  "Description": "Creates a latice model of the topology selected",
  "Name": "TopologyLaticebyRadius",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Topology.Edges",
      "Id": "599428e279064d49910aa15f95867c3f",
      "Inputs": [
        {
          "Id": "ab94ef45612d4d8b854a70649fc6ad94",
          "Name": "topology",
          "Description": "Autodesk.DesignScript.Geometry.Topology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "224f774f1c2b4a159ab3e9d4ab4b6050",
          "Name": "Edge[]",
          "Description": "Edge[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Edges of the Topology\n\nTopology.Edges: Edge[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Topology.Vertices",
      "Id": "0f4a7c13c9e849d58f288bc99a70588f",
      "Inputs": [
        {
          "Id": "16c4d111e12e42eba21559c8d8834bf2",
          "Name": "topology",
          "Description": "Autodesk.DesignScript.Geometry.Topology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "71544cd7d8f4429c998f4e29deb7c901",
          "Name": "Vertex[]",
          "Description": "Vertex[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Vertices of the Topology\n\nTopology.Vertices: Vertex[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Edge.CurveGeometry",
      "Id": "ee89a1a2b24c48cf9ccf8dbf35440f7b",
      "Inputs": [
        {
          "Id": "666300cb0c3d40b6a98fc32cfd8f2f87",
          "Name": "edge",
          "Description": "Autodesk.DesignScript.Geometry.Edge",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a046d365aca14207a938571c4065f674",
          "Name": "Curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The underlying Curve making up the Edge\n\nEdge.CurveGeometry: Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "[0,1];",
      "Id": "9dd290a8bf044142b084cf5690084852",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "85216db4a87e48b3bdd7fd3b6d474722",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vertex.PointGeometry",
      "Id": "ea7902fe99bd40e18d11a6989ffb2fb1",
      "Inputs": [
        {
          "Id": "f4fa269c106747979db8b73a0bd37b55",
          "Name": "vertex",
          "Description": "Autodesk.DesignScript.Geometry.Vertex",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "98a584d2bf7049dd9323062dd1d7925d",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Point where this Vertex is located\n\nVertex.PointGeometry: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PlaneAtParameter@double",
      "Id": "a26ec18e016d4e3cb1431bd35e6df88b",
      "Inputs": [
        {
          "Id": "bd54c3d1591a4e8ea548ab1adb83bb5c",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b3c967bfe9da434db7ff2ccc67e4d4f5",
          "Name": "param",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "712b7e88997243b8929fdff4ba590f30",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "CrossProduct",
      "Description": "Returns a Plane whose normal aligns with the tangent of the Curve. Parameters are adjusted such that 0 is always the start Point and 1 is always the end Point.\n\nCurve.PlaneAtParameter (param: double = 0): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByPlaneRadius@Autodesk.DesignScript.Geometry.Plane,double",
      "Id": "5592f6a190ec464cb0fd3b650c381f7d",
      "Inputs": [
        {
          "Id": "dd083ae841d2489c889f26a789ecec8a",
          "Name": "plane",
          "Description": "Plane\nDefault value : Autodesk.DesignScript.Geometry.Plane.XY()",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5c23376ca4bb48e884c0203b19f1eea9",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "de57cbcadee243e78a72d29a6c0403ac",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Circle centered at the input Plane origin (root), lying in the input Plane, with given radius.\n\nCircle.ByPlaneRadius (plane: Plane = Autodesk.DesignScript.Geometry.Plane.XY(), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "681df46eeabd4ee9b93c683e2944ed38",
      "Inputs": [
        {
          "Id": "513ebbb7d5e7426a83609235a1193abf",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b49fde0262424838b2d54188d8e099aa",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "35c9515dec354c80b4aca4220e9f5b05",
          "Name": "Sphere",
          "Description": "Sphere",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid Sphere cetered at the input Point, with given radius.\n\nSphere.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Sphere"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "2b50fef7a72041b0b010fce7c93fa0d2",
      "Inputs": [
        {
          "Id": "bb772500ebee45a8974e0e893d5e4da2",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1be852757b274eafb6195b68f38fe5a3",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid by lofting between input cross section closed Curves.\n\nSolid.ByLoft (crossSections: Curve[]): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction, DynamoCore",
      "FunctionSignature": "DSCore.List.Join@var[]..[]",
      "FunctionType": "VariableArgument",
      "NodeType": "FunctionNode",
      "Id": "b87da22acc30408f922236ef7b63dadb",
      "Inputs": [
        {
          "Id": "11b9a1620f08423c98e91efc3a9a0c7a",
          "Name": "list0",
          "Description": "Lists to join into one.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "454a1c00be114cae8ed21bf483a579e2",
          "Name": "list1",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f348cc28101a42f99d6c39bb98b12f25",
          "Name": "list",
          "Description": "Joined list.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Concatenates all given lists into a single list.\n\nList.Join (lists: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.ByUnion@Autodesk.DesignScript.Geometry.Solid[]",
      "Id": "c8108ec7d63c4779a80dee85c387e0ca",
      "Inputs": [
        {
          "Id": "5b5cdb8e6e89446b9cd12aa1b55c389a",
          "Name": "solids",
          "Description": "A collection of solids\n\nSolid[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1d8a51cf83bc4fb79af216ef43450404",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Union a collection of solids into one solid\n\nSolid.ByUnion (solids: Solid[]): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "topology",
        "TypeName": "Autodesk.DesignScript.Geometry.Topology",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "78eb0245d38d4af4b3da64885f34f01d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a266ba6f75834c909acc9ffdd2a18dc6",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "radius",
        "TypeName": "double",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "de87c21553bc468c8a1787dd4deca63f",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f94725b6e2e64fe7a7a885a73f691e14",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Solid",
      "Id": "56f82610a804489a986ef3708b09f67d",
      "Inputs": [
        {
          "Id": "35ae7622208e459197722587053f3aab",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Points[]",
      "Id": "565685ccc4284a679803fa802465dab3",
      "Inputs": [
        {
          "Id": "9f702c87e3e14ebaa27d3cc41350ade3",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Line[]",
      "Id": "2442cb79ee144a84bb1f86640f5e90e6",
      "Inputs": [
        {
          "Id": "810f0542f59f4703b7ee01817cfe1b02",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "224f774f1c2b4a159ab3e9d4ab4b6050",
      "End": "666300cb0c3d40b6a98fc32cfd8f2f87",
      "Id": "5b28579b65bb4ae9959501cd217466d1"
    },
    {
      "Start": "71544cd7d8f4429c998f4e29deb7c901",
      "End": "f4fa269c106747979db8b73a0bd37b55",
      "Id": "99e2c845c2c940dabe8f25fabed331b9"
    },
    {
      "Start": "a046d365aca14207a938571c4065f674",
      "End": "bd54c3d1591a4e8ea548ab1adb83bb5c",
      "Id": "c592987d59114d13b824340537c22065"
    },
    {
      "Start": "a046d365aca14207a938571c4065f674",
      "End": "810f0542f59f4703b7ee01817cfe1b02",
      "Id": "393f17f1e3aa4722b6e6a33e3fd26333"
    },
    {
      "Start": "85216db4a87e48b3bdd7fd3b6d474722",
      "End": "b3c967bfe9da434db7ff2ccc67e4d4f5",
      "Id": "ef22ae16c35f43edb9459cf0f9495be7"
    },
    {
      "Start": "98a584d2bf7049dd9323062dd1d7925d",
      "End": "513ebbb7d5e7426a83609235a1193abf",
      "Id": "ab16d932091341fda88d4577ff64668c"
    },
    {
      "Start": "98a584d2bf7049dd9323062dd1d7925d",
      "End": "9f702c87e3e14ebaa27d3cc41350ade3",
      "Id": "ca98ff1393b748ecbf11249640941457"
    },
    {
      "Start": "712b7e88997243b8929fdff4ba590f30",
      "End": "dd083ae841d2489c889f26a789ecec8a",
      "Id": "504be0a0a78c4ccaa68c6f66f6b4d962"
    },
    {
      "Start": "de57cbcadee243e78a72d29a6c0403ac",
      "End": "bb772500ebee45a8974e0e893d5e4da2",
      "Id": "3f0b857b91cc4c91a70a469c2245e954"
    },
    {
      "Start": "35c9515dec354c80b4aca4220e9f5b05",
      "End": "454a1c00be114cae8ed21bf483a579e2",
      "Id": "2f7200d0ffd14b7fa296ec4671738dd1"
    },
    {
      "Start": "1be852757b274eafb6195b68f38fe5a3",
      "End": "11b9a1620f08423c98e91efc3a9a0c7a",
      "Id": "35045d4b0079457b9cf53f3900dbbde5"
    },
    {
      "Start": "f348cc28101a42f99d6c39bb98b12f25",
      "End": "5b5cdb8e6e89446b9cd12aa1b55c389a",
      "Id": "c1dad1d9f8324f6a85212cdee0d88c19"
    },
    {
      "Start": "1d8a51cf83bc4fb79af216ef43450404",
      "End": "35ae7622208e459197722587053f3aab",
      "Id": "859391cd2fb74318b2ee0c2f976320a7"
    },
    {
      "Start": "a266ba6f75834c909acc9ffdd2a18dc6",
      "End": "ab94ef45612d4d8b854a70649fc6ad94",
      "Id": "00ebf5bc6bb247d59c97cc0455910d71"
    },
    {
      "Start": "a266ba6f75834c909acc9ffdd2a18dc6",
      "End": "16c4d111e12e42eba21559c8d8834bf2",
      "Id": "b96ff2a5e66147aeb9720fe759dff78a"
    },
    {
      "Start": "f94725b6e2e64fe7a7a885a73f691e14",
      "End": "5c23376ca4bb48e884c0203b19f1eea9",
      "Id": "df36b37822f749e49f4c9ea2ec4704f1"
    },
    {
      "Start": "f94725b6e2e64fe7a7a885a73f691e14",
      "End": "b49fde0262424838b2d54188d8e099aa",
      "Id": "ecc3256aac1c4d828220caa5be65311c"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 19.154712474402757,
      "EyeY": 33.735690514545482,
      "EyeZ": 2.2196300795342276,
      "LookX": -12.029298945282861,
      "LookY": -28.974025853450115,
      "LookZ": -6.3126762561687082,
      "UpX": -0.70249840362098015,
      "UpY": 0.608761429008721,
      "UpZ": -0.36865365244527154
    },
    "NodeViews": [
      {
        "Id": "599428e279064d49910aa15f95867c3f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Topology.Edges",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 251.280777537797,
        "Y": 41.863930885529157
      },
      {
        "Id": "0f4a7c13c9e849d58f288bc99a70588f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Topology.Vertices",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 250.0,
        "Y": 297.207343412527
      },
      {
        "Id": "ee89a1a2b24c48cf9ccf8dbf35440f7b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Edge.CurveGeometry",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 560.280777537797,
        "Y": 13.863930885529157
      },
      {
        "Id": "9dd290a8bf044142b084cf5690084852",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 820.69546436285111,
        "Y": 83.408207343412528
      },
      {
        "Id": "ea7902fe99bd40e18d11a6989ffb2fb1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vertex.PointGeometry",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 605.9395248380132,
        "Y": 472.585313174946
      },
      {
        "Id": "a26ec18e016d4e3cb1431bd35e6df88b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PlaneAtParameter",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 995.29373650107993,
        "Y": 0.0
      },
      {
        "Id": "5592f6a190ec464cb0fd3b650c381f7d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Circle.ByPlaneRadius",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 1501.8358531317494,
        "Y": 89.0
      },
      {
        "Id": "681df46eeabd4ee9b93c683e2944ed38",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Sphere.ByCenterPointRadius",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 1782.5473815238342,
        "Y": 484.87162451842619
      },
      {
        "Id": "2b50fef7a72041b0b010fce7c93fa0d2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Solid.ByLoft",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 1799.9774004060687,
        "Y": 136.51619870410366
      },
      {
        "Id": "b87da22acc30408f922236ef7b63dadb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Join",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 2204.0624359076828,
        "Y": 383.15429781902674
      },
      {
        "Id": "c8108ec7d63c4779a80dee85c387e0ca",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Solid.ByUnion",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2444.3721378328669,
        "Y": 342.71909442308561
      },
      {
        "Id": "78eb0245d38d4af4b3da64885f34f01d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "Id": "de87c21553bc468c8a1787dd4deca63f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 300.0
      },
      {
        "Id": "56f82610a804489a986ef3708b09f67d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2703.3721378328669,
        "Y": 0.0
      },
      {
        "Id": "565685ccc4284a679803fa802465dab3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2706.9329686934011,
        "Y": 655.19287833827889
      },
      {
        "Id": "2442cb79ee144a84bb1f86640f5e90e6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2686.754927150374,
        "Y": 770.326409495549
      }
    ],
    "Annotations": [],
    "X": -327.31000000000006,
    "Y": 198.7775,
    "Zoom": 0.8425
  }
}