<Workspace Version="1.3.1.1736" X="101.808128444118" Y="185.896710807304" zoom="0.784369328044827" ScaleFactor="1" Name="Pipe from strings" Description="Creates pipes from strings, be they detail lines or lines within a DWG file" ID="e7b4ecf8-42da-452f-bef6-f08dd9ef0070" Category="MisterMEP">
  <NamespaceResolutionMap>
    <ClassMap partialName="Level" resolvedName="Revit.Elements.Level" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="915a1231-7fbe-4515-baab-927893ee46f7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="164.085980501291" y="79.0062098398419" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;PolyCurve&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8e91bfc9-cced-47aa-bc14-e903f1b418ec" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="128.902224601584" y="-12.7811982441938" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="22ab1072-dad6-4f2a-a944-bf1f7ee3d73d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="RemoveIfNot" x="383.969674472808" y="-13.7362579514162" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="RemoveIfNot@var[]..[],string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ae188084-6e30-4140-b0e5-ec77ebe0486e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="109.320241404" y="279.739147822753" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3e3c6feb-796a-4247-a276-e135cd9a3978" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.Curves" x="618.528572753428" y="-13.1806248986216" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction guid="a4f70e3c-ba71-46e5-bb28-a8c241df430c" type="Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction" nickname="List.Join" x="900.319487859255" y="157.185966267544" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Join@var[]..[]" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3ac06919-12f6-4c2c-91d8-ec6b0cb256c5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1361.07440868686" y="192.722753658238" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e9f5f788-7db2-4493-a15b-5aa6a113f457" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1360.40205618691" y="107.191512834924" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="16278d33-0b0d-4d42-ac0b-8be5e87b3354" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Id" x="1354.77084237113" y="323.951943170151" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Id">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="979488f4-3639-438a-89e8-e986a40f79f4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1670.20175457721" y="145.746926078993" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference("RevitServices")
#import document manager and transaction manager
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#import revit api
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit.DB.Plumbing import *

#import revit nodes
clr.AddReference("RevitNodes")
import Revit
from Autodesk.Revit.DB import *
from Autodesk.Revit.Creation import *
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

doc =  DocumentManager.Instance.CurrentDBDocument

StartXYZ = IN[0]
EndXYZ = IN[1]
levelIdAsInt = IN[2]

levelElementId = Autodesk.Revit.DB.ElementId(levelIdAsInt) # create an element Id from integer

Output = []

TransactionManager.Instance.EnsureInTransaction(doc)
pipeTypeID = FilteredElementCollector(doc).OfClass(PipeType).FirstElement().Id
systemTypeID = FilteredElementCollector(doc).OfClass(PipingSystemType).FirstElement().Id
for index,x in enumerate(StartXYZ):
	StartPoint = StartXYZ[index].ToXyz()
	EndPoint = EndXYZ[index].ToXyz()
	
	pipe = Autodesk.Revit.DB.Plumbing.Pipe.Create(doc, systemTypeID, pipeTypeID, levelElementId, StartPoint, EndPoint)
	
	Output.append(pipe.Id)

TransactionManager.Instance.TransactionTaskDone()

OUT = Output
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="92097fac-aadf-4b76-9f71-7eaffce80a41" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-230.296588454795" y="280.786625270109" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element : Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="415acaf5-6995-4e56-9899-d6c5a6ad0e5a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1873.57630266473" y="146.350708021054" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9eebc758-d747-41de-a0b5-f0da17bbffd1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1119.36795252226" y="325.373887240356" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="level : Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="325702f5-eacf-4d44-9686-c2767e7c99f7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.StartPoint" x="1114.97797674895" y="106.714962380454" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.StartPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cd2acaf7-9dd1-42ea-afd8-4978bb6a4384" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="1114.97797674895" y="195.91166588846" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="915a1231-7fbe-4515-baab-927893ee46f7" start_index="0" end="22ab1072-dad6-4f2a-a944-bf1f7ee3d73d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8e91bfc9-cced-47aa-bc14-e903f1b418ec" start_index="0" end="22ab1072-dad6-4f2a-a944-bf1f7ee3d73d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="22ab1072-dad6-4f2a-a944-bf1f7ee3d73d" start_index="0" end="3e3c6feb-796a-4247-a276-e135cd9a3978" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae188084-6e30-4140-b0e5-ec77ebe0486e" start_index="0" end="a4f70e3c-ba71-46e5-bb28-a8c241df430c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3e3c6feb-796a-4247-a276-e135cd9a3978" start_index="0" end="a4f70e3c-ba71-46e5-bb28-a8c241df430c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a4f70e3c-ba71-46e5-bb28-a8c241df430c" start_index="0" end="325702f5-eacf-4d44-9686-c2767e7c99f7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a4f70e3c-ba71-46e5-bb28-a8c241df430c" start_index="0" end="cd2acaf7-9dd1-42ea-afd8-4978bb6a4384" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ac06919-12f6-4c2c-91d8-ec6b0cb256c5" start_index="0" end="979488f4-3639-438a-89e8-e986a40f79f4" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e9f5f788-7db2-4493-a15b-5aa6a113f457" start_index="0" end="979488f4-3639-438a-89e8-e986a40f79f4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="16278d33-0b0d-4d42-ac0b-8be5e87b3354" start_index="0" end="979488f4-3639-438a-89e8-e986a40f79f4" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="979488f4-3639-438a-89e8-e986a40f79f4" start_index="0" end="415acaf5-6995-4e56-9899-d6c5a6ad0e5a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="92097fac-aadf-4b76-9f71-7eaffce80a41" start_index="0" end="8e91bfc9-cced-47aa-bc14-e903f1b418ec" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="92097fac-aadf-4b76-9f71-7eaffce80a41" start_index="0" end="ae188084-6e30-4140-b0e5-ec77ebe0486e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9eebc758-d747-41de-a0b5-f0da17bbffd1" start_index="0" end="16278d33-0b0d-4d42-ac0b-8be5e87b3354" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="325702f5-eacf-4d44-9686-c2767e7c99f7" start_index="0" end="e9f5f788-7db2-4493-a15b-5aa6a113f457" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd2acaf7-9dd1-42ea-afd8-4978bb6a4384" start_index="0" end="3ac06919-12f6-4c2c-91d8-ec6b0cb256c5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>