<Workspace Version="1.0.0.1180" X="330.170871179549" Y="332.642355441869" zoom="0.679007436100058" Name="PointCloud.GetInstance" Description="" ID="36076ccd-89b5-4657-bc20-d7f67eaf0002" Category="BlackBox.PointCloud">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.CreateList guid="e786efd4-2b8f-4169-bc59-95b713e45d13" type="CoreNodeModels.CreateList" nickname="List.Create" x="49.5351094716593" y="11.4119681954164" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f267100a-c664-4bdf-bdc2-9ddd1b7f45ec" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Empty" x="-109.075074922037" y="71.792561634762" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Empty" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="49cbeebb-f074-4395-a3a3-597ae4fe68c9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="201.245311429669" y="13.0364585705048" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <PythonNodeModels.PythonNode guid="f953c114-f785-4888-a3fe-75f41cc24d17" type="PythonNodeModels.PythonNode" nickname="pointcloudinstance" x="334.594218164578" y="12.6021319751574" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2014, Jason Andersen, jason@serialnonstandard.com
#www.serialnonstandard.com

# Default imports
import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
import System.Collections.Generic
from System.Collections.Generic import List

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

#elements coming in
elements = UnwrapElement(IN[0])

#variables
v_element = []
v_name = []
v_id = []
v_uniqueid = []

#work
for f in elements:
	v_element.append(f.ToDSType(True))	
	v_name.append(f.Name)
	v_id.append(f.Id)
	v_uniqueid.append(f.UniqueId)
OUT = v_element,v_name,v_id,v_uniqueid
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4d24b1e2-1d42-4e10-807c-15084ba10c0c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-213.428719388615" y="-11.8471073345066" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="PointCloudElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8db07721-4a2b-405b-a970-a1f6dd7bf48f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="820.368805168943" y="-22.9501202783422" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="PointCloudInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="34415839-b1bf-44b6-9672-f4b66063a55e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="820.368805168943" y="68.4933686669889" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e0d922d8-5353-40e4-8fc0-0e95e1870697" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="code block" x="535.393584493171" y="7.72975149095032" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="element[0];&#xA;name[1];" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e786efd4-2b8f-4169-bc59-95b713e45d13" start_index="0" end="49cbeebb-f074-4395-a3a3-597ae4fe68c9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f267100a-c664-4bdf-bdc2-9ddd1b7f45ec" start_index="0" end="e786efd4-2b8f-4169-bc59-95b713e45d13" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="49cbeebb-f074-4395-a3a3-597ae4fe68c9" start_index="0" end="f953c114-f785-4888-a3fe-75f41cc24d17" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f953c114-f785-4888-a3fe-75f41cc24d17" start_index="0" end="e0d922d8-5353-40e4-8fc0-0e95e1870697" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f953c114-f785-4888-a3fe-75f41cc24d17" start_index="0" end="e0d922d8-5353-40e4-8fc0-0e95e1870697" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4d24b1e2-1d42-4e10-807c-15084ba10c0c" start_index="0" end="e786efd4-2b8f-4169-bc59-95b713e45d13" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e0d922d8-5353-40e4-8fc0-0e95e1870697" start_index="0" end="8db07721-4a2b-405b-a970-a1f6dd7bf48f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e0d922d8-5353-40e4-8fc0-0e95e1870697" start_index="1" end="34415839-b1bf-44b6-9672-f4b66063a55e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-37.0236382019738" eyeY="130.966555034726" eyeZ="-17.9899576670614" lookX="67.0146313006375" lookY="-87.8343103477504" lookZ="-50.1527448805047" upX="0.447701141259042" upY="0.829037572555044" upZ="-0.335052818832191" />
  </Cameras>
</Workspace>