<Workspace Version="1.0.0.1180" X="-17.6723939178364" Y="111.32962353267" zoom="0.579373994271777" Name="Image From Directory" Description="Create drafting views from images in specific directory" ID="d86b3d95-e0c7-4d59-865b-d99025b72eb1" Category="Dynamo4MEP.Elements">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <CoreNodeModels.Input.DirectoryObject guid="86f0ffad-9237-42e3-8dcc-b059f03d2d38" type="CoreNodeModels.Input.DirectoryObject" nickname="Directory.FromPath" x="239.30345248734" y="237.471682239794" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <CoreNodeModels.Input.StringInput guid="9467aec4-eede-4dcc-9bb5-68bca6d0e29d" type="CoreNodeModels.Input.StringInput" nickname="String" x="392.760861938028" y="343.922664002852" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>*</System.String>
      <System.String value="*" />
    </CoreNodeModels.Input.StringInput>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b809f69f-4168-4a3a-ba7b-51a49fa283a9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Directory.Contents" x="520.034405157241" y="279.421395007861" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.IO.Directory.Contents@var,string">
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="d0c07171-7c97-410d-8c52-cf0552537a19" type="PythonNodeModels.PythonNode" nickname="Python Script" x="579.047545029007" y="515.857109183894" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2016, Cesare Caoduro
# http://bimandothers.blogspot.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

#Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
import System

#Assign your output to the OUT variable
OUT = System.Enum.GetValues(BoxPlacement)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="2434faba-2091-4c21-9204-9d0813716850" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="794.007428068209" y="462.812658765748" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="IN[0];" ShouldFocus="false" />
    <CoreNodeModels.Input.BoolSelector guid="bd2692d7-41ae-4ce7-927a-c20a9f775d69" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="937.92846477291" y="158.102617149265" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <CoreNodeModels.Watch guid="e843f29f-49e2-4643-a7f7-8e02d3f117a8" type="CoreNodeModels.Watch" nickname="Watch" x="773.232503175109" y="278.027940911368" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <CoreNodeModels.Watch guid="0c72001d-5fd4-43d0-809d-83c9cb31fb5c" type="CoreNodeModels.Watch" nickname="Watch" x="730.774747254148" y="604.017300748398" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="4320456e-493e-4025-b73e-24f57e11ab23" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="943.45432624418" y="530.710802363633" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Autodesk.Point.ByCoordinates(0,0,0);&#xA;72;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="c42f68e4-5933-4304-a592-728ccc16e077" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1361.49221838803" y="498.095444542892" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <Script>#Copyright(c) 2016, Cesare Caoduro
# http://bimandothers.blogspot.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Revit API
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

placement = IN[0]
refPt = IN[1]
res = IN[2]

iio = ImageImportOptions()

def toRvtPoint(point):
	x = point.X
	y = point.Y
	z = point.Z
	return XYZ(x,y,z,)
	
message = None
if placement != None:
	iio.Placement = placement
if refPt != None:
	iio.RefPoint = toRvtPoint(refPt)
else:
	message = "Please specify placement point."
if res != None:
	iio.Resolution - res
else:
	iio.Resolution - 72
	
# Assign your output to the OUT variable
OUT = iio</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3054ab7f-eba5-4809-9b97-2fb31a57fe73" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FilePath.FileName" x="1122.90803074184" y="149.75777756384" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.IO.FilePath.FileName@string,bool">
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9068de22-a2d7-4b36-a650-e5e9874d93f6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="DraftingView.ByName" x="1348.17858221781" y="153.433028825931" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Views.DraftingView.ByName@string" />
    <CoreNodeModels.Input.BoolSelector guid="bf83b2a3-7320-4943-84d3-245331200f53" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="1433.63669518077" y="359.678499694848" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <CoreNodeModels.Watch guid="2f09c161-eed0-4508-9c22-fd2288d67dc8" type="CoreNodeModels.Watch" nickname="Watch" x="1556.77241529558" y="567.74979769001" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <PythonNodeModels.PythonNode guid="fd1d7d6c-ba66-4cc1-83e8-dbc1e02255c5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1719.37746756809" y="278.028476745559" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <Script>#Copyright(c) 2016, Cesare Caoduro
# http://bimandothers.blogspot.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

#Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

filePath= IN[0]
iio = IN[1]
view = UnwrapElement(IN[2])
RunIt = IN[3]

images = []
if RunIt:
	# Start Transaction
	TransactionManager.Instance.EnsureInTransaction(doc)
	for path1, view1 in zip(filePath, view):
		newElement = clr.StrongBox[Element]()
		doc.Import(path1, iio, view1, newElement)
		images.append(newElement.Value)	
	# End Transaction
	TransactionManager.Instance.TransactionTaskDone()
	message = "Success!"
else:
	message = "Set RunIt to True."
	
# Assign your output to the OUT variable
if message == "Success!":
	OUT = images
else:
	OUT = message</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="2e150a03-872d-401a-8814-7a16e5de3034" type="CoreNodeModels.Watch" nickname="Watch" x="1649.11481034125" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="439b61f5-b067-40e5-b33d-06d3a8b028e7" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Duct Element Collector" x="1109.40139164417" y="677.182972368814" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="16b96d76-d12d-4bad-b8b7-15b7dfc2eb41" />
      <Name value="Duct Element Collector" />
      <Description value="Duct Element Collector" />
      <Inputs>
        <Input value="Run" />
      </Inputs>
      <Outputs>
        <Output value="Element ID" />
        <Output value="Level Name" />
        <Output value="Size" />
        <Output value="Length" />
        <Output value="Elevation" />
        <Output value="Description" />
        <Output value="Curves" />
        <Output value="Connectors" />
        <Output value="Elements" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1860c4c4-e49e-463a-8736-978a7d765977" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-11.6689609229023" y="206.151642971275" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Directory Path" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b305e0f5-23d0-4175-b309-be1d3f72bac4" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="2009.08617041734" y="282.347035358443" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="86f0ffad-9237-42e3-8dcc-b059f03d2d38" start_index="0" end="b809f69f-4168-4a3a-ba7b-51a49fa283a9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9467aec4-eede-4dcc-9bb5-68bca6d0e29d" start_index="0" end="b809f69f-4168-4a3a-ba7b-51a49fa283a9" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b809f69f-4168-4a3a-ba7b-51a49fa283a9" start_index="0" end="e843f29f-49e2-4643-a7f7-8e02d3f117a8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d0c07171-7c97-410d-8c52-cf0552537a19" start_index="0" end="0c72001d-5fd4-43d0-809d-83c9cb31fb5c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d0c07171-7c97-410d-8c52-cf0552537a19" start_index="0" end="2434faba-2091-4c21-9204-9d0813716850" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2434faba-2091-4c21-9204-9d0813716850" start_index="0" end="c42f68e4-5933-4304-a592-728ccc16e077" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bd2692d7-41ae-4ce7-927a-c20a9f775d69" start_index="0" end="3054ab7f-eba5-4809-9b97-2fb31a57fe73" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e843f29f-49e2-4643-a7f7-8e02d3f117a8" start_index="0" end="3054ab7f-eba5-4809-9b97-2fb31a57fe73" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e843f29f-49e2-4643-a7f7-8e02d3f117a8" start_index="0" end="fd1d7d6c-ba66-4cc1-83e8-dbc1e02255c5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4320456e-493e-4025-b73e-24f57e11ab23" start_index="0" end="c42f68e4-5933-4304-a592-728ccc16e077" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4320456e-493e-4025-b73e-24f57e11ab23" start_index="1" end="c42f68e4-5933-4304-a592-728ccc16e077" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c42f68e4-5933-4304-a592-728ccc16e077" start_index="0" end="2f09c161-eed0-4508-9c22-fd2288d67dc8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c42f68e4-5933-4304-a592-728ccc16e077" start_index="0" end="fd1d7d6c-ba66-4cc1-83e8-dbc1e02255c5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3054ab7f-eba5-4809-9b97-2fb31a57fe73" start_index="0" end="9068de22-a2d7-4b36-a650-e5e9874d93f6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9068de22-a2d7-4b36-a650-e5e9874d93f6" start_index="0" end="2e150a03-872d-401a-8814-7a16e5de3034" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9068de22-a2d7-4b36-a650-e5e9874d93f6" start_index="0" end="fd1d7d6c-ba66-4cc1-83e8-dbc1e02255c5" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bf83b2a3-7320-4943-84d3-245331200f53" start_index="0" end="fd1d7d6c-ba66-4cc1-83e8-dbc1e02255c5" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd1d7d6c-ba66-4cc1-83e8-dbc1e02255c5" start_index="0" end="b305e0f5-23d0-4175-b309-be1d3f72bac4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1860c4c4-e49e-463a-8736-978a7d765977" start_index="0" end="86f0ffad-9237-42e3-8dcc-b059f03d2d38" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>