<Workspace Version="0.8.2.2392" X="-269.942823929569" Y="229.326301234041" zoom="0.775230660981313" Name="Set WallJoin" Description="Allow/Disallow Wall Join At End.&#xD;&#xA;True=Allow.WallJoinAtEnd&#xD;&#xA;False=Disallow.WallJoinAtEnd" ID="5e5eeaa6-7231-48da-9420-2409179213ec" Category="Hot Gear.Geometry Join">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.Symbol guid="533f4883-8735-4ebe-861a-3e6b8acf4fa2" type="Dynamo.Nodes.Symbol" nickname="Input" x="-180.410912010785" y="-56.7920402542059" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Elements" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="485f8920-79d3-4838-8098-77dabdf6ffb3" type="Dynamo.Nodes.Symbol" nickname="Input" x="-180.18524593956" y="56.6123529179382" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Bool" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="fa3e6900-73b9-4929-8845-f81802b695c6" type="Dynamo.Nodes.Output" nickname="Output" x="1329.17938293329" y="-1.67771385575063" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Elements" />
    </Dynamo.Nodes.Output>
    <DSIronPythonNode.PythonNode guid="5486e3f8-9e68-405b-ad78-a044763ca927" type="DSIronPythonNode.PythonNode" nickname="Allow_Disallow.WallJoinAtEnd" x="893.518193903467" y="8.35692860976917" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

doc = DocumentManager.Instance.CurrentDBDocument

elements = UnwrapElement(IN[0])
TF = IN[1]
beginning = 0
ending = 0
result = []
TransactionManager.Instance.EnsureInTransaction(doc)
if TF[0] == True:
	while (beginning &lt; len(elements)):
		try:
			Autodesk.Revit.DB.WallUtils.AllowWallJoinAtEnd(elements[beginning], 0)
			beginning = beginning + 1
			result.append("Success")
		except:
			beginning = beginning + 1
	while (ending &lt; len(elements)):
		try:
			Autodesk.Revit.DB.WallUtils.AllowWallJoinAtEnd(elements[ending], 1)
			ending = ending + 1
			result.append("Success")
		except:
			ending = ending + 1
elif TF[0] == False:
	while (beginning &lt; len(elements)):
		try:
			Autodesk.Revit.DB.WallUtils.DisallowWallJoinAtEnd(elements[beginning], 0)
			beginning = beginning + 1
			result.append("Success")
		except:
			beginning = beginning + 1
	while (ending &lt; len(elements)):
		try:
			Autodesk.Revit.DB.WallUtils.DisallowWallJoinAtEnd(elements[ending], 1)
			ending = ending + 1
			result.append("Success")
		except:
			ending = ending + 1
TransactionManager.Instance.TransactionTaskDone()

OUT = result , elements</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="7cf90dbd-3b05-4567-a22e-4ff4f46d12fa" type="Dynamo.Nodes.DSFunction" nickname="List.FilterByBoolMask" x="656.688143354368" y="-48.0780902358014" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="b7658620-819f-4de9-bd78-ec31657acc3e" type="Dynamo.Nodes.DSFunction" nickname="==" x="470.063930920367" y="-17.5242227214901" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="Operators" function="==@var[]..[],var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="1f4a44fb-d9ca-45ae-890d-4ab961d917b6" type="Dynamo.Nodes.DSFunction" nickname="Flatten" x="304.900414692807" y="-60.7018392538818" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="a892d555-7d39-40ad-bc3b-55d44f61f166" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="311.526797326815" y="50.9306529099002" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;Walls&quot;;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="04a9a7f4-e4bd-4be2-a4cf-ffb6bfd310fb" type="DSIronPythonNode.PythonNode" nickname="GETCategoryNameOfElement" x="51.9762346560694" y="-72.6587398369097" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

elements = UnwrapElement(IN[0])

output = []
catname = []

for item in elements:
	catname.append(item.Category.Name)
	output.append(catname)

OUT = output
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="568a0103-a0d8-43df-8e2a-0c584517371c" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1168.41887564478" y="-48.8034319354151" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="x[0];&#xA;x[1];" ShouldFocus="false" />
    <Dynamo.Nodes.Output guid="e5e15e8d-f3fe-48da-95d9-edb29c54cafe" type="Dynamo.Nodes.Output" nickname="Output" x="1319.61116171987" y="-76.7951839159477" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Result" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="2a332e37-88d0-4216-a14b-165f423c044a" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="49.1182824793807" y="58.5798773199558" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten({lsit});" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="533f4883-8735-4ebe-861a-3e6b8acf4fa2" start_index="0" end="04a9a7f4-e4bd-4be2-a4cf-ffb6bfd310fb" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="533f4883-8735-4ebe-861a-3e6b8acf4fa2" start_index="0" end="7cf90dbd-3b05-4567-a22e-4ff4f46d12fa" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="485f8920-79d3-4838-8098-77dabdf6ffb3" start_index="0" end="2a332e37-88d0-4216-a14b-165f423c044a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5486e3f8-9e68-405b-ad78-a044763ca927" start_index="0" end="568a0103-a0d8-43df-8e2a-0c584517371c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7cf90dbd-3b05-4567-a22e-4ff4f46d12fa" start_index="0" end="5486e3f8-9e68-405b-ad78-a044763ca927" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b7658620-819f-4de9-bd78-ec31657acc3e" start_index="0" end="7cf90dbd-3b05-4567-a22e-4ff4f46d12fa" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="1f4a44fb-d9ca-45ae-890d-4ab961d917b6" start_index="0" end="b7658620-819f-4de9-bd78-ec31657acc3e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a892d555-7d39-40ad-bc3b-55d44f61f166" start_index="0" end="b7658620-819f-4de9-bd78-ec31657acc3e" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="04a9a7f4-e4bd-4be2-a4cf-ffb6bfd310fb" start_index="0" end="1f4a44fb-d9ca-45ae-890d-4ab961d917b6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="568a0103-a0d8-43df-8e2a-0c584517371c" start_index="0" end="e5e15e8d-f3fe-48da-95d9-edb29c54cafe" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="568a0103-a0d8-43df-8e2a-0c584517371c" start_index="1" end="fa3e6900-73b9-4929-8845-f81802b695c6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2a332e37-88d0-4216-a14b-165f423c044a" start_index="0" end="5486e3f8-9e68-405b-ad78-a044763ca927" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>