<Workspace Version="0.9.0.3067" X="338.37308820793" Y="345.310982455888" zoom="0.954042924882812" Name="Distance Between Point" Description="Calculate the distance between 2 set of Point." ID="b1a64f35-1049-4cfa-912f-73db99de667f" Category="Hot Gear.Point">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point.x" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point.X" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="8a81f12e-333d-46ca-8fd3-82ccede4de4d" type="PythonNodeModels.PythonNode" nickname="Distance Between Point" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
import math

P0 = IN[0]
P1 = IN[1]

def xy(p):
	x0=[]
	y0=[]
	for i in p:
		x0.append(i.X)
		y0.append(i.Y)
	return x0,y0
	
def distance(x0, x1, y0, y1):
	result=[]
	count = 0
	while count&lt;len(x0):
		result.append(math.sqrt((x0[count] - x1[count])**2 + (y0[count] - y1[count])**2))
		count += 1
	return result
	
x0=xy(P0)[0]
y0=xy(P0)[1]
x1=xy(P1)[0]
y1=xy(P1)[1]
result = distance(x0,x1,y0,y1)
	
OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Symbol guid="304d1088-d5eb-4ba5-a87b-abe4c2750e79" type="Dynamo.Nodes.Symbol" nickname="Input" x="4.19268346913361" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="3e36b3a6-378d-48a8-89e3-817626dc422c" type="Dynamo.Nodes.Symbol" nickname="Input" x="3.14451260185012" y="95.4951149012636" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="ec6f28e3-b325-421e-8efb-decf947c2565" type="Dynamo.Nodes.Output" nickname="Output" x="513.304528041384" y="-1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Distance" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8a81f12e-333d-46ca-8fd3-82ccede4de4d" start_index="0" end="ec6f28e3-b325-421e-8efb-decf947c2565" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="304d1088-d5eb-4ba5-a87b-abe4c2750e79" start_index="0" end="8a81f12e-333d-46ca-8fd3-82ccede4de4d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3e36b3a6-378d-48a8-89e3-817626dc422c" start_index="0" end="8a81f12e-333d-46ca-8fd3-82ccede4de4d" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="455432.40625" eyeY="435823.53125" eyeZ="721801.5625" lookX="-3269.02490234375" lookY="-146731.9375" lookZ="1341.43334960938" upX="0.908141911029816" upY="0.190808996558189" upZ="-0.372652977705002" />
  </Cameras>
</Workspace>