<Workspace Version="0.9.0.3067" X="-78.4461587203023" Y="214.675615469762" zoom="1.33823125" Name="Get Revit Selection" Description="" ID="51e99650-6544-48c8-8174-ef130e52389e" Category="Hot Gear.Element">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="356fef17-59e4-42cc-ad14-532ab62b7bd1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="276.098819804126" y="0.252744994559038" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="0">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

select = []
elements = []
select = uidoc.Selection.GetElementIds()

for i in select:
		elements.append(doc.GetElement(i).ToDSType(True))

OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Output guid="8a6dd75b-04bf-4f27-a23e-f92545b97d15" type="Dynamo.Nodes.Output" nickname="Output" x="445.657143656265" y="-1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Element" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="356fef17-59e4-42cc-ad14-532ab62b7bd1" start_index="0" end="8a6dd75b-04bf-4f27-a23e-f92545b97d15" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>