<Workspace Version="0.8.2.2392" X="101.023264580441" Y="373.608177676956" zoom="0.869192406414823" Name="Join Geometry" Description="Join Selected Geometry" ID="8082d55c-2c72-4e19-b372-8b097006db03" Category="Hot Gear.Geometry Join">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="1e5bf471-1d33-4778-a18b-8ac5de042758" type="Dynamo.Nodes.Symbol" nickname="Input" x="42.2330411679889" y="-24.8059081276997" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Element list" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="da641034-3395-44bd-8ac7-8addbc9e0253" type="Dynamo.Nodes.Output" nickname="Output" x="1326.25235089861" y="31.851850208034" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Seccess?" />
    </Dynamo.Nodes.Output>
    <DSIronPythonNode.PythonNode guid="8eb834cb-6bb3-4aac-9184-5beb39903269" type="DSIronPythonNode.PythonNode" nickname="Join Python Script" x="1070.97428072196" y="29.9002154389058" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(doc)

elements = UnwrapElement(IN[0])
count = 0
result = []
while (count &lt; len(elements)):
	try:
		Autodesk.Revit.DB.JoinGeometryUtils.JoinGeometry(doc, elements[count][0], elements[count][1])
		count = count + 1
		result.append("Seccess")
	except:
		count = count +1

TransactionManager.Instance.TransactionTaskDone()
OUT = result</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="86e3619a-bf9e-40bb-9489-b0acdaecbb89" type="Dynamo.Nodes.DSFunction" nickname="List.FilterByBoolMask" x="809.103676177005" y="-1.05414360047928" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]" />
    <DSIronPythonNode.PythonNode guid="628f49f6-2975-4bbc-b73b-66f70281637e" type="DSIronPythonNode.PythonNode" nickname="AreElementsJoined" x="598.57084254575" y="67.6699491934727" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(doc)

element = UnwrapElement(IN[0])

list = len(element)
count = 0
end = []

while (count &lt; list):
		result = Autodesk.Revit.DB.JoinGeometryUtils.AreElementsJoined(doc, element[count][0], element[count][1])
		count = count + 1
		end.append(result)

TransactionManager.Instance.TransactionTaskDone()
OUT = end</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="3365cf46-ca2b-4154-8c11-9e233ba3b7e4" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="215.91152672144" y="2.04122603491874" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a=Flatten({item});&#xA;List.Combinations(a,2,false);" ShouldFocus="false" />
    <Dynamo.Nodes.Output guid="d869b14a-e693-45c8-a53d-904048ec4aa3" type="Dynamo.Nodes.Output" nickname="Output" x="1145.15563665983" y="-68.1371916178411" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Already Joined" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="1e5bf471-1d33-4778-a18b-8ac5de042758" start_index="0" end="3365cf46-ca2b-4154-8c11-9e233ba3b7e4" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8eb834cb-6bb3-4aac-9184-5beb39903269" start_index="0" end="da641034-3395-44bd-8ac7-8addbc9e0253" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="86e3619a-bf9e-40bb-9489-b0acdaecbb89" start_index="0" end="d869b14a-e693-45c8-a53d-904048ec4aa3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="86e3619a-bf9e-40bb-9489-b0acdaecbb89" start_index="1" end="8eb834cb-6bb3-4aac-9184-5beb39903269" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="628f49f6-2975-4bbc-b73b-66f70281637e" start_index="0" end="86e3619a-bf9e-40bb-9489-b0acdaecbb89" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="3365cf46-ca2b-4154-8c11-9e233ba3b7e4" start_index="1" end="86e3619a-bf9e-40bb-9489-b0acdaecbb89" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3365cf46-ca2b-4154-8c11-9e233ba3b7e4" start_index="1" end="628f49f6-2975-4bbc-b73b-66f70281637e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>