<Workspace Version="0.8.2.2392" X="157" Y="277" zoom="1" Name="Revit ID to Element" Description="" ID="f6df1ab5-e21d-436f-901b-1bef1482cfff" Category="Hot Gear.Python">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="753063ae-4d5e-4fb2-991e-1a603fe9db5a" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="280" y="7" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

ids = IN[0]
elements = []

for i in ids:
		elements.append(doc.GetElement(i).ToDSType(True))

OUT = elements</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Output guid="85d22ade-8ea0-4e8b-8887-8e5dc22935a5" type="Dynamo.Nodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Element" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="4f344614-9b38-4375-bdaa-a6e0bff0ca90" type="Dynamo.Nodes.Symbol" nickname="Input" x="115" y="4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Revit.ID" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="753063ae-4d5e-4fb2-991e-1a603fe9db5a" start_index="0" end="85d22ade-8ea0-4e8b-8887-8e5dc22935a5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4f344614-9b38-4375-bdaa-a6e0bff0ca90" start_index="0" end="753063ae-4d5e-4fb2-991e-1a603fe9db5a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="348.880474299286" eyeY="775.261477414609" eyeZ="90.2909983350602" lookX="-787.596176298239" lookY="-357.064130091588" lookZ="-263.525994247121" />
  </Cameras>
</Workspace>