<Workspace Version="0.9.0.3067" X="371.226516780982" Y="301.470487962354" zoom="1.07333337109291" Name="Revit ID" Description="" ID="4a1b4192-8427-4563-a893-127015a33762" Category="Hot Gear.Python">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.Symbol guid="8ab5ef80-aeee-4663-b020-fc01a136f601" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Elements" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="735f1907-c375-4f9a-a7dd-2a031957b5d7" type="Dynamo.Nodes.Output" nickname="Output" x="1258.48467713834" y="29.7244144531774" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Revit ID" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="81e98077-afa2-4f80-9109-315d5ad7e1bb" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1057.28379184703" y="40.7106239947524" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="x[0];&#xA;x[1];" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="15264e6c-50b7-4370-95c9-c1a911c6e042" type="PythonNodeModels.PythonNode" nickname="Python Script" x="814.841395921138" y="25.4470858551551" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

clr.AddReference("RevitNodes")
import Revit

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import Element wrapper extension methods
clr.ImportExtensions(Revit.Elements)

# Unwrap the Point, yielding a Revit XYZ in Revit unit system

def toRvtId(_id):
	if isinstance(_id, int) or isinstance(_id, str):
		id = Autodesk.Revit.DB.ElementId(int(_id))
		return id
	elif isinstance(_id, Autodesk.Revit.DB.ElementId):
		return _id
element = UnwrapElement(IN[1])
ID = []
GUID = []
for i in element:
	GUID.append(i.UniqueId)
for i in IN[0]:
	a = toRvtId(i)
	ID.append(a)

OUT = ID,GUID</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="fdb30185-3c2f-4316-80b3-d9a8b0927bcb" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="558.193094493018" y="-11.3524820448064" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="149284b1-da60-4b20-aa1b-e286f6cf6dea" type="Dynamo.Nodes.DSFunction" nickname="Element.Id" x="389.69157757557" y="-15.3977417828574" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.Id" />
    <Dynamo.Nodes.DSFunction guid="05de3602-4c15-4893-87d4-48c84596287c" type="Dynamo.Nodes.DSFunction" nickname="Object.Identity" x="215.200071636338" y="45.8600900462547" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.Object.Identity@var" />
    <Dynamo.Nodes.Output guid="4678a5bc-63e0-47e2-b5cb-dd480e62c48d" type="Dynamo.Nodes.Output" nickname="Output" x="1259.25270620213" y="86.7032536205351" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="GUID" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8ab5ef80-aeee-4663-b020-fc01a136f601" start_index="0" end="05de3602-4c15-4893-87d4-48c84596287c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="81e98077-afa2-4f80-9109-315d5ad7e1bb" start_index="0" end="735f1907-c375-4f9a-a7dd-2a031957b5d7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="81e98077-afa2-4f80-9109-315d5ad7e1bb" start_index="1" end="4678a5bc-63e0-47e2-b5cb-dd480e62c48d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="15264e6c-50b7-4370-95c9-c1a911c6e042" start_index="0" end="81e98077-afa2-4f80-9109-315d5ad7e1bb" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fdb30185-3c2f-4316-80b3-d9a8b0927bcb" start_index="0" end="15264e6c-50b7-4370-95c9-c1a911c6e042" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="149284b1-da60-4b20-aa1b-e286f6cf6dea" start_index="0" end="fdb30185-3c2f-4316-80b3-d9a8b0927bcb" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="05de3602-4c15-4893-87d4-48c84596287c" start_index="0" end="15264e6c-50b7-4370-95c9-c1a911c6e042" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="05de3602-4c15-4893-87d4-48c84596287c" start_index="0" end="149284b1-da60-4b20-aa1b-e286f6cf6dea" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>