<Workspace Version="0.8.2.2392" X="385.092223545014" Y="373.611749819647" zoom="0.8131456821731" Name="Unjoin Geometry" Description="Unjoin selected geometry" ID="53b39d7c-dded-4dd2-a66a-6d5d1b000b9f" Category="Hot Gear.Geometry Join">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Output guid="d2f33b81-8039-4b5e-802a-b77b269bcf89" type="Dynamo.Nodes.Output" nickname="Output" x="1234.07011336137" y="6.11695693866136" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Seccess?" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="26afd309-9432-49e2-8cff-4c5c9ece2a56" type="Dynamo.Nodes.Output" nickname="Output" x="1185.81494614948" y="139.242801377854" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Already Unjoined" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="707a044b-b9b3-4598-8c73-c399ba442aa3" type="Dynamo.Nodes.Symbol" nickname="Input" x="-51.2596573198927" y="1.94751427833779" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Element list" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.DSFunction guid="ef37ba2f-e40f-49a8-9c8d-05f0057be6ae" type="Dynamo.Nodes.DSFunction" nickname="List.FilterByBoolMask" x="740.497033429058" y="4.04636314842793" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]" />
    <DSIronPythonNode.PythonNode guid="1e2ded71-b1ed-45b8-9250-786872a9e745" type="DSIronPythonNode.PythonNode" nickname="Unjoin Python Script" x="935.657459348938" y="4.31970520508793" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(doc)

elements = UnwrapElement(IN[0])
count = 0
result = []
while (count &lt; len(elements)):
	try:
		Autodesk.Revit.DB.JoinGeometryUtils.UnjoinGeometry(doc, elements[count][0], elements[count][1])
		count = count + 1
		result.append("Seccess")
	except:
		count = count +1

TransactionManager.Instance.TransactionTaskDone()
OUT = result</Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="181b0a60-14bf-4a80-b4d4-6fa9ea0deffd" type="DSIronPythonNode.PythonNode" nickname="AreElementsJoined" x="547.682253204118" y="82.1493535398369" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(doc)

element = UnwrapElement(IN[0])

list = len(element)
count = 0
end = []
sublist = []

while (count &lt; list):
		result = Autodesk.Revit.DB.JoinGeometryUtils.AreElementsJoined(doc, element[count][0], element[count][1])
		count
		count = count + 1
		sublist.append(result)
		
end.extend(sublist)

TransactionManager.Instance.TransactionTaskDone()
OUT = end</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="10f14f99-2a43-49a0-ae1f-0a47640d3d01" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="172.219119337223" y="3.09871534378698" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a=Flatten({item});&#xA;List.Combinations(a,2,false);" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="19d3e532-bc1e-45d4-8f7c-9e667e454c7d" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="433" y="305" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="707a044b-b9b3-4598-8c73-c399ba442aa3" start_index="0" end="10f14f99-2a43-49a0-ae1f-0a47640d3d01" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ef37ba2f-e40f-49a8-9c8d-05f0057be6ae" start_index="0" end="1e2ded71-b1ed-45b8-9250-786872a9e745" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ef37ba2f-e40f-49a8-9c8d-05f0057be6ae" start_index="1" end="26afd309-9432-49e2-8cff-4c5c9ece2a56" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1e2ded71-b1ed-45b8-9250-786872a9e745" start_index="0" end="d2f33b81-8039-4b5e-802a-b77b269bcf89" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="181b0a60-14bf-4a80-b4d4-6fa9ea0deffd" start_index="0" end="ef37ba2f-e40f-49a8-9c8d-05f0057be6ae" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="10f14f99-2a43-49a0-ae1f-0a47640d3d01" start_index="1" end="ef37ba2f-e40f-49a8-9c8d-05f0057be6ae" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="10f14f99-2a43-49a0-ae1f-0a47640d3d01" start_index="1" end="181b0a60-14bf-4a80-b4d4-6fa9ea0deffd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>