<Workspace Version="0.8.2.2392" X="122.755" Y="389.2625" zoom="0.8425" Name="View Reset Element Overrides" Description="" ID="f41cdf7c-c7bb-48fe-9dd5-07584aa94dec" Category="Hot Gear.OverrideGraphicSettings ">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="3ec51344-f72f-440b-aa84-53ec0744f717" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="669.910123802593" y="45.3513273119024" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten({list});" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="c0c13d93-0ac2-427b-b4e0-22e4b87aad6e" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="908.12929563985" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

view = UnwrapElement(IN[0])
element = IN[1]
override = OverrideGraphicSettings()
result = []
count = 0

TransactionManager.Instance.EnsureInTransaction(doc)
for i in element:
	view.SetElementOverrides(i, override)
	result.append("Success")


TransactionManager.Instance.TransactionTaskDone()


OUT = result</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Function guid="a6bce502-09e3-4082-8914-a235eb3378cf" type="Dynamo.Nodes.Function" nickname="Get Element Revit ID" x="479.911961508378" y="46.4811025791209" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="4a1b4192-8427-4563-a893-127015a33762" />
      <Name value="Get Element Revit ID" />
      <Description value="" />
      <Inputs>
        <Input value="Element" />
      </Inputs>
      <Outputs>
        <Output value="Revit.ID" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function guid="3d021668-ac5e-4995-992b-f69d5c2c22e2" type="Dynamo.Nodes.Function" nickname="Get All Instance Element" x="250" y="45.7393895432801" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True">
      <ID value="e121bdbf-3df8-452f-b866-3188c63ca74c" />
      <Name value="Get All Instance Element" />
      <Description value="" />
      <Inputs />
      <Outputs>
        <Output value="Element" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol guid="a5508947-ea22-4e09-93aa-ab57c223f0d7" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="View" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="053bb344-54a5-49e4-94c1-274c0f573170" type="Dynamo.Nodes.Output" nickname="Output" x="1107.12929563985" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Result" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="3ec51344-f72f-440b-aa84-53ec0744f717" start_index="0" end="c0c13d93-0ac2-427b-b4e0-22e4b87aad6e" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="c0c13d93-0ac2-427b-b4e0-22e4b87aad6e" start_index="0" end="053bb344-54a5-49e4-94c1-274c0f573170" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a6bce502-09e3-4082-8914-a235eb3378cf" start_index="0" end="3ec51344-f72f-440b-aa84-53ec0744f717" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3d021668-ac5e-4995-992b-f69d5c2c22e2" start_index="0" end="a6bce502-09e3-4082-8914-a235eb3378cf" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a5508947-ea22-4e09-93aa-ab57c223f0d7" start_index="0" end="c0c13d93-0ac2-427b-b4e0-22e4b87aad6e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>