{
  "Uuid": "4a37b07a-6891-4e5b-94e2-70a8c70e586e",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Revit.Elements.AdaptiveComponent",
  "Description": "Creates an adaptive family by a Line geometry",
  "Name": "AdaptiveFamilytwoPointsbyCurve",
  "ElementResolver": {
    "ResolutionMap": {
      "Surface": {
        "Key": "Autodesk.DesignScript.Geometry.Surface",
        "Value": "ProtoGeometry.dll"
      },
      "Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Surface": {
        "Key": "Autodesk.DesignScript.Geometry.Surface",
        "Value": "ProtoGeometry.dll"
      },
      "Revit.Elements.FamilyType": {
        "Key": "Revit.Elements.FamilyType",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.DesignScript.Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Flatten@var[]..[],int",
      "Id": "f80a43c28aec40b7a33a59403ee591f9",
      "Inputs": [
        {
          "Id": "c9b99657472740cd997c55473afdfa6c",
          "Name": "list",
          "Description": "List to flatten.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "96df9a1a91644da8844f34ac3ba02d4a",
          "Name": "amt",
          "Description": "Layers of nesting to remove.\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "89c0e024aaba431ba9e23cdc1b63eb6b",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Flattens a nested list of lists by a certain amount.\n\nList.Flatten (list: var[]..[], amt: int = -1): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "curves",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "9ea34badc77a483d9cb08d355eba32bf",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "97f4d04a0ae2436a8aee13d4d6fe9abe",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "familyType",
        "TypeName": "Revit.Elements.FamilyType",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "06929890b38d4844badc345f395e481d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f0ace73b411d456eb51be0517e2ca0c2",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Id": "3108c5696f0443e59b1469a735645454",
      "Inputs": [
        {
          "Id": "769080775f1a4fb48102ca093ab8b298",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eb5fe079f31a4f57b48f1de4161fdc08",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.EndPoint",
      "Id": "e73c9554edb243d7b1c0800d912faece",
      "Inputs": [
        {
          "Id": "9f6ea748c7684383ae12e5f5d4910c85",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "36a4153c4616402aa3da8351aef66ed7",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the end Point along the Curve\n\nCurve.EndPoint: Point"
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "c34faafc6c684ab08976920f83999065",
      "Inputs": [
        {
          "Id": "8e1aa96c93694735836b5a1f2aa3fb6b",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "830fa03a161a4c32b5e9ee6ee7572cdc",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6cf47a605ee146a7bb77d1141ef40f13",
          "Name": "list",
          "Description": "A list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Transpose@var[]..[]",
      "Id": "c511da5f4b384dcc9639a8b8a73146ee",
      "Inputs": [
        {
          "Id": "ec8e88d3f6fe4f5eb0191e75be1671e0",
          "Name": "lists",
          "Description": "A list of lists to be transposed.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "bf6c5237421d44bda5dcc85d6705c005",
          "Name": "lists",
          "Description": "A list of transposed lists.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Swaps rows and columns in a list of lists. If there are some rows that are shorter than others, null values are inserted as place holders in the resultant array such that it is always rectangular.\n\nList.Transpose (lists: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.AdaptiveComponent.ByPoints@Autodesk.DesignScript.Geometry.Point[][],Revit.Elements.FamilyType",
      "Id": "86b892e8a3f64a148abcc4cf6363d7ae",
      "Inputs": [
        {
          "Id": "f8aef252f77e4308a90cb1777f3a4d84",
          "Name": "points",
          "Description": "a two-dimensional array of points\n\nPoint[][]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "dcf05e7af72347738ffb5c489a87c74f",
          "Name": "familyType",
          "Description": "a family type to use to create the adaptive components\n\nFamilyType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "52638579e95547c4a7ea4e592744b227",
          "Name": "AdaptiveComponent[]..[]",
          "Description": "AdaptiveComponent[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a list of adaptive components from two-dimensional array of points\n\nAdaptiveComponent.ByPoints (points: Point[][], familyType: FamilyType): AdaptiveComponent[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "AdaptiveComponent[]..[]",
      "Id": "9f0064ae636b475489e75a690f345514",
      "Inputs": [
        {
          "Id": "46f5ff2055ee4d659dea91ad44647af4",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "89c0e024aaba431ba9e23cdc1b63eb6b",
      "End": "769080775f1a4fb48102ca093ab8b298",
      "Id": "7e20df0fb90a42ea993545d4634387f6"
    },
    {
      "Start": "89c0e024aaba431ba9e23cdc1b63eb6b",
      "End": "9f6ea748c7684383ae12e5f5d4910c85",
      "Id": "6ccff5d076144293bd095ac75fd83887"
    },
    {
      "Start": "97f4d04a0ae2436a8aee13d4d6fe9abe",
      "End": "c9b99657472740cd997c55473afdfa6c",
      "Id": "94f39f29135e4709a396989147114731"
    },
    {
      "Start": "f0ace73b411d456eb51be0517e2ca0c2",
      "End": "dcf05e7af72347738ffb5c489a87c74f",
      "Id": "50b4c9055f654635932c708730af6206"
    },
    {
      "Start": "eb5fe079f31a4f57b48f1de4161fdc08",
      "End": "8e1aa96c93694735836b5a1f2aa3fb6b",
      "Id": "322b2694c3e14f07b2bbd2b628b3746e"
    },
    {
      "Start": "36a4153c4616402aa3da8351aef66ed7",
      "End": "830fa03a161a4c32b5e9ee6ee7572cdc",
      "Id": "fd41a5a104c2483db202342849c701e9"
    },
    {
      "Start": "6cf47a605ee146a7bb77d1141ef40f13",
      "End": "ec8e88d3f6fe4f5eb0191e75be1671e0",
      "Id": "4433b9fae9ec4e69845f441219158624"
    },
    {
      "Start": "bf6c5237421d44bda5dcc85d6705c005",
      "End": "f8aef252f77e4308a90cb1777f3a4d84",
      "Id": "ebe8235b4042458a9af364368583a213"
    },
    {
      "Start": "52638579e95547c4a7ea4e592744b227",
      "End": "46f5ff2055ee4d659dea91ad44647af4",
      "Id": "fceb1875f96c4b7e90531a513ade405f"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 235.40333717306441,
      "EyeY": 69.560681294838986,
      "EyeZ": 201.40269313612916,
      "LookX": -207.94093929098295,
      "LookY": -61.004095122320109,
      "LookZ": -202.13867323367691,
      "UpX": 0.0062572745716504129,
      "UpY": 0.99996192306417364,
      "UpZ": 0.0060826751301840485
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "List.Flatten",
        "Id": "f80a43c28aec40b7a33a59403ee591f9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 893.5178938376838,
        "Y": 200.95860044776222
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "9ea34badc77a483d9cb08d355eba32bf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 308.640954137508,
        "Y": 269.18644157540353
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "06929890b38d4844badc345f395e481d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 365.24332344213661,
        "Y": 454.451038575668
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.StartPoint",
        "Id": "3108c5696f0443e59b1469a735645454",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1221.7521975320044,
        "Y": 157.5674972137372
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.EndPoint",
        "Id": "e73c9554edb243d7b1c0800d912faece",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1205.5491340538279,
        "Y": 247.00161396597849
      },
      {
        "ShowGeometry": true,
        "Name": "List Create",
        "Id": "c34faafc6c684ab08976920f83999065",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1539.24030523246,
        "Y": 167.98647078004871
      },
      {
        "ShowGeometry": true,
        "Name": "List.Transpose",
        "Id": "c511da5f4b384dcc9639a8b8a73146ee",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1793.5039380726255,
        "Y": 150.10470405779577
      },
      {
        "ShowGeometry": true,
        "Name": "AdaptiveComponent.ByPoints",
        "Id": "86b892e8a3f64a148abcc4cf6363d7ae",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2176.73333678865,
        "Y": 200.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "9f0064ae636b475489e75a690f345514",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2585.73333678865,
        "Y": 200.0
      }
    ],
    "Annotations": [],
    "X": -87.078654875370148,
    "Y": 14.836698936164282,
    "Zoom": 0.642869557405948
  }
}