{
  "Uuid": "a5112afa-5d8e-42e0-969b-82c41a3eac36",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Points",
  "Description": "Changes the Point z Value",
  "Name": "ChangePointZValue",
  "ElementResolver": {
    "ResolutionMap": {
      "Revit.Elements.Element": {
        "Key": "Revit.Elements.Element",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.DesignScript.Geometry.Line": {
        "Key": "Autodesk.DesignScript.Geometry.Line",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "dced427cb9e34b1ba5cddba2056e2785",
      "Inputs": [
        {
          "Id": "6fec3abf24a74e1898e39920577850e9",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "658f18f7968f48a3873d0ee67b4e318b",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "52836d2de9e84d6580145fea8241f1b6",
      "Inputs": [
        {
          "Id": "6b8a2cf08d164dc69efcb015dbff01b0",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7aa9e8342125448390a3306edd9a01bb",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Z",
      "Id": "6a7d55148318462081144ea782782e46",
      "Inputs": [
        {
          "Id": "61c82be7ee44418195f71d3d99d862cd",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0015eebae8f44faba592dc2ee09148ea",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Z component of a Point\n\nPoint.Z: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "04e4c18a50364131b6f4c4adb75a1c00",
      "Inputs": [
        {
          "Id": "6543a15d64824bdf9d784ab0eb7ca987",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d8d776721c3f40ada8697a50d720e40c",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b7c89c6e063741e98cc1a9811377cb49",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "217722e42c134d909facab6e4c1d7c72",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "PointtoChange",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "ffc5f4703bc44cfea68b954f719acb6c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "acd4dbfd38924dc5927b3197bfc4a844",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "PointtogetZ",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "95d628c717b54412a23ac339959de710",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f94bdad997c948508aa765d84899067c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "NewPoint:Point[]",
      "Id": "cd91a5878820459990b33c6e06b6660a",
      "Inputs": [
        {
          "Id": "de0d8e98c752492292166a9cb4e125ea",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "658f18f7968f48a3873d0ee67b4e318b",
      "End": "d8d776721c3f40ada8697a50d720e40c",
      "Id": "810a543b59634ebbb6c250054293badf"
    },
    {
      "Start": "7aa9e8342125448390a3306edd9a01bb",
      "End": "6543a15d64824bdf9d784ab0eb7ca987",
      "Id": "04de5deb6a2d4ad2afb2d629b1eac3dc"
    },
    {
      "Start": "0015eebae8f44faba592dc2ee09148ea",
      "End": "b7c89c6e063741e98cc1a9811377cb49",
      "Id": "806b8253dce8485398c52767252d5f22"
    },
    {
      "Start": "217722e42c134d909facab6e4c1d7c72",
      "End": "de0d8e98c752492292166a9cb4e125ea",
      "Id": "241a7feafef943cebebfa10aab469e8d"
    },
    {
      "Start": "acd4dbfd38924dc5927b3197bfc4a844",
      "End": "6fec3abf24a74e1898e39920577850e9",
      "Id": "7017fbb4aa6e4197b384dea43ad6a25c"
    },
    {
      "Start": "acd4dbfd38924dc5927b3197bfc4a844",
      "End": "6b8a2cf08d164dc69efcb015dbff01b0",
      "Id": "36b51b43b296496ab06d406882c664fb"
    },
    {
      "Start": "f94bdad997c948508aa765d84899067c",
      "End": "61c82be7ee44418195f71d3d99d862cd",
      "Id": "a852b4a3349e49f8a793a2ff033cf6a2"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -10.734249607025419,
      "EyeY": 11.828078432053374,
      "EyeZ": -8.5300356161628876,
      "LookX": 22.769235363502808,
      "LookY": -5.7344124053854166,
      "LookZ": 7.9243499789298895,
      "UpX": 0.016482704885535552,
      "UpY": 0.99984769515640526,
      "UpZ": 0.0057364562325948479
    },
    "NodeViews": [
      {
        "Id": "dced427cb9e34b1ba5cddba2056e2785",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Y",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 250.0,
        "Y": 94.545602226206029
      },
      {
        "Id": "52836d2de9e84d6580145fea8241f1b6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.X",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 266.3009659010695,
        "Y": 0.0
      },
      {
        "Id": "6a7d55148318462081144ea782782e46",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Z",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 254.60109137704103,
        "Y": 185.00486152261215
      },
      {
        "Id": "04e4c18a50364131b6f4c4adb75a1c00",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 540.15719303904689,
        "Y": 19.561159081284018
      },
      {
        "Id": "ffc5f4703bc44cfea68b954f719acb6c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "Id": "95d628c717b54412a23ac339959de710",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 300.0
      },
      {
        "Id": "cd91a5878820459990b33c6e06b6660a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 773.15719303904689,
        "Y": 0.0
      }
    ],
    "Annotations": [],
    "X": 341.0,
    "Y": 162.0,
    "Zoom": 1.0
  }
}