{
  "Uuid": "4f9ad511-8281-4ce5-a949-8320dc8b62cd",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Revit.Elements.Topography",
  "Description": "Gets a Loop of Points using a Curve",
  "Name": "ClosedLoopThroughPointsonCurve",
  "ElementResolver": {
    "ResolutionMap": {
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Mesh": {
        "Key": "Autodesk.DesignScript.Geometry.Mesh",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Plane": {
        "Key": "Autodesk.DesignScript.Geometry.Plane",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Vector": {
        "Key": "Autodesk.DesignScript.Geometry.Vector",
        "Value": "ProtoGeometry.dll"
      },
      "Math": {
        "Key": "DSCore.Math",
        "Value": "DSCoreNodes.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [
    {
      "Id": "bdede6e2bec04b8d9a0c25d9b1d238f3",
      "Name": "Boolean",
      "Type": "boolean",
      "Value": "true",
      "Description": "Selection between a true and false."
    }
  ],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "points",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "584ce79ddfbd4f01837bf212e1d8ceb2",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "509ce1489a37492eb0858ea8e066290a",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool",
      "Id": "42a78b64c4724588ae1a2175afe138d0",
      "Inputs": [
        {
          "Id": "8ebcacc53da14ef78097e91749fd6b7f",
          "Name": "points",
          "Description": "Points to make polycurve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7bc9c16e6de043aaa12599ec58661a3c",
          "Name": "connectLastToFirst",
          "Description": "make close or open polycurve\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "909c1cada8a249f696578e41d8f7aa34",
          "Name": "PolyCurve",
          "Description": "PolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Make PolyCurve by connecting points. Set the 'connectLastToFirst' input to true to close the PolyCurve.\n\nPolyCurve.ByPoints (points: Point[], connectLastToFirst: bool = false): PolyCurve"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": true,
      "Id": "bdede6e2bec04b8d9a0c25d9b1d238f3",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a613470560c548b8a3c497f22c96978b",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.Curves",
      "Id": "6bb4540ce3244a00849279575ea010ce",
      "Inputs": [
        {
          "Id": "167070ac579849388b42ed3ee47b2049",
          "Name": "polyCurve",
          "Description": "Autodesk.DesignScript.Geometry.PolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "44ed795e075c4ef5aebe9500276f091a",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns curves of the polycurve\n\nPolyCurve.Curves ( ): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Curves",
      "Id": "1f461b72b9ab401ea795e4d509662477",
      "Inputs": [
        {
          "Id": "f4a65d99ad0c4181a7de09a6d3f9fdc8",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "509ce1489a37492eb0858ea8e066290a",
      "End": "8ebcacc53da14ef78097e91749fd6b7f",
      "Id": "e1ad3a94f6db443285d14f638d0f02c1"
    },
    {
      "Start": "909c1cada8a249f696578e41d8f7aa34",
      "End": "167070ac579849388b42ed3ee47b2049",
      "Id": "3b749521534c44d1b3ad9c63250cd2ab"
    },
    {
      "Start": "a613470560c548b8a3c497f22c96978b",
      "End": "7bc9c16e6de043aaa12599ec58661a3c",
      "Id": "68135d355ac341719ed1783cd815c93e"
    },
    {
      "Start": "44ed795e075c4ef5aebe9500276f091a",
      "End": "f4a65d99ad0c4181a7de09a6d3f9fdc8",
      "Id": "518258eafbce446a91c194696deaefbf"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.6.1.8786",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "584ce79ddfbd4f01837bf212e1d8ceb2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 885.99999999999989,
        "Y": 479.0
      },
      {
        "ShowGeometry": true,
        "Name": "PolyCurve.ByPoints",
        "Id": "42a78b64c4724588ae1a2175afe138d0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1510.8917828904798,
        "Y": 523.29427085890768
      },
      {
        "ShowGeometry": true,
        "Name": "Boolean",
        "Id": "bdede6e2bec04b8d9a0c25d9b1d238f3",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1174.8917828904798,
        "Y": 578.29427085890734
      },
      {
        "ShowGeometry": true,
        "Name": "PolyCurve.Curves",
        "Id": "6bb4540ce3244a00849279575ea010ce",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1904.89178289048,
        "Y": 523.29427085890768
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "1f461b72b9ab401ea795e4d509662477",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2228.89178289048,
        "Y": 523.29427085890768
      }
    ],
    "Annotations": [],
    "X": 0.0,
    "Y": 0.0,
    "Zoom": 1.0
  }
}