{
  "Uuid": "d90e68c8-e8a4-45f3-a1ad-b23595c363ca",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Revit.Elements.Floor",
  "Description": "Creates a Floor By Level and type using two sets of points",
  "Name": "CreateFloorbylevelusingtwosetsofpoints",
  "ElementResolver": {
    "ResolutionMap": {
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "b0545649bed143baa090d1a4f3f5a191",
      "Inputs": [
        {
          "Id": "10ff36bd69a940e2bfde080b35b4ad22",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b6696630b0ef42bd97572f37af380989",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "0de22f280cea428f948fa968f70a10e2",
      "Inputs": [
        {
          "Id": "bf72a0b1740a4260a0963bb6b455a899",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "52a1f530609b46e7a50c6b5b94a5c837",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "30bba8cfe71c40a1b9a0cb93a0639131",
      "Inputs": [
        {
          "Id": "93101d76230b4a71b8df7158aab6398c",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b02190de88444fa09b8f00b43970dde9",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Level.Elevation",
      "Id": "3e287f97a57c404d98d044c7df2e01d8",
      "Inputs": [
        {
          "Id": "46dc3ebeadf64bad928a207775cd5c1b",
          "Name": "level",
          "Description": "Revit.Elements.Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "148a2c461e3d45498433a4525368ceb3",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The elevation of the level above ground level\n\nLevel.Elevation: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "950bb948cf25470fa41ab1013cd9b746",
      "Inputs": [
        {
          "Id": "edc375eb7ea04ed0bc0b33cbfc62b26a",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "11a23218c68148c3a82e4e1de0d53208",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "aab73be800eb48abaf887401dcdcbbcd",
      "Inputs": [
        {
          "Id": "6598eb9dfbdc437183f6ca3ea6f301d1",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8506f037204f42ec8240bfff3a830f1a",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5960b0ba0c4e4dd8863b8467d5af88fb",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4fd0ad3f72094193a48e733cfca9f981",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "53f794d3fe5b4b51b7ba2a25204352d1",
      "Inputs": [
        {
          "Id": "a4fc830bb487432e8b7eca60c2e28dd0",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a28a59e8ad8042a8815bb2aed16c6fa1",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ff746a0bbd9f49118e4aaf6ada239d43",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "76a6f0012a96484795ab9dedbb3b08f0",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "ffd7ba96a0b84bf9992409c7354af31e",
      "Inputs": [
        {
          "Id": "8ce44ef1337045ba8d269e70ec74be88",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "381c7958f20b464c83fc18579ad7ddae",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by interpolating between points.\n\nNurbsCurve.ByPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "688424c14396448fb7750ba1aee48879",
      "Inputs": [
        {
          "Id": "70bff3ae37624c9fbaf8f14c2d26c476",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ceafcce411704615871f1b2a4f17030d",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by interpolating between points.\n\nNurbsCurve.ByPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction, DynamoCore",
      "FunctionSignature": "DSCore.List.Join@var[]..[]",
      "FunctionType": "VariableArgument",
      "NodeType": "FunctionNode",
      "Id": "4bdbb68bb1fd4c05a81f5a02c547ad6f",
      "Inputs": [
        {
          "Id": "950acba319dd4e1899442f2b2994bbb2",
          "Name": "list0",
          "Description": "Lists to join into one.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2dc31d53c5e44c7a8b6388eeccac31b9",
          "Name": "list1",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8e0ebaa0613e431bba39e08282d8448d",
          "Name": "list",
          "Description": "Joined list.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Concatenates all given lists into a single list.\n\nList.Join (lists: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "6274fe9787d045f9a79cb09a7cb11cf7",
      "Inputs": [
        {
          "Id": "42d6fcaae0e54b87beb16958984c5fe7",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "87fa128b3e934ecc97f0574120f1ab5f",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by lofting between input cross section Curves.\n\nSurface.ByLoft (crossSections: Curve[]): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PerimeterCurves",
      "Id": "a1a7ef671f1a4e41af9d8d945d18ad73",
      "Inputs": [
        {
          "Id": "8c3209eb4b144895970f40eea8f2b14e",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3a700a71f9f84a0ba109bfa978af1693",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return all the boundary Curves of the Surface.\n\nSurface.PerimeterCurves ( ): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Floor.ByOutlineTypeAndLevel@Autodesk.DesignScript.Geometry.Curve[],Revit.Elements.FloorType,Revit.Elements.Level",
      "Id": "f4daf21661a745b38fede6b1bcd16238",
      "Inputs": [
        {
          "Id": "6bf4a86a997045599f6d4efb19c0f157",
          "Name": "outlineCurves",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2e115217e9f446bb851c8641b7e5370d",
          "Name": "floorType",
          "Description": "FloorType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "357f6f84637644d1aeb6425916cfc475",
          "Name": "level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "47cd334979d2408a884f6e4049d5ed2b",
          "Name": "Floor",
          "Description": "The floor",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Floor given its curve outline and Level\n\nFloor.ByOutlineTypeAndLevel (outlineCurves: Curve[], floorType: FloorType, level: Level): Floor"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "firstsetpoints",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "b2e527db666a4caaaabe7ffe4b50c31e",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "ebebc9e5f6bb40f0a610d1e2eb858a8c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "secondsetpoints",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "f541ed0af9de49019be940b4310a2edf",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7f9444dbe94f41a3983ddf3e89ce1e73",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "level",
        "TypeName": "Revit.Elements.Level",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "c51829d58bad454da64930b2a2cb2919",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "9c136fe93aa24d969494ff51a11de73f",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "floorType",
        "TypeName": "Revit.Elements.FloorType",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "fbc5ea5a30fa4dafaec1d93a52e9c65a",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "3646fb255b944731bd78e4d0d4dd14fa",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Floor",
      "Id": "8a87f6f9c5224b8387c435f6102abbca",
      "Inputs": [
        {
          "Id": "d9468d3dbef3451da3099d109a20a0d1",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "b6696630b0ef42bd97572f37af380989",
      "End": "8506f037204f42ec8240bfff3a830f1a",
      "Id": "ad4b655d52bb4e61b26ded619eae0f81"
    },
    {
      "Start": "52a1f530609b46e7a50c6b5b94a5c837",
      "End": "6598eb9dfbdc437183f6ca3ea6f301d1",
      "Id": "9d21e400f01745bb812a3aa1642b9167"
    },
    {
      "Start": "b02190de88444fa09b8f00b43970dde9",
      "End": "a4fc830bb487432e8b7eca60c2e28dd0",
      "Id": "cc2a2588fce44a0ba91644d8cfb0efc8"
    },
    {
      "Start": "148a2c461e3d45498433a4525368ceb3",
      "End": "5960b0ba0c4e4dd8863b8467d5af88fb",
      "Id": "4651059fea664a858f603f11b1e7c916"
    },
    {
      "Start": "148a2c461e3d45498433a4525368ceb3",
      "End": "ff746a0bbd9f49118e4aaf6ada239d43",
      "Id": "13aa82c932494692b139743183a772b9"
    },
    {
      "Start": "11a23218c68148c3a82e4e1de0d53208",
      "End": "a28a59e8ad8042a8815bb2aed16c6fa1",
      "Id": "1e1fc59ac2664a4cb3e6d2d2dfe2a59c"
    },
    {
      "Start": "4fd0ad3f72094193a48e733cfca9f981",
      "End": "70bff3ae37624c9fbaf8f14c2d26c476",
      "Id": "21e4e817d4e849b1ba60f0878a3f3668"
    },
    {
      "Start": "76a6f0012a96484795ab9dedbb3b08f0",
      "End": "8ce44ef1337045ba8d269e70ec74be88",
      "Id": "9d8d01811eb640d885b526674b99ee29"
    },
    {
      "Start": "381c7958f20b464c83fc18579ad7ddae",
      "End": "2dc31d53c5e44c7a8b6388eeccac31b9",
      "Id": "eb3e66e3e5e54bd8aa8de45772fe2879"
    },
    {
      "Start": "ceafcce411704615871f1b2a4f17030d",
      "End": "950acba319dd4e1899442f2b2994bbb2",
      "Id": "57642825d39544cb80180db9fbdbfc45"
    },
    {
      "Start": "8e0ebaa0613e431bba39e08282d8448d",
      "End": "42d6fcaae0e54b87beb16958984c5fe7",
      "Id": "5cbb6ec9ca3f4823b958011ddbb894f0"
    },
    {
      "Start": "87fa128b3e934ecc97f0574120f1ab5f",
      "End": "8c3209eb4b144895970f40eea8f2b14e",
      "Id": "b8a6d75a6e8c4ddfb96cd2eeecd2da85"
    },
    {
      "Start": "3a700a71f9f84a0ba109bfa978af1693",
      "End": "6bf4a86a997045599f6d4efb19c0f157",
      "Id": "995788014adb450a92451d1d14cbc9e6"
    },
    {
      "Start": "47cd334979d2408a884f6e4049d5ed2b",
      "End": "d9468d3dbef3451da3099d109a20a0d1",
      "Id": "ab3a8091adf243839f71eb2f2415a8bc"
    },
    {
      "Start": "ebebc9e5f6bb40f0a610d1e2eb858a8c",
      "End": "10ff36bd69a940e2bfde080b35b4ad22",
      "Id": "192b4e0b391c4d8a8e15ba79d6364e50"
    },
    {
      "Start": "ebebc9e5f6bb40f0a610d1e2eb858a8c",
      "End": "bf72a0b1740a4260a0963bb6b455a899",
      "Id": "cf6f5f19a1c34695b28e2d8c5e5557cc"
    },
    {
      "Start": "7f9444dbe94f41a3983ddf3e89ce1e73",
      "End": "93101d76230b4a71b8df7158aab6398c",
      "Id": "048790bd62a149dda600830d3627687e"
    },
    {
      "Start": "7f9444dbe94f41a3983ddf3e89ce1e73",
      "End": "edc375eb7ea04ed0bc0b33cbfc62b26a",
      "Id": "3b161330c9ac47638a108b1a22e70e18"
    },
    {
      "Start": "9c136fe93aa24d969494ff51a11de73f",
      "End": "46dc3ebeadf64bad928a207775cd5c1b",
      "Id": "0df08c09094e4c4b981b25dbfc232266"
    },
    {
      "Start": "9c136fe93aa24d969494ff51a11de73f",
      "End": "357f6f84637644d1aeb6425916cfc475",
      "Id": "3fb4c93a903241fa9f453b9555d654f8"
    },
    {
      "Start": "3646fb255b944731bd78e4d0d4dd14fa",
      "End": "2e115217e9f446bb851c8641b7e5370d",
      "Id": "21b192a22207468baa8507ce1efc8ebc"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -122.99158168583722,
      "EyeY": 27.954895643584379,
      "EyeZ": -173.89624839822432,
      "LookX": 187.23506117186275,
      "LookY": -74.21915385134163,
      "LookZ": 84.10501960843348,
      "UpX": 0.11906549116281734,
      "UpY": 0.99144486137387222,
      "UpZ": 0.053483601875957944
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Point.Y",
        "Id": "b0545649bed143baa090d1a4f3f5a191",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 250.0,
        "Y": 208.59602388924247
      },
      {
        "ShowGeometry": true,
        "Name": "Point.X",
        "Id": "0de22f280cea428f948fa968f70a10e2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 254.38663150392676,
        "Y": 111.59061798977245
      },
      {
        "ShowGeometry": true,
        "Name": "Point.X",
        "Id": "30bba8cfe71c40a1b9a0cb93a0639131",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 271.05690446373046,
        "Y": 391.28075320427467
      },
      {
        "ShowGeometry": true,
        "Name": "Level.Elevation",
        "Id": "3e287f97a57c404d98d044c7df2e01d8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 470.94782773856059,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Point.Y",
        "Id": "950bb948cf25470fa41ab1013cd9b746",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 266.67027295980006,
        "Y": 488.28615910374481
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "aab73be800eb48abaf887401dcdcbbcd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 730.60051967836989,
        "Y": 157.98973319088861
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "53f794d3fe5b4b51b7ba2a25204352d1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 732.45277222946424,
        "Y": 374.70328166834418
      },
      {
        "ShowGeometry": true,
        "Name": "NurbsCurve.ByPoints",
        "Id": "ffd7ba96a0b84bf9992409c7354af31e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1058.9277272652562,
        "Y": 401.5354929731742
      },
      {
        "ShowGeometry": true,
        "Name": "NurbsCurve.ByPoints",
        "Id": "688424c14396448fb7750ba1aee48879",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1043.3280401944867,
        "Y": 203.41946717443113
      },
      {
        "ShowGeometry": true,
        "Name": "List.Join",
        "Id": "4bdbb68bb1fd4c05a81f5a02c547ad6f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1346.9928641756469,
        "Y": 234.6397761997672
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ByLoft",
        "Id": "6274fe9787d045f9a79cb09a7cb11cf7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1570.0683892876168,
        "Y": 250.23946327053511
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.PerimeterCurves",
        "Id": "a1a7ef671f1a4e41af9d8d945d18ad73",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1863.0134967061922,
        "Y": 237.09902064835035
      },
      {
        "ShowGeometry": true,
        "Name": "Floor.ByOutlineTypeAndLevel",
        "Id": "f4daf21661a745b38fede6b1bcd16238",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2236.8899326538503,
        "Y": 299.21909619388373
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "b2e527db666a4caaaabe7ffe4b50c31e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "f541ed0af9de49019be940b4310a2edf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 300.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "c51829d58bad454da64930b2a2cb2919",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 450.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "fbc5ea5a30fa4dafaec1d93a52e9c65a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 750.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "8a87f6f9c5224b8387c435f6102abbca",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2545.8899326538503,
        "Y": 0.0
      }
    ],
    "Annotations": [],
    "X": -866.254278163767,
    "Y": 128.94156811038738,
    "Zoom": 0.59376714062500013
  }
}