{
  "Uuid": "792f799e-d9e2-416e-aed8-ba7c98f010a2",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Abstract.Topology",
  "Description": "Creates a latice by Solid on Surface Faces",
  "Name": "Laticebysurfaceandcentroid",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Math": {
        "Key": "DSCore.Math",
        "Value": "DSCoreNodes.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "DSCore.List": {
        "Key": "DSCore.List",
        "Value": "DSCoreNodes.dll"
      },
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.Solid": {
        "Key": "Autodesk.DesignScript.Geometry.Solid",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "solid",
        "TypeName": "Autodesk.DesignScript.Geometry.Solid",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "7eb5510d1c32405998a90d0a2054338d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1a04d7ecd9a04f33857767d90786492f",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "radius",
        "TypeName": "double",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "be039bff74b94c9ab6bb58442bc87493",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "93622282cd68423a965f07d360b4a280",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "4916430334194424a979e9ba1deb391d",
      "Inputs": [
        {
          "Id": "6876159f254142b398727667db92f934",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7ade8070130c407ab3c308e38399f96b",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e2a09fd8144242f8b680173bb360c92e",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "[0,1];",
      "Id": "7587e89c6abf43949b0d685a70c42661",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "732f91cae30a408fb9f070e577d9d52e",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PlaneAtParameter@double",
      "Id": "3d538a9597b84cee92f571f682213d84",
      "Inputs": [
        {
          "Id": "31b63fbc8ba44666b197f65814a13ab9",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "590c7119987441f598b732bdfddfced4",
          "Name": "param",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "179bfc780cb8426a868465001b1a0cc8",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "CrossProduct",
      "Description": "Returns a Plane whose normal aligns with the tangent of the Curve. Parameters are adjusted such that 0 is always the start Point and 1 is always the end Point.\n\nCurve.PlaneAtParameter (param: double = 0): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByPlaneRadius@Autodesk.DesignScript.Geometry.Plane,double",
      "Id": "8cc937facd004b31ab09147e7fb065ea",
      "Inputs": [
        {
          "Id": "d34730b722134e03b6f34130fd1d3cac",
          "Name": "plane",
          "Description": "Plane\nDefault value : Autodesk.DesignScript.Geometry.Plane.XY()",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f148b365dac34212881c8882a07d91b0",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6caf9dc6768e4923baa8f42adfd62563",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Circle centered at the input Plane origin (root), lying in the input Plane, with given radius.\n\nCircle.ByPlaneRadius (plane: Plane = Autodesk.DesignScript.Geometry.Plane.XY(), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "03c8a0c95f8c48cda9b6fae180aa9a3c",
      "Inputs": [
        {
          "Id": "4fac4958ce68462e99299f332c7ee3fe",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3033bbaa91754118a95f3a2267956289",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid by lofting between input cross section closed Curves.\n\nSolid.ByLoft (crossSections: Curve[]): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Solid",
      "Id": "256dcc35e6dc4d5eb72e6b06a1b72682",
      "Inputs": [
        {
          "Id": "f24e4490a4a34eb88e4c56c01159b368",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Line",
      "Id": "42f1ba49e45e4561856c84c458165ff9",
      "Inputs": [
        {
          "Id": "b9756dc6212e4352be9ec2c8e6ac8f14",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Face.SurfaceGeometry",
      "Id": "88ab0d01caf348bfbc03658c6cd608a4",
      "Inputs": [
        {
          "Id": "c48219a51fe740edb6de19c20ebef708",
          "Name": "face",
          "Description": "Autodesk.DesignScript.Geometry.Face",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9465a74ad2a844549c91576818fdd1fb",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The underlying Surface making up the Face\n\nFace.SurfaceGeometry ( ): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Topology.Faces",
      "Id": "42fa60d947b7498c885b75aac96774d6",
      "Inputs": [
        {
          "Id": "bbfe028a840a449ab42b1af016b33334",
          "Name": "topology",
          "Description": "Autodesk.DesignScript.Geometry.Topology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0e2e056f1f784a16ba1ebf42418c7b9a",
          "Name": "Face[]",
          "Description": "Face[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Faces of the Topology\n\nTopology.Faces: Face[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double",
      "Id": "24a30686530543a0882888fc4c06d1f6",
      "Inputs": [
        {
          "Id": "7e6413ac0ec24694a56d260472a04395",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3c2e6f791a8c4237bbc5c1f12ff0b307",
          "Name": "u",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "de9f38334e394988ac470a70c0129b6f",
          "Name": "v",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "20edd2ea3a6a45d0913e2f042f612b0b",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return the Point at specified U and V parameters.\n\nSurface.PointAtParameter (u: double = 0, v: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0.5;",
      "Id": "c96e690a6b33456d9e44a9883e289fe8",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e1db2cc81724457791a59c7166f5d420",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PerimeterCurves",
      "Id": "ec7483c5364a4548ae14e7e43e4a1757",
      "Inputs": [
        {
          "Id": "18ffa429ac9545d3961c696f7d695c27",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7598889aa24048cf912534530b17f9fb",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return all the boundary Curves of the Surface.\n\nSurface.PerimeterCurves ( ): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "b6d7715f482a4dd797b0eab7acb46c43",
      "Inputs": [
        {
          "Id": "94975b7d61ce49c4b7b10e06a8d4d2ad",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2076c953cec641098af843a3d9f9b053",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7a0200fd10e547a991beb421c10b11ed",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Longest",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Flatten@var[]..[],int",
      "Id": "d735a1111757495da5bf288324295c71",
      "Inputs": [
        {
          "Id": "e692b17927244189bf53e3812edf7cb5",
          "Name": "list",
          "Description": "List to flatten.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "64ffff5487f84e39b929d1ad625e8e64",
          "Name": "amt",
          "Description": "Layers of nesting to remove.\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b2412ed19e444b339f447d5889fed7dc",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Flattens a nested list of lists by a certain amount.\n\nList.Flatten (list: var[]..[], amt: int = -1): var[]..[]"
    }
  ],
  "Connectors": [
    {
      "Start": "1a04d7ecd9a04f33857767d90786492f",
      "End": "bbfe028a840a449ab42b1af016b33334",
      "Id": "804d05a062db49759156fd08208be114"
    },
    {
      "Start": "93622282cd68423a965f07d360b4a280",
      "End": "f148b365dac34212881c8882a07d91b0",
      "Id": "fb920d761286484bb65d010a5a372b47"
    },
    {
      "Start": "e2a09fd8144242f8b680173bb360c92e",
      "End": "e692b17927244189bf53e3812edf7cb5",
      "Id": "540e384ea5d14aa5b7be5b869b74a804"
    },
    {
      "Start": "732f91cae30a408fb9f070e577d9d52e",
      "End": "590c7119987441f598b732bdfddfced4",
      "Id": "d167b1d25c354fb6a372116b5ccc7554"
    },
    {
      "Start": "179bfc780cb8426a868465001b1a0cc8",
      "End": "d34730b722134e03b6f34130fd1d3cac",
      "Id": "81d567de87e84c75a9dabc9e9ec4b7e3"
    },
    {
      "Start": "6caf9dc6768e4923baa8f42adfd62563",
      "End": "4fac4958ce68462e99299f332c7ee3fe",
      "Id": "71cf2381871340b8ac9915071e3973e1"
    },
    {
      "Start": "3033bbaa91754118a95f3a2267956289",
      "End": "f24e4490a4a34eb88e4c56c01159b368",
      "Id": "9f684ff03c24463bac3613741cdad882"
    },
    {
      "Start": "9465a74ad2a844549c91576818fdd1fb",
      "End": "7e6413ac0ec24694a56d260472a04395",
      "Id": "651122384ba047b5bf15796ddecf7328"
    },
    {
      "Start": "9465a74ad2a844549c91576818fdd1fb",
      "End": "18ffa429ac9545d3961c696f7d695c27",
      "Id": "71b6cb0de2d044e0937f78f19ff7d460"
    },
    {
      "Start": "0e2e056f1f784a16ba1ebf42418c7b9a",
      "End": "c48219a51fe740edb6de19c20ebef708",
      "Id": "28b96fa640b549dab74277898b27ebfd"
    },
    {
      "Start": "20edd2ea3a6a45d0913e2f042f612b0b",
      "End": "6876159f254142b398727667db92f934",
      "Id": "ed38596039e34ae498d1f202e82bbc8c"
    },
    {
      "Start": "e1db2cc81724457791a59c7166f5d420",
      "End": "3c2e6f791a8c4237bbc5c1f12ff0b307",
      "Id": "ea9a96852344487e955fbf92953f43bb"
    },
    {
      "Start": "e1db2cc81724457791a59c7166f5d420",
      "End": "de9f38334e394988ac470a70c0129b6f",
      "Id": "4d104c85a7034ed29abb8714d83b8ef2"
    },
    {
      "Start": "e1db2cc81724457791a59c7166f5d420",
      "End": "2076c953cec641098af843a3d9f9b053",
      "Id": "c5243c1eaca54a5a9ace78938574754c"
    },
    {
      "Start": "7598889aa24048cf912534530b17f9fb",
      "End": "94975b7d61ce49c4b7b10e06a8d4d2ad",
      "Id": "cae40427ec4040508854d148a6a2ebaf"
    },
    {
      "Start": "7a0200fd10e547a991beb421c10b11ed",
      "End": "7ade8070130c407ab3c308e38399f96b",
      "Id": "a89f3cf7cb68474cb79e113f785323d5"
    },
    {
      "Start": "b2412ed19e444b339f447d5889fed7dc",
      "End": "31b63fbc8ba44666b197f65814a13ab9",
      "Id": "06e2169a860d4e2cb2a3fc19268523ae"
    },
    {
      "Start": "b2412ed19e444b339f447d5889fed7dc",
      "End": "b9756dc6212e4352be9ec2c8e6ac8f14",
      "Id": "887c75938a7544019706c3413051e527"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -3.8915046600041308,
      "EyeY": 1.0177559283327409,
      "EyeZ": 0.47152546656455052,
      "LookX": 4.6628828311143469,
      "LookY": 0.052484532582188104,
      "LookZ": -1.3203973355044394,
      "UpX": -0.21644058100830449,
      "UpY": 0.97437008142338544,
      "UpZ": 0.0612898883473448
    },
    "NodeViews": [
      {
        "Id": "7eb5510d1c32405998a90d0a2054338d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 531.0,
        "Y": 231.0
      },
      {
        "Id": "be039bff74b94c9ab6bb58442bc87493",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 531.0,
        "Y": 531.0
      },
      {
        "Id": "4916430334194424a979e9ba1deb391d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Line.ByStartPointEndPoint",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1948.5049824346443,
        "Y": 69.096845873251823
      },
      {
        "Id": "7587e89c6abf43949b0d685a70c42661",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2233.7008042914954,
        "Y": 278.5803264687051
      },
      {
        "Id": "3d538a9597b84cee92f571f682213d84",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PlaneAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2408.1917568064255,
        "Y": 284.6574382542276
      },
      {
        "Id": "8cc937facd004b31ab09147e7fb065ea",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Circle.ByPlaneRadius",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2714.4654400439508,
        "Y": 142.98338468647256
      },
      {
        "Id": "03c8a0c95f8c48cda9b6fae180aa9a3c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Solid.ByLoft",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2999.3675717845654,
        "Y": 234.36832381444151
      },
      {
        "Id": "256dcc35e6dc4d5eb72e6b06a1b72682",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 3305.3675717845654,
        "Y": 234.36832381444151
      },
      {
        "Id": "42f1ba49e45e4561856c84c458165ff9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 3341.4482419801852,
        "Y": 394.10266506714152
      },
      {
        "Id": "88ab0d01caf348bfbc03658c6cd608a4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Face.SurfaceGeometry",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 983.5,
        "Y": 74.0
      },
      {
        "Id": "42fa60d947b7498c885b75aac96774d6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Topology.Faces",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 774.5,
        "Y": 144.0
      },
      {
        "Id": "24a30686530543a0882888fc4c06d1f6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.PointAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1601.6319949438664,
        "Y": 149.51739791755944
      },
      {
        "Id": "c96e690a6b33456d9e44a9883e289fe8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1184.6931461690033,
        "Y": 197.51033706018126
      },
      {
        "Id": "ec7483c5364a4548ae14e7e43e4a1757",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.PerimeterCurves",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1309.5,
        "Y": -22.0
      },
      {
        "Id": "b6d7715f482a4dd797b0eab7acb46c43",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1607.8145360386868,
        "Y": -4.1227139142328326
      },
      {
        "Id": "d735a1111757495da5bf288324295c71",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Flatten",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2155.60342267063,
        "Y": 127.81666447580204
      }
    ],
    "Annotations": [],
    "X": -1297.0762752572641,
    "Y": 191.67401739103065,
    "Zoom": 0.7891610329248161
  }
}