{
  "Uuid": "5daac22f-40bf-42aa-bbdc-d67d2b4c1e7d",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Curves",
  "Description": "Converts a series of point into LInes",
  "Name": "PointsToLines",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool",
      "Id": "c3a2a8e3890b404ca06aed11825ff93d",
      "Inputs": [
        {
          "Id": "8ee55514fd624bf9a838a82d1342abd4",
          "Name": "points",
          "Description": "Points to make polycurve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2bbb5355aa0746efab573f5e2becf458",
          "Name": "connectLastToFirst",
          "Description": "make close or open polycurve\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f69a00e0873f4a7b9675932f0a3a16f2",
          "Name": "PolyCurve",
          "Description": "PolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Make PolyCurve by connecting points. Set the 'connectLastToFirst' input to true to close the PolyCurve.\n\nPolyCurve.ByPoints (points: Point[], connectLastToFirst: bool = false): PolyCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.Curves",
      "Id": "9e1728eebe45422da2423ad75a6c53dc",
      "Inputs": [
        {
          "Id": "916fda8600964eb089bc09df86ad0c5f",
          "Name": "polyCurve",
          "Description": "Autodesk.DesignScript.Geometry.PolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "bbcb1027e81d4ce382790c12a55908a0",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns curves of the polycurve\n\nPolyCurve.Curves ( ): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "092dc162-8282-4019-a4d1-8359b79eb421",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "fce41c7cab714d4499cd26bcceea31a7",
      "Inputs": [
        {
          "Id": "e3145240e1ab4d1b94b0cece96659743",
          "Name": "curve",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "69a5d571aa9c41b0a56c138fb328449f",
          "Name": "Line",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Transform a Curve to a Line by StartPoint EndPoint"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "points",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "1c5cbdc20a3c427583c70e0e7fbeb770",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "442081fe02684fb6bba1de7b7627f8ac",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Line[]",
      "Id": "cd8b07bed2664214be98dc2170b1aeae",
      "Inputs": [
        {
          "Id": "c609965837b44ce8b2c65015c6516622",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "f69a00e0873f4a7b9675932f0a3a16f2",
      "End": "916fda8600964eb089bc09df86ad0c5f",
      "Id": "b5036ad145d346e7936d9e09b62e4a08"
    },
    {
      "Start": "bbcb1027e81d4ce382790c12a55908a0",
      "End": "e3145240e1ab4d1b94b0cece96659743",
      "Id": "03913e9014dc43648bb45064908b9e61"
    },
    {
      "Start": "69a5d571aa9c41b0a56c138fb328449f",
      "End": "c609965837b44ce8b2c65015c6516622",
      "Id": "90aa0e80f77447e79f4ab45d64b2f35b"
    },
    {
      "Start": "442081fe02684fb6bba1de7b7627f8ac",
      "End": "8ee55514fd624bf9a838a82d1342abd4",
      "Id": "108a2643e123410eb0683232000b8cdb"
    }
  ],
  "Dependencies": [
    "092dc162-8282-4019-a4d1-8359b79eb421"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 56.590997810635074,
      "EyeY": 66.606471114555021,
      "EyeZ": -100.01484389352838,
      "LookX": -66.815194368920785,
      "LookY": -65.192003430538719,
      "LookZ": 83.430714554150782,
      "UpX": -0.20351195085987206,
      "UpY": 0.94551857559944152,
      "UpZ": 0.25412105196907525
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "PolyCurve.ByPoints",
        "Id": "c3a2a8e3890b404ca06aed11825ff93d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 250.0,
        "Y": 47.864373975746389
      },
      {
        "ShowGeometry": true,
        "Name": "PolyCurve.Curves",
        "Id": "9e1728eebe45422da2423ad75a6c53dc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 624.36778216744415,
        "Y": 13.675535421641939
      },
      {
        "ShowGeometry": true,
        "Name": "CurvetoLine",
        "Id": "fce41c7cab714d4499cd26bcceea31a7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 928.64844529897437,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "1c5cbdc20a3c427583c70e0e7fbeb770",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "cd8b07bed2664214be98dc2170b1aeae",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1180.6484452989744,
        "Y": 0.0
      }
    ],
    "Annotations": [],
    "X": -362.59000000000003,
    "Y": 183.15249999999997,
    "Zoom": 0.8425
  }
}