{
  "Uuid": "01888dab-c3bf-4bf9-bcc9-52439ef852cf",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Surfaces",
  "Description": "Creates a Surfaces using a list of points and a integer value of where as the value changes direction using aligned points",
  "Name": "Surfacefromsortedpointsatchop",
  "ElementResolver": {
    "ResolutionMap": {
      "Get": {
        "Key": "DesignScript.Builtin.Get",
        "Value": "DesignScriptBuiltin.dll"
      },
      "List": {
        "Key": "List",
        "Value": "BuiltIn.ds"
      },
      "String": {
        "Key": "DSCore.String",
        "Value": "DSCoreNodes.dll"
      },
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "a80a3e191df04e5e8ce9d35b6a3c1f62",
      "Inputs": [
        {
          "Id": "658e40d1b3794cd784590743ce444551",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c5b1cbbde42f4ad3871dd23a2066ba0c",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by interpolating between points.\n\nNurbsCurve.ByPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Chop@var[]..[],int[]",
      "Id": "3ad9d16931864025a35a9c5ff27ab248",
      "Inputs": [
        {
          "Id": "6efe6a1f9f924e12ad94d8343931cbda",
          "Name": "list",
          "Description": "List to chop into sublists\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ffe9213677d2493fa68c9ef6ebdbba4d",
          "Name": "lengths",
          "Description": "Lengths of consecutive sublists to be created from the input list\n\nint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "58263575a51b403ea69b362a8136fba0",
          "Name": "lists",
          "Description": "Sublists created from the list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Chop a list into a set of consecutive sublists with the specified lengths. List division begins at the top of the list.\n\nList.Chop (list: var[]..[], lengths: int[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "d082ad2094504965887ce9856a2a0c8a",
      "Inputs": [
        {
          "Id": "fee29f31e7c74cacb63adb16833068ed",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d329387e252f4705a3f86338608100e0",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by lofting between input cross section Curves.\n\nSurface.ByLoft (crossSections: Curve[]): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "pointsofsurface",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "e6b813259d9a4448b03fcc7f0618216c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "c00ad9cdd8ed46c589c2bfea574c31cd",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "lengths",
        "TypeName": "int",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "0f5ae77062324da98d81a7baa7bf9222",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "520722213907466dbff75bad6de4f0e6",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Surface",
      "Id": "9fa71d380f1d4891b7b62928a490ead0",
      "Inputs": [
        {
          "Id": "a26a49fadc0848cd8b8c31d25643d81c",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "c5b1cbbde42f4ad3871dd23a2066ba0c",
      "End": "fee29f31e7c74cacb63adb16833068ed",
      "Id": "45ce4ba55fc54b4489c58ab42ae1b32d"
    },
    {
      "Start": "58263575a51b403ea69b362a8136fba0",
      "End": "658e40d1b3794cd784590743ce444551",
      "Id": "069ae346e4d849d597d708ae9bc5495f"
    },
    {
      "Start": "d329387e252f4705a3f86338608100e0",
      "End": "a26a49fadc0848cd8b8c31d25643d81c",
      "Id": "2d69fdcc138c42a3af5bbadb9257beef"
    },
    {
      "Start": "c00ad9cdd8ed46c589c2bfea574c31cd",
      "End": "6efe6a1f9f924e12ad94d8343931cbda",
      "Id": "47c40edc80134c30b8a1f0bb44584a3c"
    },
    {
      "Start": "520722213907466dbff75bad6de4f0e6",
      "End": "ffe9213677d2493fa68c9ef6ebdbba4d",
      "Id": "7c8e7ea49c824128958ebf39fe62e233"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -63.606774354551959,
      "EyeY": 86.668042916382475,
      "EyeZ": -256.53576437868026,
      "LookX": 191.15284645184232,
      "LookY": -197.15308470558648,
      "LookZ": 237.65588185991294,
      "UpX": 0.21949191629169168,
      "UpY": 0.93667218924845608,
      "UpZ": 0.27288918734760509
    },
    "NodeViews": [
      {
        "Id": "a80a3e191df04e5e8ce9d35b6a3c1f62",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "NurbsCurve.ByPoints",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 468.51322271934077,
        "Y": 7.4442149218109535
      },
      {
        "Id": "3ad9d16931864025a35a9c5ff27ab248",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Chop",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 250.0,
        "Y": 0.0
      },
      {
        "Id": "d082ad2094504965887ce9856a2a0c8a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.ByLoft",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 798.51322271934987,
        "Y": 7.4442149218109535
      },
      {
        "Id": "e6b813259d9a4448b03fcc7f0618216c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "Id": "0f5ae77062324da98d81a7baa7bf9222",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 150.0
      },
      {
        "Id": "9fa71d380f1d4891b7b62928a490ead0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1120.5132227193499,
        "Y": 0.0
      }
    ],
    "Annotations": [],
    "X": -643.0,
    "Y": 232.0,
    "Zoom": 1.0
  }
}