{
  "Uuid": "344ed230-40b5-4c73-8c5f-64c453fc288c",
  "IsCustomNode": true,
  "Category": "PracticalBIM.Geometry.Abstract.Plane",
  "Description": "Creates a vertical Plane From a Line",
  "Name": "VerticalPlaneFromLine",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.DesignScript.Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector",
      "Id": "3925ec9f52d94c608b543c8bd23db57f",
      "Inputs": [
        {
          "Id": "d5a763b2821e4612bbd292fd2d37fac0",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "32d7a8b2764349b6b08b8df8f81f5bff",
          "Name": "direction",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "5bbdf80a1d6843509e21d86c9037c969",
          "Name": "Geometry",
          "Description": "Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Longest",
      "Description": "Translate geometry in the given direction by the vector length\n\nGeometry.Translate (direction: Vector): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "87905d1ef2814623be7c3691edbd104c",
      "Inputs": [
        {
          "Id": "5002d61218af439b8e979291a08b86d2",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a98760f667ba451ca06930bba2a47550",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "23e4376e353a4fe2a4e047774c278830",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Longest",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ByCoordinates@double,double,double",
      "Id": "6325f0ad18424f67824bf5cd05c831e4",
      "Inputs": [
        {
          "Id": "bc28dbe7a14440b092ddceea7b0697da",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ee162450ab3a482183ef7861f94593cb",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7661cb0b1d334717b2d4c3939227fbef",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d242a612ef224b2594a8bbc0a027d008",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Vector by 3 Euclidean coordinates\n\nVector.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0.5;",
      "Id": "1b98e5b95b6c4712a322641449478b43",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b14b7b5dcd5746098ef55d023e53ff4f",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "5;",
      "Id": "cbccf8333b7241fa9a2d0ac7eb844f98",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "4d276ce662244a7a9d946f07c44717a3",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "curves",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "64301f8854b84a428b4032b265979793",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "2a95fac3804349c8a1c006e65cabab45",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Plane[]",
      "Id": "273f062bb77a44889657db01c4ead60e",
      "Inputs": [
        {
          "Id": "75d23f50ffa64dc5abbe68f3bda9028a",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByLineAndPoint@Autodesk.DesignScript.Geometry.Line,Autodesk.DesignScript.Geometry.Point",
      "Id": "4402ced01a81413aa47a6051a89795d9",
      "Inputs": [
        {
          "Id": "82613c221db04ce4bb1c651b2e6a840c",
          "Name": "line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fef1a9e8ae3f44158abae385f9e3158a",
          "Name": "point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1df4c199479a4a619251b9cac83d354e",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create the Plane containing the input Line and external Point. Point cannot lie on the Line or in the Line axis.\n\nPlane.ByLineAndPoint (line: Line, point: Point): Plane"
    }
  ],
  "Connectors": [
    {
      "Start": "5bbdf80a1d6843509e21d86c9037c969",
      "End": "fef1a9e8ae3f44158abae385f9e3158a",
      "Id": "150bea08e8d3450881d5aae75b7633e3"
    },
    {
      "Start": "23e4376e353a4fe2a4e047774c278830",
      "End": "d5a763b2821e4612bbd292fd2d37fac0",
      "Id": "9082ecceffdf4b16b6a20d479071d76c"
    },
    {
      "Start": "d242a612ef224b2594a8bbc0a027d008",
      "End": "32d7a8b2764349b6b08b8df8f81f5bff",
      "Id": "43f381ea86ba4ee7a792ca628528aefb"
    },
    {
      "Start": "b14b7b5dcd5746098ef55d023e53ff4f",
      "End": "a98760f667ba451ca06930bba2a47550",
      "Id": "fc15e6395fd34cd9b6fdffded5840090"
    },
    {
      "Start": "4d276ce662244a7a9d946f07c44717a3",
      "End": "7661cb0b1d334717b2d4c3939227fbef",
      "Id": "f36e3b6fec4844909ae8bc1987da6563"
    },
    {
      "Start": "2a95fac3804349c8a1c006e65cabab45",
      "End": "5002d61218af439b8e979291a08b86d2",
      "Id": "ccbd06c59554444696b2eac1781ec1de"
    },
    {
      "Start": "2a95fac3804349c8a1c006e65cabab45",
      "End": "82613c221db04ce4bb1c651b2e6a840c",
      "Id": "45469f9b964f462397b3c92e70436b55"
    },
    {
      "Start": "1df4c199479a4a619251b9cac83d354e",
      "End": "75d23f50ffa64dc5abbe68f3bda9028a",
      "Id": "993998ca10e84be2a45e5d9281ab65cf"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.2.1.5175",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 59.611128755670663,
      "EyeY": 45.853865305839264,
      "EyeZ": 7.7870840512469783,
      "LookX": -90.735565483083718,
      "LookY": -34.579392806540341,
      "LookZ": -44.626523634243568,
      "UpX": -0.10158180269054171,
      "UpY": 0.99357185567659678,
      "UpZ": -0.049961034512134996
    },
    "NodeViews": [
      {
        "Id": "3925ec9f52d94c608b543c8bd23db57f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Geometry.Translate",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 771.47082295513565,
        "Y": 118.13451325028205
      },
      {
        "Id": "87905d1ef2814623be7c3691edbd104c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 505.39119988989171,
        "Y": 17.864989287555488
      },
      {
        "Id": "6325f0ad18424f67824bf5cd05c831e4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 554.36943620178045,
        "Y": 174.23145400593478
      },
      {
        "Id": "1b98e5b95b6c4712a322641449478b43",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 314.0,
        "Y": 49.379821958457
      },
      {
        "Id": "cbccf8333b7241fa9a2d0ac7eb844f98",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 250.0,
        "Y": 230.379821958457
      },
      {
        "Id": "64301f8854b84a428b4032b265979793",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 125.66516939205951,
        "Y": -48.006918644157508
      },
      {
        "Id": "273f062bb77a44889657db01c4ead60e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1168.0648041421782,
        "Y": -21.179522931245998
      },
      {
        "Id": "4402ced01a81413aa47a6051a89795d9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Plane.ByLineAndPoint",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 941.152843278941,
        "Y": -57.196331244701014
      }
    ],
    "Annotations": [],
    "X": -119.96541713649867,
    "Y": 186.09666667284867,
    "Zoom": 0.70823125000000009
  }
}