<Workspace Version="1.0.0.1180" X="-161.524365896328" Y="-138.272006317495" zoom="1.33823125" Name="Align Part By Connectors and Couple" Description="Align parts by specified connectors.  Will couple if Boolean set to True" ID="7d5835f4-51d4-4b43-a45a-fa07ad222688" Category="DynaFabrication2017.Parts">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="320a275b-593f-4c72-bf15-5595a7920231" type="PythonNodeModels.PythonNode" nickname="Fabrication Align Connectors" x="491.2" y="279.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationPart

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.ImportExtensions(Revit.GeometryConversion)


CpleBoo= UnwrapElement(IN[0])
Conn= UnwrapElement(IN[1])
ConnTo= UnwrapElement(IN[2])
Rot= UnwrapElement(IN[3])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(Doc)

for Item in Conn:
	for Item1 in ConnTo:
		FabricationPart.AlignPartByConnectors(Doc, Item, Item1, Rot)
		
if CpleBoo == True:
	for Item in Conn:
		for Item1 in ConnTo:
			FabricationPart.ConnectAndCouple(Doc, Item, Item1)	

TransactionManager.Instance.TransactionTaskDone()

#OUT = ItmList
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5e0553a4-5f36-4ce9-a5d2-b1a1a6d177d3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="314.8" y="312.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="31ae9bd0-0c45-41d0-971c-75a61431ee07" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="345.2" y="246.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Boolean" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7c1a12d7-f996-4d4d-9e85-12bbebda9c6c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="307.6" y="373.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Connector To" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5da6be3f-ca16-4457-9b01-8b6bb59fe60c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Math.DegreesToRadians" x="301.2" y="446" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Math.DegreesToRadians@double" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="977bbfeb-33a6-4651-9c42-7306bfc36e40" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="177.6" y="468" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Degrees" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5e0553a4-5f36-4ce9-a5d2-b1a1a6d177d3" start_index="0" end="320a275b-593f-4c72-bf15-5595a7920231" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="31ae9bd0-0c45-41d0-971c-75a61431ee07" start_index="0" end="320a275b-593f-4c72-bf15-5595a7920231" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7c1a12d7-f996-4d4d-9e85-12bbebda9c6c" start_index="0" end="320a275b-593f-4c72-bf15-5595a7920231" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5da6be3f-ca16-4457-9b01-8b6bb59fe60c" start_index="0" end="320a275b-593f-4c72-bf15-5595a7920231" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="977bbfeb-33a6-4651-9c42-7306bfc36e40" start_index="0" end="5da6be3f-ca16-4457-9b01-8b6bb59fe60c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>