<Workspace Version="1.0.0.1180" X="0" Y="0" zoom="1" Name="Clear Graphics Selection" Description="RME to FAB clear graphics.  If node doesnt work execute the button manualy and look in the journal file.  You will see something like this  Jrn.RibbonEvent &quot;Execute external command:CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Clear Graphics Selection:RVTFabExchange.ClearGraphicsElementsCmd&quot;. Take inbetween the first : and next : and put in string in node." ID="93b2935f-8c41-41dd-ae8a-f8f7be01e040" Category="DynaFabrication2017.Util">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f7d27523-fc9e-4092-8348-29da79340c1d" type="PythonNodeModels.PythonNode" nickname="External Command" x="679.773680365378" y="369.780179226094" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
clr.AddReference('RevitAPIUI')
import Autodesk
from Autodesk.Revit.UI import RevitCommandId
from Autodesk.Revit.UI import UIApplication
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Doc = DocumentManager.Instance.CurrentDBDocument
App =  DocumentManager.Instance.CurrentUIApplication

ItmList = list()
ItmList1 = list()
Inpt = IN[0]

CmmdID= RevitCommandId.LookupCommandId(Inpt)
CmId = CmmdID.Id
App.PostCommand(CmmdID)
	
ItmList.append(CmmdID)
ItmList1.append(CmId)

OUT = ItmList, ItmList1</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.StringInput guid="f56618e3-2944-4d44-9477-d2807caf9cf6" type="CoreNodeModels.Input.StringInput" nickname="String" x="402.515786910252" y="368.090089613047" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Clear Graphics Selection</System.String>
      <System.String value="CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Clear Graphics Selection" />
    </CoreNodeModels.Input.StringInput>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f56618e3-2944-4d44-9477-d2807caf9cf6" start_index="0" end="f7d27523-fc9e-4092-8348-29da79340c1d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>