<Workspace Version="1.0.0.1180" X="-323.150846985548" Y="-95.4299101333562" zoom="0.888789228297156" Name="Get All Fabrication Connector(s)" Description="Gets all the Connector(s) in the configuration" ID="549971e6-a922-48d2-99d5-a32afbe9b4d8" Category="DynaFabrication2017.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1e4e12df-6400-40c1-b1d0-21656eae35f3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1156.10117395672" y="560.795751638796" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Connector Domain" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="138dfe73-892b-4061-84b9-3f7c64fa6b8e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1164.24134959518" y="455.112089818568" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Connector Group" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6b03843f-1fa7-4be4-ab11-39d7ef111c94" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1152.73028491422" y="362.128763364905" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Connector Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e25b795b-faf3-4b99-b1da-92b8a9257d04" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="754.395320242862" y="469.033095019775" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <PythonNodeModels.PythonNode guid="6e336b55-300c-4cfc-979b-0fb5a32be1b8" type="PythonNodeModels.PythonNode" nickname="Fabrication Connector Group" x="934.188946383562" y="460.436541118145" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	InsSpecGrp = Config.GetFabricationConnectorGroup(Item)
	ItmList.append(InsSpecGrp)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="0c0a1491-a176-4527-91db-c74e85db66a7" type="PythonNodeModels.PythonNode" nickname="Fabrication Connector Domain" x="930.281998120385" y="562.570780647755" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	InsSpecAbrn = Config.GetFabricationConnectorDomain(Item)
	ItmList.append(InsSpecAbrn)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="7b8cf335-7c0c-4f4d-8e71-c5f8931efc9a" type="PythonNodeModels.PythonNode" nickname="Fabrication Connector Shape" x="932.816219091744" y="670.413641241445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	InsSpecAbrn = Config.GetFabricationConnectorShape(Item)
	ItmList.append(InsSpecAbrn)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="29900c6a-3745-47e6-a13e-009d1520b7dc" type="PythonNodeModels.PythonNode" nickname="Fabrication Connector Name" x="937.616883868331" y="352.153995655495" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	InsSpecName = Config.GetFabricationConnectorName(Item)
	ItmList.append(InsSpecName)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="df657f43-3ebb-4a9a-a44c-7d56c6572fe0" type="PythonNodeModels.PythonNode" nickname="Fabrication All Connector ID's" x="494.025364283608" y="430.521685912745" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
from Autodesk.Revit.DB import ConnectorDomainType
from Autodesk.Revit.DB import ConnectorProfileType

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Doc = DocumentManager.Instance.CurrentDBDocument

ItmList = list()

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)
AllInsSpecs = Config.GetAllFabricationConnectorDefinitions(ConnectorDomainType.Undefined, ConnectorProfileType.Invalid)
ItmList.append(AllInsSpecs)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="260bc7e7-b9ac-4602-be85-6ab4d8cc9d96" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1164.27961780499" y="681.715964236194" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Connector Shape" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c31614a8-ee92-4965-9f59-302091c56b16" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1131.61855605908" y="251.125219524762" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Connector ID" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e25b795b-faf3-4b99-b1da-92b8a9257d04" start_index="0" end="29900c6a-3745-47e6-a13e-009d1520b7dc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e25b795b-faf3-4b99-b1da-92b8a9257d04" start_index="0" end="6e336b55-300c-4cfc-979b-0fb5a32be1b8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e25b795b-faf3-4b99-b1da-92b8a9257d04" start_index="0" end="0c0a1491-a176-4527-91db-c74e85db66a7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e25b795b-faf3-4b99-b1da-92b8a9257d04" start_index="0" end="7b8cf335-7c0c-4f4d-8e71-c5f8931efc9a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e25b795b-faf3-4b99-b1da-92b8a9257d04" start_index="0" end="c31614a8-ee92-4965-9f59-302091c56b16" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6e336b55-300c-4cfc-979b-0fb5a32be1b8" start_index="0" end="138dfe73-892b-4061-84b9-3f7c64fa6b8e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0c0a1491-a176-4527-91db-c74e85db66a7" start_index="0" end="1e4e12df-6400-40c1-b1d0-21656eae35f3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7b8cf335-7c0c-4f4d-8e71-c5f8931efc9a" start_index="0" end="260bc7e7-b9ac-4602-be85-6ab4d8cc9d96" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="29900c6a-3745-47e6-a13e-009d1520b7dc" start_index="0" end="6b03843f-1fa7-4be4-ab11-39d7ef111c94" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="df657f43-3ebb-4a9a-a44c-7d56c6572fe0" start_index="0" end="e25b795b-faf3-4b99-b1da-92b8a9257d04" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>