<Workspace Version="1.0.0.1180" X="-23.790736818985" Y="-440.24161245746" zoom="0.988548899604768" Name="Get Fabrication Specification(s)" Description="Get all fabrication specification(s)" ID="78a01a83-c2e2-42d8-95ac-5800069f96bb" Category="DynaFabrication2017.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="240e24ed-248f-48f3-b49e-431dead88d5c" type="PythonNodeModels.PythonNode" nickname="Fabrication All Specification ID's" x="281.113103372645" y="807.083632917508" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Doc = DocumentManager.Instance.CurrentDBDocument

ItmList = list()

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)
AllSpecs = Config.GetAllSpecifications(None)

ItmList.append(AllSpecs)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="295a9b67-b470-481c-bd37-44bef6675b17" type="PythonNodeModels.PythonNode" nickname="Fabrication Specification Name" x="661.453720883689" y="733.07032490625" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	SpecName = Config.GetSpecificationName(Item)
	ItmList.append(SpecName)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="e562440b-109a-45fc-8e67-07cb710f1662" type="PythonNodeModels.PythonNode" nickname="Fabrication Specification Group" x="657.890790244451" y="809.96884528959" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	SpecGrp = Config.GetSpecificationGroup(Item)
	ItmList.append(SpecGrp)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="a03a83d9-3059-44c4-95c2-359891783f6f" type="PythonNodeModels.PythonNode" nickname="Fabrication Specification Abbreviation" x="653.833951042438" y="881.212816747449" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	SpecAbrn = Config.GetSpecificationAbbreviation(Item)
	ItmList.append(SpecAbrn)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7efd5ec2-4201-4867-8036-7716960a0471" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="917.614126424797" y="816.962571214225" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Spec Group" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="068d14aa-adbb-4168-8436-9ed1a78ab12f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="914.644637428305" y="730.847390315969" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Spec Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5b55375d-eb3d-44bb-b2fe-92bb5d526566" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="912.664978097311" y="889.22013679552" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Spec Abbreviation" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="201892b5-88a8-422f-b9e4-782d2bbbd099" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="512.483543639572" y="798.971979536012" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="240e24ed-248f-48f3-b49e-431dead88d5c" start_index="0" end="201892b5-88a8-422f-b9e4-782d2bbbd099" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="295a9b67-b470-481c-bd37-44bef6675b17" start_index="0" end="068d14aa-adbb-4168-8436-9ed1a78ab12f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e562440b-109a-45fc-8e67-07cb710f1662" start_index="0" end="7efd5ec2-4201-4867-8036-7716960a0471" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a03a83d9-3059-44c4-95c2-359891783f6f" start_index="0" end="5b55375d-eb3d-44bb-b2fe-92bb5d526566" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="201892b5-88a8-422f-b9e4-782d2bbbd099" start_index="0" end="295a9b67-b470-481c-bd37-44bef6675b17" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="201892b5-88a8-422f-b9e4-782d2bbbd099" start_index="0" end="e562440b-109a-45fc-8e67-07cb710f1662" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="201892b5-88a8-422f-b9e4-782d2bbbd099" start_index="0" end="a03a83d9-3059-44c4-95c2-359891783f6f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>