<Workspace Version="1.0.0.1180" X="-333.538891112884" Y="-178.194466013772" zoom="1.545620359375" Name="Import Fabrication Job" Description="Import MAJ file" ID="8de4dd11-3f45-4643-a566-cf29b9380b89" Category="DynaFabrication2017.Util">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.StringInput guid="fa1926d6-1458-4a53-9d4a-f9a059c6b7d2" type="CoreNodeModels.Input.StringInput" nickname="String" x="302.4" y="424.075031971369" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>CustomCtrl_%CustomCtrl_%CustomCtrl_%Add-Ins%Revit Extension for Fabrication%PulldownGroup%Import Autodesk Fabrication Job File</System.String>
      <System.String value="CustomCtrl_%CustomCtrl_%CustomCtrl_%Add-Ins%Revit Extension for Fabrication%PulldownGroup%Import Autodesk Fabrication Job File" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="1640c9b8-9b95-44f6-8a5e-2294ff285af6" type="PythonNodeModels.PythonNode" nickname="External Command" x="562.621766340996" y="425.061612426028" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
clr.AddReference('RevitAPIUI')
import Autodesk
from Autodesk.Revit.UI import RevitCommandId
from Autodesk.Revit.UI import UIApplication
from Autodesk.Revit.UI import ExternalCommandData
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Doc = DocumentManager.Instance.CurrentDBDocument
App =  DocumentManager.Instance.CurrentUIApplication

ItmList = list()
ItmList1 = list()
Inpt = IN[0]

CmmdID= RevitCommandId.LookupCommandId(Inpt)
CmId = CmmdID.Id
App.PostCommand(CmmdID)

ItmList.append(CmmdID)
ItmList1.append(CmId)

OUT = ItmList, ItmList1</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fa1926d6-1458-4a53-9d4a-f9a059c6b7d2" start_index="0" end="1640c9b8-9b95-44f6-8a5e-2294ff285af6" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>