<Workspace Version="1.0.0.1180" X="0" Y="0" zoom="1" Name="Part(s) Current Product List Entry" Description="Get the current Product list entry for the part(s)" ID="1db979e9-6c64-4001-9c77-0fbb00b39fe8" Category="DynaFabrication2017.Parts">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="285c0588-1a77-4f59-8b8e-dd5b04e22faf" type="PythonNodeModels.PythonNode" nickname="Fabrication Part Product Entry" x="500.57223266511" y="472.401156170147" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

FabricationParts = UnwrapElement(IN[0])
functionlist = list()

for item in FabricationParts:
	try:
		functionlist.append(item.get_Parameter(BuiltInParameter.FABRICATION_PRODUCT_ENTRY).AsString())
	except:
		functionlist.append('No Value')
OUT = functionlist
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="245f9560-8e64-4879-af29-d0cd854845dd" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="815.6" y="478.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Product List Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="68f7584e-7086-4086-9007-bd27f967cb19" type="PythonNodeModels.PythonNode" nickname="Fabrication Part Product Entry" x="491.77223266511" y="326.801156170147" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationPart

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

Inpt = UnwrapElement(IN[0])
Cnt = UnwrapElement(IN[1])
ItmList = list()

if Cnt &gt; 1:
	for Item in Inpt:
		CID = Item.ProductListEntry
		ItmList.append(CID)
else:
	CID = Inpt.ProductListEntry
	ItmList.append(CID)

OUT = ItmList
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2ef8eee2-9360-4011-92bb-d24801018824" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="281.2" y="320" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]" />
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b4fa26b0-bf29-49fc-9e5d-d31892a5b78b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="813.6" y="334.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Product List Index" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="88269c78-5c93-4ec9-9f7e-260aa471413b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="184" y="434.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Item(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="285c0588-1a77-4f59-8b8e-dd5b04e22faf" start_index="0" end="245f9560-8e64-4879-af29-d0cd854845dd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="68f7584e-7086-4086-9007-bd27f967cb19" start_index="0" end="b4fa26b0-bf29-49fc-9e5d-d31892a5b78b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2ef8eee2-9360-4011-92bb-d24801018824" start_index="0" end="68f7584e-7086-4086-9007-bd27f967cb19" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="88269c78-5c93-4ec9-9f7e-260aa471413b" start_index="0" end="285c0588-1a77-4f59-8b8e-dd5b04e22faf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="88269c78-5c93-4ec9-9f7e-260aa471413b" start_index="0" end="68f7584e-7086-4086-9007-bd27f967cb19" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="88269c78-5c93-4ec9-9f7e-260aa471413b" start_index="0" end="2ef8eee2-9360-4011-92bb-d24801018824" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>