<Workspace Version="1.0.0.1180" X="-737.279641934203" Y="-410.713583848219" zoom="1.78359936238281" Name="Reposition Fabrication Part" Description="Swaps selected end part with opposite end part." ID="dd069f67-c855-4633-82e7-64fae4c975bd" Category="DynaFabrication2017.Parts">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5a94f0cb-36cc-4c61-b796-13a6ed2c8400" type="PythonNodeModels.PythonNode" nickname="Fabrication Reposition" x="661.266850144792" y="413.57441164027" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationPart

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.ImportExtensions(Revit.GeometryConversion)

FabricationParts = UnwrapElement(IN[0])
Cnt= UnwrapElement(IN[1])
functionlist = list()

Doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(Doc)

if Cnt &gt; 1:
	for Item in FabricationParts:
		Item.Reposition(Doc, FabricationParts.Id)
		functionlist.append(FabricationParts.Id)
else:
		FabricationParts.Reposition(Doc, FabricationParts.Id)
		functionlist.append(FabricationParts.Id)
		
TransactionManager.Instance.TransactionTaskDone()

OUT = functionlist
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4ad623bc-03d0-4a42-a554-b5f49be51ea7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="552.8" y="330.4" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6c5113cd-0ca9-4d87-aaeb-4818596e5c6b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="493.2" y="436.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Input" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="895c43d7-f843-4a2b-849d-59b1f3bac89c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="847.6" y="418" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="ID" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5a94f0cb-36cc-4c61-b796-13a6ed2c8400" start_index="0" end="895c43d7-f843-4a2b-849d-59b1f3bac89c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4ad623bc-03d0-4a42-a554-b5f49be51ea7" start_index="0" end="5a94f0cb-36cc-4c61-b796-13a6ed2c8400" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c5113cd-0ca9-4d87-aaeb-4818596e5c6b" start_index="0" end="4ad623bc-03d0-4a42-a554-b5f49be51ea7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c5113cd-0ca9-4d87-aaeb-4818596e5c6b" start_index="0" end="5a94f0cb-36cc-4c61-b796-13a6ed2c8400" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>