<Workspace Version="1.0.0.1180" X="0" Y="0" zoom="1" Name="RevitLookup Snoop Active View" Description="Using RevitLookup, snoop Revit's active view.  RevitLookup must be installed for this to work. If node doesnt work execute the button manualy and look in the journal file.  You will see something like this J  Jrn.RibbonEvent &quot;Execute external command:CustomCtrl_%CustomCtrl_%CustomCtrl_%Add-Ins%Revit Lookup%Options%Snoop Active View...:RevitLookup.CmdSnoopActiveView&quot;. Take inbetween the first : and next : and put in string in node." ID="372ad4df-5d24-4651-82f4-83ee8d71bd60" Category="DynaFabrication2017.Util">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.StringInput guid="3a21ace6-bfcf-4fbc-a3a0-36fce5990f37" type="CoreNodeModels.Input.StringInput" nickname="String" x="344.915786910252" y="368.980179226094" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>CustomCtrl_%CustomCtrl_%CustomCtrl_%Add-Ins%Revit Lookup%Options%Snoop Active View...</System.String>
      <System.String value="CustomCtrl_%CustomCtrl_%CustomCtrl_%Add-Ins%Revit Lookup%Options%Snoop Active View..." />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="12220d28-a3b3-4506-9730-fee944abea73" type="PythonNodeModels.PythonNode" nickname="External Command" x="622.173680365378" y="370.670268839141" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
clr.AddReference('RevitAPIUI')
import Autodesk
from Autodesk.Revit.UI import RevitCommandId
from Autodesk.Revit.UI import UIApplication
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Doc = DocumentManager.Instance.CurrentDBDocument
App =  DocumentManager.Instance.CurrentUIApplication

ItmList = list()
ItmList1 = list()
Inpt = IN[0]

CmmdID= RevitCommandId.LookupCommandId(Inpt)
CmId = CmmdID.Id
App.PostCommand(CmmdID)
	
ItmList.append(CmmdID)
ItmList1.append(CmId)

OUT = ItmList, ItmList1</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3a21ace6-bfcf-4fbc-a3a0-36fce5990f37" start_index="0" end="12220d28-a3b3-4506-9730-fee944abea73" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>