<Workspace Version="1.0.0.1180" X="-352" Y="-183.2" zoom="1" Name="Rotate Tap By Connector" Description="Rotate a tap about a connector" ID="7609665a-e83e-472a-af95-cd3d85cb4105" Category="DynaFabrication2017.Parts">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="4f52fd58-18ff-42b2-affa-c0a515d71c65" type="PythonNodeModels.PythonNode" nickname="Fabrication Rotate Postion by Angle" x="875.975266474393" y="486.80145169561" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationPart

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.ImportExtensions(Revit.GeometryConversion)

FabricationParts = UnwrapElement(IN[0])
AngPri = UnwrapElement(IN[1])
AngSec = UnwrapElement(IN[2])
Cnt= UnwrapElement(IN[3])
functionlist = list()

Doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(Doc)

if Cnt &gt; 1:
	for Item in FabricationParts:	
		functionlist.append(Item.RotateConnectedTap(Doc, FabricationParts, AngPri, AngSec))
else:		
		functionlist.append(FabricationParts.RotateConnectedTap(Doc, FabricationParts, AngPri, AngSec))
		
TransactionManager.Instance.TransactionTaskDone()
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fbda9d2c-2fcc-4418-a0b5-7f2359dced98" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Math.DegreesToRadians" x="668.262316103297" y="625.953661301195" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Math.DegreesToRadians@double" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="05468341-2803-48c0-bb9b-392d672d1765" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="505.609572795111" y="533.14156090638" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Primary Angle" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e801dec2-b6dc-4d8f-9add-55b2db4b36e2" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1118.96439520771" y="485.558118559827" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="10b5f981-8fcc-4846-9d62-65a783452d63" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="529.807454226276" y="455.712042231016" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Input(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="da4b0d13-cbe0-48d3-aa75-521b07853224" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="755.653355751834" y="377.6" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3c2ff58d-4694-4f53-bce2-86a055fb29c0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="484" y="640.070445028146" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Secondary Angle" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ccbc62af-d2ba-44d1-a47a-4b602a7d48f6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Math.DegreesToRadians" x="667.862316103297" y="528.753661301195" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.Math.DegreesToRadians@double" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4f52fd58-18ff-42b2-affa-c0a515d71c65" start_index="0" end="e801dec2-b6dc-4d8f-9add-55b2db4b36e2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fbda9d2c-2fcc-4418-a0b5-7f2359dced98" start_index="0" end="4f52fd58-18ff-42b2-affa-c0a515d71c65" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="05468341-2803-48c0-bb9b-392d672d1765" start_index="0" end="ccbc62af-d2ba-44d1-a47a-4b602a7d48f6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="10b5f981-8fcc-4846-9d62-65a783452d63" start_index="0" end="4f52fd58-18ff-42b2-affa-c0a515d71c65" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="10b5f981-8fcc-4846-9d62-65a783452d63" start_index="0" end="da4b0d13-cbe0-48d3-aa75-521b07853224" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="da4b0d13-cbe0-48d3-aa75-521b07853224" start_index="0" end="4f52fd58-18ff-42b2-affa-c0a515d71c65" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3c2ff58d-4694-4f53-bce2-86a055fb29c0" start_index="0" end="fbda9d2c-2fcc-4418-a0b5-7f2359dced98" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ccbc62af-d2ba-44d1-a47a-4b602a7d48f6" start_index="0" end="4f52fd58-18ff-42b2-affa-c0a515d71c65" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>