<Workspace Version="1.0.0.1180" X="0" Y="0" zoom="1" Name="Store Graphics Elements" Description="RME to FAB graphics elements.  If node doesnt work execute the button manualy and look in the journal file.  You will see something like this  Jrn.RibbonEvent &quot;Execute external command:CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Store Graphics Elements:RVTFabExchange.StoreGraphicsElementsCmd&quot;. Take inbetween the first : and next : and put in string in node." ID="f14f3e74-4829-49d4-a5e8-01bae6eb9023" Category="DynaFabrication2017.Util">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ab6a6b8a-3740-4710-a1fb-dc6c15674be0" type="PythonNodeModels.PythonNode" nickname="External Command" x="702.854837002657" y="444.714942370769" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
clr.AddReference('RevitAPIUI')
import Autodesk
from Autodesk.Revit.UI import RevitCommandId
from Autodesk.Revit.UI import UIApplication
from Autodesk.Revit.UI import ExternalCommandData
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Doc = DocumentManager.Instance.CurrentDBDocument
App =  DocumentManager.Instance.CurrentUIApplication

ItmList = list()
ItmList1 = list()
Inpt = IN[0]
Cnt = IN[1]

if Cnt &gt; 0:
	CmmdID= RevitCommandId.LookupCommandId(Inpt)
	CmId = CmmdID.Id
	App.PostCommand(CmmdID)
	
	ItmList.append(CmmdID)
	ItmList1.append(CmId)
else:
	ItmList.append("No Item(s) selected")
	ItmList1.append("No Item(s) selected")

OUT = ItmList, ItmList1</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.StringInput guid="2cd0a1d6-7dfc-4efa-a4d8-dc19c96751d7" type="CoreNodeModels.Input.StringInput" nickname="String" x="417.596943547531" y="460.624852757722" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Store Graphics Elements</System.String>
      <System.String value="CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Store Graphics Elements" />
    </CoreNodeModels.Input.StringInput>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9aad8e29-4011-4ae8-b4e1-0f5528a6fff8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="581.340530559735" y="350.793589908868" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]" />
    <PythonNodeModels.PythonNode guid="bd27e244-0eb8-4e4c-a919-1131248cd470" type="PythonNodeModels.PythonNode" nickname="Python Script" x="439.03181500896" y="352.575041397769" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com
#inspired by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
app = DocumentManager.Instance.CurrentUIApplication.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import ElementId
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI.Selection import *

clr.AddReference("System")
from System.Collections.Generic import List as cList

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

elements = UnwrapElement(tolist(IN[0]))

if "2014" in app.VersionName :
	TransactionManager.Instance.EnsureInTransaction(doc)
	sel1  = uidoc.Selection.Elements
	for i in xrange(len(elements)): 
		try:(sel1.Add(elements[i]))
		except: pass
	OUT = "%s elements selected in Revit." %sel1.Size
	TransactionManager.Instance.TransactionTaskDone()
else:
	ids1 = []
	for i in xrange(len(elements)):
		try:(ids1.append(elements[i].Id))
		except: pass
	ids2 = cList[ElementId](ids1)
	uidoc.Selection.SetElementIds(ids2)
	OUT = "%s elements selected in Revit." %ids2.Count</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8f77a4a0-f529-448e-95f4-b3ad5fb5f557" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="269.810936348795" y="297.076916144491" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="456776ad-f6da-461c-90a3-7eb4271e6dcb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="203.842386753065" y="363.573094235301" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="reset:bool = true;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2cd0a1d6-7dfc-4efa-a4d8-dc19c96751d7" start_index="0" end="ab6a6b8a-3740-4710-a1fb-dc6c15674be0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9aad8e29-4011-4ae8-b4e1-0f5528a6fff8" start_index="0" end="ab6a6b8a-3740-4710-a1fb-dc6c15674be0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bd27e244-0eb8-4e4c-a919-1131248cd470" start_index="0" end="9aad8e29-4011-4ae8-b4e1-0f5528a6fff8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f77a4a0-f529-448e-95f4-b3ad5fb5f557" start_index="0" end="bd27e244-0eb8-4e4c-a919-1131248cd470" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="456776ad-f6da-461c-90a3-7eb4271e6dcb" start_index="0" end="bd27e244-0eb8-4e4c-a919-1131248cd470" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>