<Workspace Version="1.0.0.1180" X="84.2634949970976" Y="-129.708461198485" zoom="1.30764135636719" Name="Store Design Line Elements" Description="RME to FAB store design lines.  If node doesnt work execute the button manualy and look in the journal file.  You will see something like this Jrn.RibbonEvent &quot;Execute external command:CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Store Design Line Elements:RVTFabExchange.StoreDesignLineElementsCmd&quot;. Take inbetween the first : and next : and put in string in node." ID="79232d39-2aca-4a00-aa04-a46b0570886b" Category="DynaFabrication2017.Util">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="521a9ad9-e8c4-452a-94ae-1d77e5f20dce" type="PythonNodeModels.PythonNode" nickname="External Command" x="526.057893455126" y="399.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2016, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
clr.AddReference('RevitAPIUI')
import Autodesk
from Autodesk.Revit.UI import RevitCommandId
from Autodesk.Revit.UI import UIApplication
from Autodesk.Revit.UI import ExternalCommandData
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Doc = DocumentManager.Instance.CurrentDBDocument
App =  DocumentManager.Instance.CurrentUIApplication

ItmList = list()
ItmList1 = list()
Inpt = IN[0]
Cnt = IN[1]

if Cnt &gt; 0:
	CmmdID= RevitCommandId.LookupCommandId(Inpt)
	CmId = CmmdID.Id
	App.PostCommand(CmmdID)
	
	ItmList.append(CmmdID)
	ItmList1.append(CmId)
else:
	ItmList.append("No Item(s) selected")
	ItmList1.append("No Item(s) selected")

OUT = ItmList, ItmList1</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.StringInput guid="78ce6ecb-9850-45ae-8c1e-e202999def9a" type="CoreNodeModels.Input.StringInput" nickname="String" x="240.8" y="415.109910386953" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Store Design Line Elements</System.String>
      <System.String value="CustomCtrl_%CustomCtrl_%Add-Ins%RME to FAB%Store Design Line Elements" />
    </CoreNodeModels.Input.StringInput>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="bd8409cc-0c0f-4919-a7c8-afbcdddd6878" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="417.810936348795" y="294.676916144491" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]" />
    <PythonNodeModels.PythonNode guid="fe5be62c-86de-43d6-bf2d-da09647a8a78" type="PythonNodeModels.PythonNode" nickname="Python Script" x="267.50222079802" y="286.858367633392" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com
#inspired by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
app = DocumentManager.Instance.CurrentUIApplication.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import ElementId
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI.Selection import *

clr.AddReference("System")
from System.Collections.Generic import List as cList

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

elements = UnwrapElement(tolist(IN[0]))

if "2014" in app.VersionName :
	TransactionManager.Instance.EnsureInTransaction(doc)
	sel1  = uidoc.Selection.Elements
	for i in xrange(len(elements)): 
		try:(sel1.Add(elements[i]))
		except: pass
	OUT = "%s elements selected in Revit." %sel1.Size
	TransactionManager.Instance.TransactionTaskDone()
else:
	ids1 = []
	for i in xrange(len(elements)):
		try:(ids1.append(elements[i].Id))
		except: pass
	ids2 = cList[ElementId](ids1)
	uidoc.Selection.SetElementIds(ids2)
	OUT = "%s elements selected in Revit." %ids2.Count</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="830f38d0-e134-4195-8ca1-cf523dd10276" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="106.281342137855" y="240.960242380114" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0d06ddf1-97a1-4f2d-9d8e-82d4c8367591" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="40.3127925421249" y="307.456420470924" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="reset:bool = true;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="78ce6ecb-9850-45ae-8c1e-e202999def9a" start_index="0" end="521a9ad9-e8c4-452a-94ae-1d77e5f20dce" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bd8409cc-0c0f-4919-a7c8-afbcdddd6878" start_index="0" end="521a9ad9-e8c4-452a-94ae-1d77e5f20dce" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fe5be62c-86de-43d6-bf2d-da09647a8a78" start_index="0" end="bd8409cc-0c0f-4919-a7c8-afbcdddd6878" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="830f38d0-e134-4195-8ca1-cf523dd10276" start_index="0" end="fe5be62c-86de-43d6-bf2d-da09647a8a78" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0d06ddf1-97a1-4f2d-9d8e-82d4c8367591" start_index="0" end="fe5be62c-86de-43d6-bf2d-da09647a8a78" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>