<?xml version="1.0"?>
<doc>
    <assembly>
        <name>QuasarII</name>
    </assembly>
    <members>
        <member name="T:QuasarII.RvtNodes">
            <summary>
            
            </summary>
        </member>
        <member name="T:QuasarII.BuiltIns">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.BuiltIns.GetBuiltInParameterName(Revit.Elements.Element,System.Collections.Generic.List{System.String})">
            <summary>
            Collect BuiltInParameter Name(s) by an Element and Parameter Name(s).
            </summary>
            <param name="Element">An Element.</param>
            <param name="ParameterNames">A list of Parameter Name(s) related to the Element.</param>
            <returns name="NameObjectDict">A list of BuitInParameter object(s).</returns>
        </member>
        <member name="M:QuasarII.BuiltIns.GetBuiltInCategory(System.Collections.Generic.List{Revit.Elements.Category})">
            <summary>
            Collect BuiltInCategory object(s).
            </summary>
            <param name="categories">A list of Category object(s).</param>
            <returns>A Dictionary (key=string, value=BuiltInCategory) object.</returns>
        </member>
        <member name="T:QuasarII.ElementGraphics">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.ElementGraphics.CopyFiltersFromView(Revit.Elements.Views.View,System.Collections.Generic.List{Revit.Elements.Views.View})">
            <summary>
            Copy filters with the override graphic settings from a View.
            </summary>
            <param name="FromView">Copy filters from a View.</param>
            <param name="ToViews">A list of View(s) to paste filters.</param>
            <returns name="Views">A list of filters pasted View(s).</returns>
        </member>
        <member name="M:QuasarII.ElementGraphics.HideUnhideElementsInViews(System.Collections.Generic.List{Revit.Elements.Element},System.Collections.Generic.List{Revit.Elements.Element},System.Boolean)">
            <summary>
            Hide/Unhide a list of Element(s) in the given View(s).
            </summary>
            <param name="Elements">A list of Element(s).</param>
            <param name="Views">A list of View(s).</param>
            <param name="HideUnhide">A boolean value. (true = hide , false = unhide)</param>
            <returns name="result">Result message.</returns>
        </member>
        <member name="M:QuasarII.ElementGraphics.HideUnhideLinkLevelGrid(System.Boolean)">
            <summary>
            Hide/Unhide Levels and Grids Elements from the Link Documents.
            </summary>
            <param name="Hide"> Hide = true, Unhide = false</param>
            <returns name="result">return message</returns>
        </member>
        <member name="T:QuasarII.LinkDocument">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.LinkDocument.GetElementFromLinkDocument(Revit.Elements.Category,Autodesk.Revit.DB.Document)">
            <summary>
            Collect Elements by a Category and a Document.
            </summary>
            <param name="Category">A Category object.</param>
            <param name="Document">A Document object.</param>
            <returns name = "Element">A list of Elements.</returns>
        </member>
        <member name="T:QuasarII.MEPSpaces">
            <summary>
            MEP Nodes
            </summary>
        </member>
        <member name="M:QuasarII.MEPSpaces.GetSpacesByZone(Autodesk.Revit.DB.Mechanical.Zone)">
            <summary>
            Collect Space(s) from a Zone.
            </summary>
            <param name="zone">A Zone element.</param>
            <returns name="Spaces">A list of Spaces</returns>
        </member>
        <member name="M:QuasarII.MEPSpaces.CenterSpace(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            Relocate Spaces' location points to the center of the Spaces.
            </summary>
            <param name="Spaces">A list of Space Elements.</param>
            <returns name="CenteredSpaces">A list of centered Space Elements.</returns>
        </member>
        <member name="M:QuasarII.MEPSpaces.SpaceTagToSpace(Revit.Elements.Element,System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            Relocate spaces' tags to the spaces' location points in given View.
            </summary>
            <param name="view">A View Element.</param>
            <param name="SpaceTags">A list of SpaceTag.</param>
            <returns name="Results">A list of relocated SpaceTag.</returns>
        </member>
        <member name="M:QuasarII.MEPSpaces.SpaceNameNumbering(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            Space's Name and Number to follow Room's Name and Number. ** Only for the Room(s) existed Space(s). 
            </summary>
            <param name="Spaces">A list of Space Element(s).</param>
            <returns name="Results">A list of modified Space Element(s).</returns>
        </member>
        <member name="T:QuasarII.RoomUtility">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.RoomUtility.CenterRoom(System.Collections.Generic.List{Revit.Elements.Room})">
            <summary>
            Relocate Rooms' location points to the center of the Rooms.
            </summary>
            <param name="Rooms">A list of Room Elements.</param>
            <returns name="CenteredRooms">A list of centered Room Elements.</returns>
        </member>
        <member name="M:QuasarII.RoomUtility.RoomTagToRoom(Revit.Elements.Element,System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            Relocate rooms' tags to the rooms' location points in given view.
            </summary>
            <param name="view">A View Element.</param>
            <param name="RoomTags">A list of RoomTag.</param>
            <returns name="Results">A list of relocated RoomTag.</returns>
        </member>
        <member name="M:QuasarII.RoomUtility.CollectRoomsByStatus">
            <summary>
            Collect Room(s) by Status.
            </summary>
            <returns>Status and A list of Room(s).</returns>
        </member>
        <member name="T:QuasarII.ViewUtility">
            <summary>
            Revit Nodes ViewUtility class
            </summary>
        </member>
        <member name="M:QuasarII.ViewUtility.ActiveView">
            <summary>
            Get the Active View of the current Document.
            
            </summary>
            <returns name = "ActiveView">returns ActiveView of the current Document </returns>
        </member>
        <member name="M:QuasarII.ViewUtility.AllViewsByViewTypeName(System.String)">
            <summary>
            Collect all the views of a ViewType by ViewType's Name.
            </summary>
            <param name="viewType">A ViewType's Name.</param>
            <returns name="Views">A list of View Elements.</returns>
        </member>
        <member name="M:QuasarII.ViewUtility.CreatePlanViewsByRooms(System.Collections.Generic.List{Revit.Elements.Room},System.Collections.Generic.List{System.String},Revit.Elements.Element,System.Int32,System.Double)">
            <summary>
            Create PlanView(s) by Room(s). *Only Placed/Correct Rooms will be created.
            Offset Measurement : METRIC Millimeter(mm) / IMPERIAL Feet(ft).
            </summary>
            <param name="Rooms">A list of Room Element(s).</param>
            <param name="Names">A list of string(s).</param>
            <param name="viewFamilyType">A FloorPlan or CeilingPlan view family type.</param>
            <param name="Scale">An integer scale value.</param>
            <param name="Offset">A double offset value. 
            mm (metric)/ft (imperial) </param>
            <returns name="PlanViews">A list of created plan view(s).</returns>
        </member>
        <member name="M:QuasarII.ViewUtility.CreateThreeDViewsByRooms(System.Collections.Generic.List{Revit.Elements.Room},System.Collections.Generic.List{System.String},Revit.Elements.Element,System.Int32,System.Double)">
            <summary>
            Create 3DView(s) by Room(s). *Only Placed/Correct Rooms will be created.
            Offset Measurement : METRIC Millimeter(mm) / IMPERIAL Feet(ft).
            </summary>
            <param name="Rooms">A list of Room Element(s).</param>
            <param name="Names">A list of string(s).</param>
            <param name="viewFamilyType">A 3D view family type.</param>
            <param name="Scale">An integer scale value.</param>
            <param name="Offset">A double offset value. 
            mm (metric) / ft (imperial) </param>
            <returns name="ThreeDViews">A list of created 3D view(s).</returns>
        </member>
        <member name="M:QuasarII.ViewUtility.CreateElevationsByRooms(System.Collections.Generic.List{Revit.Elements.Room},Revit.Elements.Element,System.Int32,System.Double)">
            <summary>
            Create Elevation View(s) by Room(s). *Only Placed/Correct Rooms will be created.
            Offset Measurement : METRIC Millimeter(mm) / IMPERIAL Feet(ft).
            </summary>
            <param name="Rooms"></param>
            <param name="viewFamilyType"></param>
            <param name="Scale"></param>
            <param name="Offset"></param>
            <returns name="Elevations">A list of created Elevation view(s).</returns>
        </member>
        <member name="T:QuasarII.WorksetUtility">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.WorksetUtility.AllElementsByWorksetName(System.String)">
            <summary>
            Collect Elements by a Workset Name.
            </summary>
            <param name="WorksetName">A Workset's Name.</param>
            <returns name="Elements">A list of Elements in the Workset.</returns>
        </member>
        <member name="M:QuasarII.WorksetUtility.AllElementsOfWorkset(Autodesk.Revit.DB.Workset)">
            <summary>
            Collect Elements by a Workset.
            </summary>
            <param name="workset">A Workset.</param>
            <returns name="Elements">A list of Elements in the Workset.</returns>
        </member>
        <member name="T:QuasarII.ZoneUtility">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.ZoneUtility.AddSpacesToZone(Autodesk.Revit.DB.Mechanical.Zone,System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            Add Space(s) to a Zone.
            </summary>
            <param name="zone">A Zone element.</param>
            <param name="Spaces">A List of Space Element(s).</param>
            <returns name="zone">A Zone Element.</returns>
        </member>
        <member name="T:QuasarII.Samples">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.Samples.Plus(System.Double,System.Double)">
            <summary>
            Plus two number.
            </summary>
            <param name="x"> first value</param>
            <param name="y"> second value</param>
            <returns>Plus result</returns>
        </member>
        <member name="M:QuasarII.Samples.RectangularGrid(System.Int32,System.Int32)">
            <summary>
            Create RectangularGrid with x and y values.
            </summary>
            <param name="xCount"> number of gird for horizontal/X direction</param>
            <param name="yCount"> number of gird for vertical/Y direction</param>
            <returns> A list of rectangles </returns>
        </member>
        <member name="M:QuasarII.Samples.MultiReturn(System.Double,System.Double)">
            <summary>
            Return multiple values
            </summary>
            <param name="a"> a double value </param>
            <param name="b"> b double value </param>
            <returns>return a dictionary</returns>
            <search>plus, multi</search>
        </member>
        <member name="M:QuasarII.Samples.CreateCube(System.Double,System.Double,System.Double,Autodesk.DesignScript.Geometry.Plane)">
            <summary>
            Create a cube by length, width, height and plane.
            </summary>
            <param name="x">length value</param>
            <param name="y">width value</param>
            <param name="z">height value</param>
            <param name="plane">reference plane</param>
            <returns> cube solid object</returns>
        </member>
        <member name="T:QuasarII.UtilsFunctions">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.UtilsFunctions.BBoxToCurveLoop(Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            
            </summary>
            <param name="bbox"></param>
            <returns></returns>
        </member>
        <member name="M:QuasarII.UtilsFunctions.RoomGeoToCurveLoop(Autodesk.Revit.DB.Architecture.Room)">
            <summary>
            
            </summary>
            <returns></returns>
        </member>
        <member name="M:QuasarII.UtilsFunctions.GetLevelView">
            <summary>
            
            </summary>
        </member>
        <member name="M:QuasarII.UtilsFunctions.DocUnitDivider">
            <summary>
            
            </summary>
            <returns></returns>
        </member>
        <member name="M:QuasarII.UtilsFunctions.CreateBoundingBox(Autodesk.Revit.DB.BoundingBoxXYZ,System.Double)">
            <summary>
            
            </summary>
            <returns></returns>
        </member>
        <member name="M:QuasarII.UtilsFunctions.RoomQualChecker(System.Collections.Generic.List{Revit.Elements.Room})">
            <summary>
            
            </summary>
            <returns></returns>
        </member>
        <member name="M:QuasarII.UtilsFunctions.SpaceQualChecker(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            
            </summary>
            <returns></returns>
        </member>
        <member name="M:QuasarII.UtilsFunctions.GetRvtTypeRoom(Revit.Elements.Room)">
            <summary>
            
            </summary>
            <returns></returns>
        </member>
    </members>
</doc>
