<Workspace Version="1.2.0.2831" X="-96.2059253520813" Y="513.716237704281" zoom="1.48315814991331" Name="PathReinforcement.GetRebar" Description="Get the Rebar objects hosted by a Path Reinforcment" ID="7f584efe-2c7c-47cb-a557-a1cb7e4eeb56" Category="BIM4Struc.Rebar.QueryTools">
  <NamespaceResolutionMap>
    <ClassMap partialName="Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Curves" resolvedName="Geometry.Curves" assemblyName="LunchBox.dll" />
    <ClassMap partialName="DesignScript.Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="d5605fdd-8fe7-4543-b483-3a3a2050cf4f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="789.785197828743" y="5.21792146528787" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Get Rebar-in-System objects woned by a Path Reinforcement.
#Authored by Dieter Vermeulen, Autodesk, 2016
#http://revitbeyondbim.wordpress.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

Rebar=[]
reb=[]

#get Host Family Instance

for i in IN[0]:
	pathReinf=UnwrapElement(i)
	ids=pathReinf.GetRebarInSystemIds()
	for id in ids:
		inst=doc.GetElement.Overloads[Autodesk.Revit.DB.ElementId](id).ToDSType(True)
		reb.append(inst)
	Rebar.append(reb)
		
OUT = Rebar
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="dc37aab2-f959-4ea7-8912-e17f1cc88b4e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="573.73885368093" y="10.7139386977901" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({lst});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d2117228-b2a4-4cad-880f-9b7a3316f684" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="944.402593532576" y="2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="RebarElements;" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bac69c95-8d23-4de8-9774-256ec3b565c5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="316" y="7" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Path Reinforcement&#xD;&#xA;PathReinforcement:var[];" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d5605fdd-8fe7-4543-b483-3a3a2050cf4f" start_index="0" end="d2117228-b2a4-4cad-880f-9b7a3316f684" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dc37aab2-f959-4ea7-8912-e17f1cc88b4e" start_index="0" end="d5605fdd-8fe7-4543-b483-3a3a2050cf4f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bac69c95-8d23-4de8-9774-256ec3b565c5" start_index="0" end="dc37aab2-f959-4ea7-8912-e17f1cc88b4e" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="2ad0c6c5-19a9-45bc-a9d4-8395678d25ae" text="*****************************************************&#xD;&#xA;Get the rebar-in-system objects owned by a Path Reinforcement.&#xD;&#xA;&#xD;&#xA;Authored by Dieter Vermeulen, Autodesk, 2016&#xD;&#xA;http://revitbeyondbim.wordpress.com&#xD;&#xA;*****************************************************" x="259.668437730577" y="-124.621114804138" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10755.896484375" eyeY="18973.96484375" eyeZ="11064.6376953125" lookX="10755.896484375" lookY="-18973.96484375" lookZ="-11064.6376953125" upX="0.433912664651871" upY="0.782608151435852" upZ="-0.446367859840393" />
  </Cameras>
</Workspace>