<Workspace Version="1.2.0.2831" X="129.630298261168" Y="263.733127847512" zoom="0.803321593462598" Name="Rebar.SetDistributionType" Description="Toggle to set the distribution type of a rebar set to &quot;Varying Length&quot; (True) or &quot;Uniform&quot; (False)" ID="97ff9e0c-15d2-4f77-8cf3-913dda3dc1db" Category="BIM4Struc.Rebar.Layout">
  <NamespaceResolutionMap>
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="107b21b0-517d-40d8-aa3f-43f9f7aaad00" type="PythonNodeModels.PythonNode" nickname="Python Script" x="289.085015824794" y="-2.13876399327188" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Sets the distribution type of a selected rebar
#Authored by Dieter Vermeulen, Autodesk, 2016
#http://revitbeyondbim.wordpress.com

import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference("System")
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
rebarElement = UnwrapElement(IN[0])
distributionToggle=IN[1]

#Change rebar in transaction
TransactionManager.Instance.EnsureInTransaction(doc)
#Case "VaryingLength Distribution Type"
if distributionToggle==True:
	rebarElement.DistributionType=DistributionType.VaryingLength
else:
	rebarElement.DistributionType=DistributionType.Uniform
TransactionManager.Instance.TransactionTaskDone()

OUT = rebarElement</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6bb269dc-4bfd-469c-b559-061b46f97282" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="rebarElement:Element;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4f958a11-22be-4075-8fea-047726df8b60" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-78.4243826042916" y="64.1066285762521" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Choose the distribution type&#xD;&#xA;//True = Varying Length&#xD;&#xA;//False = Uniform&#xD;&#xA;DistributionType:bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="78fa0366-97f0-4ce6-b4c9-1e2c4c3e0f76" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="454.964229077059" y="-3.7344944097282" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="rebarElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="107b21b0-517d-40d8-aa3f-43f9f7aaad00" start_index="0" end="78fa0366-97f0-4ce6-b4c9-1e2c4c3e0f76" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6bb269dc-4bfd-469c-b559-061b46f97282" start_index="0" end="107b21b0-517d-40d8-aa3f-43f9f7aaad00" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4f958a11-22be-4075-8fea-047726df8b60" start_index="0" end="107b21b0-517d-40d8-aa3f-43f9f7aaad00" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="4765ad7d-a2cd-44de-86b4-f39a7c7d023a" text="*****************************************************&#xD;&#xA;Toggle to set the distribution type of a rebar set to &quot;Varying Length&quot; (True) or &quot;Uniform&quot; (False).&#xD;&#xA;&#xD;&#xA;Authored by Dieter Vermeulen, Autodesk, 2016&#xD;&#xA;http://revitbeyondbim.wordpress.com&#xD;&#xA;*****************************************************" x="-74.229671835585" y="-127.885430546808" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="2099.18654837802" eyeY="2718.74320782094" eyeZ="1346.50785737952" lookX="-1857.82917054303" lookY="-1551.42610152185" lookZ="-2189.8531504461" upX="-0.178318426329325" upY="0.961261695938322" upZ="-0.210186799664539" />
  </Cameras>
</Workspace>