<Workspace Version="1.2.0.2831" X="-503" Y="-390" zoom="1" Name="Rebar.SetLayoutAsNumberWithSpacing" Description="Sets the Layout Rule property of rebar set to NumberWithSpacing" ID="824721d7-944e-4d05-a74d-faa0e698265b" Category="BIM4Struc.Rebar.Layout">
  <NamespaceResolutionMap>
    <ClassMap partialName="Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="18e06109-7418-4fc2-a4a3-46066aed533c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1062" y="617.18315586505" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="rebarElement:Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="936f0bd9-fe64-4c09-a3a0-b3b980775d99" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="831" y="699.032243863643" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The number of bar positions in rebar set&#xD;&#xA;Quantity:int" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="11ba63db-9fcf-4b33-b1a2-365b58cb0e62" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="827" y="804.881331862237" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The maximum spacing between rebar in rebar set&#xD;&#xA;Spacing:double" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="96add988-caec-4751-b413-4beafbfdc1f0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="707" y="880.73041986083" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Identifies if the bars of the rebar set are on the same side &#xD;&#xA;//of the rebar plane indicated by the normal&#xD;&#xA;barsOnNormalSide:bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="c8010114-a3c6-4973-9035-d90d981692d2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1395.36126282517" y="808.392129639187" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="7">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
      <PortInfo index="6" default="False" />
      <Script>#Sets the Layout Rule property of rebar set to NumberWithSpacing.
#Authored by Dieter Vermeulen, Autodesk, 2016
#http://revitbeyondbim.wordpress.com

import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference("System")
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
rebarElement = UnwrapElement(IN[0])
numberOfBarPositions = IN[1]
spacing = IN[2]
barsOnNormalSide = IN[3]
inclFirstBar=IN[4]
inclLastBar=IN[5]

#convert from mm to feet:
if IN[6]:
	spacing=spacing/304.8

#Change rebar in transaction
TransactionManager.Instance.EnsureInTransaction(doc)
rebarElement.SetLayoutAsNumberWithSpacing(numberOfBarPositions,spacing,barsOnNormalSide,inclFirstBar,inclLastBar)
TransactionManager.Instance.TransactionTaskDone()

OUT = rebarElement</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0f8e3cde-002b-4935-87b5-aeb8b5ca044e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1545.66884652232" y="616.806996184206" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="rebarElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="218e21e0-827e-4c19-bb83-956492fd9b37" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="806" y="989.579507859423" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Identifies if the first bar in rebar set is shown&#xD;&#xA;IncludeFirstBar:bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d9a8cfb2-d040-44d8-aac1-0de8ac01fe18" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="823" y="1080.42859585802" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//dentifies if the last bar in rebar set is shown&#xD;&#xA;IncludeLastBar:bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="11a41355-9943-413f-bec2-48a5582f06fb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="848" y="1171.27768385661" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input the value in mm (true) or feet (false)&#xD;&#xA;InputInMM: bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="18e06109-7418-4fc2-a4a3-46066aed533c" start_index="0" end="c8010114-a3c6-4973-9035-d90d981692d2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="18e06109-7418-4fc2-a4a3-46066aed533c" start_index="0" end="0f8e3cde-002b-4935-87b5-aeb8b5ca044e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="936f0bd9-fe64-4c09-a3a0-b3b980775d99" start_index="0" end="c8010114-a3c6-4973-9035-d90d981692d2" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="11ba63db-9fcf-4b33-b1a2-365b58cb0e62" start_index="0" end="c8010114-a3c6-4973-9035-d90d981692d2" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96add988-caec-4751-b413-4beafbfdc1f0" start_index="0" end="c8010114-a3c6-4973-9035-d90d981692d2" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="218e21e0-827e-4c19-bb83-956492fd9b37" start_index="0" end="c8010114-a3c6-4973-9035-d90d981692d2" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9a8cfb2-d040-44d8-aac1-0de8ac01fe18" start_index="0" end="c8010114-a3c6-4973-9035-d90d981692d2" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="11a41355-9943-413f-bec2-48a5582f06fb" start_index="0" end="c8010114-a3c6-4973-9035-d90d981692d2" end_index="6" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="d732480a-5d34-40fa-9fc7-7ccbbb7b1cc2" text="*****************************************************&#xD;&#xA;Sets the Layout Rule property of rebar set to NumberWithSpacing.&#xD;&#xA;&#xD;&#xA;Authored by Dieter Vermeulen, Autodesk, 2016&#xD;&#xA;http://revitbeyondbim.wordpress.com&#xD;&#xA;*****************************************************" x="975.618719061839" y="488" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-8531.9097315966" eyeY="9834.49726109919" eyeZ="33724.8898667426" lookX="8942.97564956535" lookY="-7434.49726109919" lookZ="-15685.4670151801" upX="0.0860075068024533" upY="0.984807753012208" upZ="-0.15085224022424" />
  </Cameras>
</Workspace>