<Workspace Version="1.2.0.2831" X="-384" Y="-289" zoom="1" Name="Rebar.SetLayoutAsSingle" Description="Sets the Layout Rule property of rebar set to Single." ID="bcc12853-1633-40f9-b413-d96dabc506f7" Category="BIM4Struc.Rebar.Layout">
  <NamespaceResolutionMap>
    <ClassMap partialName="Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9d509d16-3b11-4205-be12-dfc7c0e40732" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="435.241630876365" y="506.739809166156" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="rebarElement:Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="25aa7baa-c71c-4dfb-a203-f5f34b730e55" type="PythonNodeModels.PythonNode" nickname="Python Script" x="678.388515149362" y="612.143369997017" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Sets the Layout Rule property of rebar set to Single..
#Authored by Dieter Vermeulen, Autodesk, 2016
#http://revitbeyondbim.wordpress.com

import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference("System")
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
rebarElement = UnwrapElement(IN[0])

#Change rebar in transaction
TransactionManager.Instance.EnsureInTransaction(doc)
rebarElement.SetLayoutAsSingle()
TransactionManager.Instance.TransactionTaskDone()

OUT = rebarElement</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="51829d8e-99c9-47c6-b2c0-e3d0a20f00cf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="840.505725831855" y="505.377791362002" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="rebarElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9d509d16-3b11-4205-be12-dfc7c0e40732" start_index="0" end="25aa7baa-c71c-4dfb-a203-f5f34b730e55" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9d509d16-3b11-4205-be12-dfc7c0e40732" start_index="0" end="51829d8e-99c9-47c6-b2c0-e3d0a20f00cf" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="7a3f6bd0-92fb-4c6b-8f71-249dfd7ca16e" text="*****************************************************&#xD;&#xA;Sets the Layout Rule property of rebar set to Single.&#xD;&#xA;&#xD;&#xA;Authored by Dieter Vermeulen, Autodesk, 2016&#xD;&#xA;http://revitbeyondbim.wordpress.com&#xD;&#xA;*****************************************************" x="436" y="388" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-8531.9097315966" eyeY="9834.49726109919" eyeZ="33724.8898667426" lookX="8942.97564956535" lookY="-7434.49726109919" lookZ="-15685.4670151801" upX="0.0860075068024533" upY="0.984807753012208" upZ="-0.15085224022424" />
  </Cameras>
</Workspace>