<Workspace Version="1.2.0.2831" X="-65.8168651792424" Y="101.71066454489" zoom="0.822695359375" Name="Rebar.SetLayoutAsMaximumSpacing" Description="Sets the Layout Rule property of rebar set to Maximum Spacing" ID="19beed20-7c4b-497e-a82a-77e4eb51299a" Category="BIM4Struc.Rebar.Layout">
  <NamespaceResolutionMap>
    <ClassMap partialName="Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="7eebd21b-6f38-4c50-8df4-f135bd4ec2b5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="497.646884272997" y="275.403560830861" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="7">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
      <PortInfo index="6" default="False" />
      <Script>#Sets the Layout Rule property of rebar set to MaximumSpacing.
#Authored by Dieter Vermeulen, Autodesk, 2016
#http://revitbeyondbim.wordpress.com

import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference("System")
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
rebarElement = UnwrapElement(IN[0])
spacing = IN[1]
arrayLength = IN[2]
barsOnNormalSide = IN[3]
inclFirstBar=IN[4]
inclLastBar=IN[5]

#convert from mm to feet:
if IN[6]:
	spacing = spacing/304.8
	arrayLength = arrayLength/304.8

#Change rebar in transaction
TransactionManager.Instance.EnsureInTransaction(doc)
rebarElement.SetLayoutAsMaximumSpacing(spacing,arrayLength,barsOnNormalSide,inclFirstBar,inclLastBar)
TransactionManager.Instance.TransactionTaskDone()

OUT = rebarElement</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d1798941-0b64-4e55-9090-95fe1eef1006" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="156.5" y="145" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="rebarElement:Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="34927cad-3cea-4a7b-ad9c-cde7f1243581" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-66.5" y="208.668644906034" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The maximum spacing between rebar in rebar set&#xD;&#xA;Spacing:double" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="437c7d9e-4539-471b-9fcb-83d3691ce4db" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="8.5" y="281.337289812067" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The distribution length of rebar set&#xD;&#xA;RebarSetLength:double" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a2fec378-d29c-4634-a8b7-f1dcc476ff19" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-198.5" y="354.005934718101" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Identifies if the bars of the rebar set are on the same side &#xD;&#xA;//of the rebar plane indicated by the normal&#xD;&#xA;barsOnNormalSide:bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="16c0fbca-1ff6-4f99-ae06-65d450fa6768" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="707.953731941978" y="134.638037710776" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="rebarElement:Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3ba8b4ed-65d6-4b69-b63e-89fc52c5c283" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-99.5" y="444.674579624135" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Identifies if the first bar in rebar set is shown&#xD;&#xA;IncludeFirstBar:bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e685e787-165f-4f96-b092-29a02a8e002e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-82.5" y="517.343224530168" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//dentifies if the last bar in rebar set is shown&#xD;&#xA;IncludeLastBar:bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="525c2703-349e-451b-9f8e-94fe16d69616" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-57.5" y="590.011869436202" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input the value in mm (true) or feet (false)&#xD;&#xA;InputInMM: bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d1798941-0b64-4e55-9090-95fe1eef1006" start_index="0" end="7eebd21b-6f38-4c50-8df4-f135bd4ec2b5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1798941-0b64-4e55-9090-95fe1eef1006" start_index="0" end="16c0fbca-1ff6-4f99-ae06-65d450fa6768" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="34927cad-3cea-4a7b-ad9c-cde7f1243581" start_index="0" end="7eebd21b-6f38-4c50-8df4-f135bd4ec2b5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="437c7d9e-4539-471b-9fcb-83d3691ce4db" start_index="0" end="7eebd21b-6f38-4c50-8df4-f135bd4ec2b5" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a2fec378-d29c-4634-a8b7-f1dcc476ff19" start_index="0" end="7eebd21b-6f38-4c50-8df4-f135bd4ec2b5" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ba8b4ed-65d6-4b69-b63e-89fc52c5c283" start_index="0" end="7eebd21b-6f38-4c50-8df4-f135bd4ec2b5" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e685e787-165f-4f96-b092-29a02a8e002e" start_index="0" end="7eebd21b-6f38-4c50-8df4-f135bd4ec2b5" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="525c2703-349e-451b-9f8e-94fe16d69616" start_index="0" end="7eebd21b-6f38-4c50-8df4-f135bd4ec2b5" end_index="6" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="86a4fcd0-55dc-4f41-90c6-01b44d0af8e8" text="*****************************************************&#xD;&#xA;Sets the Layout Rule property of rebar set to MaximumSpacing.&#xD;&#xA;&#xD;&#xA;Authored by Dieter Vermeulen, Autodesk, 2016&#xD;&#xA;http://revitbeyondbim.wordpress.com&#xD;&#xA;*****************************************************" x="67.2583691236346" y="14.2601908338442" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-11761.4267578125" eyeY="3825.96337890625" eyeZ="24192.2265625" lookX="7182.1201171875" lookY="-3182.46337890625" lookZ="-5087.22509765625" upX="0.106513299047947" upY="0.991444885730743" upZ="-0.0754453092813492" />
  </Cameras>
</Workspace>