<Workspace Version="1.2.1.3083" X="0" Y="0" zoom="1" Name="SeparateBeamsAndColumns" Description="Splits lists of curves/lines into separate beam and column lists for element create" ID="123a2e66-f2f7-4bc0-ac64-5e068c1fa508" Category="Revit.Elements.StructuralFraming">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="85af6340-c961-40fa-8fef-6427d40bbfe1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="428.5" y="261.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Curves[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="96ebd7eb-e827-454a-b998-62fd7a610056" type="PythonNodeModels.PythonNode" nickname="Separate Beams" x="673.5" y="253.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitNodes
clr.AddReference("RevitNodes")
import Revit
# Import Revit elements
from Revit.Elements import *
import System

# import Revit complete API package
clr.AddReference("RevitAPI")
import Autodesk

#Use generic features from .NET platform
from System.Collections.Generic import *

#The inputs to this node will be stored as a list in the IN variables.
l = IN[0]

lBeams = []

i = 0

while i &lt; l.Count:
	if l[i].StartPoint.Z == l[i].EndPoint.Z:
		lBeams.append(l[i])
	i = i + 1

#Assign your output to the OUT variable.
OUT = lBeams</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="05fd3e9f-83ba-4f44-b389-17c7958f8e84" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="975.5" y="257.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Beams" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="abd90459-1031-40b6-90ad-be69023d44dd" type="PythonNodeModels.PythonNode" nickname="Separate Columns" x="671.5" y="367.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitNodes
clr.AddReference("RevitNodes")
import Revit
# Import Revit elements
from Revit.Elements import *
import System

# import Revit complete API package
clr.AddReference("RevitAPI")
import Autodesk

#Use generic features from .NET platform
from System.Collections.Generic import *

#The inputs to this node will be stored as a list in the IN variables.
l = IN[0]

lColumns = []

i = 0

while i &lt; l.Count:
	if l[i].StartPoint.Z != l[i].EndPoint.Z:
		if l[i].StartPoint.Z &lt; l[i].EndPoint.Z:
			lColumns.append(l[i])
		else:
			lN = Line.ByStartPointEndPoint(l[i].EndPoint, l[i].StartPoint)
			lColumns.append(lN)
	i = i + 1

#Assign your output to the OUT variable.
OUT = lColumns</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e4451e15-a5a9-48bf-8835-a152242f70b0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="973.5" y="371.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Columns" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="85af6340-c961-40fa-8fef-6427d40bbfe1" start_index="0" end="96ebd7eb-e827-454a-b998-62fd7a610056" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="85af6340-c961-40fa-8fef-6427d40bbfe1" start_index="0" end="abd90459-1031-40b6-90ad-be69023d44dd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96ebd7eb-e827-454a-b998-62fd7a610056" start_index="0" end="05fd3e9f-83ba-4f44-b389-17c7958f8e84" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="abd90459-1031-40b6-90ad-be69023d44dd" start_index="0" end="e4451e15-a5a9-48bf-8835-a152242f70b0" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-205.713272094727" eyeY="93.2533111572266" eyeZ="137.235595703125" lookX="200.655303955078" lookY="-18.9585800170898" lookZ="16.4593849182129" upX="-0.121461406350136" upY="0.992546141147614" upZ="-0.00996324885636568" />
  </Cameras>
</Workspace>