<Workspace Version="1.1.0.2094" X="318.966822987692" Y="253.210598396451" zoom="2.23890854250913" Name="Apply ViewTemplate" Description="Apply ViewTemplate(s) to selected view(s)." ID="c5f4bb20-b7c0-425f-addc-650b30215661" Category="Modelical.Views">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="80e683fa-894c-4bc2-a343-52c51db2579a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-103.656966274434" y="11.1815249982686" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="379f3538-38ab-4f31-b2f0-ea7b8dfae0d5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-129.065934360967" y="92.7900026724159" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="TempNames" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="78c8c7c6-2730-453e-bc7b-0b1a081d96f6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="486.575619330888" y="11.1455972362925" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="510c1c62-8e0d-476d-baca-c59e8afe2df4" type="PythonNodeModels.PythonNode" nickname="List Assurance" x="13.3233091603697" y="91.6750623716824" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
input = IN[0]

if isinstance(input,list) == False:
	elements = [input]
else:
	elements = input

#Assign your output to the OUT variable.
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="569cf3a4-9f17-44f9-87d3-5cfac6a6e9c1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="182.626206279306" y="11.381034640545" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="973211ca-b44f-4e84-8aba-c1d44cde61cc" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="182.855974750763" y="90.5049713129172" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <PythonNodeModels.PythonNode guid="6a24f9e7-36cb-4f9e-af69-5d42b62befda" type="PythonNodeModels.PythonNode" nickname="List Assurance" x="7.98522975124675" y="11.7338578156183" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
input = IN[0]

if isinstance(input,list) == False:
	elements = [input]
else:
	elements = input

#Assign your output to the OUT variable.
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="b0477aeb-ed2a-421c-abd9-257ca813b75f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="333.334082807071" y="10.8586764567463" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variable.
views = UnwrapElement(IN[0])
viewTempName = IN[1]
templateList = []

collector = FilteredElementCollector(doc).OfClass(View)
for j in viewTempName:
	for i in collector:
		if i.IsTemplate == True and i.Name == j:
			templateList.append(i)

TransactionManager.Instance.EnsureInTransaction(doc)
h = 0

if len(templateList) == 1 and len(views) &gt; 1:
	for i in views:
		TempTemplate = templateList[0]
		i.ViewTemplateId = TempTemplate.Id

else:
	for i in views:
		TempTemplate = templateList[h]
		i.ViewTemplateId = TempTemplate.Id
		h=h+1

TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = views</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="80e683fa-894c-4bc2-a343-52c51db2579a" start_index="0" end="6a24f9e7-36cb-4f9e-af69-5d42b62befda" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="379f3538-38ab-4f31-b2f0-ea7b8dfae0d5" start_index="0" end="510c1c62-8e0d-476d-baca-c59e8afe2df4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="510c1c62-8e0d-476d-baca-c59e8afe2df4" start_index="0" end="973211ca-b44f-4e84-8aba-c1d44cde61cc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="569cf3a4-9f17-44f9-87d3-5cfac6a6e9c1" start_index="0" end="b0477aeb-ed2a-421c-abd9-257ca813b75f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="973211ca-b44f-4e84-8aba-c1d44cde61cc" start_index="0" end="b0477aeb-ed2a-421c-abd9-257ca813b75f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6a24f9e7-36cb-4f9e-af69-5d42b62befda" start_index="0" end="569cf3a4-9f17-44f9-87d3-5cfac6a6e9c1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b0477aeb-ed2a-421c-abd9-257ca813b75f" start_index="0" end="78c8c7c6-2730-453e-bc7b-0b1a081d96f6" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>