<Workspace Version="1.3.1.1736" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Point similarity" Description="Check if a point is similar to another, with a tolerance" ID="c680789c-b91c-45a2-b07f-2a91a2e21cdc" Category="Modelical.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="14a55674-1d2c-4d55-aaa7-fc183770a447" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1071.09616941807" y="451.910690750024" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script># This node has been made by Modelical
# www.modelical.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

from math import *

#Load Dynamo wrappers
clr.AddReference("RevitNodes")
import Revit
from Revit.Elements import *
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

def toList(input):
	if isinstance(input,list) == False:
		return [input]
	else:
		return input

def flatten(x):
    result = []
    for el in x:
        if hasattr(el, "__iter__") and not isinstance(el, basestring):
            result.extend(flatten(el))
        else:
            result.append(el)
    return result

def vecSimilarity(v1,v2,tolerance):
	if abs(v1.X - v2.X) &lt;= tolerance and abs(v1.Y - v2.Y) &lt;= tolerance and abs(v1.Z - v2.Z) &lt;= tolerance:
		return True
	else:
		return False


vec1 = flatten(toList(IN[0]))
vec2 = flatten(toList(IN[1]))
tolerance = IN[2]

result = vecSimilarity(vec1[0],vec2[0],tolerance)


OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="758f1693-d5a3-4b07-8af4-57a9329d852e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1235" y="454" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Similar?" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bbfb9931-480c-4e6a-be0e-d6ae67d1481a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="820" y="417" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="p1 : Autodesk.Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1c57400c-5c18-4e0c-8dc3-a219979355cc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="821" y="477" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="p2 : Autodesk.Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c254b541-929e-403c-b8da-944300d1ef6f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="742" y="537" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Tolerance : double = 0.000001" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="14a55674-1d2c-4d55-aaa7-fc183770a447" start_index="0" end="758f1693-d5a3-4b07-8af4-57a9329d852e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bbfb9931-480c-4e6a-be0e-d6ae67d1481a" start_index="0" end="14a55674-1d2c-4d55-aaa7-fc183770a447" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1c57400c-5c18-4e0c-8dc3-a219979355cc" start_index="0" end="14a55674-1d2c-4d55-aaa7-fc183770a447" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c254b541-929e-403c-b8da-944300d1ef6f" start_index="0" end="14a55674-1d2c-4d55-aaa7-fc183770a447" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>