<Workspace Version="0.9.0.3067" X="-22982.2955849987" Y="-135.068051180609" zoom="2.37004060791358" Name="Room Tag To Room Location" Description="Move RoomTags to the location point of the room" ID="bcb58150-5605-4673-86d6-5e8d58126f40" Category="Modelical.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="1a11d60e-f539-46c0-94b3-cbe8bb961d64" type="PythonNodeModels.PythonNode" nickname="Python Script" x="10021.7838554069" y="174.28001603058" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import clr
clr.AddReference('RevitAPI') 
clr.AddReference('RevitAPIUI') 
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
 
#The inputs to this node will be stored as a list in the IN variables.
rtags = UnwrapElement(IN[0])

t = Transaction(doc, 'Move Room Tags')
t.Start()
	
for rt in rtags:
	rt.Location.Move(rt.Room.Location.Point - rt.Location.Point)

t.Commit()

#Assign your output to the OUT variable.
OUT = rtags</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Symbol guid="1991ad6d-5d81-4efd-981a-bf544644431b" type="Dynamo.Nodes.Symbol" nickname="Input" x="9623.46672161069" y="174.201008545375" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="RoomTags" />
    </Dynamo.Nodes.Symbol>
    <PythonNodeModels.PythonNode guid="a7cf230d-3bba-4150-b3b8-5f249ffcf90a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="9744.97752586797" y="174.575641781682" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
input = IN[0]

if isinstance(input,list) == False:
	elements = [input]
else:
	elements = input

#Assign your output to the OUT variable.
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Output guid="916df863-7eb7-448c-bdd1-1a174e5258b3" type="Dynamo.Nodes.Output" nickname="Output" x="10210.4982945006" y="173.021529593792" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="RoomTags" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.DSFunction guid="19448beb-82b8-453f-9e37-052ae5bf42e0" type="Dynamo.Nodes.DSFunction" nickname="Flatten" x="9891.09448450997" y="174.287330690188" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="BuiltIn" function="Flatten@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="1a11d60e-f539-46c0-94b3-cbe8bb961d64" start_index="0" end="916df863-7eb7-448c-bdd1-1a174e5258b3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1991ad6d-5d81-4efd-981a-bf544644431b" start_index="0" end="a7cf230d-3bba-4150-b3b8-5f249ffcf90a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a7cf230d-3bba-4150-b3b8-5f249ffcf90a" start_index="0" end="19448beb-82b8-453f-9e37-052ae5bf42e0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="19448beb-82b8-453f-9e37-052ae5bf42e0" start_index="0" end="1a11d60e-f539-46c0-94b3-cbe8bb961d64" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>