<Workspace Version="1.3.1.1736" X="359.509468671454" Y="509.655489666875" zoom="0.186257280641317" ScaleFactor="1" Name="Space and Tag Location Centering" Description="Move space location point and its tag to its centroid. If centroid is located outside the space, location point stays at its origin coords." ID="cffde2c0-be93-4952-b827-eb9dd60a2f0b" Category="Modelical.MEP">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4e9a0900-d4a3-4b6f-9be9-8b8b5d6c71ef" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="4256.90283694944" y="640.983937007485" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="eb509274-0111-485d-811a-1bb6be6c9915" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="4549.46892824984" y="558.466768767735" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="405d2924-5582-4832-a883-2666cb684dfa" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="3355.73333695328" y="642.340653880065" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="centroid = Autodesk.Point.ByCoordinates(p1.X, p1.Y, p2.Z);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="6ccb6f5b-6bc3-42c9-a46c-c9726de1794f" type="PythonNodeModels.PythonNode" nickname="Python Script (Centroid inside space?)" x="3882.60750504782" y="447.409658114205" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

spaces = UnwrapElement(IN[0])
points = [x.ToXyz() for x in IN[1]]

spaceBools = []
count = 0

for s in spaces:
	try:
		if s.IsPointInSpace(points[count]):
			spaceBools.append(True)
		else:
			spaceBools.append(False)
	except:
		spaceBools.append(False)
	count = count + 1

OUT = spaceBools</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="19265ea2-bd96-4f2b-8331-1fea519b419e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="4248.30487715724" y="351" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b50c11ad-870d-4b9d-b18f-fa08d5c06b00" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="4537.66160628594" y="353.164943080645" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="239fe874-7ef4-4742-a760-bab3b4b9c4a0" type="PythonNodeModels.PythonNode" nickname="Python Script (Move Location Point)" x="5046.98641253902" y="359.09433931501" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import clr
clr.AddReference('RevitAPI') 
clr.AddReference('RevitAPIUI') 
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
 
#The inputs to this node will be stored as a list in the IN variables.
spaces = UnwrapElement(IN[0])
points = [x.ToXyz() for x in IN[1]]
stags = []
spacesMoved = []
locations = []
tagsMoved = []
count = 0


t1 = Transaction(doc, 'Move Space Location')
t1.Start()
	
for s in spaces:
	P = points[count] - s.Location.Point
	s.Location.Move(P)
	spacesMoved.append(s)
	count = count + 1

t1.Commit()

collector = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_MEPSpaceTags).WhereElementIsNotElementType()
for i in collector:
	stags.append(i)

t2 = Transaction(doc, 'Move Space Tags')
t2.Start()

for rt in stags:
	for s in spacesMoved:
		if rt.Space.Id == s.Id:
			rt.Location.Move(rt.Space.Location.Point - rt.Location.Point)
			tagsMoved.append(rt)
			break
t2.Commit()

#Assign your output to the OUT variable.
OUT = spacesMoved, tagsMoved</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="9386589b-2c65-4d88-a142-935ecb2f8a51" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5323.99729015084" y="359.676669847495" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="l[0];&#xA;l[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="94f7a062-7ecc-4b9e-b509-4037f485f4ee" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.End" x="4770.31972766751" y="356.722994895574" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.End@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5cd0776b-babb-4c4a-95f5-6dcc2cacbe7e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Transaction.End" x="4768.63861665908" y="560.129105583445" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Transaction.Transaction.End@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3f438d7b-941c-4454-b562-a2ca6ab2bba1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Centroid" x="3083.28610212454" y="638.312993697715" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Centroid">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f8109895-28b7-42dd-9b96-dab0a2d7f709" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.StartPoint" x="3012.60478906754" y="812.108433924565" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.StartPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e695aa2f-aa44-4b7c-992c-033ccbb946d1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.ExtrudeAsSolid" x="2853.5778922066" y="638.977583968395" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.HigherOrder.Map guid="1cb29fbc-d536-428f-9157-d88266ad94ce" type="CoreNodeModels.HigherOrder.Map" nickname="List.Map" x="2675.04501449324" y="635.619086030745" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </CoreNodeModels.HigherOrder.Map>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f741ed9a-579f-4a48-b0bf-f48d1270f6fb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.LastItem" x="2412.41718101124" y="739.258259186735" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.LastItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="aabbe920-cbaf-4bf4-8715-2b37792f2648" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Flatten" x="2384.62259337884" y="634.431151772465" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Flatten@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f11c893a-ca1e-4f96-9c42-1bc76c66ae25" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="2379.74007218724" y="444.005551038625" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="da459e4a-a8c9-4ec4-b1c2-19bc43fff5b1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2279.15103217594" y="685.036771930225" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="1;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="451c3075-609b-4a03-87ff-ad034b519979" type="PythonNodeModels.PythonNode" nickname="Python Script (sort by key)" x="2121.10887541994" y="444.422949939805" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

keys = IN[0]
ls = IN[1]

for slot in range(len(keys)-1, 0, -1):
	positionOfMax = 0
	
	for location in range(1, slot+1):
		if keys[location] &gt; keys[positionOfMax]:
			positionOfMax = location

	temp = keys[slot]
	keys[slot] = keys[positionOfMax]
	keys[positionOfMax] = temp
	
	temp2 = ls[slot]
	ls[slot] = ls[positionOfMax]
	ls[positionOfMax] = temp2

OUT = []
OUT.append(ls)</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="575a6f2d-aa97-46a7-ad97-ee85b3794b81" type="PythonNodeModels.PythonNode" nickname="Python Script (sort by key)" x="2052.57694639104" y="633.798386397105" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

keys = IN[0]
ls = IN[1]

for slot in range(len(keys)-1, 0, -1):
	positionOfMax = 0
	
	for location in range(1, slot+1):
		if keys[location] &gt; keys[positionOfMax]:
			positionOfMax = location

	temp = keys[slot]
	keys[slot] = keys[positionOfMax]
	keys[positionOfMax] = temp
	
	temp2 = ls[slot]
	ls[slot] = ls[positionOfMax]
	ls[positionOfMax] = temp2

OUT = []
OUT.append(ls)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2a37a812-4aa8-4606-8e2f-ad63a6760b6d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Length" x="1885.55178229844" y="593.275671044125" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Length">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6c52abf2-258c-4386-bafd-6d261419f9a5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.ByJoinedCurves" x="1649.74120157214" y="658.389941342595" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByJoinedCurves@Autodesk.DesignScript.Geometry.Curve[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="11ad7d55-6c32-42ce-a74a-6609a6b46309" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1171.37967157694" y="473.685974870595" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="9c29566a-763d-4336-aeb5-75261ff6051d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1441.48557370934" y="662.027484209435" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Made by Modelical http://www.modelical.com
#With the help of a node by Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
rooms = UnwrapElement(IN[0])

boundarylist = []
boundarylistFlattened = []
curvelist = []
curves = []
outputCurves = []

options = Autodesk.Revit.DB.SpatialElementBoundaryOptions()

for r in rooms:
	boundarylist.append(r.GetBoundarySegments(options))

for b in boundarylist:
	boundarylistFlattened.append([item for sublist in b for item in sublist])


for segment in boundarylistFlattened:
	curves = []
	for s in segment:
		curves.append(s.GetCurve().ToProtoType())
	curvelist.append(curves)


def groupCurves(Line_List): 
	ignore_distance = 0.01 # Assume points this close or closer to each other are touching 
	Grouped_Lines = [] 
	Queue = set() 
	while Line_List: 
		Shape = [] 
		Queue.add(Line_List.pop()) # Move a line from the Line_List to our queue 
		while Queue: 
			Current_Line = Queue.pop() 
			Shape.append(Current_Line) 
			for Potential_Match in Line_List: 
				Points = (Potential_Match.StartPoint, Potential_Match.EndPoint)
				for P1 in Points: 
					for P2 in (Current_Line.StartPoint, Current_Line.EndPoint): 
						distance = P1.DistanceTo(P2) 
						if distance &lt;= ignore_distance: 
							Queue.add(Potential_Match) 
			Line_List = [item for item in Line_List if item not in Queue]
		Grouped_Lines.append(Shape) 
	return Grouped_Lines
	
for c in curvelist:
	outputCurves.append(groupCurves(c))

OUT = outputCurves</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="06bbd429-d9a7-458d-a86a-9502223dde32" type="PythonNodeModels.PythonNode" nickname="Python Script (List Assurance)" x="938.839179500943" y="472.812442129145" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
input = IN[0]

if isinstance(input,list) == False:
	elements = [input]
else:
	elements = input

#Assign your output to the OUT variable.
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a318bbd7-3fc7-4684-9d56-ccb82212447d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="790" y="473" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Spaces" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e95401f0-4f96-41a5-b526-265358d11129" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="5491.93332662146" y="329.66066049324" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="SpacesMoved" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="dfeb4866-3270-41f5-bb85-69bc146b0fe2" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="5495.61757354274" y="394.134981615635" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="TagsMoved" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4e9a0900-d4a3-4b6f-9be9-8b8b5d6c71ef" start_index="0" end="eb509274-0111-485d-811a-1bb6be6c9915" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eb509274-0111-485d-811a-1bb6be6c9915" start_index="0" end="5cd0776b-babb-4c4a-95f5-6dcc2cacbe7e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="405d2924-5582-4832-a883-2666cb684dfa" start_index="0" end="4e9a0900-d4a3-4b6f-9be9-8b8b5d6c71ef" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="405d2924-5582-4832-a883-2666cb684dfa" start_index="0" end="6ccb6f5b-6bc3-42c9-a46c-c9726de1794f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6ccb6f5b-6bc3-42c9-a46c-c9726de1794f" start_index="0" end="4e9a0900-d4a3-4b6f-9be9-8b8b5d6c71ef" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6ccb6f5b-6bc3-42c9-a46c-c9726de1794f" start_index="0" end="19265ea2-bd96-4f2b-8331-1fea519b419e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="19265ea2-bd96-4f2b-8331-1fea519b419e" start_index="0" end="b50c11ad-870d-4b9d-b18f-fa08d5c06b00" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b50c11ad-870d-4b9d-b18f-fa08d5c06b00" start_index="0" end="94f7a062-7ecc-4b9e-b509-4037f485f4ee" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="239fe874-7ef4-4742-a760-bab3b4b9c4a0" start_index="0" end="9386589b-2c65-4d88-a142-935ecb2f8a51" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9386589b-2c65-4d88-a142-935ecb2f8a51" start_index="0" end="e95401f0-4f96-41a5-b526-265358d11129" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9386589b-2c65-4d88-a142-935ecb2f8a51" start_index="1" end="dfeb4866-3270-41f5-bb85-69bc146b0fe2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="94f7a062-7ecc-4b9e-b509-4037f485f4ee" start_index="0" end="239fe874-7ef4-4742-a760-bab3b4b9c4a0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5cd0776b-babb-4c4a-95f5-6dcc2cacbe7e" start_index="0" end="239fe874-7ef4-4742-a760-bab3b4b9c4a0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3f438d7b-941c-4454-b562-a2ca6ab2bba1" start_index="0" end="405d2924-5582-4832-a883-2666cb684dfa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f8109895-28b7-42dd-9b96-dab0a2d7f709" start_index="0" end="405d2924-5582-4832-a883-2666cb684dfa" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e695aa2f-aa44-4b7c-992c-033ccbb946d1" start_index="0" end="3f438d7b-941c-4454-b562-a2ca6ab2bba1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1cb29fbc-d536-428f-9157-d88266ad94ce" start_index="0" end="f8109895-28b7-42dd-9b96-dab0a2d7f709" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1cb29fbc-d536-428f-9157-d88266ad94ce" start_index="0" end="e695aa2f-aa44-4b7c-992c-033ccbb946d1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f741ed9a-579f-4a48-b0bf-f48d1270f6fb" start_index="0" end="1cb29fbc-d536-428f-9157-d88266ad94ce" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aabbe920-cbaf-4bf4-8715-2b37792f2648" start_index="0" end="1cb29fbc-d536-428f-9157-d88266ad94ce" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f11c893a-ca1e-4f96-9c42-1bc76c66ae25" start_index="0" end="6ccb6f5b-6bc3-42c9-a46c-c9726de1794f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f11c893a-ca1e-4f96-9c42-1bc76c66ae25" start_index="0" end="19265ea2-bd96-4f2b-8331-1fea519b419e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="da459e4a-a8c9-4ec4-b1c2-19bc43fff5b1" start_index="0" end="aabbe920-cbaf-4bf4-8715-2b37792f2648" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="451c3075-609b-4a03-87ff-ad034b519979" start_index="0" end="f11c893a-ca1e-4f96-9c42-1bc76c66ae25" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="575a6f2d-aa97-46a7-ad97-ee85b3794b81" start_index="0" end="aabbe920-cbaf-4bf4-8715-2b37792f2648" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a37a812-4aa8-4606-8e2f-ad63a6760b6d" start_index="0" end="451c3075-609b-4a03-87ff-ad034b519979" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a37a812-4aa8-4606-8e2f-ad63a6760b6d" start_index="0" end="575a6f2d-aa97-46a7-ad97-ee85b3794b81" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c52abf2-258c-4386-bafd-6d261419f9a5" start_index="0" end="575a6f2d-aa97-46a7-ad97-ee85b3794b81" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c52abf2-258c-4386-bafd-6d261419f9a5" start_index="0" end="2a37a812-4aa8-4606-8e2f-ad63a6760b6d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="11ad7d55-6c32-42ce-a74a-6609a6b46309" start_index="0" end="451c3075-609b-4a03-87ff-ad034b519979" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="11ad7d55-6c32-42ce-a74a-6609a6b46309" start_index="0" end="9c29566a-763d-4336-aeb5-75261ff6051d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9c29566a-763d-4336-aeb5-75261ff6051d" start_index="0" end="6c52abf2-258c-4386-bafd-6d261419f9a5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="06bbd429-d9a7-458d-a86a-9502223dde32" start_index="0" end="11ad7d55-6c32-42ce-a74a-6609a6b46309" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a318bbd7-3fc7-4684-9d56-ccb82212447d" start_index="0" end="06bbd429-d9a7-458d-a86a-9502223dde32" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>