<Workspace Version="1.3.1.1736" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Space Tag To Space Location" Description="Move Space Tags to the location point of the space" ID="75803eeb-6937-4213-a770-c0eb392982a5" Category="Modelical.MEP">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c069c6df-9560-4c1d-8406-95b670865325" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1169.29471986161" y="619.248083025083" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import clr
clr.AddReference('RevitAPI') 
clr.AddReference('RevitAPIUI') 
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
 
#The inputs to this node will be stored as a list in the IN variables.
stags = UnwrapElement(IN[0])

t = Transaction(doc, 'Move Space Tags')
t.Start()
	
for st in stags:
	st.Location.Move(st.Space.Location.Point - st.Location.Point)

t.Commit()

#Assign your output to the OUT variable.
OUT = stags</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3bb6c007-b557-47fe-80e0-236fda90b531" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1347.15233713421" y="617" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="SpaceTags" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6b576d95-b56d-480f-8460-25223a5445ad" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="964.627762899279" y="619.255397684691" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="b5822847-7efc-4854-abc3-0f4961c03612" type="PythonNodeModels.PythonNode" nickname="Python Script" x="818.510804257279" y="619.543708776185" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
input = IN[0]

if isinstance(input,list) == False:
	elements = [input]
else:
	elements = input

#Assign your output to the OUT variable.
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="daed2ed2-952b-4e17-8abe-597829d766ee" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="697" y="619.169075539878" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SpaceTags" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c069c6df-9560-4c1d-8406-95b670865325" start_index="0" end="3bb6c007-b557-47fe-80e0-236fda90b531" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6b576d95-b56d-480f-8460-25223a5445ad" start_index="0" end="c069c6df-9560-4c1d-8406-95b670865325" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b5822847-7efc-4854-abc3-0f4961c03612" start_index="0" end="6b576d95-b56d-480f-8460-25223a5445ad" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="daed2ed2-952b-4e17-8abe-597829d766ee" start_index="0" end="b5822847-7efc-4854-abc3-0f4961c03612" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>