<?xml version="1.0"?>
<doc>
    <assembly>
        <name>Rhynamo</name>
    </assembly>
    <members>
        <member name="M:Rhynamo.classes.clsRhinoFace.#ctor(Rhino.Geometry.NurbsSurface,Rhynamo.classes.clsRhinoLoop,System.Boolean)">
            <summary>
            Constructor
            </summary>
            <param name="surface">The untrimmed NurbsSurface</param>
            <param name="loop">The Rhino loop</param>
            <param name="IsSurface">Is the face and untrimmed surface?</param>
        </member>
        <member name="P:Rhynamo.classes.clsRhinoFace.SurfaceFace">
            <summary>
            the face surface
            </summary>
        </member>
        <member name="P:Rhynamo.classes.clsRhinoFace.EdgeLoop">
            <summary>
            Loop curves
            </summary>
        </member>
        <member name="P:Rhynamo.classes.clsRhinoFace.IsUntrimmedSurface">
            <summary>
            Is the face untrimmed?
            </summary>
        </member>
        <member name="F:Rhynamo.clsRhinoBrepUtils.Curve2DLoops">
            <summary>
            Sorted 2D Curve Loops (first curve is the "outer" curve)
            </summary>
        </member>
        <member name="F:Rhynamo.clsRhinoBrepUtils.Curve3DLoops">
            <summary>
            Sorted 3D Curve Loops (first curve is the "outer" curve)
            </summary>
        </member>
        <member name="M:Rhynamo.clsRhinoBrepUtils.#ctor(System.Collections.Generic.List{Rhino.Geometry.PolyCurve},System.Collections.Generic.List{Rhino.Geometry.PolyCurve},Rhino.Geometry.NurbsSurface)">
            <summary>
            A class for sorting brep edges
            </summary>
            <param name="rh_2d">2D loops</param>
            <param name="rh_3d">3D loops</param>
            <param name="rh_srf">Rhino surface</param>
        </member>
        <member name="M:Rhynamo.clsRhinoBrepUtils.InnerOuterSort(System.Collections.Generic.List{Rhino.Geometry.PolyCurve},System.Collections.Generic.List{Rhino.Geometry.PolyCurve})">
            <summary>
            Sorts based on inner or outer condition.  the first curve is the outer curve.
            </summary>
            <param name="rh_2dpc"></param>
            <param name="rh_3dpc"></param>
        </member>
        <member name="M:Rhynamo.clsRhinoBrepUtils.LoopDirCheck(Rhino.Geometry.NurbsSurface)">
            <summary>
            Loop direction check
            </summary>
            <param name="rh_srf"></param>
        </member>
        <member name="M:Rhynamo.clsRhinoBrepUtils.FlipCurve(Rhino.Geometry.PolyCurve)">
            <summary>
            Flip the direction of the polycurve
            </summary>
            <param name="rh_pc"></param>
            <returns></returns>
        </member>
        <member name="P:Rhynamo.clsRhinoBrepUtils.Curve2DSegments">
            <summary>
            All 2D Segments
            </summary>
        </member>
        <member name="P:Rhynamo.clsRhinoBrepUtils.Curve3DSegments">
            <summary>
            All 3D segments
            </summary>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_PointsToDS(System.Collections.Generic.List{Rhino.Geometry.Point})">
            <summary>
            Converts Rhino points to DesignScript points
            </summary>
            <param name="rh_points">list of Rhino points</param>
            <returns>List of DesignScript points</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_LinesToDS(System.Collections.Generic.List{Rhino.Geometry.LineCurve})">
            <summary>
            Converts Rhino lines to DesignScript lines.
            </summary>
            <param name="rh_lines">List of Rhino lines</param>
            <returns>List of DesignScript lines</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_ArcsToDS(System.Collections.Generic.List{Rhino.Geometry.ArcCurve})">
            <summary>
            Converts Rhino arcs to DesignScript arcs
            </summary>
            <param name="rh_arcs">List of Rhino arcs</param>
            <returns>List of DesignScript arcs</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_CirclesToDS(System.Collections.Generic.List{Rhino.Geometry.Curve})">
            <summary>
            Converts Rhino circles to DesignScript circles
            </summary>
            <param name="rh_crvs">Circle curve</param>
            <returns>DesignScript circle.</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_EllipsesToDS(System.Collections.Generic.List{Rhino.Geometry.Curve})">
            <summary>
            Converts Rhino circles to DesignScript circles
            </summary>
            <param name="rh_crvs">Circle curve</param>
            <returns>DesignScript circle.</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_NurbsCurveToDS(System.Collections.Generic.List{Rhino.Geometry.NurbsCurve})">
            <summary>
            Converts Rhino Nurbs curves to DesignScript Nurbs curves
            </summary>
            <param name="rh_nurbscrv">List of Rhino Nurbs curves</param>
            <returns>List of DesignScript Nurbs curves</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_MultiSpanNurbsCurveToDS(System.Collections.Generic.List{Rhino.Geometry.NurbsCurve})">
            <summary>
            Converts Rhino Nurbs curves to DesignScript Nurbs curves
            </summary>
            <param name="rh_nurbscrv">List of Rhino Nurbs curves</param>
            <returns>List of DesignScript Nurbs curves</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_PolylineToDS(System.Collections.Generic.List{Rhino.Geometry.PolylineCurve})">
            <summary>
            Converts Rhino Polyline to DesignScript Polyline
            </summary>
            <param name="rh_polyline">Rhino Polyline</param>
            <returns>DesignScript Polyline</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_PolyCurveToDS(System.Collections.Generic.List{Rhino.Geometry.PolyCurve})">
            <summary>
            Converts Rhino PolyCurve to DesignScript PolyCurve
            </summary>
            <param name="rh_polycurve">Rhino PolyCurve</param>
            <returns>DesignScript PolyCurve</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_CurvesToDS(System.Collections.Generic.List{Rhino.Geometry.Curve})">
            <summary>
            Converts all Rhino curve types to DesignScript Curve
            </summary>
            <param name="rh_curves">Rhino Curves</param>
            <returns>DesignScript Curves</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_NurbsSurfaceToDS(System.Collections.Generic.List{Rhino.Geometry.NurbsSurface})">
            <summary>
            Converts Rhino Nurbs Surfaces to DesignScript Nurbs Surfaces.
            </summary>
            <param name="rh_nurbssurface">Rhino Nurbs Surfaces</param>
            <returns>DesignScript Nurbs Surfaces</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_BrepsToDS(System.Collections.Generic.List{Rhino.Geometry.Brep})">
            <summary>
            Converts Rhino breps to DesignScript polysurfaces
            </summary>
            <param name="rh_breps">Rhino breps</param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_ExtrusionToDS(System.Collections.Generic.List{Rhino.Geometry.Extrusion})">
            <summary>
            Converts Rhino Extrusions to DesignScript polysurfaces
            </summary>
            <param name="rh_extrusions">Rhino extrusions</param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_MeshToDS(System.Collections.Generic.List{Rhino.Geometry.Mesh})">
            <summary>
            Convert a Rhino mesh to a DesignScript mesh
            </summary>
            <param name="rh_meshes">Rhino meshes</param>
            <returns>DesignScript meshes</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_PointsTo3dm(Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Converts DesignScript points to Rhino points
            </summary>
            <param name="pt">DesignScript points</param>
            <returns>Rhino points</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_CurvesTo3dm(Autodesk.DesignScript.Geometry.Curve)">
            <summary>
            Converts DesignScript curves to Rhino curves
            </summary>
            <param name="crv">DesignScript curves</param>
            <returns>Rhino curves</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_SurfacesTo3dm(Autodesk.DesignScript.Geometry.NurbsSurface)">
            <summary>
            Converts DesignScript surfaces to Rhino surfaces
            </summary>
            <param name="srf">DesignScript surface</param>
            <returns>Rhino surface</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_PolySurfaceTo3dm(Autodesk.DesignScript.Geometry.PolySurface)">
            <summary>
            Converts DesignScript PolySurfaces to Rhino breps
            </summary>
            <param name="ds_polysurface"></param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_MeshTo3dm(Autodesk.DesignScript.Geometry.Mesh)">
            <summary>
            Converts DesignScript meshes to Rhino meshes
            </summary>
            <param name="ds_mesh">DesignScript mesh</param>
            <returns>Rhino mesh</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_LineTo3dm(Autodesk.DesignScript.Geometry.Line)">
            <summary>
            Converts DesignScript Line curves to Rhino Line curves
            </summary>
            <param name="ds_ln">DesignScript Line</param>
            <returns>Rhino Line Curve</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_ArcTo3dm(Autodesk.DesignScript.Geometry.Arc)">
            <summary>
            Converts DesignScript Arc curves to Rhino Arc curves
            </summary>
            <param name="ds_arc">DesignScript Arc</param>
            <returns>Rhino Arc curve</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_NurbsCurveTo3dm(Autodesk.DesignScript.Geometry.NurbsCurve)">
            <summary>
            Converts DesignScript Nurbs curves to Rhino Nurbs curves
            </summary>
            <param name="ds_nurbs">DesignScript NurbsCurve</param>
            <returns>Rhino Nurbs curve</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_RectangleTo3dm(Autodesk.DesignScript.Geometry.Rectangle)">
            <summary>
            Convert DesignScript Rectangles to Rhino Rectangle3D
            </summary>
            <param name="ds_rect"></param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Convert_PolyCurveTo3dm(Autodesk.DesignScript.Geometry.PolyCurve)">
            <summary>
            Converts DesignScript polycurves to Rhino polycurves
            </summary>
            <param name="ds_polycrv"></param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.Make2DParameterCurves(Autodesk.DesignScript.Geometry.NurbsSurface,Autodesk.DesignScript.Geometry.Curve[])">
            <summary>
            Takes 3D edge curves and defines 2D parameter space curves relative to a surface
            </summary>
            <param name="srf">base surface</param>
            <param name="ds_3dcurves">3D curves</param>
            <returns>2d parameter curves</returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.JoinLoopCurves(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Curve})">
            <summary>
            Iteratively Create PolyCurve "ByJoinedCurves" (reduce occurence of branching segments)
            </summary>
            <param name="m_crvs"></param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.RemoveSmallSegments(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Curve},System.Double)">
            <summary>
            Remove very small segments from a curve list
            </summary>
            <param name="m_crvs"></param>
            <param name="tol"></param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.RemoveDuplicateCurves(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Curve})">
            <summary>
            Return unique list of curves without duplicates
            </summary>
            <param name="m_crvs"></param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.JoinPerimeterCurves(System.Collections.Generic.List{Rhino.Geometry.Curve})">
            <summary>
            Join Perimeter curves into close loops
            </summary>
            <param name="rh_curves"></param>
            <returns></returns>
        </member>
        <member name="M:Rhynamo.classes.clsGeometryConversionUtils.JoinCurves(System.Collections.Generic.List{Rhino.Geometry.Curve})">
            <summary>
            Join Perimeter curves into close loops
            </summary>
            <param name="rh_curves"></param>
            <returns></returns>
        </member>
        <member name="T:Interoperability.LiveRhino">
            <summary>
            Send Rhino Commands
            </summary>
        </member>
        <member name="M:Interoperability.LiveRhino.RhinoApp(System.Boolean)">
            <summary>
            Starts an instance of the Rhino Application
            </summary>
            <param name="StartRhino">Start Rhino</param>
            <returns name = "RhinoApplication">The Rhino Application object</returns>
            <search>case,rhino,3dm,rhynamo,live</search>
        </member>
        <member name="M:Interoperability.LiveRhino.RhinoCommand(ProvingGround.RhinoConnect.RhinoApplication,System.String,System.Boolean)">
            <summary>
            Sends a Command to Rhino
            </summary>
            <param name="RhinoApp">Rhino Application</param>
            <param name="Command">Command</param>
            <param name="SendCommand">Boolean Toggle</param>
            <search>case,rhino,3dm,rhynamo,live,command</search>
        </member>
        <member name="T:Interoperability.ReadRhino.OpenRhino3dmModel">
            <summary>
            Get the Rhino File3dm Object
            </summary>
        </member>
        <member name="M:Interoperability.ReadRhino.OpenRhino3dmModel.Get_RhinoFile(System.Object)">
            <summary>
            Gets a Rhino file object using a path string.
            </summary>
            <param name="RhinoFile">The file or path of the Rhino file (*.3dm)</param>
            <returns name="RhinoModel">The File3dm object (Rhino file)</returns>
            <returns name="Name">Name of the Rhino File</returns>
            <returns name="Bytes">Size of the Rhino file in Bytes</returns>
            <returns name="Created">Time created</returns>
            <returns name="CreatedBy">Creator of the Rhino file</returns>
            <returns name="LastEdited">Time the file was last edited</returns>
            <returns name="LastEditedBy">Name of the last person who edited the file.</returns>
            <returns name="Revision">Time of the last revision</returns>
            <returns name="Units">Units of the Rhino file</returns>
            <returns name="Notes">Notes in the Rhino file</returns>
            <search>case,rhino,model,3dm,rhynamo</search>
        </member>
        <member name="T:Interoperability.ReadRhino.RhinoObject">
            <summary>
            Get Rhino Object Types
            </summary>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObject.Get_DocumentObjects(Rhino.FileIO.File3dm)">
             <summary>
             Gets Rhino document objects (file3dmobjects, dimension styles, hatch patterns, layers, linetypes, materials, views)
             </summary>
             <param name="RhinoModel">The Rhino model object</param>
             <returns name="RhinoObjects">Geometry Objects in the Rhino file.</returns>
            <returns name="HatchPatterns">Hatch patterns.</returns>
            <returns name="Layers">Layers</returns>
            <returns name="Linetypes">Linetypes</returns>
            <returns name="Materials">materials</returns>
            <returns name="Views">Views</returns>
            <search>case,rhino,model,3dm,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObject.Get_RhinoObjects(Rhino.FileIO.File3dm)">
            <summary>
            Gets Rhino all Rhino 3dm Objects
            </summary>
            <param name="RhinoModel">The Rhino model object (File3dm)</param>
            <returns name="RhinoObjects">The list of Rhino objects.</returns>
            <search>case,rhino,model,3dm,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObject.Get_RhinoObjectsByLayer(Rhino.FileIO.File3dm,System.String)">
            <summary>
            Gets Rhino File3dmObjects from a model using a layer name.
            </summary>
            <param name="RhinoModel">The Rhino model object (File3dm)</param>
            <param name="layer">The name of the layer</param>
            <returns name="RhinoObjects">The list of Rhino objects.</returns>
            <search>case,rhino,model,3dm,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObject.Get_RhinoLayerNames(Rhino.FileIO.File3dm)">
            <summary>
            Gets Rhino layer names.
            </summary>
            <param name="RhinoModel">The Rhino model object</param>
            <returns name="LayerNames">List of Rhino layer names.</returns>
            <search>case,rhino,model,layers,3dm,rhynamo</search>
        </member>
        <member name="T:Interoperability.ReadRhino.RhinoObjectAttributes">
            <summary>
            Get Rhino Object Attribute info
            </summary>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_HatchPatternAttributes(Rhino.DocObjects.HatchPattern)">
            <summary>
            Rhino Hatch Pattern Attributes
            </summary>
            <param name="RhinoHatchPattern">Rhino Hatch Pattern</param>
            <returns name="Name">Name of the Hatch Pattern.</returns>
            <returns name="Index">Index of the Hatch Pattern</returns>
            <returns name="Description">Description.</returns>
            <returns name="FillType">Fill type.</returns>
            <search>case,rhino,model,3dm,rhynamo,hatch</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_LayerAttributes(Rhino.DocObjects.Layer)">
            <summary>
            Rhino Layer Attributes
            </summary>
            <param name="RhinoLayer">Rhino Layer</param>
            <returns name="Name">Layer Name</returns>
            <returns name="Index">Layer Index</returns>
            <returns name="LinetypeIndex">Linetype Index</returns>
            <returns name="MaterialIndex">Material Index</returns>
            <returns name="Color">Layer Color</returns>
            <returns name="PlotColor">Plot Color</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,rhynamo,layer</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_LinetypeAttributes(Rhino.DocObjects.Linetype)">
            <summary>
            Rhino Linetype Attributes
            </summary>
            <param name="RhinoLinetype">Rhino Linetype</param>
            <returns name="Name">Linetype Name</returns>
            <returns name="Index">Linetype Index</returns>
            <returns name="SegmentCount">Segment count</returns>
            <returns name="PatternLength">Pattern length</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,rhynamo,linetype</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_MaterialAttributes(Rhino.DocObjects.Material)">
            <summary>
            Rhino Material Attributes
            </summary>
            <param name="RhinoMaterial">Rhino Material</param>
            <returns name="Name">Material Name</returns>
            <returns name="Index">Material Index</returns>
            <returns name="IndexOfRefraction">Index of Refraction</returns>
            <returns name="Reflectivity">Reflectivity</returns>
            <returns name="Transparency">Transparency</returns>
            <returns name="AmbientColor">Ambient Color (as System.Color)</returns>
            <returns name="DiffuseColor">Diffuse Color (as System.Color)</returns>
            <returns name="ReflectionColor">Reflection Color (as System.Color)</returns>
            <returns name="RefractionColor">Refraction Color (as System.Color)</returns>
            <returns name="TransparentColor">Transparent Color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,rhynamo,material</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_ViewAttributes(Rhino.DocObjects.ViewInfo)">
            <summary>
            Rhino View Attributes
            </summary>
            <param name="RhinoView">Rhino Linetype</param>
            <returns name="Name">Material Name</returns>
            <returns name="Index">Material Index</returns>
            <returns name="Location">Location (as Point)</returns>
            <returns name="Target">Target (as Point)</returns>
            <returns name="LensLength">Lens Length</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,rhynamo,view</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_RhinoGeometryAttributes(Rhino.FileIO.File3dmObject)">
            <summary>
            Gets Rhino object names
            </summary>
            <param name="RhinoObject">List of Rhino objects.</param>
            <returns name="Name">Geometry Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="LinetypeIndex">Linetype Index</returns>
            <returns name="MaterialIndex">Material Index</returns>
            <returns name="Color">Object color</returns>
            <returns name="PlotColor">Plot color</returns>
            <returns name="ObjectType">Type of Rhino Object</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,names,3dm,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_UserDictionary(Rhino.FileIO.File3dmObject)">
            <summary>
            Get Custom User Dictionary Data from Rhino 3DM objects
            </summary>
            <param name="RhinoObject">Rhino File3dmObject</param>
            <returns name="Attribute_UserDictionary">Attribute User Dictionary object</returns>
            <returns name="Attribute_Keys">Attribute Dictionary Keys</returns>
            <returns name="Attribute_Values">Attribute Dictionary values</returns>
            <returns name="Geometry_UserDictionary">Geometry User Dictionary object</returns>
            <returns name="Geometry_Keys">Geometry Dictionary Keys</returns>
            <returns name="Geometry_Values">Geometry Dictionary values</returns>
            <search>case,rhino,model,user,dictionary,3dm,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_UserDictionaryValue(Rhino.Collections.ArchivableDictionary,System.String)">
            <summary>
            Returns a value from a Rhino UserDictionary based on a Key
            </summary>
            <param name="RhinoDictionary">Rhino UserDictionary</param>
            <param name="key">Key value</param>
            <returns name="Value">Material Name</returns>
            <search>case,rhino,model,user, dictionary,3dm,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_UserStrings(Rhino.FileIO.File3dmObject)">
            <summary>
            Returns a Rhino UserStrings
            </summary>
            <param name="RhinoObject">Rhino File3dmObject</param>
            <returns name="Keys">User string keys.</returns>
            <returns name="Values">User string values.</returns>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoObjectAttributes.Get_UserStringValue(Rhino.FileIO.File3dmObject,System.String)">
            <summary>
            Returns a value from a Rhino UserDictionary based on a Key
            </summary>
            <param name="RhinoObject">Rhino File3dmObject</param>
            <param name="key">Key value</param>
            <returns name="Value">UserDictionary Value</returns>
            <search>case,rhino,model,user, dictionary,3dm,rhynamo</search>
        </member>
        <member name="T:Interoperability.ReadRhino.RhinoTranslationToDS">
            <summary>
            Convert Rhino Geometry
            </summary>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_AllGeometryToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino objects to Dynamo geometry
            </summary>
            <param name="RhinoObjects">List of Rhino Objects</param>
            <returns name="Points">Dynamo Point</returns>
            <returns name="Curves">Dynamo Curves</returns>
            <returns name="Breps">Dynamo PolySurfaces</returns>
            <returns name="Extrusions">Dynamo PolySurfaces</returns>
            <returns name="Meshes">Dynamo Meshes</returns>
            <search>case,rhino,model,3dm,geometry,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_ArcsToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino arc objects to Dynamo arcs.
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,arc,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_BrepsToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino Breps to Dynamo PolySurface objects
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through.</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,nurbs,brep,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_CirclesToDS(System.Collections.Generic.List{Rhino.FileIO.File3dmObject})">
            <summary>
            Converts Rhino circle objects to Dynamo circles
            </summary>
            <param name="RhinoObjects">Rhino circle objects</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,nurbs,circle,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_CurvesToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino curve objects to Dynamo curves (lines, arcs, nurbs, polyline, polycurve)
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through.</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,curve,3dm,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_ExtrusionToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino Extrusions to Dynamo PolySurface objects
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through.</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,nurbs,extrusion,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_LinesToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino line objects to Dynamo lines.
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <returns name="lines">DesignScript Lines</returns>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_MeshToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Convert Rhino meshes to Dynamo meshes
            </summary>
            <param name="RhinoObjects">Rhino mesh objects</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,nurbs,mesh,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_NurbsCurvesToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino NurbsCurve objects to Dynamo NurbsCurves
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through.</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,nurbs,curve,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_NurbsSurfaceToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Untrimmed Rhino NurbsSurface objects to Dynamo NurbsSurfaces
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,nurbs,surface,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_PolylinesToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino Polyline objects to Dynamo Polyline
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through.</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,polyline,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_PolyCurvesToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino PolyCurve objects to Dynamo PolyCurves
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through.</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,polycurve,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_PointsToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino point objects to Dynamo points.
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through.</param>
            <returns name="Geometry">Dynamo Geometry</returns>
            <returns name="Name">Object Name</returns>
            <returns name="LayerIndex">Layer Index</returns>
            <returns name="Color">Object color (as System.Color)</returns>
            <returns name="GUID">GUID</returns>
            <search>case,rhino,model,3dm,point,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_ColorRGB(System.Drawing.Color)">
            <summary>
            Get RGB values form a system color
            </summary>
            <param name="color">Rhino system color</param>
            <returns name="R">Red (0-255)</returns>
            <returns name="G">Green (0-255)</returns>
            <returns name="B">Blue (0-255)</returns>
            <search>case,rhino,model,3dm,color,convert,rhynamo</search>
        </member>
        <member name="M:Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_TextToDS(Rhino.FileIO.File3dmObject[])">
            <summary>
            Converts Rhino text-based objects to Dynamo
            </summary>
            <param name="RhinoObjects">List of Rhino objects to search through.</param>
            <returns name="Text">Text string</returns>
            <returns name="Location">Text location</returns>
            <returns name="Height">Text height</returns>
            <returns>Text information</returns>
        </member>
        <member name="T:Interoperability.WriteRhino.CreateRhinoGeometry">
            <summary>
            Translate Dynamo Geometry to Rhino Geometry
            </summary>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoGeometry.DS_BrepToRhino(Autodesk.DesignScript.Geometry.PolySurface)">
            <summary>
            Converts Dynamo PolySurfaces to Rhino Breps
            </summary>
            <param name="DynamoPolysurface">Dynamo Breps</param>
            <returns name="RhinoBrep">Rhino Brep</returns>
            <search>case,rhino,3dn,rhynamo,brep</search>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoGeometry.DS_CurvesToRhino(Autodesk.DesignScript.Geometry.Curve)">
            <summary>
            Converts Dynamo curves to Rhino curve objects
            </summary>
            <param name="DynamoCurve">Dynamo Curves</param>
            <returns name="RhinoCurve">Rhino Curves</returns>
            <search>case,rhino,3dm,rhynamo,curve</search>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoGeometry.DS_MeshToRhino(Autodesk.DesignScript.Geometry.Mesh)">
            <summary>
            Converts Dynamo meshes to Rhino meshes
            </summary>
            <param name="DynamoMesh">Dynamo Meshes</param>
            <returns name="RhinoMesh">Rhino Meshes</returns>
            <search>case,rhino,3dm,rhynamo,mesh</search>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoGeometry.DS_NurbsSurfaceToRhino(System.Object)">
            <summary>
            Converts Dynamo nurbs surfaces to Rhino nurbs surface objects
            </summary>
            <param name="DynamoSurface">Dynamo Nurbs Surfaces</param>
            <returns name="NurbsSurface">Rhino Nurbs Surfaces</returns>
            <search>case,rhino,3dm,rhynamo,nurbssurface</search>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoGeometry.DS_PointsToRhino(Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Converts Dynamo points to Rhino point objects
            </summary>
            <param name="DynamoPoint">Dynamo Points</param>
            <returns name="RhinoPoint">Rhino Points</returns>
            <search>case,rhino,3dm,rhynamo,point</search>
        </member>
        <member name="T:Interoperability.WriteRhino.CreateRhinoObjects">
            <summary>
            Create Rhino Objects with Attributes
            </summary>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoObjects.Create_RhinoColor(System.Int32,System.Int32,System.Int32)">
            <summary>
            Creates a true System color object for Rhino layers and object colors.
            </summary>
            <param name="Red">Red (0-255)</param>
            <param name="Green">Green (0-255)</param>
            <param name="Blue">Blue (0-255)</param>
            <returns name="SystemColor">System.Drawing.Color</returns>
            <search>case,rhino,3dm,rhynamo,layer,color,model</search>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoObjects.Create_RhinoLayer(System.String,System.Drawing.Color)">
            <summary>
            Create a Rhino Layer
            </summary>
            <param name="LayerName">Layer name</param>
            <param name="LayerColor">Layer color</param>
            <returns name="RhinoLayer">Layer object</returns>
            <search>case,rhino,3dm,rhynamo,layer,model</search>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoObjects.Create_RhinoObject(System.Object,System.String,System.Drawing.Color,Rhino.DocObjects.Layer)">
            <summary>
            Create Rhino Object
            </summary>
            <param name="RhinoGeometry">Rhino Geometry</param>
            <param name="ObjName">Object Name</param>
            <param name="ObjColor">Object Color</param>
            <param name="ObjLayer">Layer</param>
            <returns name="RhinoObject">Rhino Object</returns>
            <search>case,rhino,3dm,rhynamo,object,model</search>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoObjects.Set_UserString(System.Object,System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.String})">
            <summary>
            Sets a User String to an Object using matching keys and values
            </summary>
            <param name="RhinoObject"></param>
            <param name="keys">Keys as strings</param>
            <param name="values">Values as strings</param>
            <returns name="RhinoObject">Rhino object with user string</returns>
        </member>
        <member name="M:Interoperability.WriteRhino.CreateRhinoObjects.Set_UserDictionary(System.Object,System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.Object})">
            <summary>
            Sets a User Dictionary to an Object using matching keys and values
            </summary>
            <param name="RhinoObject"></param>
            <param name="keys">Keys as strings</param>
            <param name="values">Values as integer, double, string, guid, or boolean</param>
            <returns name="RhinoObject">Rhino object with user string</returns>
        </member>
        <member name="T:Interoperability.WriteRhino.SaveRhino3dmModel">
            <summary>
            Save the Rhino model to a File
            </summary>
        </member>
        <member name="M:Interoperability.WriteRhino.SaveRhino3dmModel.Save_Rhino3dmModel(System.String,System.Boolean,System.Object[],System.String)">
            <summary>
            Save Rhino Model
            </summary>
            <param name="FilePath">Location of the Rhino File</param>
            <param name="SaveBool">Toggle to Save the File</param>
            <param name="RhinoObjects">Rhino Geometry to Save</param>
            <param name="Units">Model units as string (ex. millimeters, centimeters, meters, feet, inches)</param>
            <returns name="RhinoModel">Rhino 3dm Model Object</returns>
            <search>case,rhino,3dm,rhynamo,save,model</search>
        </member>
    </members>
</doc>
