<?xml version="1.0"?>
<doc>
    <assembly>
        <name>DuctTape</name>
    </assembly>
    <members>
        <member name="T:DuctTape.Revit.Elements.CableTray">
            <summary>
            Wrapper class for Cable Trays.
            </summary>
        </member>
        <member name="M:DuctTape.Revit.Elements.CableTray.CreateByLine(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line,Revit.Elements.Level,System.Double,System.Double,System.Double)">
            <summary>
            This node will obtain the location point of the space.
            </summary>
            <param name="cableTrayType">The cable tray type to use.</param>
            <param name="line">The line to create cable tray along.</param>
            <param name="level">The level to associate cable tray to.</param>
            <param name="offset">The offset from level.</param>
            <param name="width">The width of the cable tray.</param>
            <param name="height">The height of the cable tray.</param>
            <returns name="CableTray">The resulting cable tray.</returns>
            <search>
            space, space.location, ducttape
            </search>
        </member>
        <member name="T:DuctTape.Revit.Elements.MechanicalSystem">
            <summary>
            Wrapper class for Mechanical Systems.
            </summary>
        </member>
        <member name="M:DuctTape.Revit.Elements.MechanicalSystem.Elements(Revit.Elements.Element)">
            <summary>
            This node will obtain the individual elements in the mechanical system.
            </summary>
            <param name="mechanicalSystem">The mechanical system to obtain elements from.</param>
            <returns name="elements">The elements in that system.</returns>
            <search>
            duct system, pipe system, ducttape
            </search>
        </member>
        <member name="M:DuctTape.Revit.Elements.MechanicalSystem.GetFlow(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            Gets the flow of this mechanical system.
            </summary>
            <param name="mechanicalSystem">The mechanical system to obtain the flow from.</param>
            <returns name="flow">The flow of the system.</returns>
            <search>
            duct system, pipe system, flow, ducttape
            </search>
        </member>
        <member name="M:DuctTape.Revit.Elements.MechanicalSystem.GetStaticPressure(System.Collections.Generic.List{Revit.Elements.Element})">
            <summary>
            Gets the static pressure of this mechanical system.
            </summary>
            <param name="mechanicalSystem">The mechanical system to obtain the flow from.</param>
            <returns name="staticPressure">The static pressure of the system.</returns>
            <search>
            duct system, pipe system, static pressure, ducttape
            </search>
        </member>
        <member name="M:DuctTape.Revit.Elements.Wire.Vertices(Revit.Elements.Element)">
            <summary>
            This node will obtain the vertices of the wire.
            </summary>
            <param name="wire">The wire to obtain vertices from.</param>
            <returns name="vertices">The wire's vertices.</returns>
            <search>
            space, space.number, ducttape
            </search>
        </member>
        <member name="M:DuctTape.Revit.Elements.Wire.Curve(Revit.Elements.Element)">
            <summary>
            This node will obtain the vertices of the wire.
            </summary>
            <param name="wire">The wire to obtain vertices from.</param>
            <returns name="curve">The wire's curve.</returns>
            <search>
            space, space.number, ducttape
            </search>
        </member>
        <member name="T:DuctTape.Revit.Selection.Select">
            <summary>
            Wrapper class for selection.
            </summary>
        </member>
        <member name="M:DuctTape.Revit.Selection.Select.SpaceAtPoint(Autodesk.DesignScript.Geometry.Point)">
            <summary>
            This node will attempt to obtain the space at the given point.
            </summary>
            <param name="point">The point to check.</param>
            <returns name="space">The space.</returns>
            <search>
            space, space.location, ducttape
            </search>
        </member>
        <member name="T:Revit.Elements.Space">
            <summary>
            Space Element
            </summary>
        </member>
        <member name="P:Revit.Elements.Space.InternalRevitElement">
            <summary>
            Internal reference to the Revit Element
            </summary>
        </member>
        <member name="P:Revit.Elements.Space.InternalElement">
            <summary>
            Reference to the Element
            </summary>
        </member>
        <member name="M:Revit.Elements.Space.#ctor(Autodesk.Revit.DB.Mechanical.Space)">
            <summary>
            Create from existing element
            </summary>
            <param name="Space"></param>
        </member>
        <member name="M:Revit.Elements.Space.#ctor(Autodesk.Revit.DB.Level,Autodesk.Revit.DB.XYZ,System.String,System.String)">
            <summary>
            Create a new Space by Level and location
            </summary>
            <param name="level"></param>
            <param name="location"></param>
            <param name="name"></param>
            <param name="number"></param>
        </member>
        <member name="M:Revit.Elements.Space.InitElement(Autodesk.Revit.DB.Mechanical.Space)">
            <summary>
            Set internal element
            </summary>
        </member>
        <member name="M:Revit.Elements.Space.InternalSetElement(Autodesk.Revit.DB.Mechanical.Space)">
            <summary>
            Set the internal Element, ElementId, and UniqueId
            </summary>
        </member>
        <member name="M:Revit.Elements.Space.ByLocation(Revit.Elements.Level,Autodesk.DesignScript.Geometry.Point,System.String,System.String)">
            <summary>
            Create a Revit Space Element
            </summary>
            <param name="level">Level the Space is hosted on</param>
            <param name="location">Location for the center of the Space</param>
            <param name="name">Space name</param>
            <param name="number">Space number</param>
            <returns></returns>
        </member>
        <member name="P:Revit.Elements.Space.AssociatedRoomName">
            <summary>
            Get associated room name
            </summary>
        </member>
        <member name="P:Revit.Elements.Space.AssociatedRoomNumber">
            <summary>
            Get associated room number
            </summary>
        </member>
        <member name="M:Revit.Elements.Space.IsInsideSpace(Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Check if a point is inside of a Space
            </summary>
        </member>
    </members>
</doc>
