{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "TestWriteDefinition",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "SketchUpForDynamo.SketchUp.WriteModel@string,Autodesk.DesignScript.Geometry.Surface[],Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "f7e40e951e624d1c8482c6e7f598352d",
      "Inputs": [
        {
          "Id": "42ba758c46d345e393d03ca8d3f8c4e8",
          "Name": "path",
          "Description": "Path to SketchUp file\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1cfe6e344c344452888c65ceec1e2d9b",
          "Name": "surfaces",
          "Description": "Surface Geometries\n\nSurface[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f5d35eacf832451e8b2ff2095b25aa34",
          "Name": "curves",
          "Description": "Curve Geometries\n\nCurve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a8997b492b5f43c4988036475f917aa4",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Write SketchUp Model. This node writes surfaces and cures into a SketchUp model.\n\nSketchUp.WriteModel (path: string, surfaces: Surface[], curves: Curve[]): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "120f074cf3a4472ca046117192d1cf8a",
      "Inputs": [
        {
          "Id": "a1fa4a1971b04da4a917bc788bce3d11",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "94e563ea6df14d79ac923582809ac844",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "05889a8dfca4495881046c4eb90adf8c",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "bfa3ffda251f456cae3b410177cca74d",
      "Inputs": [
        {
          "Id": "efe1b54333ef4e2ea848c35ef9f62aa6",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c1dab21461414adcbdecc4c7c851b797",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2f10a0c7ff0743e8b8a2234b8ee87723",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ba2a7b5188404774a1a15ae8ef05101f",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "64816af25ef441579273e2835dde43b7",
      "Inputs": [
        {
          "Id": "863858d115394e458a863b4fd93bf0df",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5b4013fb5a494347b441b92d882d8131",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "eafea2c646c94309bb07307046127643",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1f6ddad2813349bab41a523dc1572648",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "100;",
      "Id": "d59fc58d34d5488f9b0617c777a2be73",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "413ab48c3b644f999cbed5c3e00b8c06",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByPatch@Autodesk.DesignScript.Geometry.Curve",
      "Id": "25c3bce38f214091ad957b691860add9",
      "Inputs": [
        {
          "Id": "e629007e5d7843eb851475aeaae5cdeb",
          "Name": "closedCurve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "15464f9300274bd1b6096ba2cabb50cb",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by filling in the interior of a closed boundary defined by input Curves.\n\nSurface.ByPatch (closedCurve: Curve): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Rectangle.ByCornerPoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "569ea4dd0f9d4f1aa2f6c896c00778f3",
      "Inputs": [
        {
          "Id": "5d07d8c6da584910821c323ad52ff4ab",
          "Name": "p1",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a3a3df251273408b808c7f5fae9a6b97",
          "Name": "p2",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ae37c61f59714f5794d32b07ddcb7ad1",
          "Name": "p3",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "915bb7488a234e35a65947efa16412dd",
          "Name": "p4",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c191ce85e0e540fabbb0bff2dcaa1d70",
          "Name": "Rectangle",
          "Description": "Rectangle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Rectangle by four corner Points.\n\nRectangle.ByCornerPoints (p1: Point, p2: Point, p3: Point, p4: Point): Rectangle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "cc0318de8e8b42d885eec810c46e708c",
      "Inputs": [
        {
          "Id": "b1e1d182ef4c493e9a706b5a80730f66",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "138efef54a0746b88a0fc65f71463cbb",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b653e9f9be23483fa9e2f6a6e16b89be",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1045b8a0abfa421cb921e97bb77e1f72",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "43fdb4a85b9b431299a0fabb00e6b6b8",
      "Inputs": [
        {
          "Id": "902c0545735b4ce58dc9bd83a3e13c61",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c6995594589a46438671eb18b006fae1",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bfce896cff95426f92070c8f1c8e58fb",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "28237705882c416987c2a3e647f5c39d",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    }
  ],
  "Connectors": [
    {
      "Start": "05889a8dfca4495881046c4eb90adf8c",
      "End": "f5d35eacf832451e8b2ff2095b25aa34",
      "Id": "ead6bb49c5bd475a908a2f6eb20e0d80"
    },
    {
      "Start": "ba2a7b5188404774a1a15ae8ef05101f",
      "End": "a1fa4a1971b04da4a917bc788bce3d11",
      "Id": "4956d3781d704a50b451f02d9c2ab7c1"
    },
    {
      "Start": "ba2a7b5188404774a1a15ae8ef05101f",
      "End": "5d07d8c6da584910821c323ad52ff4ab",
      "Id": "5fda49ffcad64f14821f38d127b974f1"
    },
    {
      "Start": "1f6ddad2813349bab41a523dc1572648",
      "End": "94e563ea6df14d79ac923582809ac844",
      "Id": "8cb44cb8bbfc4dc1a3b33394487fb22b"
    },
    {
      "Start": "1f6ddad2813349bab41a523dc1572648",
      "End": "a3a3df251273408b808c7f5fae9a6b97",
      "Id": "fb68ad37374146b9947deb3f8dec6914"
    },
    {
      "Start": "413ab48c3b644f999cbed5c3e00b8c06",
      "End": "863858d115394e458a863b4fd93bf0df",
      "Id": "0a79ade93c7a4617a101f976f35cee83"
    },
    {
      "Start": "413ab48c3b644f999cbed5c3e00b8c06",
      "End": "b1e1d182ef4c493e9a706b5a80730f66",
      "Id": "14324665e5104a88a679605e293021bb"
    },
    {
      "Start": "413ab48c3b644f999cbed5c3e00b8c06",
      "End": "138efef54a0746b88a0fc65f71463cbb",
      "Id": "f2b8d48074784d27af1928af1087535e"
    },
    {
      "Start": "413ab48c3b644f999cbed5c3e00b8c06",
      "End": "c6995594589a46438671eb18b006fae1",
      "Id": "98d06e364d0b40eaa6f682310dc35aeb"
    },
    {
      "Start": "15464f9300274bd1b6096ba2cabb50cb",
      "End": "1cfe6e344c344452888c65ceec1e2d9b",
      "Id": "076721a206014a0b81d34677afe0f8c2"
    },
    {
      "Start": "c191ce85e0e540fabbb0bff2dcaa1d70",
      "End": "e629007e5d7843eb851475aeaae5cdeb",
      "Id": "d28f32b026814407a47ad29ff68408ad"
    },
    {
      "Start": "1045b8a0abfa421cb921e97bb77e1f72",
      "End": "ae37c61f59714f5794d32b07ddcb7ad1",
      "Id": "4590533039a447dfb3eddd80c8418cc8"
    },
    {
      "Start": "28237705882c416987c2a3e647f5c39d",
      "End": "915bb7488a234e35a65947efa16412dd",
      "Id": "07b7a5d5a5fd4eff877da7910216a43a"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "SketchUpForDynamo",
      "Version": "1.6.0",
      "ReferenceType": "Package",
      "Nodes": [
        "f7e40e951e624d1c8482c6e7f598352d"
      ]
    }
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.10.1.3976",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -50.964431762695313,
      "EyeY": 173.29475402832031,
      "EyeZ": 291.89361572265625,
      "LookX": 65.450859069824219,
      "LookY": -70.905097961425781,
      "LookZ": -316.3458251953125,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "SketchUp.WriteModel",
        "Id": "f7e40e951e624d1c8482c6e7f598352d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 883.865703997989,
        "Y": -37.1862207535059
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "120f074cf3a4472ca046117192d1cf8a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 291.319125183647,
        "Y": 11.3292498260188
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "bfa3ffda251f456cae3b410177cca74d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -10.2805001159875,
        "Y": 22.129062475836
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "64816af25ef441579273e2835dde43b7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -13.8855496032978,
        "Y": 182.025875070564
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "d59fc58d34d5488f9b0617c777a2be73",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -218.614836712971,
        "Y": 267.551974398957
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ByPatch",
        "Id": "25c3bce38f214091ad957b691860add9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 539.910126403641,
        "Y": 203.521675736607
      },
      {
        "ShowGeometry": true,
        "Name": "Rectangle.ByCornerPoints",
        "Id": "569ea4dd0f9d4f1aa2f6c896c00778f3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 303.369540658277,
        "Y": 209.674707796059
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "cc0318de8e8b42d885eec810c46e708c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -11.7137590592679,
        "Y": 339.440072157612
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "43fdb4a85b9b431299a0fabb00e6b6b8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -9.02843070573242,
        "Y": 493.15992069823
      }
    ],
    "Annotations": [],
    "X": 170.67132562981223,
    "Y": 110.8168837831964,
    "Zoom": 0.60498987240461188
  }
}