<Workspace Version="1.3.2.2480" X="360.5328526875" Y="249.704967393554" zoom="1.545620359375" ScaleFactor="1" Name="RebarShape.GetCurves" Description="Generate curves for the rebar shape, as used in the shape browser." ID="eb17910d-f82f-4aab-8024-95ba2ce069b2" Category="Zhukoven.Revit.Rebar">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="170546bf-91bd-46e6-93c4-846bece1a9b3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Author Konstantin Zhukoven @ https://zhukoven.com
#Tested to work with Dynamo 1.3.0+
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

RebarShape = UnwrapElement(IN[0])
bCurves = RebarShape.GetCurvesForBrowser()
curves = []
for i in bCurves:
	curves.append(i.ToProtoType())

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

OUT = curves
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="43f164a4-d04d-4b39-bccf-fa72f038c66b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-31.7024809506353" y="0.646989407155814" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input rebar shape element&#xD;&#xA;RebarShape" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4defc8cf-1f42-4a8e-8e2b-ae890655d4ab" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="170546bf-91bd-46e6-93c4-846bece1a9b3" start_index="0" end="4defc8cf-1f42-4a8e-8e2b-ae890655d4ab" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="43f164a4-d04d-4b39-bccf-fa72f038c66b" start_index="0" end="170546bf-91bd-46e6-93c4-846bece1a9b3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-820.768770005375" eyeY="3453.62372370347" eyeZ="72.1683459122414" lookX="1070.76877477375" lookY="-3453.62372370347" lookZ="674.021656529165" upX="0.713755452829293" upY="0.537299608346827" upZ="0.449290868399088" />
  </Cameras>
</Workspace>