<Workspace Version="1.2.0.2831" X="356.533386259029" Y="-11.798602180813" zoom="1.30764135636719" Name="Rebar.SetSolidInView" Description="Sets this rebar element to be shown solidly in a 3D view." ID="f07c3afa-4a0d-4257-90c9-738c6922a4da" Category="BIM4Struc.Rebar.Modify">
  <NamespaceResolutionMap>
    <ClassMap partialName="Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Elements.View3D" resolvedName="Revit.Elements.Views.View3D" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="870fbdee-f6d4-47b9-a4f5-f6a51acbb324" type="PythonNodeModels.PythonNode" nickname="Python Script" x="313" y="212" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference("System")
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#Preparing input from dynamo to revit
rebarElements = UnwrapElement(IN[0])
views = UnwrapElement(IN[1])
solid=IN[2];

#Change rebar in transaction
TransactionManager.Instance.EnsureInTransaction(doc)
for view in views:
	for rebarElement in rebarElements:
		rebarElement.SetSolidInView(view,solid)
TransactionManager.Instance.TransactionTaskDone()

OUT = rebarElements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c480fab9-526d-41c3-9169-a15a8dfc7d40" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="32.5919881305638" y="181.72997032641" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="rebarElements : Element[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d337441c-6472-4289-91e8-970ea15986dd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-149.931896358917" y="248.656965727169" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The 3D view element in which to set the rebar&#xD;&#xA;views: Elements.View3D[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0d68d879-0346-427f-999d-7150baf67aa0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="464.620542770262" y="211.342527736981" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="rebar" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="974d60ef-3a06-41f1-96bd-7ba8dd0c280b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-175.532369897435" y="323.329175941182" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//True if rebar is shown solidly, false otherwise.&#xD;&#xA;solid:bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="870fbdee-f6d4-47b9-a4f5-f6a51acbb324" start_index="0" end="0d68d879-0346-427f-999d-7150baf67aa0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c480fab9-526d-41c3-9169-a15a8dfc7d40" start_index="0" end="870fbdee-f6d4-47b9-a4f5-f6a51acbb324" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d337441c-6472-4289-91e8-970ea15986dd" start_index="0" end="870fbdee-f6d4-47b9-a4f5-f6a51acbb324" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="974d60ef-3a06-41f1-96bd-7ba8dd0c280b" start_index="0" end="870fbdee-f6d4-47b9-a4f5-f6a51acbb324" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-24598.9375" eyeY="32225.466796875" eyeZ="26204.94921875" lookX="24598.9375" lookY="-32225.466796875" lookZ="-26204.94921875" upX="0.337020516395569" upY="0.870355665683746" upZ="-0.359023869037628" />
  </Cameras>
</Workspace>