<Workspace Version="0.9.0.3067" X="-20.1729246708525" Y="-105.161648894293" zoom="0.910909980001544" Name="TitleblockFromSheet" Description="Returns the TitleBlock corresponding to the input Sheet element. Also works with lists of Sheets." ID="c35e2a07-8f14-44be-a7fe-c30fbbd3c988" Category="Dynablaster">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSFunction guid="39195d7e-685a-4562-9891-2920115c0eec" type="Dynamo.Nodes.DSFunction" nickname="Sheet.SheetNumber" x="836.820947921572" y="430.031971135853" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Views.Sheet.SheetNumber" />
    <DSRevitNodesUI.ElementsOfCategory guid="9a38565e-3853-4705-b9fc-ddc5e4d1832d" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="461.987563892807" y="359.577111963878" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" />
    <DSRevitNodesUI.Categories guid="f01d99b9-a076-41e6-b6ef-e82a11544f23" type="DSRevitNodesUI.Categories" nickname="Categories" x="250" y="360.344598835875" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="872:TitleBlocks" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="f81e713d-7fd6-4237-ad1a-2fdc487a5173" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="449.621108312626" y="263.850505805399" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;Sheet Number&quot;;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="251cbe70-e749-495f-8e97-79ed69d7ca2a" type="Dynamo.Nodes.DSFunction" nickname="Element.GetParameterValueByName" x="718.923110395302" y="232.272556549652" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <Dynamo.Nodes.Output guid="1f13330d-1eb9-4384-8fae-2c65fea63923" type="Dynamo.Nodes.Output" nickname="Output" x="1286.00596774325" y="334.811518600335" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="TitleBlock(s)" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="dee99736-a1ad-4513-8d1d-3d35c805a601" type="Dynamo.Nodes.Symbol" nickname="Input" x="107.596888322868" y="431.122579577108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="sheet(s)" />
    </Dynamo.Nodes.Symbol>
    <PythonNodeModels.PythonNode guid="bd7379bb-1f1d-49d8-91bc-f07537858ff5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1064.9933915853" y="335.371016396092" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="3">
      <Script>#Coded by Miguel Salvador Altava, March 2016.
#msalvador.altava@gmail.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

dataEnteringNode = IN

keys = IN[0]
values = IN[1]
search = IN[2]
a =list()

# create a dictionary called "mydict" from the keys list and values list
mydict = dict(zip(keys, values))

"""
checks wether the input is a list or a single element. If it's a list,
a loop searches for each input element and the result is appended to the void list created above.
"""
if type(search)==list :

	for s in search :
		b=mydict[s]
		a.append(b)
	
	OUT = a
else :
	b=mydict[search]
	OUT = b</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="39195d7e-685a-4562-9891-2920115c0eec" start_index="0" end="bd7379bb-1f1d-49d8-91bc-f07537858ff5" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="9a38565e-3853-4705-b9fc-ddc5e4d1832d" start_index="0" end="251cbe70-e749-495f-8e97-79ed69d7ca2a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9a38565e-3853-4705-b9fc-ddc5e4d1832d" start_index="0" end="bd7379bb-1f1d-49d8-91bc-f07537858ff5" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="f01d99b9-a076-41e6-b6ef-e82a11544f23" start_index="0" end="9a38565e-3853-4705-b9fc-ddc5e4d1832d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f81e713d-7fd6-4237-ad1a-2fdc487a5173" start_index="0" end="251cbe70-e749-495f-8e97-79ed69d7ca2a" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="251cbe70-e749-495f-8e97-79ed69d7ca2a" start_index="0" end="bd7379bb-1f1d-49d8-91bc-f07537858ff5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="dee99736-a1ad-4513-8d1d-3d35c805a601" start_index="0" end="39195d7e-685a-4562-9891-2920115c0eec" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bd7379bb-1f1d-49d8-91bc-f07537858ff5" start_index="0" end="1f13330d-1eb9-4384-8fae-2c65fea63923" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel guid="da89150f-d7aa-4c87-b4c5-adb2a88e8cef" text="the expected input is a Sheet or a list of sheets." x="34.1218422819842" y="502.871481211966" />
    <Dynamo.Models.NoteModel guid="16500415-23ac-4e30-89f4-bc83a91f6264" text="get the sheet number and performs a search in a dictionary created with the sheet numbers and the titleblocks themselves" x="1027.91157353393" y="471.274725185734" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>