<Workspace Version="0.8.2.2392" X="87.3164116803279" Y="240.13678545082" zoom="0.808946875" Name="Wall.GetTotalWidth_2" Description="Get Wall's  Total Width parameter" ID="64cd5fd3-af27-4fcc-9216-8e6cea02a658" Category="SteamNodes.Wall">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="c8e22a10-f890-4105-ac4f-5c4d62ea8b75" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="485" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>#python nodes in dynamo 0.7
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

elt = []
for i in IN[0]:
	elt.append(UnwrapElement(i))
list=[]
metersToFeet = 0.3048
feetToMeters = 1 / metersToFeet 

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

for i in elt:
	a=i.Width*metersToFeet
	list.append(a)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT=list</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="a388d2d4-b826-4c71-82ac-98ffb672b749" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="177" y="4.21833333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Nodes.Symbol guid="235bd6fe-4a52-454e-8d69-a749cf3e8342" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Wall(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="47dea727-187b-4fe4-ad25-7ff1df53a2d8" type="Dynamo.Nodes.Output" nickname="Output" x="947" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Width" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="c8e22a10-f890-4105-ac4f-5c4d62ea8b75" start_index="0" end="47dea727-187b-4fe4-ad25-7ff1df53a2d8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a388d2d4-b826-4c71-82ac-98ffb672b749" start_index="0" end="c8e22a10-f890-4105-ac4f-5c4d62ea8b75" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="235bd6fe-4a52-454e-8d69-a749cf3e8342" start_index="0" end="a388d2d4-b826-4c71-82ac-98ffb672b749" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="11208679751680" eyeY="158501691195392" eyeZ="-187804340453376" lookX="-369077310717952" lookY="-724148800192512" lookZ="-326532035772416" />
  </Cameras>
</Workspace>