<Workspace Version="1.3.4.6666" X="56.032966343918" Y="-34.6078999079705" zoom="0.655237890296823" ScaleFactor="1" Name="Dimension ByReferences" Description="Creates a new linear dimension from at least two geometric references of an object." ID="ba8b7d16-46d3-4c93-96c3-df912d9c1f9e" Category="GeniusLoci.Dimension">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Revit.Elements.Views.View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.Plane.Revit" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Plane.Revit" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Revit.DB.Reference" resolvedName="Autodesk.Revit.DB.Reference" assemblyName="" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2a669606-9a7a-4425-8bba-844586ea7985" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="47.9372690035981" y="316.222666529495" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Location of the dimension&#xD;&#xA;line:Autodesk.DesignScript.Geometry.Curve[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c816ba57-e7da-420c-b311-9276ca0ecb78" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="47.9372690035981" y="409.222666529495" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Autodesk.Revit.DB.Reference&#xD;&#xA;references" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3d3baadf-39dd-4a12-9658-918a39b36c82" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1091.9372690036" y="409.222666529495" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Dimension" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="89172725-ad21-4146-87d9-1b8577d2cbaf" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="47.9372690035981" y="492.222666529495" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="dimensionType:var[]..[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="b3b4c08b-9235-409a-8a7c-320945d47c07" type="PythonNodeModels.PythonNode" nickname="DimensionWithReference" x="821.537269003598" y="409.222666529495" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>#Alban de Chasteigner 2019
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

def tolist(obj1):
    if hasattr(obj1,"__iter__"): return obj1
    else: return [obj1]

lines = tolist(IN[0])
references= IN[1]
dimensionType=tolist(UnwrapElement(IN[2]))[0]
view = tolist(UnwrapElement(IN[3]))[0]

elementsRef = ReferenceArray()
for reference in references :
	elementsRef.Append(reference)
	
TransactionManager.Instance.EnsureInTransaction(doc)
for line in lines:
	if doc.IsFamilyDocument == True :
		if IN[2]== None: 
			dim = doc.FamilyCreate.NewDimension(view, line.ToRevitType(), elementsRef).ToDSType(True)
		else:
			dim = doc.FamilyCreate.NewDimension(view, line.ToRevitType(), elementsRef,dimensionType).ToDSType(True)
	else:
		if IN[2]== None: 
			dim = doc.Create.NewDimension(view, line.ToRevitType(), elementsRef).ToDSType(True)
		else:
			dim = doc.Create.NewDimension(view, line.ToRevitType(), elementsRef,dimensionType).ToDSType(True)
TransactionManager.Instance.TransactionTaskDone()

OUT=dim</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fdc47ab3-7157-41ff-9a10-3702c5218d39" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="47.9372690035981" y="575.222666529495" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//View to place dimension in&#xD;&#xA;view:Revit.Elements.Views.View = Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2a669606-9a7a-4425-8bba-844586ea7985" start_index="0" end="b3b4c08b-9235-409a-8a7c-320945d47c07" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c816ba57-e7da-420c-b311-9276ca0ecb78" start_index="0" end="b3b4c08b-9235-409a-8a7c-320945d47c07" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="89172725-ad21-4146-87d9-1b8577d2cbaf" start_index="0" end="b3b4c08b-9235-409a-8a7c-320945d47c07" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b3b4c08b-9235-409a-8a7c-320945d47c07" start_index="0" end="3d3baadf-39dd-4a12-9658-918a39b36c82" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fdc47ab3-7157-41ff-9a10-3702c5218d39" start_index="0" end="b3b4c08b-9235-409a-8a7c-320945d47c07" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>