<Workspace Version="1.3.3.4651" X="216.641763832199" Y="55.7544860454581" zoom="0.716982951558227" ScaleFactor="1" Name="SelectByCategoryAndLevel from document" Description="Select Elements by Category and Level from linked doc or open document in the background.&#xD;&#xA;From archilab" ID="655edf8d-b9ac-42b0-a60f-c074ef90ff18" Category="GeniusLoci.Document">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e2f7ec9d-88b6-4dfa-90c2-6c31933ab49a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="548.2" y="273.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="DSCore.List.Flatten(item,-1);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4a037dd1-d35c-44f2-bc5f-6cdea18eb042" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-129.806528189911" y="235.032640949554" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Collected level from document&#xD;&#xA;Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a962ecc6-630e-4dfc-8158-58cc0b623da4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-231.560598020699" y="316.877259755285" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Lacing on Longest for various categories&#xD;&#xA;Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8af937a6-827a-4510-ad90-9e3484f15a31" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="71.9738872403561" y="407.851632047478" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Document" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="de48ee01-c821-4572-9630-f57cfbf3acaa" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="900.460534124629" y="272.540059347181" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="5ba75202-ccb2-4022-8703-46abee83288a" type="PythonNodeModels.PythonNode" nickname="SelectByCategoryAndLevel from document" x="236.920801473165" y="248.543416214008" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Copyright(c) 2014, Konrad K Sobon
# Grimshaw Architects, http://grimshaw-architects.com/
# Archi-lab, http://wwww.archi-lab.net

# Default imports
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Import Collections
from System.Collections.Generic import *
import System

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

def tolist(x):
    if hasattr(x,'__iter__'): return x
    else : return [x]

doc = tolist(IN[2])

levelInput = tolist(IN[0])
cat = IN[1] 
catlist = []

for d in doc:
	collector = FilteredElementCollector(d)
for levelIn in levelInput:
	levelFilter = ElementLevelFilter(UnwrapElement(levelIn).Id)

bic = System.Enum.ToObject(BuiltInCategory, cat.Id)
catlist.append(collector.WherePasses(levelFilter).OfCategory(bic).ToElements())		
		
OUT=catlist</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e2f7ec9d-88b6-4dfa-90c2-6c31933ab49a" start_index="0" end="de48ee01-c821-4572-9630-f57cfbf3acaa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a037dd1-d35c-44f2-bc5f-6cdea18eb042" start_index="0" end="5ba75202-ccb2-4022-8703-46abee83288a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a962ecc6-630e-4dfc-8158-58cc0b623da4" start_index="0" end="5ba75202-ccb2-4022-8703-46abee83288a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8af937a6-827a-4510-ad90-9e3484f15a31" start_index="0" end="5ba75202-ccb2-4022-8703-46abee83288a" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5ba75202-ccb2-4022-8703-46abee83288a" start_index="0" end="e2f7ec9d-88b6-4dfa-90c2-6c31933ab49a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>