<Workspace Version="1.3.3.4651" X="-113.497879625328" Y="-13.3167570683166" zoom="1.00600419002725" ScaleFactor="1" Name="SelectByCategoryAnd3DView" Description="Collect elements by category and 3D View." ID="45627d39-aee2-479b-8d50-29c7e20c4c35" Category="GeniusLoci.View">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="21e0513d-21c2-497a-8d31-8f7072034275" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="218.84641079847" y="224.596905307619" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="3DView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2f5dd010-5a56-4461-b162-ba086114aa99" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="502.954053689998" y="227.682158511727" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="baaf42c0-c9a1-4592-89cd-18ea5c4fa65d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="209.647399194333" y="298.382583797508" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="f2a9ae86-0c52-4f0d-8055-3f507b680a19" type="PythonNodeModels.PythonNode" nickname="Python Script" x="346.616726930216" y="214.429282906341" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#From Einar_Raknes

import clr
clr.AddReference('RevitAPI')
clr.AddReference('System')
clr.AddReference('RevitNodes')
clr.AddReference('RevitServices')
import Revit
import RevitServices
from Autodesk.Revit.DB import *
from System.Collections.Generic import List
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
doc = DocumentManager.Instance.CurrentDBDocument

#Functions for list handling
def ProcessList(_func, _list):
   return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

#Preparing input from dynamo to revit

def Unwrap(item):
    return UnwrapElement(item)

if isinstance(IN[0], list):
    views = ProcessList(Unwrap, IN[0])
else:
    views = [Unwrap(IN[0])]

if isinstance(IN[1], list):
	cats = ProcessList(UnwrapElement, IN[1])
else:
	cats = [UnwrapElement(IN[1])]

viewlist = []

for view in views:
    viewlist.append(view)
    sectionbox = view.GetSectionBox()
    transform = sectionbox.Transform
    sboxoriginx = transform.Origin.X
    sboxoriginy = transform.Origin.Y
    sboxoriginz = transform.Origin.Z
    minx = sectionbox.Min.X + sboxoriginx
    maxx = sectionbox.Max.X + sboxoriginx
    miny = sectionbox.Min.Y + sboxoriginy
    maxy = sectionbox.Max.Y + sboxoriginy
    minz = sectionbox.Min.Z + sboxoriginz
    maxz = sectionbox.Max.Z + sboxoriginz
    bbox = BoundingBoxXYZ()

catlist = []
for cat in cats:
	catlist.append(cat.Id)
filtercats = List[ElementId](catlist)
catfilter = ElementMulticategoryFilter(filtercats)

def collectElementsInBB(bbox):
	outline = Outline(XYZ((minx), (miny), (minz)), XYZ((maxx), (maxy), (maxz)))
	bbfilter = BoundingBoxIntersectsFilter(outline)
	andfilter = LogicalAndFilter(catfilter,bbfilter)
	collector = FilteredElementCollector(doc).WherePasses(andfilter)
	return [e.ToDSType(True) for e in collector]

OUT = ProcessList(collectElementsInBB,views)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="21e0513d-21c2-497a-8d31-8f7072034275" start_index="0" end="f2a9ae86-0c52-4f0d-8055-3f507b680a19" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="baaf42c0-c9a1-4592-89cd-18ea5c4fa65d" start_index="0" end="f2a9ae86-0c52-4f0d-8055-3f507b680a19" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f2a9ae86-0c52-4f0d-8055-3f507b680a19" start_index="0" end="2f5dd010-5a56-4461-b162-ba086114aa99" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>