<?xml version="1.0"?>
<doc>
    <assembly>
        <name>DiRoots</name>
    </assembly>
    <members>
        <member name="T:DiRoots.Structural.Query">
            <summary>
            
            </summary>
        </member>
        <member name="M:DiRoots.Structural.Query.GetHost(Revit.Elements.Element)">
            <summary>
            
            </summary>
            <param name="Rebar"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.Structural.Query.GetRebarProperties(Revit.Elements.Element)">
            <summary>
            
            </summary>
            <param name="Rebar"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.Structural.Query.GetCenterLineCurves(Revit.Elements.Element,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Int32)">
            <summary>
            
            </summary>
            <param name="Rebar"></param>
            <param name="AdjustForSelfIntersection"></param>
            <param name="SuppressHooks"></param>
            <param name="SuppressBendRadius"></param>
            <param name="MultiPlanarOption"></param>
            <param name="BarPositionIndex"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.Structural.Create.DistributionByShapeAndPath(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.PolyCurve,System.Double,System.Double,System.Double)">
            <summary>
            
            </summary>
            <param name="Host"></param>
            <param name="Path"></param>
            <param name="PolyCurve"></param>
            <param name="DistanceFromStart"></param>
            <param name="DistanceFromEnd"></param>
            <param name="DistanceBetweenRebars"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.Structural.Create.RebarByCurves(Revit.Elements.Element,System.String,Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,System.String,System.String,System.Collections.Generic.List{Autodesk.DesignScript.Geometry.PolyCurve},System.Boolean)">
            <summary>
            
            </summary>
            <param name="Host"></param>
            <param name="RebarStyle"></param>
            <param name="RebarBarType"></param>
            <param name="RebarHookTypeAtStart"></param>
            <param name="RebarHookTypeAtEnd"></param>
            <param name="RebarHookOrientationAtStart"></param>
            <param name="RebarHookOrientationAtEnd"></param>
            <param name="PolyCurves"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.QA.Documents.GetLinkedRVT(System.Double,System.Double)">
            <summary>
            
            </summary>
            <param name="MaxLinkedRVT"></param>
            <param name="MaxScore"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.QA.Documents.GetCADImportedInstances(System.Double,System.Double)">
            <summary>
            
            </summary>
            <param name="MaxCADInstances"></param>
            <param name="MaxScore"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.QA.Documents.GetFileInfo(System.Double,System.Double)">
            <summary>
            
            </summary>
            <param name="MaxFileDimension"></param>
            <param name="MaxScore"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.QA.Documents.GetDetailGroup(System.Double,System.Double)">
            <summary>
            
            </summary>
            <param name="MaxDetailGroup"></param>
            <param name="MaxScore"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.QA.Documents.GetModelGroup(System.Double,System.Double)">
            <summary>
            
            </summary>
            <param name="MaxModelGroup"></param>
            <param name="MaxScore"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.QA.Views.GetProjectViewsByType">
            <summary>
            
            </summary>
            <returns></returns>
        </member>
        <member name="M:DiRoots.QA.Parameters.CheckListOfParameters(System.Collections.Generic.List{System.String},System.Double)">
            <summary>
            
            </summary>
            <param name="ParameterList"></param>
            <param name="MaxScore"></param>
            <returns></returns>
        </member>
        <member name="M:DiRoots.QA.Parameters.CheckParametersBinding(System.Collections.Generic.List{Autodesk.Revit.DB.ParameterElement},System.Collections.Generic.List{System.Collections.Generic.List{System.String}},System.Double)">
            <summary>
            
            </summary>
            <param name="ParameterElements"></param>
            <param name="CategoriesList"></param>
            <param name="MaxScore"></param>
            <returns></returns>
        </member>
    </members>
</doc>
