<Workspace Version="1.0.0.1180" X="-35" Y="79" zoom="1" Name="Get Revit ActiveView" Description="Active View" ID="92960965-5bfc-41ab-9ceb-d61917dfe6c5" Category="Hot Gear.View">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="94b482ea-4a20-43ae-b326-11d394264190" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

select = []
elements = []
select = uidoc.ActiveView

OUT = select</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f0d4584f-9af8-43aa-89a0-88b9e05563de" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="573.901180195874" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Active.View" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="94b482ea-4a20-43ae-b326-11d394264190" start_index="0" end="f0d4584f-9af8-43aa-89a0-88b9e05563de" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>