<Workspace Version="1.3.2.2480" X="565" Y="292" zoom="1" ScaleFactor="1" Name="AttachToStructure" Description="Attach Fabrication hanger rod ends to nearest structural member." ID="303951d3-982e-426f-b948-f77fcfdfd41d" Category="Fabrication">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="5b63dbc8-211a-445c-9b23-d6fb30bc316f" type="PythonNodeModels.PythonNode" nickname="AttachToStructure" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationRodInfo

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Inpt = UnwrapElement(IN[0])
Cnt = UnwrapElement(IN[1])
f = list()

Doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(Doc)

if Cnt &gt; 1:
	for e in Inpt:
		f.append(e.GetRodInfo().AttachToStructure())
else:
	f.append(Inpt.GetRodInfo().AttachToStructure())

TransactionManager.Instance.TransactionTaskDone()

OUT = f#Inpt, DimName, DimValue, ItmDims
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="97ca30ac-36a2-492c-a4f4-db9d7274c870" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="450" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="496035cd-5c4c-45e0-b2ee-f2fa87695c40" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-145" y="-34" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Hangers only.&#xD;&#xA;FabricationPart(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="50100096-aeae-4aff-80fc-814a467520dc" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="51" y="-109" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5b63dbc8-211a-445c-9b23-d6fb30bc316f" start_index="0" end="97ca30ac-36a2-492c-a4f4-db9d7274c870" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="496035cd-5c4c-45e0-b2ee-f2fa87695c40" start_index="0" end="50100096-aeae-4aff-80fc-814a467520dc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="496035cd-5c4c-45e0-b2ee-f2fa87695c40" start_index="0" end="5b63dbc8-211a-445c-9b23-d6fb30bc316f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="50100096-aeae-4aff-80fc-814a467520dc" start_index="0" end="5b63dbc8-211a-445c-9b23-d6fb30bc316f" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-45.6594070950538" eyeY="20.5272872201538" eyeZ="-60.4306888475094" lookX="-1.40669256314627" lookY="-4.17608315027596" lookZ="-2.4551676136851" upX="-0.342205101497538" upY="0.725374371012295" upZ="-0.597266850233291" />
  </Cameras>
</Workspace>