<Workspace Version="1.3.2.2480" X="346.343403731774" Y="221.333566770249" zoom="0.888789228297156" ScaleFactor="1" Name="SetDimensionValue" Description="Set dimension values for FabricationParts." ID="11a7aebb-2c30-40ff-b3c5-cf961d8e2d10" Category="Fabrication">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c933f0c9-5784-4140-b43e-c9b9993f785b" type="PythonNodeModels.PythonNode" nickname="Set Dimension Value(s)" x="250" y="-1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationDimensionDefinition

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

Inpt = UnwrapElement(IN[0])
Cnt = UnwrapElement(IN[1])
DimName = UnwrapElement(IN[2])
DimValue = UnwrapElement(IN[3])
f = list()

Doc = DocumentManager.Instance.CurrentDBDocument
TransactionManager.Instance.EnsureInTransaction(Doc)

if Cnt &gt; 1:
	for e in Inpt:
		ItmDims = e.GetDimensions()
		f.append(e.SetDimensionValue(ItmDims[DimName], DimValue))
else:
	ItmDims = Inpt[0].GetDimensions()
	f.append(Inpt[0].SetDimensionValue(ItmDims[DimName], DimValue))

TransactionManager.Instance.TransactionTaskDone()

OUT = f#Inpt, DimName, DimValue, ItmDims
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="18461d83-c95c-4c18-b08c-cdc0e9d3d382" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-198" y="16" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FabricationPart(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0a4ebca4-d6f0-4678-b063-2a1ab44e15b4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Index of the dimension to modify.&#xD;&#xA;//For example: The Index of &quot;Width In&quot;&#xD;&#xA;//for CID 2 is 0&#xD;&#xA;DimIndex : int" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9496b800-eca9-4175-8005-8673cdacdd17" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="450" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Value in feet for linear dimensions, or&#xD;&#xA;//in radians for angular dimensions.&#xD;&#xA;DimValue : double" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6a708dab-8213-4402-a062-57cc88aaace7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="61" y="-107" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="18461d83-c95c-4c18-b08c-cdc0e9d3d382" start_index="0" end="c933f0c9-5784-4140-b43e-c9b9993f785b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="18461d83-c95c-4c18-b08c-cdc0e9d3d382" start_index="0" end="6a708dab-8213-4402-a062-57cc88aaace7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0a4ebca4-d6f0-4678-b063-2a1ab44e15b4" start_index="0" end="c933f0c9-5784-4140-b43e-c9b9993f785b" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9496b800-eca9-4175-8005-8673cdacdd17" start_index="0" end="c933f0c9-5784-4140-b43e-c9b9993f785b" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6a708dab-8213-4402-a062-57cc88aaace7" start_index="0" end="c933f0c9-5784-4140-b43e-c9b9993f785b" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>