<Workspace Version="1.0.0.1180" X="153.898936142433" Y="176.440095637982" zoom="0.97676875" Name="Geometry Intersection" Description="Find the intersection solid between two list of geometries" ID="358b04af-2eee-4f52-b41c-80d8d3f6610f" Category="Dynamo4MEP.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6cdd43c7-ac06-44fb-a841-9e9618436fc1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="192.438054042986" y="3.73362169909722" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2016 http://bimandothers.blogspot.com
#Please contact at cesare.caoduro@gmail.com

import clr
clr.AddReference('RevitAPI')
clr.AddReference("RevitNodes")

import Revit
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

baseGeometry = IN[0]
intersectionGeometry = IN[1]
interferences = []


for i in intersectionGeometry:
	for j in baseGeometry:
		interference = i.DoesIntersect(j)
		if interference == True:
			interferences.append(j.Intersect(i))

			
			
OUT = interferences
			</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="49054258-c54e-4fb0-828a-24013433b6b9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Base Geometry" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="82daeea0-9c08-4b5e-b318-54c31f3184fd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-66.4" y="57.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Intersection Geometry" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fc7bc9a1-082c-4048-9345-4640b406b317" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="648.123891914028" y="1.65708106447912" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Element(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a69bec7e-81a6-4c9d-962b-2a6f3e1633bd" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="515.2" y="0.800000000000001" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6cdd43c7-ac06-44fb-a841-9e9618436fc1" start_index="0" end="a69bec7e-81a6-4c9d-962b-2a6f3e1633bd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="49054258-c54e-4fb0-828a-24013433b6b9" start_index="0" end="6cdd43c7-ac06-44fb-a841-9e9618436fc1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="82daeea0-9c08-4b5e-b318-54c31f3184fd" start_index="0" end="6cdd43c7-ac06-44fb-a841-9e9618436fc1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a69bec7e-81a6-4c9d-962b-2a6f3e1633bd" start_index="0" end="fc7bc9a1-082c-4048-9345-4640b406b317" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-616.054931640625" eyeY="4327.63818359375" eyeZ="-300.386291503906" lookX="22199.23828125" lookY="-7137.45751953125" lookZ="-8216.4306640625" upX="0.0719489455223084" upY="0.997052729129791" upZ="-0.0266299042850733" />
  </Cameras>
</Workspace>