{
  "Uuid": "7355aab1-d1d2-4ebc-a4bf-b61c5d7e3d94",
  "IsCustomNode": true,
  "Category": "Synthesize.Packages.Clockwork.Revit.Elements.Floor.Actions",
  "Description": "Transform a slab shape based on a list of XYZs. PLEASE NOTE: Will reset any previous edits on the slab shape.",
  "Name": "CW.Floor.SlabShapeByPoints",
  "ElementResolver": {
    "ResolutionMap": {
      "Floor": {
        "Key": "Revit.Elements.Floor",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "VARpoints",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "5bb0ff9a241549dcba603dcc5445ee1c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "73c8cbaf3aa6417097f024a92246dbd1",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "VARfloor",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "ef4556c3fc584ae19feed7d62f9d2795",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "961df7a6f9a14ab9bee2b828e7894d3c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "VARfloor",
      "Id": "e34a3b6a64974e21b5f4d6ace55f2c7b",
      "Inputs": [
        {
          "Id": "64dae8314c5a4a58afa36a2a77cba713",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "058d300c-24b5-4e79-9da0-c04c793d3103",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "918e92e658814f86a959f72c3eb96d06",
      "Inputs": [
        {
          "Id": "dda22424a1f94f3a97a2616cb7e35d9f",
          "Name": "VARpoints",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb26baedc35c4e33b6daf5d7d1052c61",
          "Name": "VARroof",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "26c74b9937d546e38cb783347bd29a02",
          "Name": "VARroof",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Transform a slab shape based on a list of XYZs. PLEASE NOTE: Will reset any previous edits on the slab shape."
    }
  ],
  "Connectors": [
    {
      "Start": "73c8cbaf3aa6417097f024a92246dbd1",
      "End": "dda22424a1f94f3a97a2616cb7e35d9f",
      "Id": "255a7037b6cd4797ad1dfc03fe5884a6"
    },
    {
      "Start": "961df7a6f9a14ab9bee2b828e7894d3c",
      "End": "fb26baedc35c4e33b6daf5d7d1052c61",
      "Id": "2f4da644fa1442f2a66cc54255baeeb9"
    },
    {
      "Start": "26c74b9937d546e38cb783347bd29a02",
      "End": "64dae8314c5a4a58afa36a2a77cba713",
      "Id": "30c94e8d69f34c31bb955c74b1d7aff0"
    }
  ],
  "Dependencies": [
    "058d300c-24b5-4e79-9da0-c04c793d3103"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.7500",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "5bb0ff9a241549dcba603dcc5445ee1c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 0.0
      },
      {
        "Id": "ef4556c3fc584ae19feed7d62f9d2795",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 0.0,
        "Y": 84.0
      },
      {
        "Id": "e34a3b6a64974e21b5f4d6ace55f2c7b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 602.0,
        "Y": 29.0
      },
      {
        "Id": "918e92e658814f86a959f72c3eb96d06",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "CW.Roof.SlabShapeByPoints",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 340.0,
        "Y": 29.0
      }
    ],
    "Annotations": [],
    "X": 30.0000000000001,
    "Y": 287.028443113772,
    "Zoom": 1.2185628742515
  }
}