{
  "Uuid": "36862be7-40cd-452a-bb91-fe2638817cdc",
  "IsCustomNode": true,
  "Category": "Synthesize.Packages.Hot Gear.Element",
  "Description": "",
  "Name": "HOT.Get Revit Selection",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\n\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\nfrom System.Collections.Generic import *\r\n\r\nclr.AddReference(\"RevitAPI\")\r\nimport Autodesk\r\nfrom Autodesk.Revit.DB import *\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuiapp = DocumentManager.Instance.CurrentUIApplication\r\napp = uiapp.Application\r\nuidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument\r\n\r\nselect = []\r\nelements = []\r\nselect = uidoc.Selection.GetElementIds()\r\n\r\nfor i in select:\r\n\t\telements.append(doc.GetElement(i).ToDSType(True))\r\n\r\nOUT = elements",
      "VariableInputPorts": true,
      "Id": "356fef1759e442ccad14532ab62b7bd1",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "4d8eb7c34ee34f6e826415fc38e9e31a",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "VARElement",
      "Id": "8a6dd75b04bf4f27a23ef92545b97d15",
      "Inputs": [
        {
          "Id": "ac75136a334c4af48575e408a2d27dc0",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    }
  ],
  "Connectors": [
    {
      "Start": "4d8eb7c34ee34f6e826415fc38e9e31a",
      "End": "ac75136a334c4af48575e408a2d27dc0",
      "Id": "ed399ec3070d409f98c86462e29f3f60"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.7500",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "356fef1759e442ccad14532ab62b7bd1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Python Script",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 276.098819804126,
        "Y": 0.252744994559038
      },
      {
        "Id": "8a6dd75b04bf4f27a23ef92545b97d15",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 445.657143656265,
        "Y": -1.0
      }
    ],
    "Annotations": [],
    "X": -95.246158720302361,
    "Y": 213.075615469762,
    "Zoom": 1.33823125
  }
}