{
  "Uuid": "f518f735-2512-4536-a2a3-173101818603",
  "IsCustomNode": true,
  "Category": "Synthesize.Packages.Springs.Revit.FamilyInstance",
  "Description": "You must provide a valid family template path that will be used for all input geometry objects. The project units(and not the templates) will be used to determine the size of the output geometry.\r\nThe provided category will be used only if the family template supports it. If not, the default template category will be used instead.\r\nLikewise, the family material(provided as a string) will be set only if a material with that name exists in the template. If not, the default material will be used instead (\"By Category\").\r\nFor void cuts, the material settings will be ignored.\r\nThe Subcategory name is an optional input. If you'd like to skip assigning a Subcategory to any new instance, simply use null.\r\nThe node expects a unique family name for each geometry object. The rest of the input lists will be processed as if the node lacing is set to longest.",
  "Name": "SP.AutoSATGeometry.ByElements",
  "ElementResolver": {
    "ResolutionMap": {
      "PolyCurve": {
        "Key": "Autodesk.DesignScript.Geometry.PolyCurve",
        "Value": "ProtoGeometry.dll"
      },
      "Vector": {
        "Key": "Autodesk.DesignScript.Geometry.Vector",
        "Value": "ProtoGeometry.dll"
      },
      "CoordinateSystem": {
        "Key": "Autodesk.DesignScript.Geometry.CoordinateSystem",
        "Value": "ProtoGeometry.dll"
      },
      "Rectangle": {
        "Key": "Autodesk.DesignScript.Geometry.Rectangle",
        "Value": "ProtoGeometry.dll"
      },
      "Plane": {
        "Key": "Autodesk.DesignScript.Geometry.Plane",
        "Value": "ProtoGeometry.dll"
      },
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "FamilyInstance": {
        "Key": "Revit.Elements.FamilyInstance",
        "Value": "RevitNodes.dll"
      },
      "Cuboid": {
        "Key": "Autodesk.DesignScript.Geometry.Cuboid",
        "Value": "ProtoGeometry.dll"
      },
      "Sphere": {
        "Key": "Autodesk.DesignScript.Geometry.Sphere",
        "Value": "ProtoGeometry.dll"
      },
      "Category": {
        "Key": "Revit.Elements.Category",
        "Value": "RevitNodes.dll"
      },
      "List": {
        "Key": "DSCore.List",
        "Value": "DSCoreNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "VARgeometry",
        "TypeName": "var",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "7971abd8ecd24e2fa28e52027545f3f6",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "45ea1c511f194c6da29d7b99a4a5480e",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "VARinstance",
      "Id": "325026eade93449a9cffbea72f2165f3",
      "Inputs": [
        {
          "Id": "9d0a8567965441fda6b6724bbeda08f5",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "VARfamily",
      "Id": "e35db8a4f8ae40deae1cdf5ba7ae6bb5",
      "Inputs": [
        {
          "Id": "5d35122a6ca74087b5ebfd18855efe7b",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "res[0];\nres[1];",
      "Id": "fba20a1f96ab4c49b5cc89d6e5b024aa",
      "Inputs": [
        {
          "Id": "227acd47d29c43008bbd3a6eb420d17a",
          "Name": "res",
          "Description": "res",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6e59e61c44b74b15a95b1b883ebc37bc",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1f9c25cd69c14b059e11e8eb77446930",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "#Copyright(c) 2016, Dimitar Venkov\r\n# @5devene, dimitar.ven@gmail.com\r\n# Modified & Improved By Karam Baki, karam@aecedx.com\r\nimport clr\r\nimport System\r\nfrom System.Collections.Generic import *\r\n\r\nfrom itertools import repeat\r\n\r\npf_path = System.Environment.GetFolderPath(System.Environment.SpecialFolder.ProgramFilesX86)\r\nimport sys\r\nsys.path.append('%s\\IronPython 2.7\\Lib' %pf_path)\r\nimport traceback\r\n\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\nfrom Autodesk.DesignScript.Geometry import Point as DynPoint\r\nfrom Autodesk.DesignScript.Geometry import Line as DynLine\r\nfrom Autodesk.DesignScript.Geometry import Curve as DynCurve\r\n\r\nclr.AddReference('RevitServices')\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\n\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\nfrom Autodesk.Revit.DB.Structure import StructuralType\r\n\r\nclr.AddReference('RevitNodes')\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\ndef tolist(obj1):\r\n\tif hasattr(obj1,'__iter__'): return obj1\r\n\telse: return [obj1]\r\n\r\ndef output1(l1):\r\n\tif len(l1) == 1: return l1[0]\r\n\telse: return l1\r\n\r\ndef PadLists(lists):\r\n\tlen1 = len(lists[0])\r\n\tfor i in xrange(1,len(lists)):\r\n\t\tlen2 = len(lists[i])\r\n\t\tif len2 == len1 : continue\r\n\t\telif len2 > len1: lists[i] = lists[i][:len1]\r\n\t\telse : lists[i].extend(repeat(lists[i][-1],len1 - len2))\r\n\treturn lists\r\n\r\nclass FamOpt1(IFamilyLoadOptions):\r\n\tdef __init__(self):\r\n\t\tpass\r\n\tdef OnFamilyFound(self,familyInUse, overwriteParameterValues):\r\n\t\treturn True\r\n\tdef OnSharedFamilyFound(self,familyInUse, source, overwriteParameterValues):\r\n\t\treturn True\r\n\r\ngeom = UnwrapElement(IN[0])\r\nif geom != None:\r\n\tgeom = tolist(geom)\r\nelse:\r\n\tpass\r\npositionSystem = tolist(IN[1])\r\n\r\nif int(DocumentManager.Instance.CurrentUIApplication.Application.VersionNumber) < 2021:\r\n\tunits = doc.GetUnits().GetFormatOptions(UnitType.UT_Length).DisplayUnits\r\n\tfactor = UnitUtils.ConvertToInternalUnits(1,units)\r\nelse:\r\n\tfactor = UnitUtils.ConvertToInternalUnits(1,doc.GetUnits().GetFormatOptions(SpecTypeId.Length).GetUnitTypeId())\r\nacceptable_views = ('ThreeD', 'FloorPlan', 'EngineeringPlan', 'CeilingPlan', 'Elevation', 'Section')\r\norigin = XYZ.Zero\r\nstr_typ = StructuralType.NonStructural\r\nt1 = TransactionManager.Instance\r\ntemp_path = System.IO.Path.GetTempPath()\r\ninvalid_chars = System.IO.Path.GetInvalidFileNameChars()\r\nsatOpt = SATImportOptions()\r\nsatOpt.Placement = ImportPlacement.Origin\r\nsatOpt.Unit = ImportUnit.Foot\r\nopt1 = Options()\r\nopt1.ComputeReferences = True\r\nSaveAsOpt = SaveAsOptions()\r\nSaveAsOpt.OverwriteExistingFile = True\r\n\r\ndef NewForm_background(s1, positionSystem1):\r\n\ttry:\r\n\t\tif mat1 == None or mat1 == \"\":\r\n\t\t\tenable_mat = False\r\n\t\telse:\r\n\t\t\tenable_mat = True\r\n\t\t\t\r\n\t\tif subcat1 == None or subcat1 == \"\":\r\n\t\t\tenable_subcat = False\r\n\t\telse:\r\n\t\t\tenable_subcat = True\r\n\r\n\t\tif any( (c in name1 for c in invalid_chars) ):\r\n\t\t\traise Exception('Family name contains invalid characters')\r\n\t\tTransactionManager.ForceCloseTransaction(t1)\r\n\t\tfamdoc = doc.Application.NewFamilyDocument(fam_path)\r\n\t\tsat_path = '%s%s.sat' % (temp_path, name1)\r\n\t\tif factor != 1:\r\n\t\t    tlist = []\r\n\t\t    for each in s1:\r\n\t\t        tlist.append(each.Scale(factor))\r\n\t\t\ts1 = tlist\r\n\t\tif positionSystem1 == False:\r\n\t\t\tbbox = BoundingBox.ByGeometry(s1)\r\n\t\t\tMinploc = bbox.MinPoint\r\n\t\t\tMaxploc = bbox.MaxPoint\r\n\t\t\tMAX_X = Maxploc.X\r\n\t\t\tMAX_Y = Maxploc.Y\r\n\t\t\tmin_Z = Minploc.Z\r\n\t\t\tNEWMAX = DynPoint.ByCoordinates(MAX_X,MAX_Y,min_Z)\r\n\t\t\tlinebet = DynLine.ByStartPointEndPoint(Minploc,NEWMAX)\r\n\t\t\tlocpoint = DynCurve.PointAtParameter(linebet,0.5)\r\n\t\t\tvec1 = Vector.ByTwoPoints(locpoint, DynPoint.Origin())\r\n\t\t\ttlist = []\r\n\t\t\tfor each in s1:\r\n\t\t\t\ttlist.append(each.Translate(vec1))\r\n\t\ts1 = tlist\r\n\t\tsat1 = Geometry.ExportToSAT(s1, sat_path)\r\n\t\tview_fec = FilteredElementCollector(famdoc).OfClass(View)\r\n\t\tview1 = None\r\n\t\tfor v in view_fec:\r\n\t\t\tif str(v.ViewType) in acceptable_views and not v.IsTemplate:\r\n\t\t\t\tview1 = v\r\n\t\t\t\tbreak\r\n\t\tt1.EnsureInTransaction(famdoc)\r\n\t\tsatId = famdoc.Import(sat1, satOpt, view1)\r\n\t\tel1 = famdoc.GetElement(satId)\r\n\t\tgeom1 = el1.get_Geometry(opt1)\r\n\t\tenum = geom1.GetEnumerator()\r\n\t\tenum.MoveNext()\r\n\t\tgeom2 = enum.Current.GetInstanceGeometry()\r\n\t\tenum2 = geom2.GetEnumerator()\r\n\t\tenum2.MoveNext()\r\n\t\ts1 = enum2.Current\r\n\t\tfamdoc.Delete(satId)\r\n\t\tSystem.IO.File.Delete(sat_path)\r\n\t\tsave_path = '%s%s.rfa' % (temp_path, name1)\r\n\t\t#for seach in s1:\r\n\t\ts2 = FreeFormElement.Create(famdoc,s1)\r\n\t\tTransactionManager.ForceCloseTransaction(t1)\t\r\n\texcept:\r\n\t\treturn traceback.format_exc(),''\r\nresult = []\r\n\r\nif geom == None or len(geom) == 0:\r\n\tOUT = None\r\nelse:\r\n\tif len(geom) == len(names):\r\n\t\tglist = []\r\n\t\tfor each in geom:\r\n\t\t\tglist.append([each])\r\n\t\tgeom = glist\r\n\t\tpadded = PadLists([geom, positionSystem])\r\n\t\tp_positionSystem = padded[1]\r\n\t\treturn1 = map(NewForm_background, geom, names, p_positionSystem)\r\n\t\tresult = output1([i[0] for i in return1]), output1([i[1] for i in return1])\r\n\telse :\r\n\t\tresult = NewForm_background(geom, names[0], positionSystem[0])\r\n\tOUT = result\r\n\tsatOpt.Dispose()\r\n\topt1.Dispose()\r\n\tSaveAsOpt.Dispose()",
      "VariableInputPorts": true,
      "Id": "deec7271456f4bbc9e87545f29fd4c95",
      "Inputs": [
        {
          "Id": "5bcceba853e54274b55865a8e468a48a",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3b65093dd60045c19fd3bad069ba021e",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "05b6a52de53d43e3ac67ad57c2408bc7",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "VARPositionSystemFalseIsInstanceOriginTrueRelativeToProjectOrigin",
        "TypeName": "bool",
        "TypeRank": 1,
        "DefaultValue": "false",
        "Description": ""
      },
      "Id": "cd1e8a1752c444988d886f67ccf81432",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "ef5a7cf57a3e4f88aa1edeb0b14819ce",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    }
  ],
  "Connectors": [
    {
      "Start": "45ea1c511f194c6da29d7b99a4a5480e",
      "End": "5bcceba853e54274b55865a8e468a48a",
      "Id": "3f64c64862544c968953bacbfdd6c743"
    },
    {
      "Start": "6e59e61c44b74b15a95b1b883ebc37bc",
      "End": "9d0a8567965441fda6b6724bbeda08f5",
      "Id": "15f87ffcaefc47538c8baa995d4eb353"
    },
    {
      "Start": "1f9c25cd69c14b059e11e8eb77446930",
      "End": "5d35122a6ca74087b5ebfd18855efe7b",
      "Id": "e760f54bb0e14573b804404c9149c732"
    },
    {
      "Start": "05b6a52de53d43e3ac67ad57c2408bc7",
      "End": "227acd47d29c43008bbd3a6eb420d17a",
      "Id": "ab7232a8fb1f47ee981c869022688853"
    },
    {
      "Start": "ef5a7cf57a3e4f88aa1edeb0b14819ce",
      "End": "3b65093dd60045c19fd3bad069ba021e",
      "Id": "e170c4a4947f405c8be87a78ca8bc0ca"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.7500",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "7971abd8ecd24e2fa28e52027545f3f6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -819.756143590251,
        "Y": 18.4611183263116
      },
      {
        "Id": "325026eade93449a9cffbea72f2165f3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -229.314093012575,
        "Y": 185.368375770972
      },
      {
        "Id": "e35db8a4f8ae40deae1cdf5ba7ae6bb5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -228.574297495933,
        "Y": 244.619074879458
      },
      {
        "Id": "fba20a1f96ab4c49b5cc89d6e5b024aa",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -376.537588759307,
        "Y": 189.621910227416
      },
      {
        "Id": "deec7271456f4bbc9e87545f29fd4c95",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Python Script",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -557.256842163068,
        "Y": 156.388071537748
      },
      {
        "Id": "cd1e8a1752c444988d886f67ccf81432",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -1300.48159961837,
        "Y": 163.074974181083
      }
    ],
    "Annotations": [],
    "X": 1084.8177005123,
    "Y": 136.922258743921,
    "Zoom": 0.879759357238854
  }
}