<?xml version="1.0"?>
<doc>
    <assembly>
        <name>StructuralDesign.Precast</name>
    </assembly>
    <members>
        <member name="T:StructuralDesign.Precast.Computation">
            <Summary>
             Computation Category
            </Summary>
        </member>
        <member name="M:StructuralDesign.Precast.Computation.PointParameterBasedOnDivision(System.Double,System.Double,System.Double,System.Boolean,System.Int32)">
            <summary>Returns point parameters based on specified division.</summary>
            <param name="length">Length of an element.</param>
            <param name="startEndOffset">Start/End offset.</param>
            <param name="maxSpacing">Max divison spacing.</param>
            <param name="ignoreSpacing">Ignore spacing (true or false).</param>
            <param name="divisionNumber">Division number.</param>
            <returns name="pointParameters">PointParameters.</returns>
            <search>
            point, parameter, division
            </search>
        </member>
        <member name="M:StructuralDesign.Precast.Computation.GroutTubeRotationAngle(Autodesk.DesignScript.Geometry.Surface)">
            <summary>Returns the grout tube rotation angle.</summary>
            <param name="surface">Wall face.</param>
            <returns name="angle">Angle</returns>
            <search>
            point, origin, location, wall, face
            </search>
        </member>
    </members>
</doc>
