{
  "Uuid": "c3e0f7f4-2b4f-4e72-bcc6-34d49f72249c",
  "IsCustomNode": true,
  "Category": "RIE.Geometry",
  "Description": "Find the XZ rotation component of a line",
  "Name": "RIE_Curve_Rotation_XZ",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.DesignScript.Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "curve",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "5bea39a005c34cf897d5751bbbe96206",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "8f622c5c04c8428fb3427e0a6dca2629",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "angleXZ",
      "Id": "b9d76c7658994ada954042dd3a33ad07",
      "Inputs": [
        {
          "Id": "f14262a74323471aaf49db199036c4f2",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "f8221fba0d2f4a908ee69d773e3f47a8",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "95d225f22b7e4547902241eec038ca8a",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "cb24972bff1742118f65cdac00b31864",
      "Inputs": [
        {
          "Id": "9b81b81f67d946b6b719e54375b9733e",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f97d5b02845b4b279ca01aea89b3295b",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5b4f93dadd224adc81abd18ad3556747",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "66bb375aff5c437a879a7279319057be",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.AngleAboutAxis@Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Vector",
      "Id": "b91838cfab5c48ae81e322ff72b4099a",
      "Inputs": [
        {
          "Id": "1fbede61241141cbbadeafd479434bf4",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "28b223f3dd754cee8751d5e0c6eab376",
          "Name": "otherVector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ddd4822511bd493183c75b5b4c9eca1c",
          "Name": "rotationAxis",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "84b6cc9e93f344338ff20c59784420e2",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns the angle between the two Vectors, in the range [0, 360] degrees. It uses axis of rotation to determine the direction of the angle.\n\nVector.AngleAboutAxis (otherVector: Vector, rotationAxis: Vector): double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "713d23608c724e31b56158b5e171a6b0",
      "Inputs": [
        {
          "Id": "7b34e7ee8be74ac48464a983eae9a700",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bf83f39bf45f47558be25f7da978b816",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "de63be7f60d0488cb147d11a222f45d2",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.Direction",
      "Id": "d88ceb8ae8ac4107a1127591b162849b",
      "Inputs": [
        {
          "Id": "1b5be60149794b019cfda52f4547fde8",
          "Name": "line",
          "Description": "Autodesk.DesignScript.Geometry.Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b03c06cd74b646f9be844390204a3695",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The direction of the Curve\n\nLine.Direction: Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "38e52a73b2594e03badc080c398ad049",
      "Inputs": [
        {
          "Id": "e01efaa69f8746119dd8725f239956a8",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cee440756cc145aaa1121734b57f9882",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "09dae4dfb3fb4a179a81b3d72da7f3c3",
      "Inputs": [
        {
          "Id": "cc1be2ff626c4999a559c18c1dbe8cb8",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "bd145b228f694bd5ba8ee7bb465ab024",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "845e73c6d2dc40a2b8cbd25139c0dfbe",
      "Inputs": [
        {
          "Id": "799bc995f0df40008580ff7002dd2ed9",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "330a4e23a32b4c3aaf42dadc9dd9dba7",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "1808cb1da464407da260f42438e92f41",
      "Inputs": [
        {
          "Id": "908c4543635c4159a6b989b3287828e7",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4a751c4a70504796a49bd4020f346ecb",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "abc76b7639ab458eabaa38ffa8a051d4",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0703455063df4e11b1cdaaf38a244400",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.XAxis",
      "Id": "9bee13b0af354182aa52db276ab7d493",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d57220dae7cf46eeaf319e871a4afb2b",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical X axis Vector (1,0,0)\n\nVector.XAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Id": "9954a4fdcbf442f59627e34716c2a4b2",
      "Inputs": [
        {
          "Id": "7a1d7471ba55472d894a806b8d43a8ad",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "128e3ba0f03d40faa4ebf2ffe504742a",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.EndPoint",
      "Id": "d91dc959989d44798f9a57eb96a7dd59",
      "Inputs": [
        {
          "Id": "97511d0b584b45d185b9f08cb8b0a011",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f86aae3de5584d3cb47c8a97f7b1aca4",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the end Point along the Curve\n\nCurve.EndPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "362a45bd06c64ac9957e9f2128f6b3f9",
      "Inputs": [
        {
          "Id": "5b2ab642e72447e88f66a29974b4e46d",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f40607b6cb1249539f724840061ce6ea",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    }
  ],
  "Connectors": [
    {
      "Start": "8f622c5c04c8428fb3427e0a6dca2629",
      "End": "7a1d7471ba55472d894a806b8d43a8ad",
      "Id": "93b8d7701dc34342a907cf72e228975b"
    },
    {
      "Start": "8f622c5c04c8428fb3427e0a6dca2629",
      "End": "97511d0b584b45d185b9f08cb8b0a011",
      "Id": "15febe9d445244bb94c0be9d81a113ef"
    },
    {
      "Start": "95d225f22b7e4547902241eec038ca8a",
      "End": "ddd4822511bd493183c75b5b4c9eca1c",
      "Id": "4cc92dfdae1f4298995bca93e7463b88"
    },
    {
      "Start": "66bb375aff5c437a879a7279319057be",
      "End": "bf83f39bf45f47558be25f7da978b816",
      "Id": "4b7cd9d464b5423688834e98bc2c8890"
    },
    {
      "Start": "84b6cc9e93f344338ff20c59784420e2",
      "End": "f14262a74323471aaf49db199036c4f2",
      "Id": "f69a29d1df7b4750b2f684d67b625ec8"
    },
    {
      "Start": "de63be7f60d0488cb147d11a222f45d2",
      "End": "1b5be60149794b019cfda52f4547fde8",
      "Id": "121d249df2b74471a7d58d91b038baaf"
    },
    {
      "Start": "b03c06cd74b646f9be844390204a3695",
      "End": "28b223f3dd754cee8751d5e0c6eab376",
      "Id": "3ea3f30d7c214373ada7aaf71fdcbba8"
    },
    {
      "Start": "cee440756cc145aaa1121734b57f9882",
      "End": "f97d5b02845b4b279ca01aea89b3295b",
      "Id": "81a17d422db643fa9e67ceffaedf4853"
    },
    {
      "Start": "bd145b228f694bd5ba8ee7bb465ab024",
      "End": "9b81b81f67d946b6b719e54375b9733e",
      "Id": "62a6acbfe3ab492f9ed045276b52e3e8"
    },
    {
      "Start": "330a4e23a32b4c3aaf42dadc9dd9dba7",
      "End": "4a751c4a70504796a49bd4020f346ecb",
      "Id": "f497eb523e1e433782cd2c64d17ea469"
    },
    {
      "Start": "0703455063df4e11b1cdaaf38a244400",
      "End": "7b34e7ee8be74ac48464a983eae9a700",
      "Id": "8a3a17e3a1c54b6fa34897d77250ee4a"
    },
    {
      "Start": "d57220dae7cf46eeaf319e871a4afb2b",
      "End": "1fbede61241141cbbadeafd479434bf4",
      "Id": "df3f62368383422fa9f5be4b16258291"
    },
    {
      "Start": "128e3ba0f03d40faa4ebf2ffe504742a",
      "End": "799bc995f0df40008580ff7002dd2ed9",
      "Id": "aa81ac236efa4ab68ff7eb46c03bd3dc"
    },
    {
      "Start": "128e3ba0f03d40faa4ebf2ffe504742a",
      "End": "5b2ab642e72447e88f66a29974b4e46d",
      "Id": "444d65897564400cb6c54758b8a14996"
    },
    {
      "Start": "f86aae3de5584d3cb47c8a97f7b1aca4",
      "End": "e01efaa69f8746119dd8725f239956a8",
      "Id": "b4c10c49598e40cd8c4c70061e824348"
    },
    {
      "Start": "f86aae3de5584d3cb47c8a97f7b1aca4",
      "End": "cc1be2ff626c4999a559c18c1dbe8cb8",
      "Id": "50cafe477a2a476cb68f656c380d4d11"
    },
    {
      "Start": "f40607b6cb1249539f724840061ce6ea",
      "End": "908c4543635c4159a6b989b3287828e7",
      "Id": "e7b6762626b04ad09a87747d856c00a6"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.3.0.5885",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "5bea39a005c34cf897d5751bbbe96206",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -258.0,
        "Y": 453.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "b9d76c7658994ada954042dd3a33ad07",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1509.6739875234866,
        "Y": 445.0
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.ZAxis",
        "Id": "f8221fba0d2f4a908ee69d773e3f47a8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1139.217579742457,
        "Y": 551.35366198873953
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "cb24972bff1742118f65cdac00b31864",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 634.018178887987,
        "Y": 531.92350110632651
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.AngleAboutAxis",
        "Id": "b91838cfab5c48ae81e322ff72b4099a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1262.5322421988067,
        "Y": 447.45863141528446
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "713d23608c724e31b56158b5e171a6b0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 822.97627185801412,
        "Y": 472.53667188717554
      },
      {
        "ShowGeometry": true,
        "Name": "Line.Direction",
        "Id": "d88ceb8ae8ac4107a1127591b162849b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1050.8582546753169,
        "Y": 473.67513445718441
      },
      {
        "ShowGeometry": true,
        "Name": "Point.Y",
        "Id": "38e52a73b2594e03badc080c398ad049",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 372.24862404337796,
        "Y": 597.25351057576245
      },
      {
        "ShowGeometry": true,
        "Name": "Point.X",
        "Id": "09dae4dfb3fb4a179a81b3d72da7f3c3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 371.2067280506069,
        "Y": 517.02751913244344
      },
      {
        "ShowGeometry": true,
        "Name": "Point.Y",
        "Id": "845e73c6d2dc40a2b8cbd25139c0dfbe",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 369.088678517925,
        "Y": 442.22599144331843
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "1808cb1da464407da260f42438e92f41",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 630.41897711712909,
        "Y": 363.660818318731
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.XAxis",
        "Id": "9bee13b0af354182aa52db276ab7d493",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1138.2465981483169,
        "Y": 395.02562533148512
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.StartPoint",
        "Id": "9954a4fdcbf442f59627e34716c2a4b2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 155.5,
        "Y": 398.46635974696278
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.EndPoint",
        "Id": "d91dc959989d44798f9a57eb96a7dd59",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 158.62568797831091,
        "Y": 522.45198288663642
      },
      {
        "ShowGeometry": true,
        "Name": "Point.X",
        "Id": "362a45bd06c64ac9957e9f2128f6b3f9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 368.04678252515396,
        "Y": 362.0
      }
    ],
    "Annotations": [],
    "X": 330.0,
    "Y": 169.0,
    "Zoom": 1.0
  }
}