<Workspace Version="0.8.2.2392" X="35.7020000000001" Y="264.8" zoom="1.1575" Name="Element.Category" Description="returns an elements category" ID="9b9be7be-d0de-4cb3-8aed-38d6970836da" Category="Hollandaise.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="b730675e-57c4-4ad1-9ed4-4e4d0e6cd4d3" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="211.515194650042" y="133.95447304206" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="0;&#xA;1;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="18c7379e-7144-4685-8ddb-910f34c7fe38" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="249.308855291577" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

elements = UnwrapElement(IN[0])

elementlist = list()
catlist=[]
for item in elements:
	elementlist.append(item.Category.Name)
	catlist.append(item.Category.Id)
	
outlist=[]
outlist.append(elementlist)
outlist.append(catlist)
OUT = outlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol guid="16182692-a663-453a-86a5-51f1711d755d" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="element" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="467d0760-0399-4e8b-814f-2aada10d47c9" type="Dynamo.Nodes.Output" nickname="Output" x="609.248671971856" y="-5.52915766738658" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Category name" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.DSFunction guid="1eaf6f89-f0ef-43f4-bfbe-85ddec17e70b" type="Dynamo.Nodes.DSFunction" nickname="List.GetItemAtIndex" x="446.261771058315" y="-7.73218142548586" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int" />
    <Dynamo.Nodes.DSFunction guid="16ea2c7a-cfbb-4144-81f9-16b380b72d1b" type="Dynamo.Nodes.DSFunction" nickname="List.GetItemAtIndex" x="449.825485961123" y="137.861771058315" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int" />
    <Dynamo.Nodes.Output guid="2dad1539-51c9-479a-ba6b-8cac7551ab25" type="Dynamo.Nodes.Output" nickname="Output" x="611.186177105832" y="140.259179265659" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Category Id" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="b730675e-57c4-4ad1-9ed4-4e4d0e6cd4d3" start_index="0" end="1eaf6f89-f0ef-43f4-bfbe-85ddec17e70b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="b730675e-57c4-4ad1-9ed4-4e4d0e6cd4d3" start_index="1" end="16ea2c7a-cfbb-4144-81f9-16b380b72d1b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="18c7379e-7144-4685-8ddb-910f34c7fe38" start_index="0" end="1eaf6f89-f0ef-43f4-bfbe-85ddec17e70b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="18c7379e-7144-4685-8ddb-910f34c7fe38" start_index="0" end="16ea2c7a-cfbb-4144-81f9-16b380b72d1b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="16182692-a663-453a-86a5-51f1711d755d" start_index="0" end="18c7379e-7144-4685-8ddb-910f34c7fe38" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1eaf6f89-f0ef-43f4-bfbe-85ddec17e70b" start_index="0" end="467d0760-0399-4e8b-814f-2aada10d47c9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="16ea2c7a-cfbb-4144-81f9-16b380b72d1b" start_index="0" end="2dad1539-51c9-479a-ba6b-8cac7551ab25" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>