<Workspace Version="0.7.6.3921" X="0" Y="0" zoom="1" Name="Family.LocationPoints" ID="86547407-a754-4ef0-9aed-31756dbb591e" Description="returns location points for families" Category="KOP.FAMILIES">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="7cf706dc-920c-4542-99db-a3430c866104" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>"""
Copyright Peter Kompolschek 2015
Deletes openings from walls and rolls back the transaction
"""
import sys
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
#initialise lists and parameters
#librarypaths

#unitconversion 
m1 = 3.2808
m2 = m1**2
m3 = m1**3
#lists
elements = []

outlist=[]


#parameters

#external functions

# load elements, flatten list and unwrap revit elements
for x in IN[0]:
    for y in x:
        elements.append(UnwrapElement(y))


for element in elements:
	point= element.Location.Point
	outlist.append(point.ToPoint())


OUT=outlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol guid="ad71f747-2eb3-42e2-a61a-5974d890b029" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Families" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="9a8981c4-38aa-48a6-afeb-1d1f15994c33" type="Dynamo.Nodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="LocationPoints" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="7cf706dc-920c-4542-99db-a3430c866104" start_index="0" end="9a8981c4-38aa-48a6-afeb-1d1f15994c33" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ad71f747-2eb3-42e2-a61a-5974d890b029" start_index="0" end="7cf706dc-920c-4542-99db-a3430c866104" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>