<Workspace Version="1.3.0.875" X="-760.520375563993" Y="-278.364848826798" zoom="1.62766375666706" ScaleFactor="1" Name="Get Custom Data" Description="" ID="3f11833b-874b-4311-9722-0b8a8367e26e" Category="DynaFabrication2018.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="9d1c9ad5-ffb2-48ba-8e87-d2b73fa03bcb" type="PythonNodeModels.PythonNode" nickname="Custom Data Name" x="1009.21914332368" y="354" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = []
ItmList = list()
Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	CustName = Config.GetPartCustomDataName(e)
	ItmList.append(CustName)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f1638b8c-a5f0-4ba1-a574-e8da55eb6279" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="756.45544595845" y="355.337134343691" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="4b6f6f84-4f80-4870-8132-4a57b04a097e" type="PythonNodeModels.PythonNode" nickname="Fabrication Custom Data" x="537" y="357.078616492849" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Doc = DocumentManager.Instance.CurrentDBDocument

ItmList = list()

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)
CustData = Config.GetAllPartCustomData()
ItmList.append(CustData)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ecbe2b44-f287-4860-aa91-05b0e40978d7" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1188.1728904059" y="359.182779776236" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Custom Data Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="56da6746-6333-4eaa-bf58-0b6c8d21a816" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1198.25127945131" y="459.157454172876" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Custom Data Type" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="3fa9fdbc-a476-459c-87ef-1bb95ae48f96" type="PythonNodeModels.PythonNode" nickname="Custom Data Type" x="1019.29753236909" y="453.97467439664" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = []
ItmList = list()
Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	CustName = Config.GetPartCustomDataType(e)
	ItmList.append(CustName)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9d1c9ad5-ffb2-48ba-8e87-d2b73fa03bcb" start_index="0" end="ecbe2b44-f287-4860-aa91-05b0e40978d7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f1638b8c-a5f0-4ba1-a574-e8da55eb6279" start_index="0" end="9d1c9ad5-ffb2-48ba-8e87-d2b73fa03bcb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f1638b8c-a5f0-4ba1-a574-e8da55eb6279" start_index="0" end="3fa9fdbc-a476-459c-87ef-1bb95ae48f96" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4b6f6f84-4f80-4870-8132-4a57b04a097e" start_index="0" end="f1638b8c-a5f0-4ba1-a574-e8da55eb6279" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fa9fdbc-a476-459c-87ef-1bb95ae48f96" start_index="0" end="56da6746-6333-4eaa-bf58-0b6c8d21a816" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>