<Workspace Version="0.8.2.2392" X="453.007777338603" Y="119.734086088322" zoom="0.572433706679815" Name="ElementParamByParam" Description="Takes an element, finds its host, retrieves a value from a parameter and assigns that value to the same parameter of the hosted element" ID="db50072c-8af4-4f33-b781-3792dd7cbd40" Category="Hollandaise.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSFunction guid="8d4cc2ad-9ba8-445c-b565-4c79ef6cef93" type="Dynamo.Nodes.DSFunction" nickname="Element.SetParameterByName" x="1591.17476376154" y="144.979189732149" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Nodes.DSFunction guid="5730d679-e75f-4e68-a218-8d2c7cf315a5" type="Dynamo.Nodes.DSFunction" nickname="Element.GetParameterValueByName" x="1327.41234013862" y="315.942662710012" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <Dynamo.Nodes.Symbol guid="93aabb85-acda-45f0-819f-4347f74afd2a" type="Dynamo.Nodes.Symbol" nickname="Input" x="-46.3125568096578" y="324.187897667605" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="parameterName" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="3758fd05-fe3c-4440-a9f7-d8cd955911db" type="Dynamo.Nodes.Output" nickname="Output" x="1756.48476140136" y="-43.5547144478005" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Element" />
    </Dynamo.Nodes.Output>
    <DSIronPythonNode.PythonNode guid="4192fb0a-885e-4c84-8286-49f913739ecf" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="409.842133364691" y="514.3060324554" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
faminsts = UnwrapElement(IN[0])
elementlist = list()
for item in faminsts:
	try:
		elementlist.append(item.Host.ToDSType(True))
	except:
		# if that doesn't work, maybe it's a WallSweep
		try:
			hostidlist = list()
			for host in item.GetHostIds():
				hostidlist.append(doc.GetElement(host).ToDSType(True))
			elementlist.append(hostidlist)
		except:
			elementlist.append(list())
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="5164d4ad-e136-457c-a9d3-b7c2b57b1823" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-52.1871010723715" y="178.343634474552" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="elements;" ShouldFocus="false" />
    <Dynamo.Nodes.Symbol guid="fc3ccba6-1426-45f1-836f-acf3a4f94bc5" type="Dynamo.Nodes.Symbol" nickname="Input" x="-550.060366665258" y="147.457725921789" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="element" />
    </Dynamo.Nodes.Symbol>
    <DSCoreNodesUI.CreateList guid="c831a9eb-5125-4aec-9b63-e04090ce22d5" type="DSCoreNodesUI.CreateList" nickname="List.Create" x="-378.859085875629" y="135.756972610216" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1" />
    <Dynamo.Nodes.DSFunction guid="fd2ddddb-df0e-427a-9ddf-f005afc43b8c" type="Dynamo.Nodes.DSFunction" nickname="Flatten" x="-203.859831640558" y="158.712284168734" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="BuiltIn" function="Flatten@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8d4cc2ad-9ba8-445c-b565-4c79ef6cef93" start_index="0" end="3758fd05-fe3c-4440-a9f7-d8cd955911db" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5730d679-e75f-4e68-a218-8d2c7cf315a5" start_index="0" end="8d4cc2ad-9ba8-445c-b565-4c79ef6cef93" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="93aabb85-acda-45f0-819f-4347f74afd2a" start_index="0" end="8d4cc2ad-9ba8-445c-b565-4c79ef6cef93" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="93aabb85-acda-45f0-819f-4347f74afd2a" start_index="0" end="5730d679-e75f-4e68-a218-8d2c7cf315a5" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="4192fb0a-885e-4c84-8286-49f913739ecf" start_index="0" end="5730d679-e75f-4e68-a218-8d2c7cf315a5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5164d4ad-e136-457c-a9d3-b7c2b57b1823" start_index="0" end="8d4cc2ad-9ba8-445c-b565-4c79ef6cef93" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5164d4ad-e136-457c-a9d3-b7c2b57b1823" start_index="0" end="4192fb0a-885e-4c84-8286-49f913739ecf" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fc3ccba6-1426-45f1-836f-acf3a4f94bc5" start_index="0" end="c831a9eb-5125-4aec-9b63-e04090ce22d5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c831a9eb-5125-4aec-9b63-e04090ce22d5" start_index="0" end="fd2ddddb-df0e-427a-9ddf-f005afc43b8c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fd2ddddb-df0e-427a-9ddf-f005afc43b8c" start_index="0" end="5164d4ad-e136-457c-a9d3-b7c2b57b1823" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="9c5de0cd-81f2-4466-a578-7c0690aea748" annotationText="Element.Host from an old clockwork package" left="399.842133364691" top="470.7060324554" width="144.8" height="137" fontSize="14" InitialTop="514.3060324554" InitialHeight="177.740479483012" TextblockHeight="33.6" backgrouund="#FFC1D676">
      <Models ModelGuid="4192fb0a-885e-4c84-8286-49f913739ecf" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>