<Workspace Version="0.8.2.2392" X="-70.3999999999999" Y="83.2" zoom="1" Name="Element.GetDesignOption" Description="gets an elements design option" ID="60db1182-2cec-46ef-96fb-4eb29166f8d4" Category="Hollandaise.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="3e214dac-0691-4bfe-9b42-5c7409d5278a" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="460.870841571833" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
#from dynamo to revit type
elems=UnwrapElement(IN[0])
options=[]
#run through elements and assign their options to a container array
for elem in elems:
	options.append(elem.DesignOption)
#Assign your output to the OUT variable
OUT = options

</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="19c78f08-5b83-4094-b388-80a849b6d50a" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250" y="142.510309833816" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="elements;" ShouldFocus="false" />
    <Dynamo.Nodes.Symbol guid="a1d46b6c-a592-4ce1-8fdd-0c41986c5752" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="elements" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="18396120-03e0-4d2a-9c96-ccf885b88f09" type="Dynamo.Nodes.Output" nickname="Output" x="766.389522331008" y="0.800000000000011" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="DesignOption" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="3e214dac-0691-4bfe-9b42-5c7409d5278a" start_index="0" end="18396120-03e0-4d2a-9c96-ccf885b88f09" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="19c78f08-5b83-4094-b388-80a849b6d50a" start_index="0" end="3e214dac-0691-4bfe-9b42-5c7409d5278a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a1d46b6c-a592-4ce1-8fdd-0c41986c5752" start_index="0" end="19c78f08-5b83-4094-b388-80a849b6d50a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>