<Workspace Version="0.9.0.3067" X="216" Y="52.8" zoom="1" Name="Sheet.GetViewports" Description="returns all of the viewports on a sheet" ID="727fb507-5633-40ca-9c02-684cff5c2bc4" Category="Hollandaise.Revit">
  <NamespaceResolutionMap>
    <ClassMap partialName="List.map" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="6bc97e94-799c-4cc0-9464-620d9173ed47" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
Sheet=UnwrapElement(IN[0])
doc = DocumentManager.Instance.CurrentDBDocument
#Assign your output to the OUT variable
views=Sheet.GetAllViewports()
viewports=[]
for view in views:
		viewports.append(doc.GetElement(view))
	
OUT = viewports</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Symbol guid="c4c6d7ad-bafb-4fe9-9f0e-0a03d5cba123" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Sheet" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="2a6afd70-1610-46ef-b4d5-81cbafaf721b" type="Dynamo.Nodes.Output" nickname="Output" x="449.8" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Viewports" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="6bc97e94-799c-4cc0-9464-620d9173ed47" start_index="0" end="2a6afd70-1610-46ef-b4d5-81cbafaf721b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c4c6d7ad-bafb-4fe9-9f0e-0a03d5cba123" start_index="0" end="6bc97e94-799c-4cc0-9464-620d9173ed47" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>