<Workspace Version="1.3.0.875" X="-235.730518507228" Y="-124.158514317253" zoom="1.00277440221292" ScaleFactor="1" Name="Connector(s) Information" Description="Gets the connector(s) information.  " ID="f5ecb4a7-329c-4b39-a079-e32886f22e32" Category="DynaFabrication2018.Parts">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="18d5d15e-fed3-47ff-af33-e03115b3d0b6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="15.9833693686279" y="363.709930881459" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Item(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="4a484af1-f9ec-482a-b855-7604fa9e8889" type="PythonNodeModels.PythonNode" nickname="Part Connector Name" x="940.562944556864" y="338.582584307961" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = []
ItmList = list()
Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	ConnName = Config.GetFabricationConnectorName(e)

	ItmList.append(ConnName)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="93d088a7-e354-4c35-a4b8-c14f954727f3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Count" x="551.566309067526" y="428.879429990597" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Count@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="8299b05a-979b-4a83-b99c-93fe91b99855" type="PythonNodeModels.PythonNode" nickname="Part ConnectorInfo / Id" x="754.833198337758" y="338.066186907792" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

Inpt = []
Inpt1 = []
ItmList = list()

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	ConnInfo = e.GetFabricationConnectorInfo()

	Inpt1.append(ConnInfo)

for n in Inpt1:
	ConnId = n.BodyConnectorId

	ItmList.append(ConnId)
	
OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ba474930-ea52-43db-b2ce-fe4ae5a946b4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="531.366061805222" y="328.962367128429" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="5e8c4aae-ae35-4f8d-9ea9-91bbcc60d75a" type="PythonNodeModels.PythonNode" nickname="Part Connector" x="374.18352671917" y="362.700687586146" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

Inpt = []
ItmList = list()

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	CM = e.ConnectorManager
	Conn = CM.Connectors
	ItmList.append(Conn)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e719750f-501b-4c3c-97e4-b0b53ce1c566" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="149.566631142436" y="361.96500585786" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f6b51aac-26ce-4654-862b-9dd6e4f35757" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Chop" x="1130.65331785495" y="332.713052821257" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c6a0f484-10d4-4976-9bfb-0f84d480227a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1392.65538373737" y="332.874156660874" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Connector Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f30e7909-b7a5-4c0a-b9ae-7955ef43fc98" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1390.77401303678" y="484.358305180263" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Connector Domain" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e0ea7841-d362-4fd3-a4a0-66ea2f8d9f11" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Chop" x="1128.77194715436" y="484.197201340646" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="022ed62f-e73c-4b24-b26c-dc8bb0df4994" type="PythonNodeModels.PythonNode" nickname="Part Connector Domain" x="938.681573856273" y="490.06673282735" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = []
ItmList = list()
Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	ConnName = Config.GetFabricationConnectorDomain(e)

	ItmList.append(ConnName)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6851809e-6f81-480a-b124-a8fbd0555985" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1386.78507994159" y="616.990330595447" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Connector Shape" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8685d356-b708-42d0-badf-6479f5bc853b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Chop" x="1124.78301405917" y="616.82922675583" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="fedc1096-6f39-48ba-968d-677cba296cfa" type="PythonNodeModels.PythonNode" nickname="Part Connector Shape" x="934.692640761079" y="622.698758242534" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = []
ItmList = list()
Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	ConnName = Config.GetFabricationConnectorShape(e)

	ItmList.append(ConnName)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8d810799-0c90-4ad7-92b1-73417137ef70" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1389.77677976299" y="742.641723094042" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Connector Group" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7b65d78f-7474-4610-bd8f-76668ac3b720" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Chop" x="1127.77471388057" y="742.480619254425" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="ea3c07ba-5c82-45a4-8308-41d93d19e251" type="PythonNodeModels.PythonNode" nickname="Part Connector Group" x="937.684340582474" y="748.350150741129" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = []
ItmList = list()
Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	ConnName = Config.GetFabricationConnectorGroup(e)

	ItmList.append(ConnName)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="18d5d15e-fed3-47ff-af33-e03115b3d0b6" start_index="0" end="e719750f-501b-4c3c-97e4-b0b53ce1c566" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a484af1-f9ec-482a-b855-7604fa9e8889" start_index="0" end="f6b51aac-26ce-4654-862b-9dd6e4f35757" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93d088a7-e354-4c35-a4b8-c14f954727f3" start_index="0" end="f6b51aac-26ce-4654-862b-9dd6e4f35757" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93d088a7-e354-4c35-a4b8-c14f954727f3" start_index="0" end="e0ea7841-d362-4fd3-a4a0-66ea2f8d9f11" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93d088a7-e354-4c35-a4b8-c14f954727f3" start_index="0" end="8685d356-b708-42d0-badf-6479f5bc853b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93d088a7-e354-4c35-a4b8-c14f954727f3" start_index="0" end="7b65d78f-7474-4610-bd8f-76668ac3b720" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8299b05a-979b-4a83-b99c-93fe91b99855" start_index="0" end="4a484af1-f9ec-482a-b855-7604fa9e8889" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8299b05a-979b-4a83-b99c-93fe91b99855" start_index="0" end="022ed62f-e73c-4b24-b26c-dc8bb0df4994" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8299b05a-979b-4a83-b99c-93fe91b99855" start_index="0" end="fedc1096-6f39-48ba-968d-677cba296cfa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8299b05a-979b-4a83-b99c-93fe91b99855" start_index="0" end="ea3c07ba-5c82-45a4-8308-41d93d19e251" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ba474930-ea52-43db-b2ce-fe4ae5a946b4" start_index="0" end="8299b05a-979b-4a83-b99c-93fe91b99855" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5e8c4aae-ae35-4f8d-9ea9-91bbcc60d75a" start_index="0" end="93d088a7-e354-4c35-a4b8-c14f954727f3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5e8c4aae-ae35-4f8d-9ea9-91bbcc60d75a" start_index="0" end="ba474930-ea52-43db-b2ce-fe4ae5a946b4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e719750f-501b-4c3c-97e4-b0b53ce1c566" start_index="0" end="5e8c4aae-ae35-4f8d-9ea9-91bbcc60d75a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f6b51aac-26ce-4654-862b-9dd6e4f35757" start_index="0" end="c6a0f484-10d4-4976-9bfb-0f84d480227a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e0ea7841-d362-4fd3-a4a0-66ea2f8d9f11" start_index="0" end="f30e7909-b7a5-4c0a-b9ae-7955ef43fc98" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="022ed62f-e73c-4b24-b26c-dc8bb0df4994" start_index="0" end="e0ea7841-d362-4fd3-a4a0-66ea2f8d9f11" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8685d356-b708-42d0-badf-6479f5bc853b" start_index="0" end="6851809e-6f81-480a-b124-a8fbd0555985" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fedc1096-6f39-48ba-968d-677cba296cfa" start_index="0" end="8685d356-b708-42d0-badf-6479f5bc853b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7b65d78f-7474-4610-bd8f-76668ac3b720" start_index="0" end="8d810799-0c90-4ad7-92b1-73417137ef70" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ea3c07ba-5c82-45a4-8308-41d93d19e251" start_index="0" end="7b65d78f-7474-4610-bd8f-76668ac3b720" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>