<Workspace Version="1.3.0.875" X="-170.804317533298" Y="-406.836046864587" zoom="0.948768827037605" ScaleFactor="1" Name="Get Fabrication Material(s) Information" Description="Get fabrication material information" ID="49c017cc-594a-4912-ac4a-0c9b5ddd0674" Category="DynaFabrication2018.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="2d3aa910-22d2-4cb1-a449-b3abea584efd" type="PythonNodeModels.PythonNode" nickname="Fabrication Material Abbreviation" x="561.254037716533" y="867.895199403267" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

SpecID = UnwrapElement(IN[0])

doc = DocumentManager.Instance.CurrentDBDocument
elementlist = list()
config = FabricationConfiguration.GetFabricationConfiguration(doc)

for item in SpecID:
	for itemId in item:
		MatAbrn = config.GetMaterialAbbreviation(itemId)
		elementlist.append(MatAbrn)

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="527e70bc-256e-4307-bc40-51c1e8d22525" type="PythonNodeModels.PythonNode" nickname="Fabrication Material Group" x="565.876163598062" y="787.027507654724" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

SpecID = UnwrapElement(IN[0])

doc = DocumentManager.Instance.CurrentDBDocument
elementlist = list()
config = FabricationConfiguration.GetFabricationConfiguration(doc)

for item in SpecID:
	for itemId in item:
		MatGrp = config.GetMaterialGroup(itemId)
		elementlist.append(MatGrp)

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="b87c2f2e-a5c8-46fe-9223-0eb290d6f549" type="PythonNodeModels.PythonNode" nickname="Fabrication Material Name" x="568.317819597779" y="708.896439948402" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

SpecID = UnwrapElement(IN[0])

doc = DocumentManager.Instance.CurrentDBDocument
elementlist = list()
config = FabricationConfiguration.GetFabricationConfiguration(doc)

for item in SpecID:
	for itemId in item:
		MatName = config.GetMaterialName(itemId)
		elementlist.append(MatName)

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="0898d478-894b-42b9-b7a1-d8ae35f7baf6" type="PythonNodeModels.PythonNode" nickname="Fabrication All Material ID's" x="334.4" y="784.44648778929" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
elementlist = list()
config = FabricationConfiguration.GetFabricationConfiguration(doc)
allInsulSpec = config.GetAllMaterials(None)

elementlist.append(allInsulSpec)

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d9eb8ec4-0d39-45c9-86a1-51be0f22cb91" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="808.411967546239" y="706.090073783264" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Material Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="660a6b2a-890a-4fb2-a659-195afbfdf575" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="809.363380672166" y="787.15228948231" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Material Group" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4ef48a43-e295-418c-8d85-2f5025e11792" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="809.986434461771" y="865.3163851765" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Material Abbreviation" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b856fe2b-a2cf-4010-9236-05a3073dc899" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="808.431799655318" y="950.96745474722" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Material Indentifier" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2d3aa910-22d2-4cb1-a449-b3abea584efd" start_index="0" end="4ef48a43-e295-418c-8d85-2f5025e11792" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="527e70bc-256e-4307-bc40-51c1e8d22525" start_index="0" end="660a6b2a-890a-4fb2-a659-195afbfdf575" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b87c2f2e-a5c8-46fe-9223-0eb290d6f549" start_index="0" end="d9eb8ec4-0d39-45c9-86a1-51be0f22cb91" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0898d478-894b-42b9-b7a1-d8ae35f7baf6" start_index="0" end="b87c2f2e-a5c8-46fe-9223-0eb290d6f549" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0898d478-894b-42b9-b7a1-d8ae35f7baf6" start_index="0" end="527e70bc-256e-4307-bc40-51c1e8d22525" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0898d478-894b-42b9-b7a1-d8ae35f7baf6" start_index="0" end="2d3aa910-22d2-4cb1-a449-b3abea584efd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0898d478-894b-42b9-b7a1-d8ae35f7baf6" start_index="0" end="b856fe2b-a2cf-4010-9236-05a3073dc899" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>