<Workspace Version="1.3.0.875" X="-168.675681345083" Y="-63.0915489574187" zoom="0.915562285281224" ScaleFactor="1" Name="Get Fabrication Insulation Specification(s)" Description="Sets fabrication part bases of connector" ID="2c119e3b-b907-45fd-9757-18ebe70d0a48" Category="DynaFabrication2018.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="55ebfdd6-3109-4037-8eee-03a4b54b2b4c" type="PythonNodeModels.PythonNode" nickname="Fabrication Insulation Specification Abbreviation" x="760.658631293695" y="501.45384476771" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	InsSpecAbrn = Config.GetInsulationSpecificationAbbreviation(Item)
	ItmList.append(InsSpecAbrn)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="afd46530-0446-400d-8c69-4b3d71ef93ab" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1110.90938332836" y="503.702441982409" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Insul Spec Abbreviation" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="e052bd37-018c-4d29-acbb-558709564c7b" type="PythonNodeModels.PythonNode" nickname="Fabrication Insulation Specification Name" x="763.644860576607" y="355.39717545796" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	InsSpecName = Config.GetInsulationSpecificationName(Item)
	ItmList.append(InsSpecName)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="d74b1631-309e-40b2-a2e8-1df37b5f784b" type="PythonNodeModels.PythonNode" nickname="Fabrication Insulation Specification Group" x="765.435310849879" y="432.369394372365" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = UnwrapElement(IN[0])
ItmList = list()

Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for Item in Inpt:
	InsSpecGrp = Config.GetInsulationSpecificationGroup(Item)
	ItmList.append(InsSpecGrp)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="cbd78db4-2691-4048-a064-942dd7f0b27f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1112.97917023915" y="432.164716755285" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Insul Spec Group" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f4778ee6-cad4-4288-b45a-9e6b3e0b91d5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1113.60888301352" y="346.769376211201" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Insul Spec Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="c2e6d918-30b8-48a4-812b-1f99c3e19d7a" type="PythonNodeModels.PythonNode" nickname="Fabrication All Insulation Specification ID's" x="260.185525341575" y="411.821330710774" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Doc = DocumentManager.Instance.CurrentDBDocument

ItmList = list()

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)
AllInsSpecs = Config.GetAllInsulationSpecifications(None)
ItmList.append(AllInsSpecs)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3fa92c03-5a7e-48ee-8c1a-c509d6837c69" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="559.488831160157" y="409.190390888475" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="55ebfdd6-3109-4037-8eee-03a4b54b2b4c" start_index="0" end="afd46530-0446-400d-8c69-4b3d71ef93ab" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e052bd37-018c-4d29-acbb-558709564c7b" start_index="0" end="f4778ee6-cad4-4288-b45a-9e6b3e0b91d5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d74b1631-309e-40b2-a2e8-1df37b5f784b" start_index="0" end="cbd78db4-2691-4048-a064-942dd7f0b27f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2e6d918-30b8-48a4-812b-1f99c3e19d7a" start_index="0" end="3fa92c03-5a7e-48ee-8c1a-c509d6837c69" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fa92c03-5a7e-48ee-8c1a-c509d6837c69" start_index="0" end="e052bd37-018c-4d29-acbb-558709564c7b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fa92c03-5a7e-48ee-8c1a-c509d6837c69" start_index="0" end="d74b1631-309e-40b2-a2e8-1df37b5f784b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fa92c03-5a7e-48ee-8c1a-c509d6837c69" start_index="0" end="55ebfdd6-3109-4037-8eee-03a4b54b2b4c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>