<Workspace Version="1.3.0.875" X="-1403.01535000135" Y="-277.315714427813" zoom="1.92101320430154" ScaleFactor="1" Name="Get All Part Statuses" Description="Gets Fabrication part statuses from database" ID="3d1f3529-d673-42d5-a007-bafe4982ac6f" Category="DynaFabrication2018.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="58cd8c99-3027-4852-923e-7b4c5ec31a26" type="PythonNodeModels.PythonNode" nickname="Part Statuses" x="1134.77980735008" y="346.479441370959" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = []
ItmList = list()
Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	STName = Config.GetPartStatusDescription(e)
	ItmList.append(STName)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8a0579f0-9427-4e6e-bc74-76a153c8f0f3" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="882.016109984851" y="348.337134343691" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="12fb9bf6-6db9-42ab-8393-309d8e4d00e0" type="PythonNodeModels.PythonNode" nickname="Fabrication Statuses All" x="678.177422897618" y="346.434706089565" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Doc = DocumentManager.Instance.CurrentDBDocument

ItmList = list()

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)
AllStatuses = Config.GetAllPartStatuses()
ItmList.append(AllStatuses)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="981ce17c-708d-4e33-bc94-d5b36dcfab16" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1305.02210196821" y="344.227230053407" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Status Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="58cd8c99-3027-4852-923e-7b4c5ec31a26" start_index="0" end="981ce17c-708d-4e33-bc94-d5b36dcfab16" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8a0579f0-9427-4e6e-bc74-76a153c8f0f3" start_index="0" end="58cd8c99-3027-4852-923e-7b4c5ec31a26" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="12fb9bf6-6db9-42ab-8393-309d8e4d00e0" start_index="0" end="8a0579f0-9427-4e6e-bc74-76a153c8f0f3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>