<Workspace Version="1.3.0.875" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Get All Fabrication Dampers" Description="" ID="62dce836-bb8e-490f-86ee-e039d36e3ad3" Category="DynaFabrication2018.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f93ed7ff-655b-4942-a9eb-1607c9481a92" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="830.45544595845" y="395.337134343691" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="ec30f432-ec17-4e0f-8c82-92678a8cd78b" type="PythonNodeModels.PythonNode" nickname="Damper Name" x="1083.21914332368" y="394" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FabricationPart
from Autodesk.Revit.DB import FabricationConfiguration

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Inpt = []
ItmList = list()
Doc = DocumentManager.Instance.CurrentDBDocument

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)

for i in IN[0]:
	Inpt.append(UnwrapElement(i))
	
for e in Inpt:
	STName = Config.GetDamperName(e)
	ItmList.append(STName)

OUT = ItmList

</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="dcf6d720-0dac-4008-b3c3-f16f101b2e10" type="PythonNodeModels.PythonNode" nickname="Fabrication Dampers All" x="611" y="397.078616492849" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Doc = DocumentManager.Instance.CurrentDBDocument

ItmList = list()

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)
AllDampers = Config.GetAllDampers()
ItmList.append(AllDampers)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="91b82644-e2c9-4729-a0fa-f7a0fb9291f0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1260" y="390" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Damper Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f93ed7ff-655b-4942-a9eb-1607c9481a92" start_index="0" end="ec30f432-ec17-4e0f-8c82-92678a8cd78b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ec30f432-ec17-4e0f-8c82-92678a8cd78b" start_index="0" end="91b82644-e2c9-4729-a0fa-f7a0fb9291f0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dcf6d720-0dac-4008-b3c3-f16f101b2e10" start_index="0" end="f93ed7ff-655b-4942-a9eb-1607c9481a92" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>