<Workspace Version="1.3.0.875" X="-19.1316965442765" Y="-37.9989" zoom="1.33823125" ScaleFactor="1" Name="Get All Fabrication Configuration(s)" Description="Gets all the fabrication configurations in the current document." ID="48bdf4da-fd7f-417b-a246-2f791c3d0715" Category="DynaFabrication2018.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="63c8edb5-ff2e-43ee-b5a0-37f00f9cbcfb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="468.348675042554" y="267.927783409696" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="021b77d6-dafa-4c69-9339-513ba4673cc6" type="PythonNodeModels.PythonNode" nickname="Get All Fabrication Configuration(s)" x="206.865879869417" y="274.004213762614" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Doc = DocumentManager.Instance.CurrentDBDocument

ItmList = list()

ConfigName = FabricationConfiguration.GetFabricationConfiguration(Doc)
ConfigInfo = ConfigName.GetFabricationConfigurationInfo()
test = ConfigInfo.GetAllFabricationConfigurations()
ItmList.append(test)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6ee7fdae-9e06-4480-b32c-cd3f8d91b07c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="849.525500544095" y="193.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Config Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="1ff66bd2-fe3b-4a57-9693-ac5e04caef8a" type="PythonNodeModels.PythonNode" nickname="Config Name" x="682.316788781867" y="194.155461011803" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

faminsts = UnwrapElement(IN[0])
elementlist = list()
for item in faminsts:
	try:
		elementlist.append(item.Name)
	except:
		elementlist.append(list())
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="096ae9c8-2468-4d8b-99a3-922bb87ac1a9" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="798.4" y="315.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Config Info" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="63c8edb5-ff2e-43ee-b5a0-37f00f9cbcfb" start_index="0" end="1ff66bd2-fe3b-4a57-9693-ac5e04caef8a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="63c8edb5-ff2e-43ee-b5a0-37f00f9cbcfb" start_index="0" end="096ae9c8-2468-4d8b-99a3-922bb87ac1a9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="021b77d6-dafa-4c69-9339-513ba4673cc6" start_index="0" end="63c8edb5-ff2e-43ee-b5a0-37f00f9cbcfb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1ff66bd2-fe3b-4a57-9693-ac5e04caef8a" start_index="0" end="6ee7fdae-9e06-4480-b32c-cd3f8d91b07c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>