<Workspace Version="1.3.0.875" X="-193.806" Y="-103.904" zoom="1.1575" ScaleFactor="1" Name="Get All Fabrication Service(s)" Description="Get all fabrication services in loaded configuration" ID="e88551a3-b9be-46ec-9da1-d52a846303c4" Category="DynaFabrication2018.Configuration">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="62481b6f-ffd7-4d90-9619-0dbdc20542dd" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="748.095785164536" y="438.725459727786" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Service(s) ID" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="3730daaa-7e5e-43a2-9238-3f6a0bc84658" type="PythonNodeModels.PythonNode" nickname="ID" x="602.307578602081" y="440.608639617524" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

Inpt = UnwrapElement(IN[0])
ItmList = list()

for Item in Inpt:
	try:
		ItmList.append(Item.ServiceId)
	except:
		ItmList.append(list())
		
OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="7fa837f2-267c-48b9-879a-2d352216a89a" type="PythonNodeModels.PythonNode" nickname="Fabrication Services All" x="208.998704103672" y="393.698974829726" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import FabricationConfiguration
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

Doc = DocumentManager.Instance.CurrentDBDocument

ItmList = list()

Config = FabricationConfiguration.GetFabricationConfiguration(Doc)
AllServices = Config.GetAllServices()
ItmList.append(AllServices)

OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ee7cf144-625d-4cde-a863-9431b0a67bcc" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="410.884035712606" y="328.367540850005" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="92a0acb4-81c8-4460-a19e-bfc3b4dfc7a5" type="PythonNodeModels.PythonNode" nickname="Name" x="603.214887763953" y="331.103239740821" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, Nathan Chapman
# nchapman@generalheating.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

Inpt = UnwrapElement(IN[0])
ItmList = list()

for Item in Inpt:
	try:
		ItmList.append(Item.Name)
	except:
		ItmList.append(list())
		
OUT = ItmList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="728f448f-d321-466d-ac76-c1ce23938f79" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="753.853353019788" y="331.189871667771" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Service(s) Name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1e75f83d-83be-4801-b42b-08935478c125" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="411.76669670366" y="435.423732333558" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3730daaa-7e5e-43a2-9238-3f6a0bc84658" start_index="0" end="62481b6f-ffd7-4d90-9619-0dbdc20542dd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7fa837f2-267c-48b9-879a-2d352216a89a" start_index="0" end="ee7cf144-625d-4cde-a863-9431b0a67bcc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7fa837f2-267c-48b9-879a-2d352216a89a" start_index="0" end="1e75f83d-83be-4801-b42b-08935478c125" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ee7cf144-625d-4cde-a863-9431b0a67bcc" start_index="0" end="92a0acb4-81c8-4460-a19e-bfc3b4dfc7a5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="92a0acb4-81c8-4460-a19e-bfc3b4dfc7a5" start_index="0" end="728f448f-d321-466d-ac76-c1ce23938f79" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1e75f83d-83be-4801-b42b-08935478c125" start_index="0" end="3730daaa-7e5e-43a2-9238-3f6a0bc84658" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>