<Workspace Version="1.3.3.4111" X="-184.930933089104" Y="-168.532895484508" zoom="1.0669527078898" ScaleFactor="1" Name="❄_Pick Points on Workplane" Description="(Sastrugi_Selection) This node allows users to pick points in Revit on the Active Workplane." ID="dfe47202-e657-4fa6-ad37-ee30ce786e8d" Category="Sastrugi.Selection">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="1d0edd98-6294-43db-8c20-9be5c43d73bc" type="PythonNodeModels.PythonNode" nickname="Python Script" x="386.364471648959" y="313.010599340348" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitAPIUI")
from  Autodesk.Revit.UI import TaskDialog

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB.Events import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

x=True
dypoint=[]
rpoint=[]
counter=0
msg = 'Pick Points on current Workplane in order, hit ESC when finished.'

TaskDialog.Show("Sastrugi", msg)

while x == True:
	try:
		pt=uidoc.Selection.PickPoint(UnwrapElement(IN[0]))
		rp=Point.ByCoordinates(pt.X*304.8,pt.Y*304.8,pt.Z*304.8)
		counter=+1
		dypoint.append(pt)
		rpoint.append(rp)
	except:
		x=False
OUT=(dypoint,rpoint)

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8b2f3b44-4294-4836-b9fa-7dc4a0cc7dd8" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="162" y="299" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="//String Input Req&#xA;&quot;Run&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="80393ac5-196b-49a4-b6cc-8e3f7cb50112" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="165" y="388" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Reset: bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="2373adae-4a20-46ce-b471-a6b8299ab8f5" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="534.371192182462" y="318.29889965319" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0];&#xA;a[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="54ec629f-809a-4fd8-b8f4-219419396800" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="654.572012239629" y="311.800845733593" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="DynamoPoints" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f3f665ae-7b87-415b-8545-3422c60cc9b0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="660.345223125425" y="377.471119559531" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="RevitPoints" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1d0edd98-6294-43db-8c20-9be5c43d73bc" start_index="0" end="2373adae-4a20-46ce-b471-a6b8299ab8f5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8b2f3b44-4294-4836-b9fa-7dc4a0cc7dd8" start_index="0" end="1d0edd98-6294-43db-8c20-9be5c43d73bc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80393ac5-196b-49a4-b6cc-8e3f7cb50112" start_index="0" end="1d0edd98-6294-43db-8c20-9be5c43d73bc" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2373adae-4a20-46ce-b471-a6b8299ab8f5" start_index="0" end="54ec629f-809a-4fd8-b8f4-219419396800" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2373adae-4a20-46ce-b471-a6b8299ab8f5" start_index="1" end="f3f665ae-7b87-415b-8545-3422c60cc9b0" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>