<Workspace Version="1.3.4.6666" X="-638.813374975672" Y="41.8153252580242" zoom="0.910063803931439" ScaleFactor="1" Name="â„_Pointcloud Graphics Override Settings By Elevation" Description="(Sastrugi_Pointcloud_Graphics) Override settings for Pointcloud by Elevation." ID="0ba8f433-2bc5-4d91-936a-3dd4eb6ac950" Category="Sastrugi.Pointcloud.Graphics">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="01812ee5-d331-419d-9eb2-c08d46c42aca" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1419.19860965536" y="188" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

pt_cloud_settings = DB.PointClouds.PointCloudOverrideSettings()

pt_cloud_settings.ColorMode = DB.PointCloudColorMode.Elevation

OUT = pt_cloud_settings.ColorMode

	</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="ac0bc967-d5f3-4385-b17a-a85c7589aae1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1424.690353349" y="310.661442503065" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument

color1 = IN[0]
color2 = IN[1]

r1 = color1.Red
g1 = color1.Green
b1 = color1.Blue

r2 = color2.Red
g2 = color2.Green
b2 = color2.Blue

c1 = Autodesk.Revit.DB.Color(r1,g1,b1)
c2 = Autodesk.Revit.DB.Color(r2,g2,b2)

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

pc_col_set = DB.PointClouds.PointCloudColorSettings(c1,c2)

OUT=pc_col_set</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="e861fdf7-c41c-45e9-91ab-c195077ff88c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1862.13871808689" y="297.863427892231" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]	
	
cmode = tolist(IN[0])
csettings = tolist(IN[1])

pcOSsettings = []

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

for cm,cs in zip(cmode, csettings):
	pc_os = DB.PointClouds.PointCloudOverrideSettings()
	pc_os.ColorMode = cm
	pc_os.SetModeOverride(cm,cs)
	pcOSsettings.append(pc_os)

OUT = pcOSsettings
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="be0316c3-30f9-451d-88fb-ed38764ea4f2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1612.50576484152" y="306.027555284581" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="col_mode;&#xA;col_settings;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="710d533c-2c35-4164-bcb3-b17177f997bc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="883.245967268088" y="294.134854489356" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MinColor: DSCore.Color = DSCore.Color.ByARGB(255,0,0,255);" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3caefc02-49a9-474d-826f-bdd1dc2fb3d0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="885.443615379528" y="363.360769999721" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MaxColor: DSCore.Color = DSCore.Color.ByARGB(255,255,0,0);" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="bf1bcc21-1d2f-4ed9-ac62-4522c82a5d12" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="2032.61592955131" y="310.617215325158" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OverrideSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="01812ee5-d331-419d-9eb2-c08d46c42aca" start_index="0" end="be0316c3-30f9-451d-88fb-ed38764ea4f2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ac0bc967-d5f3-4385-b17a-a85c7589aae1" start_index="0" end="be0316c3-30f9-451d-88fb-ed38764ea4f2" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e861fdf7-c41c-45e9-91ab-c195077ff88c" start_index="0" end="bf1bcc21-1d2f-4ed9-ac62-4522c82a5d12" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="be0316c3-30f9-451d-88fb-ed38764ea4f2" start_index="0" end="e861fdf7-c41c-45e9-91ab-c195077ff88c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="be0316c3-30f9-451d-88fb-ed38764ea4f2" start_index="1" end="e861fdf7-c41c-45e9-91ab-c195077ff88c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="710d533c-2c35-4164-bcb3-b17177f997bc" start_index="0" end="ac0bc967-d5f3-4385-b17a-a85c7589aae1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3caefc02-49a9-474d-826f-bdd1dc2fb3d0" start_index="0" end="ac0bc967-d5f3-4385-b17a-a85c7589aae1" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="1cdf56ec-97f7-40de-b4ce-42b0913b6e96" annotationText="Elevation" left="873.245967268088" top="142" width="1331.36996228322" height="289.360769999721" fontSize="30" InitialTop="188" InitialHeight="240.759083348515" TextblockHeight="36" backgrouund="#FFFFC999">
      <Models ModelGuid="ac0bc967-d5f3-4385-b17a-a85c7589aae1" />
      <Models ModelGuid="01812ee5-d331-419d-9eb2-c08d46c42aca" />
      <Models ModelGuid="e861fdf7-c41c-45e9-91ab-c195077ff88c" />
      <Models ModelGuid="be0316c3-30f9-451d-88fb-ed38764ea4f2" />
      <Models ModelGuid="bf1bcc21-1d2f-4ed9-ac62-4522c82a5d12" />
      <Models ModelGuid="710d533c-2c35-4164-bcb3-b17177f997bc" />
      <Models ModelGuid="3caefc02-49a9-474d-826f-bdd1dc2fb3d0" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-995.536804199219" eyeY="972.672424316406" eyeZ="716.995056152344" lookX="-29.082202911377" lookY="-629.75048828125" lookZ="-919.973693847656" upX="-0.0118361487984657" upY="0.927183866500854" upZ="-0.374419569969177" />
  </Cameras>
</Workspace>