<Workspace Version="1.3.4.6666" X="-152.244241675775" Y="-268.993142750725" zoom="0.867977507649016" ScaleFactor="1" Name="â„_Pointcloud Graphics Override Settings No-Override" Description="(Sastrugi_Pointcloud_Graphics) Override settings for Pointcloud by No-Override." ID="d9577dd4-4465-4a7d-bc72-233c75275873" Category="Sastrugi.Pointcloud.Graphics">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="dda171e6-8563-428e-8601-c2c1f51cac66" type="PythonNodeModels.PythonNode" nickname="Python Script" x="753.104941078223" y="711.164658586314" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]	
	
cmode = tolist(IN[0])

pcOSsettings = []

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

for cm in cmode:
	pc_os = DB.PointClouds.PointCloudOverrideSettings()
	pc_os.ColorMode = cm
	pcOSsettings.append(pc_os)

OUT = pcOSsettings
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="ce0f32a7-55f9-484a-a84a-cfc274d7ec02" type="PythonNodeModels.PythonNode" nickname="Python Script" x="575.216662694643" y="711.706727599724" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

pt_cloud_settings = DB.PointClouds.PointCloudOverrideSettings()

pt_cloud_settings.ColorMode = DB.PointCloudColorMode.NoOverride

OUT = pt_cloud_settings.ColorMode

	</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="358de8a0-448a-453b-ad9c-f87ff4fa74f6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="918.76979574031" y="712.510403464798" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OverrideSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="dda171e6-8563-428e-8601-c2c1f51cac66" start_index="0" end="358de8a0-448a-453b-ad9c-f87ff4fa74f6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ce0f32a7-55f9-484a-a84a-cfc274d7ec02" start_index="0" end="dda171e6-8563-428e-8601-c2c1f51cac66" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="0557a772-ce0a-4947-bf7d-aedf1904bc60" annotationText="No Override" left="565.216662694643" top="665.164658586314" width="525.553133045667" height="115.345744878484" fontSize="30" InitialTop="711.164658586314" InitialHeight="98.54206901341" TextblockHeight="36" backgrouund="#FFFFC999">
      <Models ModelGuid="ce0f32a7-55f9-484a-a84a-cfc274d7ec02" />
      <Models ModelGuid="dda171e6-8563-428e-8601-c2c1f51cac66" />
      <Models ModelGuid="358de8a0-448a-453b-ad9c-f87ff4fa74f6" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-995.536804199219" eyeY="972.672424316406" eyeZ="716.995056152344" lookX="-29.082202911377" lookY="-629.75048828125" lookZ="-919.973693847656" upX="-0.0118361487984657" upY="0.927183866500854" upZ="-0.374419569969177" />
  </Cameras>
</Workspace>