<Workspace Version="1.3.4.6666" X="-274.106727231683" Y="-45.7845654477187" zoom="0.646865613092414" ScaleFactor="1" Name="❄_Pointcloud Get Graphics Override Settings" Description="(Sastrugi_Pointcloud_Graphics) Get the current OverrideSettings for a Pointcloud Instance." ID="93a41009-9a6d-424b-9085-a5398141e106" Category="Sastrugi.Pointcloud.Graphics">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="da3ad326-42a8-4c19-b1d1-1a8e52d3dd1e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="504" y="438" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="PointcloudInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="44efa0bb-bbbd-4d0f-bf75-2bfb24ebff75" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1009.37177251903" y="389.363680195361" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="InstanceOverrideSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="833943d2-553d-40ee-8147-981e09c9ac05" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1012.4215800484" y="453.578516381396" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ScanOverrideSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="076f9030-0cd5-4166-b3a8-b6c1d4e39549" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1008.43005809125" y="516.297495159063" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="RegionOverrideSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="800e03e2-7b83-491c-91ef-76cd79e8a3ed" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="590.072734703468" y="507.17131178685" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="a307c300-9fcb-4b41-87b7-c79a9370d422" type="PythonNodeModels.PythonNode" nickname="Python Script" x="784.064432586967" y="298.448915053932" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]	
	
cloud = tolist(UnwrapElement(IN[0]))
views = tolist(UnwrapElement(IN[1]))

pc0a = []

for c in cloud:
	for v in views:
		pc0 = []
		pt_overrides = v.GetPointCloudOverrides()
		pp=pt_overrides.GetPointCloudScanOverrideSettings(c.Id)
		ppMode = pp.ColorMode
		pc0.append(pt_overrides)
		pc0.append(pp)
		pc0.append(ppMode)
	pc0a.append(pc0)
   
OUT = pc0a</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="1fb65063-0109-43fe-9973-35ad7460fb6c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="777.760816232794" y="440.253059806772" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]	
	
cloud = tolist(UnwrapElement(IN[0]))
views = tolist(UnwrapElement(IN[1]))

scans = []

for c in cloud:
	scans.append(c.GetScans())

for v in views:
	pc1b = []
	for sca, c in zip(scans,cloud):
			pc1a = []
			for s in sca:
				pc1 = []
				pt_overrides = v.GetPointCloudOverrides()
				pp=pt_overrides.GetPointCloudScanOverrideSettings(c.Id,s,doc)
				ppMode = pp.ColorMode
				pc1.append(pt_overrides)
				pc1.append(pp)
				pc1.append(ppMode)
				pc1a.append(pc1)
			pc1b.append(pc1a)
   
OUT = pc1b</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="5a2a2c30-e46e-40cf-9a0f-2a26ddf823af" type="PythonNodeModels.PythonNode" nickname="Python Script" x="782.628362476681" y="593.201848951502" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.AddReference('DSCoreNodes') 
import DSCore
from DSCore import *

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]	
	
cloud = tolist(UnwrapElement(IN[0]))
views = tolist(UnwrapElement(IN[1]))

regions = []

for c in cloud:
	regions.append(c.GetRegions())

for v in views:
	pc1b = []
	for reg, c in zip(regions,cloud):
			pc1a = []
			for r in reg:
				pc1 = []
				pt_overrides = v.GetPointCloudOverrides()
				pp=pt_overrides.GetPointCloudRegionOverrideSettings(c.Id,r,doc)
				ppMode = pp.ColorMode
				pc1.append(pt_overrides)
				pc1.append(pp)
				pc1.append(ppMode)
				pc1a.append(pc1)
			pc1b.append(pc1a)
   
OUT = pc1b</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="da3ad326-42a8-4c19-b1d1-1a8e52d3dd1e" start_index="0" end="a307c300-9fcb-4b41-87b7-c79a9370d422" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="da3ad326-42a8-4c19-b1d1-1a8e52d3dd1e" start_index="0" end="1fb65063-0109-43fe-9973-35ad7460fb6c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="da3ad326-42a8-4c19-b1d1-1a8e52d3dd1e" start_index="0" end="5a2a2c30-e46e-40cf-9a0f-2a26ddf823af" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="800e03e2-7b83-491c-91ef-76cd79e8a3ed" start_index="0" end="a307c300-9fcb-4b41-87b7-c79a9370d422" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="800e03e2-7b83-491c-91ef-76cd79e8a3ed" start_index="0" end="1fb65063-0109-43fe-9973-35ad7460fb6c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="800e03e2-7b83-491c-91ef-76cd79e8a3ed" start_index="0" end="5a2a2c30-e46e-40cf-9a0f-2a26ddf823af" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a307c300-9fcb-4b41-87b7-c79a9370d422" start_index="0" end="44efa0bb-bbbd-4d0f-bf75-2bfb24ebff75" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1fb65063-0109-43fe-9973-35ad7460fb6c" start_index="0" end="833943d2-553d-40ee-8147-981e09c9ac05" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a2a2c30-e46e-40cf-9a0f-2a26ddf823af" start_index="0" end="076f9030-0cd5-4166-b3a8-b6c1d4e39549" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-995.536804199219" eyeY="972.672424316406" eyeZ="716.995056152344" lookX="-29.082202911377" lookY="-629.75048828125" lookZ="-919.973693847656" upX="-0.0118361487984657" upY="0.927183866500854" upZ="-0.374419569969177" />
  </Cameras>
</Workspace>