<Workspace Version="1.3.4.6666" X="-593.006860597019" Y="-321.757757456752" zoom="1.62766375666706" ScaleFactor="1" Name="â„_Pointcloud Graphics Override Settings By Normals" Description="(Sastrugi_Pointcloud_Graphics) Override settings for Pointcloud by Normals." ID="866d569f-bb0b-4479-9c53-28f66ab10fa5" Category="Sastrugi.Pointcloud.Graphics">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="1f1bb86b-aa9b-4cda-ba75-3d87f912369a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="765.840519056585" y="424.664312481829" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]	
	
cmode = tolist(IN[0])

pcOSsettings = []

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

for cm in cmode:
	pc_os = DB.PointClouds.PointCloudOverrideSettings()
	pc_os.ColorMode = cm
	pcOSsettings.append(pc_os)

OUT = pcOSsettings
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="77116446-105a-4dcb-927b-a58f766fcf8b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="591.928112468242" y="424.438609840464" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

pt_cloud_settings = DB.PointClouds.PointCloudOverrideSettings()

pt_cloud_settings.ColorMode = DB.PointCloudColorMode.Normals

OUT = pt_cloud_settings.ColorMode

	</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="922329f4-0ef0-409f-a273-1728a39f2681" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="931.472281393184" y="424.150606533789" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OverrideSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1f1bb86b-aa9b-4cda-ba75-3d87f912369a" start_index="0" end="922329f4-0ef0-409f-a273-1728a39f2681" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="77116446-105a-4dcb-927b-a58f766fcf8b" start_index="0" end="1f1bb86b-aa9b-4cda-ba75-3d87f912369a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="2a1d6346-5c5a-443d-ba7d-53d6386cd587" annotationText="Normals" left="581.928112468242" top="378.150606533789" width="521.544168924942" height="114.51370594804" fontSize="30" InitialTop="424.150606533789" InitialHeight="101.297590173124" TextblockHeight="36" backgrouund="#FFFFC999">
      <Models ModelGuid="77116446-105a-4dcb-927b-a58f766fcf8b" />
      <Models ModelGuid="1f1bb86b-aa9b-4cda-ba75-3d87f912369a" />
      <Models ModelGuid="922329f4-0ef0-409f-a273-1728a39f2681" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-995.536804199219" eyeY="972.672424316406" eyeZ="716.995056152344" lookX="-29.082202911377" lookY="-629.75048828125" lookZ="-919.973693847656" upX="-0.0118361487984657" upY="0.927183866500854" upZ="-0.374419569969177" />
  </Cameras>
</Workspace>