<Workspace Version="1.3.4.6666" X="90" Y="7" zoom="1" ScaleFactor="1" Name="â„_Pointcloud Graphics Override Settings Visibility Show" Description="(Sastrugi_Pointcloud_Graphics) Override settings to Show Scans/Regions." ID="06c2068c-b793-43c5-ae09-272b2a856283" Category="Sastrugi.Pointcloud.Graphics">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="629e8d1f-8de3-417e-9125-ade4e158542f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="294" y="408.391691718136" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]	
	
cmode = tolist(IN[0])

pcOSsettings = []

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

for cm in cmode:
	pc_os = DB.PointClouds.PointCloudOverrideSettings()
	pc_os.Visible = True
	pcOSsettings.append(pc_os)

OUT = pcOSsettings
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="170f1d40-2f0f-468a-b4b4-03db8e162f6d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="469" y="406" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OverrideSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="629e8d1f-8de3-417e-9125-ade4e158542f" start_index="0" end="170f1d40-2f0f-468a-b4b4-03db8e162f6d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="5328963a-403e-4c16-912b-da169fa304c1" annotationText="Show Scan/Region Setting" left="284" top="360" width="357" height="116.391691718136" fontSize="30" InitialTop="406" InitialHeight="99.345744878484" TextblockHeight="36" backgrouund="#FFFFC999">
      <Models ModelGuid="629e8d1f-8de3-417e-9125-ade4e158542f" />
      <Models ModelGuid="170f1d40-2f0f-468a-b4b4-03db8e162f6d" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-995.536804199219" eyeY="972.672424316406" eyeZ="716.995056152344" lookX="-29.082202911377" lookY="-629.75048828125" lookZ="-919.973693847656" upX="-0.0118361487984657" upY="0.927183866500854" upZ="-0.374419569969177" />
  </Cameras>
</Workspace>