<Workspace Version="1.3.4.6666" X="-532.6379125" Y="-311.95835" zoom="0.70823125" ScaleFactor="1" Name="❄_Pointcloud Graphics Override Settings By Intensity" Description="(Sastrugi_Pointcloud_Graphics) Override settings for Pointcloud by Intensity." ID="63774f34-8eb8-4e91-b631-089ea96ffce1" Category="Sastrugi.Pointcloud.Graphics">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="636b88b1-cf47-498e-a892-92e4005e4d88" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1629.20298154599" y="710.92231168571" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

pt_cloud_settings = DB.PointClouds.PointCloudOverrideSettings()

pt_cloud_settings.ColorMode = DB.PointCloudColorMode.FixedColor

OUT = pt_cloud_settings.ColorMode

	</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="b53e7c95-ab63-4c0f-b75b-45a37f68c19d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1628.11510488084" y="851.681248293812" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument

color1 = IN[0]
color2 = IN[1]

r1 = color1.Red
g1 = color1.Green
b1 = color1.Blue

r2 = color2.Red
g2 = color2.Green
b2 = color2.Blue

c1 = Autodesk.Revit.DB.Color(r1,g1,b1)
c2 = Autodesk.Revit.DB.Color(r2,g2,b2)

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

pc_col_set = DB.PointClouds.PointCloudColorSettings(c1,c2)

OUT=pc_col_set</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e9122e9e-7b22-4591-a952-2619607e8e98" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1816.98678294176" y="852.847214345485" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="col_mode;&#xA;col_settings;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="e30d3f3b-5b93-478b-81fc-9588d701a831" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2087.54520843469" y="846.053901906319" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Python coding credit to Dynamo Forum user - @Ewan_Opie 2019
# Sastrugi Package https://sites.google.com/view/sastrugi/home

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

from Autodesk.Revit import DB

clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]	
	
cmode = tolist(IN[0])
csettings = tolist(IN[1])

pcOSsettings = []

pts = DB.FilteredElementCollector(doc).OfClass(DB.PointCloudInstance).WhereElementIsNotElementType().ToElements()

for cm,cs in zip(cmode, csettings):
	pc_os = DB.PointClouds.PointCloudOverrideSettings()
	pc_os.ColorMode = cm
	pc_os.SetModeOverride(cm,cs)
	pcOSsettings.append(pc_os)

OUT = pcOSsettings
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2c637124-6398-47a8-941c-0627a4ba74b1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1064.23763424729" y="863.484613959071" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MinColor: DSCore.Color = DSCore.Color.ByARGB(255,0,0,0);" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a4bf2669-2ed4-4c33-9913-5ea95e959320" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="2251.70288659248" y="846.540995614074" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OverrideSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="33f02bc0-23db-488e-8a0f-f9907c7ec791" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1029.59079396737" y="931.491532603228" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="MaxColor: DSCore.Color = DSCore.Color.ByARGB(255,255,255,255);" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="636b88b1-cf47-498e-a892-92e4005e4d88" start_index="0" end="e9122e9e-7b22-4591-a952-2619607e8e98" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b53e7c95-ab63-4c0f-b75b-45a37f68c19d" start_index="0" end="e9122e9e-7b22-4591-a952-2619607e8e98" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e9122e9e-7b22-4591-a952-2619607e8e98" start_index="0" end="e30d3f3b-5b93-478b-81fc-9588d701a831" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e9122e9e-7b22-4591-a952-2619607e8e98" start_index="1" end="e30d3f3b-5b93-478b-81fc-9588d701a831" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e30d3f3b-5b93-478b-81fc-9588d701a831" start_index="0" end="a4bf2669-2ed4-4c33-9913-5ea95e959320" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2c637124-6398-47a8-941c-0627a4ba74b1" start_index="0" end="b53e7c95-ab63-4c0f-b75b-45a37f68c19d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="33f02bc0-23db-488e-8a0f-f9907c7ec791" start_index="0" end="b53e7c95-ab63-4c0f-b75b-45a37f68c19d" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="b6d0e19b-6097-44cc-9c4a-679c5257848b" annotationText="Fixed Color" left="1019.59079396737" top="664.92231168571" width="1404.11209262511" height="334.569220917518" fontSize="30" InitialTop="710.92231168571" InitialHeight="256.114406874986" TextblockHeight="36" backgrouund="#FFFFC999">
      <Models ModelGuid="636b88b1-cf47-498e-a892-92e4005e4d88" />
      <Models ModelGuid="e9122e9e-7b22-4591-a952-2619607e8e98" />
      <Models ModelGuid="b53e7c95-ab63-4c0f-b75b-45a37f68c19d" />
      <Models ModelGuid="e30d3f3b-5b93-478b-81fc-9588d701a831" />
      <Models ModelGuid="a4bf2669-2ed4-4c33-9913-5ea95e959320" />
      <Models ModelGuid="2c637124-6398-47a8-941c-0627a4ba74b1" />
      <Models ModelGuid="33f02bc0-23db-488e-8a0f-f9907c7ec791" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-995.536804199219" eyeY="972.672424316406" eyeZ="716.995056152344" lookX="-29.082202911377" lookY="-629.75048828125" lookZ="-919.973693847656" upX="-0.0118361487984657" upY="0.927183866500854" upZ="-0.374419569969177" />
  </Cameras>
</Workspace>