<Workspace Version="1.3.3.4111" X="-333" Y="-10" zoom="1" ScaleFactor="1" Name="❄_Surface Plane" Description="(Sastrugi_Geometry) This node will extract a plane that best fits a surface." ID="fba9d8e4-0358-49e1-b306-da38076bf26d" Category="Sastrugi.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3cf1e5ea-d3ea-4307-a52e-b822fd9ab5f4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vertex.PointGeometry" x="1156.4433264397" y="377.834268397163" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vertex.PointGeometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1deb5c49-69db-4ad7-a99e-87377c27df65" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Plane.ByBestFitThroughPoints" x="1376.43817213265" y="378.925158111553" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Plane.ByBestFitThroughPoints@Autodesk.DesignScript.Geometry.Point[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f007adc9-528c-4823-a6b8-4c8c01f1cd9a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Face.Vertices" x="952.37600184406" y="377.834268397163" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Face.Vertices">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5bc69703-1787-4173-a3f0-ff234cabedf5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Topology.Faces" x="717.13172487964" y="375" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Topology.Faces">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a80d9470-a072-4abc-b96d-6403d0dfdaaa" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="547.5" y="374" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="InputSurfaces" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="28d81f53-752e-40c3-8ea0-1063137bccb8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1617.5" y="387" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Planes" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3cf1e5ea-d3ea-4307-a52e-b822fd9ab5f4" start_index="0" end="1deb5c49-69db-4ad7-a99e-87377c27df65" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1deb5c49-69db-4ad7-a99e-87377c27df65" start_index="0" end="28d81f53-752e-40c3-8ea0-1063137bccb8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f007adc9-528c-4823-a6b8-4c8c01f1cd9a" start_index="0" end="3cf1e5ea-d3ea-4307-a52e-b822fd9ab5f4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5bc69703-1787-4173-a3f0-ff234cabedf5" start_index="0" end="f007adc9-528c-4823-a6b8-4c8c01f1cd9a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a80d9470-a072-4abc-b96d-6403d0dfdaaa" start_index="0" end="5bc69703-1787-4173-a3f0-ff234cabedf5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="542a7834-3b5e-478f-90c0-48dd66f3004c" annotationText="Convert Surfaces to Planes" left="707.13172487964" top="329" width="878.30644725301" height="142.925158111553" fontSize="30" InitialTop="375" InitialHeight="126.925158111553" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="5bc69703-1787-4173-a3f0-ff234cabedf5" />
      <Models ModelGuid="3cf1e5ea-d3ea-4307-a52e-b822fd9ab5f4" />
      <Models ModelGuid="1deb5c49-69db-4ad7-a99e-87377c27df65" />
      <Models ModelGuid="f007adc9-528c-4823-a6b8-4c8c01f1cd9a" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>