<Workspace Version="1.0.0.1180" X="-99.762560792375" Y="109.906474394347" zoom="1.15419855371436" Name="Element.SelectInView" Description="Select the input elements in active view. Disconnect / Connect to refresh." ID="3aad227f-68ab-471c-856a-f835c5293c37" Category="SteamNodes.Element">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2088ce20-7afe-4b97-8259-5199b816ddbb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-80.8095259830751" y="56.6011907478844" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Element(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="39108650-f2b5-4d76-a98f-92d033f27cce" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="874.190474016925" y="14.6011907478844" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Element(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="69f11f1f-c25d-442c-b073-f932f70b1f7b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="138.190474016925" y="60.8145240812177" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="17c90d9b-45d9-4b96-aea7-d215785c2501" type="PythonNodeModels.PythonNode" nickname="Python Script" x="446.190474016925" y="56.6011907478844" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
import System.Object
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

input = UnwrapElement(IN[0])
elt=[]
for i in input:
	elt.append(i.Id)

collection = List[ElementId](elt)

uidoc.Selection.SetElementIds(collection)

OUT = input,collection</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="2e53fa07-216c-4eeb-a494-8e93fcb5fbb6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="670.190474016925" y="60.8145240812177" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0];&#xA;a[1];" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="42b7daa8-a55b-4831-b695-0cef564badf7" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="874.190474016925" y="98.6011907478844" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Id(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2088ce20-7afe-4b97-8259-5199b816ddbb" start_index="0" end="69f11f1f-c25d-442c-b073-f932f70b1f7b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="69f11f1f-c25d-442c-b073-f932f70b1f7b" start_index="0" end="17c90d9b-45d9-4b96-aea7-d215785c2501" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="17c90d9b-45d9-4b96-aea7-d215785c2501" start_index="0" end="2e53fa07-216c-4eeb-a494-8e93fcb5fbb6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2e53fa07-216c-4eeb-a494-8e93fcb5fbb6" start_index="0" end="39108650-f2b5-4d76-a98f-92d033f27cce" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2e53fa07-216c-4eeb-a494-8e93fcb5fbb6" start_index="1" end="42b7daa8-a55b-4831-b695-0cef564badf7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>