{
  "Uuid": "3cbe90a6-0d6c-439a-b6e8-f5e0b63cef9e",
  "IsCustomNode": true,
  "Category": "Synthesize.Automate.Lines",
  "Description": "Extract UV Revit Lines",
  "Name": "Extract UV Revit Lines",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double",
      "Id": "8e1b25c1531d40b5a69a24ec3ecffad5",
      "Inputs": [
        {
          "Id": "563e7da7928d4b3d86e464075ae2f7f2",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "01b17d2cb203442a8481e428a844a894",
          "Name": "u",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c62e75c97d52471fa43b50270211ad77",
          "Name": "v",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b09ad05eab59417f90643160d0d719ee",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return the Point at specified U and V parameters.\n\nSurface.PointAtParameter (u: double = 0, v: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "7149f7a1d95b4a609d5febedb82c04a8",
      "Inputs": [
        {
          "Id": "3053230edb024dd8a3d7efde96dcefb3",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "df12896fbd164c5b8d4ecf17cf559d7b",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "dae229099db84b3faa70b8959bfbb0ce",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PlaneAtParameter@double",
      "Id": "fa038b41d3964020b244cfceca2b08cd",
      "Inputs": [
        {
          "Id": "3c55cb24e6c647c4a057c86c7bab14c6",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3f8a3ee852784b3b9cdc7f612d2a2518",
          "Name": "param",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "077624143859458bb90ef68e71579e6b",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns a Plane whose normal aligns with the tangent of the Curve. Parameters are adjusted such that 0 is always the start Point and 1 is always the end Point.\n\nCurve.PlaneAtParameter (param: double = 0): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0.5;\n1;\n0;",
      "Id": "940957abad6f4627835ba4e853df75f7",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "5fbc0ba58fb943ffbde2b938f94dfab5",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "380e9e45592143dfad411f1bbaeef33d",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c16771006d674d69b68e3ea5c7fd9aeb",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "c5df249c7a944429a22afa0d947bce31",
      "Inputs": [
        {
          "Id": "663bdf3969614ee7acd16843b9a777c2",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f32d9b134804437280175ba1cc47fc03",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3d5f4c9052294d6386ae137749054c6b",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.Rotate@Autodesk.DesignScript.Geometry.Plane,double",
      "Id": "89fb70e026cf48c297a1dd95695fa282",
      "Inputs": [
        {
          "Id": "a6e58de9cd734a649d0e5eb336c498b8",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1463c2ecba1641a29f953f7939a4a1e3",
          "Name": "plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e0115d0e3cc040609ee3c53f5ad7e16a",
          "Name": "degrees",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "11d753ce268740bd96d9be79c9fbc636",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Rotates a vector around the Plane origin and normal by a specified degree\n\nVector.Rotate (plane: Plane, degrees: double = 0): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double",
      "Id": "d0f5915f6b604a75bbfc696c741e6b78",
      "Inputs": [
        {
          "Id": "22c3a71a93bc458eb0207b08685c0e00",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "52cf41a1372641b8a07d92ca3e56da18",
          "Name": "u",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d4771971d11c49d2918cc8f96d0a36ca",
          "Name": "v",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "12b476f5c2d84698b9211f8105b8ce13",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return the Point at specified U and V parameters.\n\nSurface.PointAtParameter (u: double = 0, v: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "90;",
      "Id": "b5820486f9604e91bc26b56d6794ac49",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "df4a69f730cb4ba9a6decc09a09cfa1d",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Enable Python support and load DesignScript library\r\n# IMPORTANT : ALL DYNAMO DESIGN SCRIPT NODES ARE AS (dg)\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript import Geometry as dg\r\n\r\n# EXTENSION Enable ToDSType\r\nclr.AddReference('RevitNodes')\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\n\r\n# Enable Revit Elements\r\nfrom Revit.Elements import *\r\n\r\n# EXTENSION Enable Geometry Conversion Methods\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\n# Enable Revit API\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\n# Enable DocumentManager and TransactionManager\r\nclr.AddReference('RevitServices')\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\n# Enable ICollection List Translate\r\nclr.AddReference(\"System\")\r\nimport System.Collections.Generic\r\nfrom System.Collections.Generic import List\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\napp = doc.Application\r\n\r\nPointslist = UnwrapElement(IN[0])\r\nSketchplanes = UnwrapElement(IN[1])\r\n\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\n\r\nConvertedSketchPlanes = []\r\nfor each in Sketchplanes:\r\n\tConvertedSketchPlanes.append(each.GetPlaneReference())\r\n\r\nresrefpoints=[]\r\n\r\ncount = 0\r\nfor eachlist in Pointslist:\r\n\ttmp = []\r\n\tfor e in eachlist:\r\n\t\tdynpoints = PointOnPlane.NewPointOnPlane(doc,ConvertedSketchPlanes[count],e.ToXyz(),XYZ(0,0,1))\r\n\t\tdynpoints.SetPlaneReference(ConvertedSketchPlanes[count])\r\n\t\trefpoints = doc.FamilyCreate.NewReferencePoint(dynpoints)\r\n\t\ttmp.append(refpoints)\r\n\tresrefpoints.append(tmp)\r\n\tcount = count + 1\r\n\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\nOUT = resrefpoints",
      "VariableInputPorts": true,
      "Id": "67cec48ec7bb46e7b4c46c5c8c87fd78",
      "Inputs": [
        {
          "Id": "183ed5cefc5d47d3b403857bb5a80ebe",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "79a85652f69745ad8cebb92977e944b8",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a9494db6344c480f8134061b64eca608",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.NormalAtPoint@Autodesk.DesignScript.Geometry.Point",
      "Id": "29a71ff5eb184aedb423308277cb8f13",
      "Inputs": [
        {
          "Id": "8fa5df6dc02c45dca0d9329cefe84b35",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "83555345543440ceba34776563d4fd03",
          "Name": "point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "74f3860df6464ec1ac291e57aa96fed3",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return the surface normal at the input Point on the Surface.\n\nSurface.NormalAtPoint (point: Point): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0.5;",
      "Id": "77c8345daf0e48dd82dec74db24ef9ea",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7ba1937872ff4b2188c72b667a499352",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Flatten@var[]..[],int",
      "Id": "dfd2dc245c784009a619e8fa9f0ab9f1",
      "Inputs": [
        {
          "Id": "d0d9129ef80c4874ae75a8fd63c43fa4",
          "Name": "list",
          "Description": "List to flatten.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": true,
          "KeepListStructure": false
        },
        {
          "Id": "306ab6506c8a485598598f50713e5b5b",
          "Name": "amt",
          "Description": "Layers of nesting to remove.\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d30df32ae2b1487c870148698c727ef4",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Flattens a nested list of lists by a certain amount.\n\nList.Flatten (list: var[]..[], amt: int = -1): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.CurveByPoints.ByReferencePoints@Revit.Elements.ReferencePoint[],bool",
      "Id": "376aa6c42619445997ebe219982394e6",
      "Inputs": [
        {
          "Id": "d363c75799a548ff8352439bbc79c15f",
          "Name": "points",
          "Description": "ReferencePoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ffacccdba75645beb3d35ecf56bb1c6b",
          "Name": "isReferenceLine",
          "Description": "bool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0a4226d565404fcab89bf2970eed416f",
          "Name": "CurveByPoints",
          "Description": "CurveByPoints",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Construct a Revit CurveByPoints Element (a CurveElement) from a collection of ReferencePoint's\n\nCurveByPoints.ByReferencePoints (points: ReferencePoint[], isReferenceLine: bool = false): CurveByPoints"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Flatten@var[]..[],int",
      "Id": "b550e329c91948d7947ae36ebb9c6ddd",
      "Inputs": [
        {
          "Id": "1db8d7651f8042a0ae56bba6af4341b6",
          "Name": "list",
          "Description": "List to flatten.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2031d3aa989043ab83fefdf594e1f5f7",
          "Name": "amt",
          "Description": "Layers of nesting to remove.\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "111e1e5849e544b5a2cac68d9ee17007",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Flattens a nested list of lists by a certain amount.\n\nList.Flatten (list: var[]..[], amt: int = -1): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Flatten@var[]..[],int",
      "Id": "cc2192e57feb44f58cc8edb1a93ec91f",
      "Inputs": [
        {
          "Id": "7cda79b25e814bc683bdf708e08cb003",
          "Name": "list",
          "Description": "List to flatten.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b455f4bb9e104435a4e68ee3aebac7b7",
          "Name": "amt",
          "Description": "Layers of nesting to remove.\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c2164b58c33e4aaa81e8dcd12a8152b6",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Flattens a nested list of lists by a certain amount.\n\nList.Flatten (list: var[]..[], amt: int = -1): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "true;",
      "Id": "9954c268bfbf4a96bdc99441d564ec70",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e176093e0e714bf6986c63055acfcc27",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Enable Python support and load DesignScript library\r\n# IMPORTANT : ALL DYNAMO DESIGN SCRIPT NODES ARE AS (dg)\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript import Geometry as dg\r\n\r\n# EXTENSION Enable ToDSType\r\nclr.AddReference('RevitNodes')\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\n\r\n# EXTENSION Enable Geometry Conversion Methods\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\n# Enable DocumentManager and TransactionManager\r\nclr.AddReference('RevitServices')\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\n\r\n# Choose The Current Document\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument\r\nuiapp = DocumentManager.Instance.CurrentUIApplication\r\napp = uiapp.Application\r\n\r\n\r\n#unwrap all elements to use with API\r\nxyzstart = UnwrapElement(IN[0])\r\nxyzend = UnwrapElement(IN[1])\r\nxyzvec = UnwrapElement(IN[2])\r\n\r\n\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\nplanes = []\r\ncount = 0\r\nfor each in xyzvec:\r\n\r\n\tplanes.append(doc.FamilyCreate.NewReferencePlane(xyzstart[count].ToXyz(), xyzend[count].ToXyz(), each.ToXyz(), doc.ActiveView))\r\n\tcount = count + 1\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\n#Assign your output to the OUT variable\r\nOUT = planes",
      "VariableInputPorts": true,
      "Id": "54596b028a78428cbe1da883c7a3a971",
      "Inputs": [
        {
          "Id": "965b0af528c0420d9acb6ca404c29248",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2b575864959d42e7ae7cc41667897aa6",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b3d2a561ad7d4a2ebb2255d13e3f54e5",
          "Name": "IN[2]",
          "Description": "Input #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cf329d5f9ac444efafd9c3d76fb25fe9",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Flatten@var[]..[],int",
      "Id": "c7e2e38180564417b317f200cfa76974",
      "Inputs": [
        {
          "Id": "947a2360e28649a2b4ebe82ca8a50eab",
          "Name": "list",
          "Description": "List to flatten.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cfe557c3209f4c0f94af085f077ca2e1",
          "Name": "amt",
          "Description": "Layers of nesting to remove.\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4b4a1e5c1bcc449ea95331ecdc60de0e",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Flattens a nested list of lists by a certain amount.\n\nList.Flatten (list: var[]..[], amt: int = -1): var[]..[]"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\n# Import Element wrapper extension methods\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\n\r\n# Import geometry conversion extension methods\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\n# Import DocumentManager and TransactionManager\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuiapp = DocumentManager.Instance.CurrentUIApplication\r\napp = uiapp.Application\r\n\r\n# Import RevitAPI\r\nclr.AddReference(\"RevitAPI\")\r\nimport Autodesk\r\nfrom Autodesk.Revit.DB import *\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuiapp = DocumentManager.Instance.CurrentUIApplication\r\napp = uiapp.Application\r\n\r\n# The inputs to this node will be stored as a list in the IN variable.\r\ndataEnteringNode = IN\r\n\r\n# Unwrap elements and convert geometry from Dynamo to Revit:\r\n\r\nrPlanes = UnwrapElement(IN[0])\r\nresult = []\r\n# Set the reference plane as the sketchplane in the active view in another transaction\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\nfor each in rPlanes:\r\n\tresult.append(SketchPlane.Create(doc,each.Id))\r\n\r\nelt = []\r\nfor i in rPlanes:\r\n\telt.append(UnwrapElement(i).Id)\r\ncantdelete=[]\r\nfor item in elt:\r\n\ttry:\r\n\t\tdoc.Delete(item)\r\n\texcept:\r\n\t\tcantdelete.append(item)\r\n\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\nOUT = result",
      "VariableInputPorts": true,
      "Id": "59fead46566b40b592346c683aefaccb",
      "Inputs": [
        {
          "Id": "c6cc0bac160b4f919719eb8c42a32991",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2062a02cf970479e96b6e0f7de0ebc55",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector",
      "Id": "be88f381ca8a48ea83b803ced4070b10",
      "Inputs": [
        {
          "Id": "910a41bd079c4fdbb3ff6e8e4ada0a04",
          "Name": "origin",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8abd6fc06f4f40ea8bb7dcca65ee9c64",
          "Name": "normal",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cc50c16f9740454cac16c6d7b5f6dc46",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Plane centered at root Point, with input normal Vector.\n\nPlane.ByOriginNormal (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), normal: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.NormalAtPoint@Autodesk.DesignScript.Geometry.Point",
      "Id": "df3c0b758dbf4cf9ab815726ffc5c0a0",
      "Inputs": [
        {
          "Id": "7fc761c967cc438e9e5166c507741fe6",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "965b64ad099644c28bf175b2e447b996",
          "Name": "point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f7c621e8948c4a22b2158b53a4bd04ec",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return the surface normal at the input Point on the Surface.\n\nSurface.NormalAtPoint (point: Point): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "5f7bef6dede9414ea3366b48598a6dc6",
      "Inputs": [
        {
          "Id": "f2f41172675b488ab073a09a4fb24b12",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f8512ebbd673440fa4fad2d2bdca3b0a",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d15abe2744934385ad9ee4f737dd841c",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "296788fd15f04878a784dd1ccd955c04",
      "Inputs": [
        {
          "Id": "1d6ce5a8e62046e6ae31969905ea7ad0",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6a66b51f720040db8b1578cc0cf574ea",
          "Name": "NurbsCurve",
          "Description": "NurbsCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by interpolating between points.\n\nNurbsCurve.ByPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0.5;",
      "Id": "4cef505bc10d4cb8ba5c73f3a02edb9b",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "41ff94e0c34f40b7928331ceab4266fa",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double",
      "Id": "973781e25f7d4d1fab034e4a2365431c",
      "Inputs": [
        {
          "Id": "177620a2146a4e3aad4c1234a744fb2f",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b6b697bd4627473b8fda89da821c0c73",
          "Name": "u",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1e913226e14d4195a535d5e520f3c87a",
          "Name": "v",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1a533a4e0b224e40b9dd6e80e1de5545",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "CrossProduct",
      "Description": "Return the Point at specified U and V parameters.\n\nSurface.PointAtParameter (u: double = 0, v: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0..1..#u;\n0..1..#v;",
      "Id": "efbc9d43c32c4151b127355750bef55d",
      "Inputs": [
        {
          "Id": "ddc04cfe569849bd8f77c2e7ce2b09e6",
          "Name": "u",
          "Description": "u",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0cacd76680de49eba95298e4ea7ec54a",
          "Name": "v",
          "Description": "v",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "812a73c0ec3347d5ba37ce49449c8d4a",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4a512cbad2df4b6fbba0895cfb6bd55f",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Flatten@var[]..[],int",
      "Id": "e94e114a1e5045c0b7ac64ec321f9c05",
      "Inputs": [
        {
          "Id": "b99e607b8a0143c1b2e0aa7b50a8a57e",
          "Name": "list",
          "Description": "List to flatten.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a74f64dfff9b4f2bb8a3ad303ae25b42",
          "Name": "amt",
          "Description": "Layers of nesting to remove.\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "85ee430062654ce8a7d1496348f02e5f",
          "Name": "var[]..[]",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Flattens a nested list of lists by a certain amount.\n\nList.Flatten (list: var[]..[], amt: int = -1): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "VARu",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "7fcff3e7b1e24a168b12b61714a2cc32",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e658b2a2510a41ce8eaf4606d040505c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "VARv",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "e06d9bf5fd1340bab98bae09954e2f02",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "82dfb5bc1ab849ed889114d689b27a5a",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "VARSurfaces",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "c1df3064dd244146b2508719dfe1a5fa",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "be5c3df2e98d4bb28c363554872f0312",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "VARCurveByPoints",
      "Id": "b834c154c36f4fc99163ae2bf5ab6fad",
      "Inputs": [
        {
          "Id": "4e05d91e72924121a14460a3a5f286f0",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "VARSketchPlanes",
      "Id": "d5b7e86ca579465c92d09fba26ac0b38",
      "Inputs": [
        {
          "Id": "87c84a15cee144169b6d7612f0aa9192",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.Transpose@var[]..[]",
      "Id": "59a6690d7de045698b09d4ef9380595b",
      "Inputs": [
        {
          "Id": "07c4cdaffe2448d68d09dc2d6374d6f9",
          "Name": "lists",
          "Description": "A list of lists to be transposed.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 3,
          "UseLevels": true,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "fa138e6a3c3e4de8a9c5ca67da085302",
          "Name": "lists",
          "Description": "A list of transposed lists.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Swaps rows and columns in a list of lists. If there are some rows that are shorter than others, null values are inserted as place holders in the resultant array such that it is always rectangular.\n\nList.Transpose (lists: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "597def74-6997-4484-bb18-67a97819c8bd",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "b552b8808fb34aae8c7fde4e91763b76",
      "Inputs": [
        {
          "Id": "8771e9aaac154995992ae25f863cdc51",
          "Name": "VARtest",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d937c2d2b62e4741b0626e7a3b9d3c50",
          "Name": "VARtrue",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c7dfbe2aa55b4370a3681912dc2f2150",
          "Name": "VARfalse",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "5d0163f896ae4c7dbbcc1977ab29237c",
          "Name": "VARresult",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "A (hopefully) more robust implementation of ScopeIf. Tests a single boolean and returns a value accordingly."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "VARUFalseVTrue",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "0acb7c80ed39443abd4454718bcd607c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d4d0839777cd4d249ce927d9a74b66d5",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "VARReferencePoints",
      "Id": "880c6e23902947da8986191412b03fb3",
      "Inputs": [
        {
          "Id": "35d2e58989f74a21b3b3d553242554eb",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@Autodesk.DesignScript.Geometry.Plane,double,double",
      "Id": "e8b1363a98d04391800c1638cd0c44af",
      "Inputs": [
        {
          "Id": "ea20033543e14d5c895e70e637091a10",
          "Name": "plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "256aca50841248688e835e7946565459",
          "Name": "width",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "57cb7ba2acdf425c84edd482ca676f20",
          "Name": "length",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "907d09068cef4ed1bbbbe67886c416a8",
          "Name": "Rectangle",
          "Description": "Rectangle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Rectangle centered at input Plane root, with input width (Plane X axis length), and length (Plane Y axis length).\n\nRectangle.ByWidthLength (plane: Plane, width: double = 1, length: double = 1): Rectangle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByPatch@Autodesk.DesignScript.Geometry.Curve",
      "Id": "af77311185494605a93dec4568d0f294",
      "Inputs": [
        {
          "Id": "754f079b40d64eb9987079532e691240",
          "Name": "closedCurve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "bea8814bdff040c2aa835738da208d25",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by filling in the interior of a closed boundary defined by input Curves.\n\nSurface.ByPatch (closedCurve: Curve): Surface"
    }
  ],
  "Connectors": [
    {
      "Start": "b09ad05eab59417f90643160d0d719ee",
      "End": "3053230edb024dd8a3d7efde96dcefb3",
      "Id": "56150cd8f6384abb8e13728e6a4114be"
    },
    {
      "Start": "b09ad05eab59417f90643160d0d719ee",
      "End": "1db8d7651f8042a0ae56bba6af4341b6",
      "Id": "dc1f5405311242c58066dc4776687987"
    },
    {
      "Start": "dae229099db84b3faa70b8959bfbb0ce",
      "End": "663bdf3969614ee7acd16843b9a777c2",
      "Id": "e1486004d2274d4b89082ccaf3fcb777"
    },
    {
      "Start": "dae229099db84b3faa70b8959bfbb0ce",
      "End": "3c55cb24e6c647c4a057c86c7bab14c6",
      "Id": "ba913df7cea94a33a4f2df1e0c9f1bda"
    },
    {
      "Start": "077624143859458bb90ef68e71579e6b",
      "End": "1463c2ecba1641a29f953f7939a4a1e3",
      "Id": "46ce0dda80fa43f1a0fd041931e8ce7f"
    },
    {
      "Start": "5fbc0ba58fb943ffbde2b938f94dfab5",
      "End": "52cf41a1372641b8a07d92ca3e56da18",
      "Id": "bd2a9b7c3b7d40dc982b6245c0244ab9"
    },
    {
      "Start": "5fbc0ba58fb943ffbde2b938f94dfab5",
      "End": "01b17d2cb203442a8481e428a844a894",
      "Id": "df7bec5da116432f96699381c9a85808"
    },
    {
      "Start": "380e9e45592143dfad411f1bbaeef33d",
      "End": "d4771971d11c49d2918cc8f96d0a36ca",
      "Id": "6dbff44d04634a0bb3f6c4667a003f15"
    },
    {
      "Start": "c16771006d674d69b68e3ea5c7fd9aeb",
      "End": "c62e75c97d52471fa43b50270211ad77",
      "Id": "d0b079840308481ab15aa973aef16d64"
    },
    {
      "Start": "3d5f4c9052294d6386ae137749054c6b",
      "End": "83555345543440ceba34776563d4fd03",
      "Id": "7dbfc06d668b4a7186d3c47615a64e6f"
    },
    {
      "Start": "11d753ce268740bd96d9be79c9fbc636",
      "End": "947a2360e28649a2b4ebe82ca8a50eab",
      "Id": "417acd14cd1e4e3c9e17e5b4e9cfde4b"
    },
    {
      "Start": "12b476f5c2d84698b9211f8105b8ce13",
      "End": "df12896fbd164c5b8d4ecf17cf559d7b",
      "Id": "a41dddaa495f4c3f905eb66352f571b7"
    },
    {
      "Start": "12b476f5c2d84698b9211f8105b8ce13",
      "End": "7cda79b25e814bc683bdf708e08cb003",
      "Id": "6f69de6f0d1a494bbf406594c8985012"
    },
    {
      "Start": "df4a69f730cb4ba9a6decc09a09cfa1d",
      "End": "e0115d0e3cc040609ee3c53f5ad7e16a",
      "Id": "b67ba33c02bc4ec8a1ab603f7527d86c"
    },
    {
      "Start": "a9494db6344c480f8134061b64eca608",
      "End": "d363c75799a548ff8352439bbc79c15f",
      "Id": "fd290ce670dc4f9787aa562fff3e1868"
    },
    {
      "Start": "a9494db6344c480f8134061b64eca608",
      "End": "35d2e58989f74a21b3b3d553242554eb",
      "Id": "d39f40e9d9f249daa82f234ff4238bd0"
    },
    {
      "Start": "74f3860df6464ec1ac291e57aa96fed3",
      "End": "a6e58de9cd734a649d0e5eb336c498b8",
      "Id": "eb440da8490a479480267b8570afd2c6"
    },
    {
      "Start": "7ba1937872ff4b2188c72b667a499352",
      "End": "f32d9b134804437280175ba1cc47fc03",
      "Id": "1a3f66b287e646baa08c3dab44cdd46a"
    },
    {
      "Start": "7ba1937872ff4b2188c72b667a499352",
      "End": "3f8a3ee852784b3b9cdc7f612d2a2518",
      "Id": "95b84238a1d343e9b49489d7cf05cf09"
    },
    {
      "Start": "d30df32ae2b1487c870148698c727ef4",
      "End": "183ed5cefc5d47d3b403857bb5a80ebe",
      "Id": "9df15aae511349ba865e48f922ef2551"
    },
    {
      "Start": "0a4226d565404fcab89bf2970eed416f",
      "End": "4e05d91e72924121a14460a3a5f286f0",
      "Id": "9d8774f4d81641b693c39449106d341f"
    },
    {
      "Start": "111e1e5849e544b5a2cac68d9ee17007",
      "End": "965b0af528c0420d9acb6ca404c29248",
      "Id": "1d4e65f87cc8416aa511d2f6252d8232"
    },
    {
      "Start": "c2164b58c33e4aaa81e8dcd12a8152b6",
      "End": "2b575864959d42e7ae7cc41667897aa6",
      "Id": "2b2c259578324cd0a4b5442efa502088"
    },
    {
      "Start": "e176093e0e714bf6986c63055acfcc27",
      "End": "ffacccdba75645beb3d35ecf56bb1c6b",
      "Id": "8180a79fb1fe4810bf779f34a24f2821"
    },
    {
      "Start": "cf329d5f9ac444efafd9c3d76fb25fe9",
      "End": "c6cc0bac160b4f919719eb8c42a32991",
      "Id": "0489e26ec0324b66b9798ced6cc0d538"
    },
    {
      "Start": "4b4a1e5c1bcc449ea95331ecdc60de0e",
      "End": "b3d2a561ad7d4a2ebb2255d13e3f54e5",
      "Id": "ec9b6f99764241349fd8df2e1f6384e6"
    },
    {
      "Start": "2062a02cf970479e96b6e0f7de0ebc55",
      "End": "79a85652f69745ad8cebb92977e944b8",
      "Id": "bde666af92924243953aa47cce322309"
    },
    {
      "Start": "2062a02cf970479e96b6e0f7de0ebc55",
      "End": "87c84a15cee144169b6d7612f0aa9192",
      "Id": "6f50500b91fe44c290838a9ed8e36a78"
    },
    {
      "Start": "cc50c16f9740454cac16c6d7b5f6dc46",
      "End": "ea20033543e14d5c895e70e637091a10",
      "Id": "6e0ee1e0de134968a823f63b121f250c"
    },
    {
      "Start": "f7c621e8948c4a22b2158b53a4bd04ec",
      "End": "8abd6fc06f4f40ea8bb7dcca65ee9c64",
      "Id": "41fbda0a65044bf696644c207a1f5563"
    },
    {
      "Start": "d15abe2744934385ad9ee4f737dd841c",
      "End": "965b64ad099644c28bf175b2e447b996",
      "Id": "b92aa2d94cb343849ee7309168070fd9"
    },
    {
      "Start": "d15abe2744934385ad9ee4f737dd841c",
      "End": "910a41bd079c4fdbb3ff6e8e4ada0a04",
      "Id": "b7b6e20265ad45efa426db2c95507c6d"
    },
    {
      "Start": "6a66b51f720040db8b1578cc0cf574ea",
      "End": "f2f41172675b488ab073a09a4fb24b12",
      "Id": "cf7d9ab81cc14e16b160e7356e359920"
    },
    {
      "Start": "41ff94e0c34f40b7928331ceab4266fa",
      "End": "f8512ebbd673440fa4fad2d2bdca3b0a",
      "Id": "8ce0f59ba5c64ea5a39370c9ac2f1943"
    },
    {
      "Start": "1a533a4e0b224e40b9dd6e80e1de5545",
      "End": "d937c2d2b62e4741b0626e7a3b9d3c50",
      "Id": "bad2f1e02e694a5da99f523e40426b19"
    },
    {
      "Start": "1a533a4e0b224e40b9dd6e80e1de5545",
      "End": "07c4cdaffe2448d68d09dc2d6374d6f9",
      "Id": "72f3c504a17e48698cc3e68708945703"
    },
    {
      "Start": "812a73c0ec3347d5ba37ce49449c8d4a",
      "End": "b6b697bd4627473b8fda89da821c0c73",
      "Id": "ed64e6587f3f40c9847ccdeb9d9b772f"
    },
    {
      "Start": "4a512cbad2df4b6fbba0895cfb6bd55f",
      "End": "1e913226e14d4195a535d5e520f3c87a",
      "Id": "5c444ddf7847463c9e7feeb3e4400eaf"
    },
    {
      "Start": "85ee430062654ce8a7d1496348f02e5f",
      "End": "177620a2146a4e3aad4c1234a744fb2f",
      "Id": "9698df1f235d49b4b0ffaf659d1438cb"
    },
    {
      "Start": "85ee430062654ce8a7d1496348f02e5f",
      "End": "7fc761c967cc438e9e5166c507741fe6",
      "Id": "a3c610858e8a488797b802c2d4d73e9f"
    },
    {
      "Start": "e658b2a2510a41ce8eaf4606d040505c",
      "End": "ddc04cfe569849bd8f77c2e7ce2b09e6",
      "Id": "76bc0db17ad44a51b6845d46dfda4b96"
    },
    {
      "Start": "82dfb5bc1ab849ed889114d689b27a5a",
      "End": "0cacd76680de49eba95298e4ea7ec54a",
      "Id": "41ea7a39ba40432b80d3531541195521"
    },
    {
      "Start": "be5c3df2e98d4bb28c363554872f0312",
      "End": "b99e607b8a0143c1b2e0aa7b50a8a57e",
      "Id": "dfdaff28665d4cdd97d0ce6f0f47f81b"
    },
    {
      "Start": "fa138e6a3c3e4de8a9c5ca67da085302",
      "End": "c7dfbe2aa55b4370a3681912dc2f2150",
      "Id": "75d5ad331c0f481889e232a87050f865"
    },
    {
      "Start": "5d0163f896ae4c7dbbcc1977ab29237c",
      "End": "1d6ce5a8e62046e6ae31969905ea7ad0",
      "Id": "8acf06dcaf6b40eeaf4f3cb8c2091514"
    },
    {
      "Start": "5d0163f896ae4c7dbbcc1977ab29237c",
      "End": "d0d9129ef80c4874ae75a8fd63c43fa4",
      "Id": "96f9cf9a232040118af1472347d7fddc"
    },
    {
      "Start": "d4d0839777cd4d249ce927d9a74b66d5",
      "End": "8771e9aaac154995992ae25f863cdc51",
      "Id": "0d7a760e4a3446d88fb258223a7c1bf4"
    },
    {
      "Start": "907d09068cef4ed1bbbbe67886c416a8",
      "End": "754f079b40d64eb9987079532e691240",
      "Id": "db4c6821ba8643a4a94f316ce5937a16"
    },
    {
      "Start": "bea8814bdff040c2aa835738da208d25",
      "End": "8fa5df6dc02c45dca0d9329cefe84b35",
      "Id": "98a78910abda40798a71e3c4f0684a37"
    },
    {
      "Start": "bea8814bdff040c2aa835738da208d25",
      "End": "22c3a71a93bc458eb0207b08685c0e00",
      "Id": "6645f49d63944c4c9fc50afc9a17c6ea"
    },
    {
      "Start": "bea8814bdff040c2aa835738da208d25",
      "End": "563e7da7928d4b3d86e464075ae2f7f2",
      "Id": "4ed78be36de246b590d6d8658ade9f62"
    }
  ],
  "Dependencies": [
    "597def74-6997-4484-bb18-67a97819c8bd"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.7500",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -69.446052551269531,
      "EyeY": 137.12933349609375,
      "EyeZ": 48.626022338867188,
      "LookX": 84.156402587890625,
      "LookY": -197.8341064453125,
      "LookZ": -50.787693023681641,
      "UpX": 0.66724675893783569,
      "UpY": 0.62660384178161621,
      "UpZ": -0.40267786383628845
    },
    "NodeViews": [
      {
        "Id": "8e1b25c1531d40b5a69a24ec3ecffad5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.PointAtParameter",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 4556.14772111215,
        "Y": 1610.44593505879
      },
      {
        "Id": "7149f7a1d95b4a609d5febedb82c04a8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Line.ByStartPointEndPoint",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 4814.53486925725,
        "Y": 1647.25780904561
      },
      {
        "Id": "fa038b41d3964020b244cfceca2b08cd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PlaneAtParameter",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 5241.62937891465,
        "Y": 1658.03393283216
      },
      {
        "Id": "940957abad6f4627835ba4e853df75f7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 4322.73795573725,
        "Y": 1734.62320123327
      },
      {
        "Id": "c5df249c7a944429a22afa0d947bce31",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 5074.07038581455,
        "Y": 1803.6656829941
      },
      {
        "Id": "89fb70e026cf48c297a1dd95695fa282",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.Rotate",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 5649.64058897075,
        "Y": 1822.35806545757
      },
      {
        "Id": "d0f5915f6b604a75bbfc696c741e6b78",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.PointAtParameter",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 4562.13641559005,
        "Y": 1812.8581462632
      },
      {
        "Id": "b5820486f9604e91bc26b56d6794ac49",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 5392.37776038865,
        "Y": 1879.80341720186
      },
      {
        "Id": "67cec48ec7bb46e7b4c46c5c8c87fd78",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Python Script",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 6930.94770128019,
        "Y": 1661.36444347709
      },
      {
        "Id": "29a71ff5eb184aedb423308277cb8f13",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.NormalAtPoint",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 5336.26698717605,
        "Y": 1988.7324316486
      },
      {
        "Id": "77c8345daf0e48dd82dec74db24ef9ea",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 4663.66584540315,
        "Y": 2074.71016106107
      },
      {
        "Id": "dfd2dc245c784009a619e8fa9f0ab9f1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Flatten",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 6032.17846201169,
        "Y": 1563.3482677377
      },
      {
        "Id": "376aa6c42619445997ebe219982394e6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "CurveByPoints.ByReferencePoints",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 7328.65867079479,
        "Y": 1636.2184439053
      },
      {
        "Id": "b550e329c91948d7947ae36ebb9c6ddd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Flatten",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 6071.87397856639,
        "Y": 1761.07368590664
      },
      {
        "Id": "cc2192e57feb44f58cc8edb1a93ec91f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Flatten",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 6048.70033751499,
        "Y": 1874.92679194198
      },
      {
        "Id": "9954c268bfbf4a96bdc99441d564ec70",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 7130.06247416719,
        "Y": 1773.38101956525
      },
      {
        "Id": "54596b028a78428cbe1da883c7a3a971",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Python Script",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 6445.03858766669,
        "Y": 1899.54234299952
      },
      {
        "Id": "c7e2e38180564417b317f200cfa76974",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Flatten",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 6062.80603206799,
        "Y": 1986.76479875545
      },
      {
        "Id": "59fead46566b40b592346c683aefaccb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Python Script",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 6681.06401263379,
        "Y": 1953.83400483453
      },
      {
        "Id": "be88f381ca8a48ea83b803ced4070b10",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Plane.ByOriginNormal",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 3055.71016168153,
        "Y": 1545.51773892433
      },
      {
        "Id": "df3c0b758dbf4cf9ab815726ffc5c0a0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.NormalAtPoint",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 2755.43198121298,
        "Y": 1465.13149921665
      },
      {
        "Id": "5f7bef6dede9414ea3366b48598a6dc6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 2412.96286147883,
        "Y": 1423.3901106618
      },
      {
        "Id": "296788fd15f04878a784dd1ccd955c04",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "NurbsCurve.ByPoints",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 1934.72564813728,
        "Y": 1534.40090029205
      },
      {
        "Id": "4cef505bc10d4cb8ba5c73f3a02edb9b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 2132.84880982498,
        "Y": 1423.81548776018
      },
      {
        "Id": "973781e25f7d4d1fab034e4a2365431c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.PointAtParameter",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 800.500981320321,
        "Y": 1753.30186775749
      },
      {
        "Id": "efbc9d43c32c4151b127355750bef55d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 575.072680960705,
        "Y": 1873.28465284911
      },
      {
        "Id": "e94e114a1e5045c0b7ac64ec321f9c05",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Flatten",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 250.0,
        "Y": 1571.38230644719
      },
      {
        "Id": "7fcff3e7b1e24a168b12b61714a2cc32",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -432.602647273756,
        "Y": 1638.7960825933
      },
      {
        "Id": "e06d9bf5fd1340bab98bae09954e2f02",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -432.602647273756,
        "Y": 1788.7960825933
      },
      {
        "Id": "c1df3064dd244146b2508719dfe1a5fa",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -432.602647273756,
        "Y": 1938.7960825933
      },
      {
        "Id": "b834c154c36f4fc99163ae2bf5ab6fad",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 7766.31101818839,
        "Y": 1718.45184664528
      },
      {
        "Id": "d5b7e86ca579465c92d09fba26ac0b38",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 7776.99133304479,
        "Y": 1795.45555557716
      },
      {
        "Id": "59a6690d7de045698b09d4ef9380595b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.Transpose",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1047.8325564885,
        "Y": 1699.03213482657
      },
      {
        "Id": "b552b8808fb34aae8c7fde4e91763b76",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "CW.ScopeIf+",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1316.83670997089,
        "Y": 1600.29125841619
      },
      {
        "Id": "0acb7c80ed39443abd4454718bcd607c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -427.237413569535,
        "Y": 2042.9443207809
      },
      {
        "Id": "880c6e23902947da8986191412b03fb3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 7765.06994904199,
        "Y": 1609.49201458865
      },
      {
        "Id": "e8b1363a98d04391800c1638cd0c44af",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Rectangle.ByWidthLength",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 3414.14843269976,
        "Y": 1989.54530334661
      },
      {
        "Id": "af77311185494605a93dec4568d0f294",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Surface.ByPatch",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 3787.4257238511,
        "Y": 2031.05432635341
      }
    ],
    "Annotations": [],
    "X": 371.556767605284,
    "Y": 27.9824748678547,
    "Zoom": 0.190579344711359
  }
}