<Workspace Version="1.3.0.875" X="8.25236795147339" Y="200.716723389539" zoom="0.823080562643654" ScaleFactor="1" Name="Get Element Rotation" Description="Get the rotation of a family instance whose location is a point." ID="67321173-5da2-4da8-948f-9fbb25fea448" Category="Modelical.Elements">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <CoreNodeModels.Watch guid="50800932-ffee-404a-8456-a5ae9d942cdc" type="CoreNodeModels.Watch" nickname="Watch(isYMirrored)" x="1649.13481827148" y="371.620104238699" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Watch guid="c208fde1-c925-4e79-931f-b39b17eca173" type="CoreNodeModels.Watch" nickname="Watch(isXMirrored)" x="1650.14507776923" y="203.238466374042" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <PythonNodeModels.PythonNode guid="046a5a5d-566d-48de-81d7-a1fa2296f65e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1682.83080071306" y="23.8683177727529" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># This node has been made by Modelical
# www.modelical.com

import clr
from math import *
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
X=IN[0]
Y=IN[1]
outlist = []
templist = []
templist2 = []
count = 0


for e in X:
	templist.append((acos(e)))


while count &lt; len(templist):
#for item in templist:
	if Y[count] &gt;= 0:
		templist2.append(degrees(templist[count]))
	elif Y[count] &lt; 0:
		templist2.append((degrees(templist[count])) + (2*(180-(degrees(templist[count])))))
	count = count + 1

for e in templist2:
	if e == 0:
		outlist.append(0)
	else:
		outlist.append(360 - e)

#Assign your output to the OUT variable
OUT = outlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9df942c0-b4b7-4d89-b59b-6204ce9b3780" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="String.ToNumber" x="1455.57089975417" y="107.027328564059" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.String.ToNumber@string">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c59cb780-cf1e-478e-b1d0-5ba6f1045304" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="transpose list and split output" x="1052.1232714753" y="14.6134440565843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="IN=List.Transpose(inputlist);&#xA;X=IN[0];&#xA;Y=IN[1];&#xA;Z=IN[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d61ef866-3805-4754-aeb4-a774da2a086d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="String.ToNumber" x="1454.96951687665" y="27.0059272013882" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.String.ToNumber@string">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="9dd87da2-f0af-43d9-9479-ed76e2146dd9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="872.620670110247" y="10.9822082366936" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variable.
vect = IN[0]
outlist = []
templist = []

for e in vect:
	e = str(e)
	e = e.replace('(', '')
	e = e.replace(')', '')
	e = e.replace(',', '')
	templist.append(e)

for i in templist:
	outlist.append(i.split(" "))
	
for e in outlist:
	for i in e:
		i = float(i)

#Assign your output to the OUT variable
OUT = outlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e5445a50-89f3-42cc-b3b3-fe85c70acea5" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="556.533678566456" y="15.8196712103979" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="XYZvectorHand = list[0];&#xA;xMirrored = list[1];&#xA;yMirrored = list[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f67550fe-2379-4120-9071-1a8d5f73bca6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Transpose" x="365.596153811093" y="12.5382527261297" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Transpose@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="c5860fdb-a578-42fe-8304-a2dbe3df6263" type="PythonNodeModels.PythonNode" nickname="Python Script" x="206.685580670203" y="11.5749932643729" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># This node has been made by Modelical
# www.modelical.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
#The inputs to this node will be stored as a list in the IN variable.

def toList(input):
	if isinstance(input,list) == False:
		return [input]
	else:
		return input

elements = toList(UnwrapElement(IN[0]))

outlist = [] #export list
templist = [] #temporary list to group attributes by element
for i in elements:
	templist.append(i.HandOrientation) #vector XYZ Hand
	templist.append(i.FacingFlipped) #is mirrored over X axis?
	templist.append(i.HandFlipped) #is mirrored over Y axis?
	outlist.append(templist[:])

	del templist[:] #clear the templist

#Assign your output to the OUT variable
OUT = outlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1a4ba093-220e-4ffb-97f0-bb728ed28ebd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="51.0366551814334" y="10.9881519038709" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FamInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5a647a9e-9414-4c07-b280-9ddfc828efce" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1942.83810445947" y="24.5888734372654" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Rotation" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8e3c8f5b-b1b2-4668-83f3-1b8e60856b08" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1934.4320985725" y="205.91842899919" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="isXmirrored?" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="41560683-c160-4cd4-aad8-319e14faefce" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1935.21837083084" y="377.226534964769" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="isYmirrored?" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="50800932-ffee-404a-8456-a5ae9d942cdc" start_index="0" end="41560683-c160-4cd4-aad8-319e14faefce" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c208fde1-c925-4e79-931f-b39b17eca173" start_index="0" end="8e3c8f5b-b1b2-4668-83f3-1b8e60856b08" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="046a5a5d-566d-48de-81d7-a1fa2296f65e" start_index="0" end="5a647a9e-9414-4c07-b280-9ddfc828efce" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9df942c0-b4b7-4d89-b59b-6204ce9b3780" start_index="0" end="046a5a5d-566d-48de-81d7-a1fa2296f65e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c59cb780-cf1e-478e-b1d0-5ba6f1045304" start_index="1" end="d61ef866-3805-4754-aeb4-a774da2a086d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c59cb780-cf1e-478e-b1d0-5ba6f1045304" start_index="2" end="9df942c0-b4b7-4d89-b59b-6204ce9b3780" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d61ef866-3805-4754-aeb4-a774da2a086d" start_index="0" end="046a5a5d-566d-48de-81d7-a1fa2296f65e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9dd87da2-f0af-43d9-9479-ed76e2146dd9" start_index="0" end="c59cb780-cf1e-478e-b1d0-5ba6f1045304" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e5445a50-89f3-42cc-b3b3-fe85c70acea5" start_index="0" end="9dd87da2-f0af-43d9-9479-ed76e2146dd9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e5445a50-89f3-42cc-b3b3-fe85c70acea5" start_index="1" end="c208fde1-c925-4e79-931f-b39b17eca173" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e5445a50-89f3-42cc-b3b3-fe85c70acea5" start_index="2" end="50800932-ffee-404a-8456-a5ae9d942cdc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f67550fe-2379-4120-9071-1a8d5f73bca6" start_index="0" end="e5445a50-89f3-42cc-b3b3-fe85c70acea5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c5860fdb-a578-42fe-8304-a2dbe3df6263" start_index="0" end="f67550fe-2379-4120-9071-1a8d5f73bca6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1a4ba093-220e-4ffb-97f0-bb728ed28ebd" start_index="0" end="c5860fdb-a578-42fe-8304-a2dbe3df6263" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>