<Workspace Version="1.3.1.1736" X="288.885064351549" Y="-108.657948444286" zoom="1.01715733291329" ScaleFactor="1" Name="Room.Boundaries" Description="Gets a list of all boundaries of a given room or area and a corresponding list of the elements that are generating those boundaries." ID="fb07f5d8-94b8-4985-bf2f-a54fe832aa66" Category="Clockwork.Revit.Elements.Room.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="981a0e03-9fe7-44f9-9504-2ea77ca18745" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="104.008431567804" y="307.664824827435" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="room" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="aa6058d6-2d2c-419c-adc4-23f58c7f5767" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1020.72155697236" y="323.884040420045" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="a8eb6ee0-7fe9-44ef-8cdb-9fb618413d2f" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="ReturnListOrSingleValue" x="765.24657176038" y="471.893386445294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="unknownItem" />
        <Input value="seq" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="b5ecaffa-7fdb-49da-be7e-e30501d742ac" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="ReturnListOrSingleValue" x="758.420423413928" y="323.432857539774" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="unknownItem" />
        <Input value="seq" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="53d33e3a-cece-4638-b60a-d477a6b4abee" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="600.988342758828" y="410.887838650037" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="seq[0];&#xA;seq[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="9e250749-068e-4ff1-bbcd-57eeb0ee62d4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="414.903632690643" y="405.771487040763" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

items = UnwrapElement(IN[0])
version = IN[1]
elementlist = list()
curvelist = list()

for item in items:
	doc = item.Document
	calculator = SpatialElementGeometryCalculator(doc)
	options = Autodesk.Revit.DB.SpatialElementBoundaryOptions()
	# get boundary location from area computation settings
	boundloc = Autodesk.Revit.DB.AreaVolumeSettings.GetAreaVolumeSettings(doc).GetSpatialElementBoundaryLocation(SpatialElementType.Room)
	options.SpatialElementBoundaryLocation = boundloc
	#method #1 - get boundary segments
	blist = list()
	clist = list()
	try:
		for boundarylist in item.GetBoundarySegments(options):
			for boundary in boundarylist:
				blist.append(doc.GetElement(boundary.ElementId))
				if version &gt; 2016:
					clist.append(boundary.GetCurve().ToProtoType())
				else:
					clist.append(boundary.Curve.ToProtoType())
	except:
		pass
	#method #2 - spatial element geometry calculator
	"""try:
		results = calculator.CalculateSpatialElementGeometry(item)
		for face in results.GetGeometry().Faces:
			for bface in results.GetBoundaryFaceInfo(face):
				blist.append(doc.GetElement(bface.SpatialBoundaryElement.HostElementId))
	except:
		pass	"""
	# write results to list
	elementlist.append(blist)
	curvelist.append(clist)
OUT = (elementlist,curvelist)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="ff96cfb0-38bf-456a-b0b9-ed358727796d" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="TurnIntoList" x="204.665035388418" y="373.055604891986" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="unknownItem" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d71efcb4-3df8-472f-b598-63d7a11c097e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1013.99880522976" y="471.172184766106" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="3a8e8c07-23e8-4c4f-a986-ae45a639d204" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Application.Version" x="230.053140864384" y="459.290714003493" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <ID value="3df0961d-9d46-464f-9175-0a74eeb61bc1" />
      <Name value="Application.Version" />
      <Description value="Retrieves the name, version and build of the current Revit application." />
      <Inputs />
      <Outputs>
        <Output value="Name" />
        <Output value="Version" />
        <Output value="Build" />
        <Output value="Language" />
        <Output value="fullVersion" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="981a0e03-9fe7-44f9-9504-2ea77ca18745" start_index="0" end="ff96cfb0-38bf-456a-b0b9-ed358727796d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="981a0e03-9fe7-44f9-9504-2ea77ca18745" start_index="0" end="a8eb6ee0-7fe9-44ef-8cdb-9fb618413d2f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="981a0e03-9fe7-44f9-9504-2ea77ca18745" start_index="0" end="b5ecaffa-7fdb-49da-be7e-e30501d742ac" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a8eb6ee0-7fe9-44ef-8cdb-9fb618413d2f" start_index="0" end="d71efcb4-3df8-472f-b598-63d7a11c097e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b5ecaffa-7fdb-49da-be7e-e30501d742ac" start_index="0" end="aa6058d6-2d2c-419c-adc4-23f58c7f5767" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="53d33e3a-cece-4638-b60a-d477a6b4abee" start_index="0" end="b5ecaffa-7fdb-49da-be7e-e30501d742ac" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="53d33e3a-cece-4638-b60a-d477a6b4abee" start_index="1" end="a8eb6ee0-7fe9-44ef-8cdb-9fb618413d2f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9e250749-068e-4ff1-bbcd-57eeb0ee62d4" start_index="0" end="53d33e3a-cece-4638-b60a-d477a6b4abee" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff96cfb0-38bf-456a-b0b9-ed358727796d" start_index="0" end="9e250749-068e-4ff1-bbcd-57eeb0ee62d4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3a8e8c07-23e8-4c4f-a986-ae45a639d204" start_index="1" end="9e250749-068e-4ff1-bbcd-57eeb0ee62d4" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>