<?xml version="1.0"?>
<doc>
    <assembly>
        <name>SketchUpForDynamo</name>
    </assembly>
    <members>
        <member name="M:SketchUpForDynamo.Material.GetName">
            <summary>
            Get Material Name
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetTextureFileName">
            <summary>
            Get Texture Filename
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetTextureHeight">
            <summary>
            Get Textrue Height
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetTextureWidth">
            <summary>
            Get Texture Width
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetTextureScaleH">
            <summary>
            Get Texture Scale in Height
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetTextureScaleW">
            <summary>
            Get Textute Scale in Width
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetTextureUsesAlpha">
            <summary>
            Does the material texture use alpha?
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetColour">
            <summary>
            Get Colour
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetTextureColour">
            <summary>
            Get Texture Colour
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetOpacity">
            <summary>
            Get Opacity
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetUseOpacity">
            <summary>
            Does the material use opacity?
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetUsesColor">
            <summary>
            Does the material use colour?
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.Material.GetUsesTexture">
            <summary>
            Does the material use texture?
            </summary>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.SketchUp.ReformatModel(System.String,System.String,System.String)">
            <summary>
            Reformats an existing SketchUp Model to another Version
            </summary>
            <param name="filepath">Original Model</param>
            <param name="version">Target Version like 2015 or 2018</param>
            <param name="newfilepath">Target Model Path</param>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.SketchUp.LoadModel(System.String,System.Boolean)">
            <summary>
            Load SketchUp Model by Path. 
            This node will load all SketchUp content into Dynamo. 
            By default it will include meshes.
            Turn meshes off if you are experiencing performance issues. 
            </summary>
            <param name="path">Path to SketchUp file</param>
            <param name="includeMeshes">Include Meshes (might be faster to turn it off)</param>
        </member>
        <member name="M:SketchUpForDynamo.SketchUp.LoadModelByLayer(System.String,System.String,System.Boolean)">
            <summary>
            Load SketchUp Model by Path and Layername. 
            This node loads only contents of the specified layer into Dynamo.
            By default it will include meshes.
            Turn meshes off if you are experiencing performance issues. 
            </summary>
            <param name="path"></param>
            <param name="layername"></param>
            <param name="includeMeshes"></param>
            <returns></returns>
        </member>
        <member name="M:SketchUpForDynamo.SketchUp.GetInstance(SketchUpNET.Instance)">
            <summary>
            SketchUp Component Instance Data. 
            This node extracts all components from an instance. 
            </summary>
            <param name="instance">SketchUp Component Instance</param>
        </member>
        <member name="M:SketchUpForDynamo.SketchUp.GetGroup(SketchUpNET.Group)">
            <summary>
            SketchUp Group Data. 
            This node extracts all contents from a group. 
            </summary>
            <param name="group">SketchUp Component Instance</param>
        </member>
        <member name="M:SketchUpForDynamo.SketchUp.FlattenInstances(System.Collections.Generic.List{SketchUpNET.Instance})">
            <summary>
            Flatten Instances.
            This node returns a list of all geometries from a list of instances. 
            </summary>
            <param name="instances"></param>
            <returns>All Geometries</returns>
        </member>
        <member name="M:SketchUpForDynamo.SketchUp.WriteModel(System.String,System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Surface},System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Curve})">
            <summary>
            Write SketchUp Model.
            This node writes surfaces and cures into a SketchUp model. 
            </summary>
            <param name="path">Path to SketchUp file</param>
            <param name="surfaces">Surface Geometries</param>
            <param name="curves">Curve Geometries</param>
        </member>
    </members>
</doc>
