<Workspace Version="1.0.0.1180" X="323.9475" Y="218.575" zoom="0.8425" Name="Collector.RoomFromElements" Description="Feed elements into this node and get the Rooms they are in. This uses the Revit API property of Room that each elemant inherits. " ID="b301126c-123f-48bf-b7f9-ae294d0ec53f" Category="BlackBox.Collection">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c6103fcd-479f-4679-b005-138277b65bb2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="10.452598048603" y="73.734537964301" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c39d9363-5bfd-4427-a0ac-dd8bfbe74a3f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="10" y="132.863757595644" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Phase [string]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="8d2d25e8-e4a7-4d82-a3c9-4a8a42fa07b3" type="PythonNodeModels.PythonNode" nickname="collector_room_from_elements" x="207.877166205199" y="89.092836419549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2014, Jason Andersen, jason@serialnonstandard.com

# Default imports
import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
import System.Collections.Generic
from System.Collections.Generic import List
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

#phase coming in
elementz = IN[0]
phaseProject = IN[1]

phase = []
collector = FilteredElementCollector(doc)
phase_collector = collector.OfClass(Phase)

for i in phase_collector:
	if i.Name == phaseProject:
  		phase = i
  	else:
 		print("Phase not found")

#unwrapelements
elements = []
for i in elementz:
    elements.append(UnwrapElement(i))

#variables
output = []
roomelems = []
elemNotInRooms = []

#work
for f in elements:
	fi = (f)
	fs = fi.Symbol
	fm = fi.Symbol.Family
	room = fi.Room[phase]

	if room != None:
		roomelems.append(room)
	else:
		elemNotInRooms.append(fi)
		continue
	
output.append(roomelems)
output.append(elemNotInRooms)
	
#Assign your output to the OUT variable
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1b90f6ec-5735-40be-a7c1-bb541d59c9da" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="888.277448071216" y="49.4665649856363" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Room Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8fcc99a2-bc06-49cc-903a-2405e8886fe1" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="895.094955489614" y="135.745496736378" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Elements Not In Rooms" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="2fe09db0-4639-453e-b188-d3473ba67d12" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="444.445103857567" y="85.4421364985164" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="elements[0];&#xA;elements_not_in_room[1];" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c6103fcd-479f-4679-b005-138277b65bb2" start_index="0" end="8d2d25e8-e4a7-4d82-a3c9-4a8a42fa07b3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c39d9363-5bfd-4427-a0ac-dd8bfbe74a3f" start_index="0" end="8d2d25e8-e4a7-4d82-a3c9-4a8a42fa07b3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8d2d25e8-e4a7-4d82-a3c9-4a8a42fa07b3" start_index="0" end="2fe09db0-4639-453e-b188-d3473ba67d12" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8d2d25e8-e4a7-4d82-a3c9-4a8a42fa07b3" start_index="0" end="2fe09db0-4639-453e-b188-d3473ba67d12" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2fe09db0-4639-453e-b188-d3473ba67d12" start_index="0" end="1b90f6ec-5735-40be-a7c1-bb541d59c9da" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2fe09db0-4639-453e-b188-d3473ba67d12" start_index="1" end="8fcc99a2-bc06-49cc-903a-2405e8886fe1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>