<Workspace Version="1.0.0.1180" X="509.59921913569" Y="63.9699518417401" zoom="1.09269143853539" Name="PointCloud.ToDynamoPoints" Description="" ID="f64e94ce-80e4-4103-aa06-50473ad65ada" Category="BlackBox.PointCloud">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="bfc3ebaa-09e9-4542-a941-b4a947b2acfc" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="14.88225338794" y="162.767013354019" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <PythonNodeModels.PythonNode guid="a26d0788-a093-4b22-8a38-176c276939ad" type="PythonNodeModels.PythonNode" nickname="GetRevitPoints" x="163.46658426992" y="162.827265819239" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2014, Jason Andersen, jason@serialnonstandard.com


# Default imports
import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.PointClouds import *
import System.Collections.Generic
from System.Collections.Generic import List

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

#elements coming in
elements = UnwrapElement(IN[0])

#variables
v_points = []

#work
for p in elements:
	# Process each point
	v_points.append(Autodesk.Revit.DB.XYZ(float(p.X),float(p.Y),float(p.Z)).ToPoint())
OUT = v_points
</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.CreateList guid="ead23854-e93f-4ea6-bc95-6531fbaf0891" type="CoreNodeModels.CreateList" nickname="List.Create" x="-140.61774661206" y="161.827265819239" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4b4a796f-1cac-47c9-9079-bb3afcc1cfcb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Empty" x="-288.127317769114" y="221.529307388522" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Empty" />
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1b2775e8-69f6-43d1-96a7-f77f7944525b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1120.36040141099" y="157.776501887127" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="DynamoPoints" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="64c96ac5-2d8d-45dd-be97-0a39275bc490" type="PythonNodeModels.PythonNode" nickname="GetTransform_vectors" x="140.521248060446" y="343.807809940901" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2014, Jason Andersen, jason@serialnonstandard.com 

# Default imports
import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
import System.Collections.Generic
from System.Collections.Generic import List

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

#elements coming in
elements = UnwrapElement(IN[0])

#variables
v_transform = []
v_origin = []
x_axis = []
y_axis = []
z_axis = []
vector_x=[]
vector_y = []
vector_z =[]
#work
for f in elements:
	v_transform.append(f.GetTotalTransform())
	v_origin.append(v_transform[0].Origin.ToPoint())
	x_axis.append(v_transform[0].get_Basis(0))
	y_axis.append(v_transform[0].get_Basis(1))
	z_axis.append(v_transform[0].get_Basis(2))
	vector_x.append(Autodesk.Revit.DB.XYZ(float(x_axis[0].X),float(x_axis[0].Y),float(x_axis[0].Z)).ToVector())
	vector_y.append(Autodesk.Revit.DB.XYZ(float(y_axis[0].X),float(y_axis[0].Y),float(y_axis[0].Z)).ToVector())
	vector_z.append(Autodesk.Revit.DB.XYZ(float(z_axis[0].X),float(z_axis[0].Y),float(z_axis[0].Z)).ToVector())
OUT = vector_x,vector_y,vector_z
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d6a59300-dff1-42b2-bf8a-7f1ffd21728a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.Length" x="587.27743639732" y="250.937636847436" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.Length" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="66c3f021-d9c5-4a34-bfa4-e75a2dcf3f9d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.Length" x="587.650379595802" y="331.210281530101" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.Length" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1e5b0229-3803-47bb-adea-f214b94850a1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.Length" x="586.77816862155" y="411.402435798092" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.Length" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="56a4f424-b79b-4d8f-bb41-9cef3752d157" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Scale" x="825.582472013566" y="162.071656542098" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Scale@double,double,double">
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f6132007-5350-4427-8015-a2f9b5d94787" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-404.843015036082" y="349.122371121566" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="PointCloudInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3a171030-a19b-433b-8ad7-49e0b3b15878" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-380.146622965302" y="160.383751908338" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="PointCloudPoints" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <CoreNodeModels.CreateList guid="2a729589-ef6f-4214-908f-a2c47177ae25" type="CoreNodeModels.CreateList" nickname="List.Create" x="-167.552553425132" y="353.485685261356" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="68dee05d-093d-4997-aaba-c6a1133e7e1d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Empty" x="-285.132459653609" y="407.80958236886" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Empty" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6faaf255-42b6-491c-92f5-039fe3c3f782" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="-10.6908636144053" y="347.943936035216" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="07048a73-c0be-4617-a0c7-1ee530556983" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="336.463893120862" y="322.096515884697" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="vectorX[0];&#xA;vectorY[1];&#xA;vectorZ[2];" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="bfc3ebaa-09e9-4542-a941-b4a947b2acfc" start_index="0" end="a26d0788-a093-4b22-8a38-176c276939ad" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a26d0788-a093-4b22-8a38-176c276939ad" start_index="0" end="56a4f424-b79b-4d8f-bb41-9cef3752d157" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ead23854-e93f-4ea6-bc95-6531fbaf0891" start_index="0" end="bfc3ebaa-09e9-4542-a941-b4a947b2acfc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4b4a796f-1cac-47c9-9079-bb3afcc1cfcb" start_index="0" end="ead23854-e93f-4ea6-bc95-6531fbaf0891" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="64c96ac5-2d8d-45dd-be97-0a39275bc490" start_index="0" end="07048a73-c0be-4617-a0c7-1ee530556983" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="64c96ac5-2d8d-45dd-be97-0a39275bc490" start_index="0" end="07048a73-c0be-4617-a0c7-1ee530556983" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="64c96ac5-2d8d-45dd-be97-0a39275bc490" start_index="0" end="07048a73-c0be-4617-a0c7-1ee530556983" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6a59300-dff1-42b2-bf8a-7f1ffd21728a" start_index="0" end="56a4f424-b79b-4d8f-bb41-9cef3752d157" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="66c3f021-d9c5-4a34-bfa4-e75a2dcf3f9d" start_index="0" end="56a4f424-b79b-4d8f-bb41-9cef3752d157" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1e5b0229-3803-47bb-adea-f214b94850a1" start_index="0" end="56a4f424-b79b-4d8f-bb41-9cef3752d157" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56a4f424-b79b-4d8f-bb41-9cef3752d157" start_index="0" end="1b2775e8-69f6-43d1-96a7-f77f7944525b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f6132007-5350-4427-8015-a2f9b5d94787" start_index="0" end="2a729589-ef6f-4214-908f-a2c47177ae25" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3a171030-a19b-433b-8ad7-49e0b3b15878" start_index="0" end="ead23854-e93f-4ea6-bc95-6531fbaf0891" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a729589-ef6f-4214-908f-a2c47177ae25" start_index="0" end="6faaf255-42b6-491c-92f5-039fe3c3f782" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="68dee05d-093d-4997-aaba-c6a1133e7e1d" start_index="0" end="2a729589-ef6f-4214-908f-a2c47177ae25" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6faaf255-42b6-491c-92f5-039fe3c3f782" start_index="0" end="64c96ac5-2d8d-45dd-be97-0a39275bc490" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="07048a73-c0be-4617-a0c7-1ee530556983" start_index="0" end="d6a59300-dff1-42b2-bf8a-7f1ffd21728a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="07048a73-c0be-4617-a0c7-1ee530556983" start_index="1" end="66c3f021-d9c5-4a34-bfa4-e75a2dcf3f9d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="07048a73-c0be-4617-a0c7-1ee530556983" start_index="2" end="1e5b0229-3803-47bb-adea-f214b94850a1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>