<Workspace Version="1.3.0.875" X="286" Y="157" zoom="1" ScaleFactor="1" Name="ViewSheetSet To Sheet (BattleBIM)" Description="This custom node retrieve all sheets available in the ViewSheetSet " ID="69d34ba5-2f21-4a4b-b12f-d4cc1d8ff2cb" Category="BattleBIM.Revit.Views.Sheet.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="25e48a9b-0d46-469a-92ea-64bad6386b8c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = IN[1]

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

vsName = IN[0]

viewSets = FilteredElementCollector(doc).OfClass(ViewSheetSet)

for i in viewSets:
	if i.Name == vsName:
		vs = i
	else:
		continue

#Assign your output to the OUT variable
OUT = [i.ToDSType(True) for i in vs.Views]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6459e497-3b64-4567-8b28-d46a0ae3ba99" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-181" y="85" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Can be used link file&#xD;&#xA;//Autodesk.Revit.DB.Document&#xD;&#xA;document" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e7f62fd5-79d5-49d5-8c33-1322e5796dd6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-162" y="-1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ViewSheetSet:string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4a10bd99-6761-4d71-9668-402b3feb4ed8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Sheet" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="64815523-f586-4660-bf68-071f0553af1e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-83" y="232" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="reset:bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="25e48a9b-0d46-469a-92ea-64bad6386b8c" start_index="0" end="4a10bd99-6761-4d71-9668-402b3feb4ed8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6459e497-3b64-4567-8b28-d46a0ae3ba99" start_index="0" end="25e48a9b-0d46-469a-92ea-64bad6386b8c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e7f62fd5-79d5-49d5-8c33-1322e5796dd6" start_index="0" end="25e48a9b-0d46-469a-92ea-64bad6386b8c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="64815523-f586-4660-bf68-071f0553af1e" start_index="0" end="25e48a9b-0d46-469a-92ea-64bad6386b8c" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>