<Workspace Version="1.2.0.2831" X="-152" Y="233" zoom="1" Name="TopographyToPolySurface(BattleBIM)" Description="This custom node will convert Topography to PolySurface" ID="76b85ae9-e09c-4509-b12f-86a3b771a797" Category="BattleBIM.Revit.Element.Topography.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolySurface" resolvedName="Autodesk.DesignScript.Geometry.PolySurface" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8078fd2c-c06e-4534-986f-fb91b5edf7e6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="465.94645443916" y="155.912352975607" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="mo = mes.Mesh;&#xA;m = mo.FaceIndices;&#xA;p1 = mo.VertexPositions;&#xA;PolySurface.ByJoinedSurfaces(Surface.ByPerimeterPoints(List.Transpose({List.GetItemAtIndex(p1,m.A),List.GetItemAtIndex(p1,m.B),List.GetItemAtIndex(p1,m.C)})));" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="af138312-8fab-4893-91ab-e8c123b3315b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1236.94645443916" y="205" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="PolySurface" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="eacf1d88-34d4-49ae-8dc9-0b041414016f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="293" y="152" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Topography" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8078fd2c-c06e-4534-986f-fb91b5edf7e6" start_index="3" end="af138312-8fab-4893-91ab-e8c123b3315b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eacf1d88-34d4-49ae-8dc9-0b041414016f" start_index="0" end="8078fd2c-c06e-4534-986f-fb91b5edf7e6" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="f942582e-de86-4e29-939e-2f2b15bbca1b" text="#Copyright Â© 2016, Lingkon&#xD;&#xA;# @Lingkon, lingkonn@gmail.com&#xD;&#xA;###############################" x="520" y="-28.5" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-26959.515625" eyeY="13217.7255859375" eyeZ="66340.0859375" lookX="28161.45703125" lookY="-20374.25" lookZ="-40686.4375" upX="0.0988278463482857" upY="0.984807729721069" upZ="-0.142782151699066" />
  </Cameras>
</Workspace>