<Workspace Version="1.2.0.2514" X="-516.576501936964" Y="607.186579053109" zoom="1.05429821501133" Name="Delete.UnoccupiedSpace (BattleBIM)" Description="This custom node help you to delete those Unoccupied Space" ID="28d81363-5964-45c4-9359-a8987d3fd37b" Category="BattleBIM.Revit.MEP.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="dcb15b8e-61fa-4f80-aacd-8ebfb68368da" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="699.114285007496" y="-255.469836927032" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="s = spc.GetParameterValueByName(&quot;Room Name&quot;);&#xA;ftr = String.Contains(s, &quot;Unoccupied&quot;, false);&#xA;__TryGetValueFromNestedDictionaries(List.FilterByBoolMask(li1, ftr), &quot;in&quot;);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <DSRevitNodesUI.ElementsOfCategory guid="281a914f-6de9-4962-bdd2-977a066bfed4" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="512.86546091997" y="-250.222142168252" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="1328e83c-9dc6-4ae6-89a8-8aed4401986c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="16.0693123233822" y="-259.00779688458" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Category.ByName(&quot;OST_MEPSpaces&quot;);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c02a02a0-b13a-45f3-939e-42f0286b0b79" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="1201" y="-158" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="reset:bool = true;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="78ac7bcf-26b4-4bc1-b14a-945e16e49c16" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1438.26868531195" y="-218.050834546095" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

from System.Collections.Generic import *

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
deleteBoolean = IN[1]
#unwrap all elements to use with API
elements = []
for i in IN[0]:
	elements.append(UnwrapElement(i))

idsToDelete = List[Autodesk.Revit.DB.ElementId]()
for i in elements:
	idsToDelete.Add(i.Id)

# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

if deleteBoolean:
	doc.Delete(idsToDelete)
	message = "You have successfully deleted \n " + str(idsToDelete.Count) + " MEPSpaces from Revit model."
else:
	message = "Delete set to false."

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

OUT = '\n'.join('{:^35}'.format(s) for s in message.split('\n'))</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="dcb15b8e-61fa-4f80-aacd-8ebfb68368da" start_index="2" end="78ac7bcf-26b4-4bc1-b14a-945e16e49c16" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="281a914f-6de9-4962-bdd2-977a066bfed4" start_index="0" end="dcb15b8e-61fa-4f80-aacd-8ebfb68368da" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="281a914f-6de9-4962-bdd2-977a066bfed4" start_index="0" end="dcb15b8e-61fa-4f80-aacd-8ebfb68368da" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1328e83c-9dc6-4ae6-89a8-8aed4401986c" start_index="0" end="281a914f-6de9-4962-bdd2-977a066bfed4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c02a02a0-b13a-45f3-939e-42f0286b0b79" start_index="0" end="78ac7bcf-26b4-4bc1-b14a-945e16e49c16" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>