<Workspace Version="1.0.0.1180" X="442" Y="255" zoom="1" Name="PointCloud.ReadPoints" Description="" ID="160fe99f-e790-453b-a037-8c0424d216f4" Category="BlackBox.PointCloud">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d3ce7b5d-b2d4-4bfd-b6e4-a3a353af3a58" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="162.710201958011" y="-32.3755096249113" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <CoreNodeModels.CreateList guid="9be82675-4e0b-429f-a30c-db04c61d85d8" type="CoreNodeModels.CreateList" nickname="List.Create" x="11.0000000000009" y="-34.0000000000011" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="dda10f5f-a40c-4de6-9c62-eedc0c70cdb1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Empty" x="13.0000000000009" y="-118.000000000001" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Empty" />
    <PythonNodeModels.PythonNode guid="13e351c9-1f47-481a-974b-4a41c47b1422" type="PythonNodeModels.PythonNode" nickname="pointcloudreadpoints" x="361.763540710431" y="12.0865033049388" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <Script>#Copyright(c) 2014, Jason Andersen, jason@serialnonstandard.com 

# Default imports
import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.PointClouds import *
import System.Collections.Generic
from System.Collections.Generic import List

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

#elements coming in
elements = UnwrapElement(IN[0])
pcFilter = UnwrapElement(IN[1])
density = UnwrapElement(IN[2])
#variables
v_points = []

#work
for f in elements:
	#local variable
	averageDistance = 0.0001
	# Get points.  Number of points is determined by the needs of the client
	points = f.GetPoints(pcFilter[0], averageDistance, density)
	v_points.append(points)   
    #for p in points:
        # Process each point
        #System.Drawing.Color color = System.Drawing.ColorTranslator.FromWin32(point.Color);
        #String pointDescription = String.Format("({0}, {1}, {2}, {3}", point.X, point.Y, point.Z, color.ToString());


OUT = v_points
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5992bcce-064b-4fe2-981b-915e6efda37d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-244.5" y="-36" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="PointCloudInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="dba66dfc-e4e9-452f-94e0-56302cd60c42" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="636.5" y="12" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="PointCloudPoints" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="96e0de44-c2c2-42fe-b02e-2143cc3822cd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-243" y="34" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="PointCloudFilter" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="155c6040-79ab-4585-a7e8-603dcf9c3ecc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-245" y="104" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Density of Points [Int]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d3ce7b5d-b2d4-4bfd-b6e4-a3a353af3a58" start_index="0" end="13e351c9-1f47-481a-974b-4a41c47b1422" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9be82675-4e0b-429f-a30c-db04c61d85d8" start_index="0" end="d3ce7b5d-b2d4-4bfd-b6e4-a3a353af3a58" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dda10f5f-a40c-4de6-9c62-eedc0c70cdb1" start_index="0" end="9be82675-4e0b-429f-a30c-db04c61d85d8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="13e351c9-1f47-481a-974b-4a41c47b1422" start_index="0" end="dba66dfc-e4e9-452f-94e0-56302cd60c42" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5992bcce-064b-4fe2-981b-915e6efda37d" start_index="0" end="9be82675-4e0b-429f-a30c-db04c61d85d8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96e0de44-c2c2-42fe-b02e-2143cc3822cd" start_index="0" end="13e351c9-1f47-481a-974b-4a41c47b1422" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="155c6040-79ab-4585-a7e8-603dcf9c3ecc" start_index="0" end="13e351c9-1f47-481a-974b-4a41c47b1422" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>